### ISSUE TITLE
Red "Delete" button is scary

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1007]
Will it delete my files, or will it unshare my folder?

**Comment by davidbaumann** [comment]
+1 for "detach", this was my first thought on this issue.

**Comment by vvllaadd** [comment]
'detach' implies that something was attached in the first place.
'delete' is being used in most operating system as the word describing the action of trashing data.

My suggestion: 
1. Rename the button to "Remove", as it is the most common antonym for "Add".
2. Remove it's red color, make it silver, because the red color implies danger.
3. Add a confirmation prompt to the button, which makes it clear to the user that no data will be lost in this process and that the only thing that is being removed is the folder settings from Syncthing.

P.S. It's not an uneducated suggestion.

**Comment by calmh** [comment]
How about `Obliterate`? Or maybe `Destroy`?

**Comment by vvllaadd** [comment]
I like "Extirpate" though :)

**Comment by calmh** [comment]
On that note `Exterminate! Exterminate!` has a certain ring to it. Could add a metallic voice of it somewhere to resolve #1101 as well.

**Comment by DragoonAethis** [comment]
...but honestly, could that show up instead of <whatever is going to end up in "Delete" box> if you were holding Shift while opening this window?

**Comment by dragetd** [comment]
Ops, sorry. I only found this issue after creating my PR @78f6794d358d67f48dd8fa4a69f5a67d4ed97a0e

Was on android and this 'translation' was the first thing that struck me. Sorry for bringing that old bikeshedding-topic back up.

**Comment by timabell** [comment]
How about "Forget" or "Forget folder"

**Comment by filerun** [comment]
A computer does not forget things (:D), so the user wouldn't know what to expect after pressing the button.

**Comment by Ferroin** [comment]
The point is still valid though, 'Delete' is not an accurate description of what's happening.  'Disconnect' might be better.

As far as 'Forget', I doubt that that would cause as much confusion as you think, that's pretty typical UI jargon for 'persistently stop processing this data' or 'purge local details of this particular item', both of which accurately describe what the 'Delete' button currently does.

**Comment by calmh** [comment]
Thanks everyone. I think we have all the suggestions required at this point.
