### ISSUE TITLE
Protocol changes before v1.0

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1027]
I'd like to propose the following changes and reasons why I think these would be useful:

Discovery:

1. Address - add a integer to indicate the protocol over which the client is listening, or alternatively, ideally replace addresses with a `[]string` then sending full URLs with arbitrary amount of information, such as `dst://123.123.123.123:22002/?certname=pulse`

BEP:

1. Request - Add hash of the block being requested - So that in the future we could verify that the block we've read matches the hash, and to do block lookups by hash.
3. Request - Add `[]Options` for general extensibility
3. Folder - Add `[]Options` for general extensibility (and in the future perhaps sending some verification to the receiver to indicate that we hold the correct encryption key for that folder)
4. IndexMessage - Add `[]Options` for general extensibility (and in the future perhaps sending a signature over the IndexMessage if the folder is encrypted to verify that we have the correct key hence other party should accept our index update)
5. Probably some new derivative of IndexMessage required for #950 
6. Some better response mechanism for Requests (to indicate that we don't have the block anymore for example)

**Comment by MarkusTeufelberger** [comment]
Could a (more) variable block size also be part of the final protocol, please? As far as I understand, blocks are all 128 kiB in size, except for the last one (which might be the only one too). https://discourse.syncthing.net/t/better-delta-sync-algorithm-like-rsync/984/14 seems like a reasonable implementation to determine splits in files by file content, not a fixed length. https://github.com/bup/bup for example uses such an algorithm to handle inserts in the middle of files better, check out bup-split.

You could still insist on having 128 kiB as maximum block size (though you seem to prefer this to be the "average" or "typical" size), then a splitting algorithm would simply split at the boundaries it finds or at 128 kiB, if no boundary was found since the last split. This might be necessary to prevent attacks on the splitting algo anyways.

Your current version of splitting files into blocks only works well with append-heavy file changes, bup-split works also with inserts and prepends and you need to hash the file anyways.

It would be nice to at least have the option to add such a feature to the client later on by making the file size requirements of blocks a bit more relaxed.

**Comment by calmh** [comment]
@MarkusTeufelberger At this point no, unless someone contributes that.

**Comment by AudriusButkevicius** [comment]
What else would we need for encryption? Extentions to blocks?

**Comment by calmh** [comment]
I don't know... But I'm pretty sure it should be a new major version anyway so I wouldn't worry about it too much. :)
