### ISSUE TITLE
Move special .st* files into a .syncthing directory

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1056]
Instead of cluttering the synced folder with .st* files (such as ```.stfolder```, ```(.stignoreglobal)```, ```.stignore``` and ```.stversions```), we should use a ```.syncthing``` folder that allows the storage of all this and future information.
BTSync did a similar conversion some months ago.

**Comment by webid4me** [comment]
+1

**Comment by pirog** [comment]
+1 

this would be very helpful for things like git which cannot clone into a non-empty folder

**Comment by calmh** [comment]
@pirog Whatever that issue is, I don't think this will help...?

**Comment by pirog** [comment]
Yeah I think you're right. Skimmed this too quickly I guess :/

but seems like either way a synced folder would be non-empty by default either with a hidden dir or some hidden files. 

We are having this issue on the KALABOX project where we are git cloning directly into a synced folder. The clone fails because the die is non-empty. For now we are just moving .stfolder to tmp, cloning and then moving .stfolder back in. This seems like a bad thing to do but seems to be working this far. 

Anyway, ignore this I guess :)

**Comment by calmh** [comment]
@pirog Yeah, or clone to the dir before letting syncthing know about it... But there's also some ticket about handling read only dirs without creating any crap in them, maybe that fits your use case? I'm kind of hoping at least one side is read only (from the syncthing perspective), or you'll probably corrupt your git directory anyway.

**Comment by pirog** [comment]
We might be a bit on the frontier for ST here then.

We are building a local dev environment which is kind of in between docker and vagrant so a lot of this stuff happens automatically and needs to be RW both ways. 

About to roll out an alpha so we can get some useable feedback soon!

**Comment by calmh** [comment]
Going to close this, as I think we should instead minimize the amount of special files.

`.stfolder` must exist and may as well be what it is today
`.stignore` should cease to exist and move into the config

There should be nothing else.
