### ISSUE TITLE
rsync/delta transfer

### ISSUE THREAD

**Issue by pgega** [syncthing/syncthing#107]
Documentation (feature list) does not make it clear if syncthing supports diff/delta (rsync like) file transfer.

Is diff transfer supported?

**Comment by MarkusTeufelberger** [comment]
Could this issue be reopened or clarified? As Far as I understand the current model, it works efficiently only in some specific cases:

* Data is appended at the end of a file
* An exact multiple of 128 kiB is added anywhere in the file (start/middle)
* Data is being replaced by different data with exactly the same size anywhere in the file
* An exact multiple of 128 kiB is deleted from anywhere in the file

In all these cases, this would cause only very few blocks to be transmitted.

Where this method fails, is in any other case.

A potential worst case would be e.g. a video file format that stores metadata right at the beginning of the file. If your movie from "last christmas" should now be called "Christmas video 2014" or you fix a typo in the subtitles, Syncthing will have to transmit the whole file, even if only a few bytes were added. Rsync prevents this by using the file content itself to decide where to place block boundaries, not only size.

**Comment by calmh** [comment]
That's true, but the creators of said video format should be tried for crimes against humanity. Not only would it be an inefficient transfer, it would be an inefficient file write and and an inefficient backup. My point being, I don't think it's a common case - compare for example (my closest personal experience) the Adobe DNG format for raw photos, which includes metadata. Said metadata is stored in XML at the start of the file. But it's padded with a lot of nuls, just for this purpose - normally there's a kilobyte or two of them after the end of the XML. Writing a larger or smaller XML into this area is just a small rewrite and does not touch the rest of the file.

There are other reasons not to do the rsync thing as well. Primarily, it requires syncing a given file between exactly two parties who both read and hash the file pretty much in lockstep. There's no simple clustering here because how we chop up the file depends on it's contents, and if I have a set of block hashes for different block offsets than you, there's no reconciling them.

**Comment by MarkusTeufelberger** [comment]
This was just the first example that came to my mind, I'm sure there are better ones out there. My point is that the current solution does not handle the general case and I'm not 100% sure if the current cases are really the most common ones.

Any change can max. impact 2 existing block hashes (+ the amount of blocks within that change). Rsync splits files based on a fixed size sliding window, so introducing a new split somewhere in the beginning does not have an impact on later splits. See http://manpages.ubuntu.com/manpages/maverick/man1/bup-split.1.html for a similar implementation.

**Comment by csindle** [comment]
My 2¢ scenario where this also hurts us:
We use (and love) Syncthing to sync (within our LAN) our daily Postgresql ('custom' -Fc format) database backup from the Internet.   The compressd backup is about 1.5 GB.   The daily rsync diffs (from the previous day) are less than 30 MB.   Probably for the reasons discussed above, Syncthing transfers about 1 GB. 

I would guess that syncing any sort of archive (e.g. plain tar) is not a rare use-case, and would trigger this behaviour (even archives with append-only (e.g. logs) components).

Thanks for a great application.

**Comment by calmh** [comment]
@csindle How is that backup compressed? I'd expect a (for example) gzip compressed file to be almost completely different if it differs anywhere - at least in the blocks following the change...

**Comment by csindle** [comment]
@calmh From [here](http://www.postgresql.org/docs/9.4/static/app-pgdump.html):

> --format=c, and --compress "For the custom archive format, this specifies compression of individual table-data segments, and the default is to compress at a moderate level." )

it seems to be an archive of compressed components.  E.g. I can see SQL text in between the compressed table data.

Re: gzip:  yes, I agree, but the internal deltas it seems to work their way out eventually: that is why the rsync diff is 30 MB when the changed data gziped is a actually fraction of that.  

Note that the rsync algorithm is used very effectively for file *distribution* as well as syncing:
From http://zsync.moria.org.uk/ :
 
> It uses the same algorithm as rsync. However, where rsync is designed for synchronising data from one computer to another within an organisation, zsync is designed for file distribution, with one file on a server to be distributed to thousands of downloaders

**Comment by MarkusTeufelberger** [comment]
https://github.com/syncthing/syncthing/issues/1284 seems to reference the same issue by the way.
