### ISSUE TITLE
Specify a web root for the WebUi

### ISSUE THREAD

**Issue by randomessence** [syncthing/syncthing#1106]
Is there a way to specify the web root in the WebUi?

If not could this be added?

The specific issue is a proxypass/webserver/reverse proxy configuration in a subdirectory where i need to force a webroot so as to have a working proxypass.

**Comment by dangmai** [comment]
I know this ticket has been closed for awhile now, but I'm still hoping that it can be reconsidered.

My use case is that I'm using [Caddy](https://github.com/mholt/caddy) to reverse proxy a subdirectory to Syncthing (let's say `http://test.com/syncthing`). By default, Caddy proxies requests to `http://localhost:8384/syncthing`, which returns 404.

It does have an option to specify a prefix to trim before sending a request to upstream - so for example, if I specify `without /syncthing`, Syncthing will receive a request at `http://localhost:8384` correctly. However, if I use that option, Syncthing returns all assets relative to `http://test.com` instead of `http://test.com/syncthing`. The vendor libraries will be at `http://test.com/vendor/` instead of `http://test.com/syncthing/vendor`, which is not the correct behavior.

That issue is semi fixable if I rewrite URL based on the referrer of the request, but at that point it's really more complicated than it needs to be (and also some assets that don't have the referrer needed won't be proxied correctly). So I'm hoping that Syncthing can just add the option for a web root, which would simplify the set up considerably (at that point the default proxy would Just Work™).

Thanks a lot!

**Comment by AudriusButkevicius** [comment]
Technically, the reverse proxy should rewrite the URLs

**Comment by calmh** [comment]
It currently Just Works(tm) with both Nginx and Apache proxying. If it doesn't with Caddy, I think the unusual behavior is on Caddy's side. At least for me it's quite common to have lots of small services that all consider `/` to be their namespace, and then something in front of that that binds `/foo` to `http://localhost:8123/`, `/bar` to `http://localhost:8124/` and so on. Syncthing fits in perfectly in such a setup.

**Comment by uok** [comment]
or you could use `http://syncthing.example.com` and proxy requests to `http://localhost:8384`

**Comment by dangmai** [comment]
Argh you guys are of course right - it's a Caddy misunderstanding on my part. Trimming the prefix with `without` does work, however if I don't include the trailing slash (/) at the end of my URL it won't proxy to the right thing. I can either include that trailing slash manually or do a redirection automatically. Here's part of my Caddy config now that works, in case people try to search for it later:

```
redir /syncthing /syncthing/ 302
proxy /syncthing http://syncthing:8384/ {
  transparent
  without /syncthing
}
```

**Comment by randomessence** [comment]
The reason I originally considered this issue resolved was because I used these proxypass configurations with apache and nginx respectively and it worked perfectly without needing to specify a webroot which was needed with btsync. I guess syncthing was coded better. 

Note: this is for a webhost where the https url is non implemented in tradition way so it may not work as a copy and paste solution but it worked for me exactly how i needed it work work and i successfully proxypassed to a custom web sub directory.

Apache:

```
Include /etc/apache2/mods-available/proxy.load
Include /etc/apache2/mods-available/proxy_http.load
Include /etc/apache2/mods-available/headers.load
Include /etc/apache2/mods-available/ssl.load

ProxyRequests Off
ProxyPreserveHost On
ProxyVia On
SSLProxyEngine on

ProxyPass /syncthing http://10.0.0.1:PORT
ProxyPassReverse /syncthing http://10.0.0.1:PORT
```

Nginx:

```
location /syncthing {
    proxy_set_header        Host            $http_x_host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    # redirect for no trailing slash
    rewrite ^/syncthing$ https://$http_x_host/USERNAME/syncthing/ permanent;
    #
    rewrite /syncthing/(.*) /$1 break;
    proxy_pass http://10.0.0.1:PORT;
    proxy_redirect off;
    proxy_buffering off;
}
```

**Comment by letroll** [comment]
it's not working for me ( nginx with let's encrypt cert, on archlinux)

**Comment by AudriusButkevicius** [comment]
Use forum for support.
