### ISSUE TITLE
Race condition on directory delete / modification

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#114]
If one node deletes a directory with all contents and another node creates a file in the same directory at the same time, the following warning is printed on the console on the created-the-file node:

```
[373HS] 2014/04/13 17:45:14 WARNING: remove s23-3/6/64: directory not empty
```

(It got an index entry to say to remove the directory, but there is a file in the directory which wasn't deleted.)

**Comment by Novox** [comment]
I also ran into a "The directory is not empty." issue, however, I wasn't performing modifications on both sides.  It threw a:

[XV4KT] 16:06:07 WARNING: Folder "Sync" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

but after about 3 cycles, everything recovered.  Could the delete file manifest be listing the directory first, and then the files within it?  Causing an out-of-order delete?

**Comment by calmh** [comment]
We handle deletions in reverse sorted order, so longer paths before shorter, so no. But there might have been something else temporary or locked in the directory that prevented it's removal.

**Comment by lkwg82** [comment]
Is this still relevant? Seems stale.

**Comment by calmh** [comment]
Indeed. I think the scanner is smart enough to resurrect directory nowadays.
