### ISSUE TITLE
Small improvements for footer navbar

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1154]
small improvements for footer
- open links in new tab
- optional: add link to [Twitter @Syncthing](https://twitter.com/syncthing)
- add icons
![syncthing footer](https://cloud.githubusercontent.com/assets/9367272/5569156/b34cd526-8f6b-11e4-838f-acca6062c890.png)

if :smiley:  = I will create a pull request

**Comment by davidak** [comment]
@uok you can create a pull request yourself. this changes are easy and to know how to contribute to projects on github is very helpful.

since the bootstrap icons are already used you should try to use them.

as @calmh already mentioned, users should open links in a new tab themselves. i hate if i don't have the choice!

**Comment by uok** [comment]
> you can create a pull request yourself

I know :wink: but not a lot of :watch: currently

**Comment by davidak** [comment]
@uok haha, same here!

**Comment by uok** [comment]
:checkered_flag: :door:
