### ISSUE TITLE
Reduce memory/CPU footprint

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1157]
Use `sync.Pool` in `model.Request`, because judging from:
https://discourse.syncthing.net/t/disable-data-encryption/416/44
we seem to be making a lot of allocations while sending the 5GB file which seem to be taking a fair share of CPU time.

**Comment by krozycki** [comment]
Hi. I think I'll try to do this.

As far as I can see, sync.Pool gives us what we want and will lower the cost of allocs, but we want to return the buffer to the pool after using it in model.Request, thus we need to write to the socket handler rightaway in model.Request, right?

I only can't find a place from where we call model.Request, could you please help me find it?

**Comment by AudriusButkevicius** [comment]
So I think this will be fairly hard.
model.Request gets called from the protocol package.

The reason this is hard:
1. We cannot pass a socket handle into the model, because we need to send packet headers before the actual request content, which means we need to know the size of the data before we write it (since it's one of the fields).

Possible options:
1. Instead of expecting a []byte, err return value from .Request, we could pass a []byte into request which it then copies the data into.
The []byte would be allocated by sync.Pool in the protocol package, knowing when it can be reused.
Not sure if you can make go read a file into a []byte though.
2. Have some sort of clever writer wrapper which internally uses sync.Pool beween different instances and knows how output the exact set of bytes to the socket once it has all the relevant fields set.

**Comment by calmh** [comment]
In my experience, one issue with using sync.Pools for buffers is that it's a long way from where we allocate to where we can reuse, and it's not always when exactly we are done with a buffer (some slices of it may live on as hashes etc). When I tried earlier it was less efficient than what we're doing now. But! There were also bugs with sync.Pool in go 1.3 so that objects in the pool weren't freed as they were supposed to when GC kicked in, and sync.Pool has caused massive improvements in other places I've used them, so I think it's probably worth it to take another look.
