### ISSUE TITLE
[enhancement] [webui] Use something more efficient than base64 for binary blobs

### ISSUE THREAD

**Issue by asdil12** [syncthing/syncthing#1158]
The binary icons of the webui are included in the binary as gzip encoded base64 strings. It would be more efficient to directly use (gziped) byte-arrays.
I'm not very familiar with the go compilar but I think that should allow the byte-arrays to directly be a binary part of the executable - without the base64 storing and decoding overhead.

**Comment by calmh** [comment]
Unless I'm wrong and someone shows that by improving it, yes. :)

**Comment by calmh** [comment]
So I actually tried this when I was anyway tweaking the asset generator. Using plain `[]byte{...}` instead of  `base64.StdEncoding.DecodeString("...")` made the binary about 100 KB smaller (10611668 bytes vs 10738452) and presumably has about the same impact on memory. It increased the source code size of the autogenerated file by 2.3 MB (2571895 bytes vs 585326) and hade a similar effect on compilation time. All in, not worth it, but worth checking out. :)
