### ISSUE TITLE
Ignore exclusion not good enough

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1185]
```
!/some/deep/directory/with/a/file
*
```
Does not work.
That is fixable by excluding every directory up to the target.
But these arent:
```
!unachored/deep/exclude
*
```
or
```
!/some/deep/**/wildcard/exclude
*
```

See:
https://discourse.syncthing.net/t/un-ignore-subfolders-files-of-ignored-folder/1460/6 
and discussion:
https://github.com/syncthing/syncthing/pull/1168

Also, currently we SkipDir in the walker if the directory matches an ignore, but we shouldn't as there might be some excludes down there.

**Comment by AudriusButkevicius** [comment]
I had an idea yesterday.

If we never skip dir, and we manage to match something to an exclude pattern, we can use matchers cache to check if the parent directories have been ignored or not.
If they have, we could forcefully mark them as unignored in the cache, and rewalk them one directory at a time (cd ..) until we reach the part which is not ignored anymore.

If ignore cache is disabled it's a bit harder, as we most likely won't know the outcome whether or not parent directories were ignored or not, so we'd have to have some special exclusion list which we populate going one directory up at a time which would force the matcher to exclude given directories from ignores, and then rescan those paths (and those paths only) causing parent directories to be indexed.

Possible fix for making the decision of whether or not we should SkipDir could be done by the matcher under the following conditions:
1. If we have an unachored exclude, never skip dir.
2. If we have a double wildcard exclude, do not skip if the directory we are currently at matches the prefix of the exclude (up to the wildcard). 
3. For a single wildcard, something like 2, but a bit more clever where we only traverse one level.

Alternatively, we could do this double walk thing, where we establish what we are going to walk first, and then walk it.
This would also allow us to deduce scan percentage.

**Comment by calmh** [comment]
What's the actual use case for this unignore-in-ignored-directory business? Is it really worth the agony?

**Comment by AudriusButkevicius** [comment]
Well:
```
/stuff/movies/something/this_one_movie_I_want_to_watch.avi
*
```

**Comment by calmh** [comment]
Right, indeed. So how about something like this...

We introduce the new concept *path filters* (or something like that), which is a list of directories. If this list is non-empty, *only* those directories are synced. Technically, this is a prefix match on incoming index entries (no match => throw them away) and a SkipDir on other directories in the walker. Wildcards are not supported here (I think? I'm thinking this should really be built by the classic tree-of-checkboxes.). Easy to understand, easy to implement (hopefully). This *could* be allowed to go all the way down to the file level, for your first case above, but I suppose the common case will be directories.

On top of that we have the *ignores* or *excludes* list. This is simplified from what we have today, to match only files or directories but *not path names* (i.e. no slashes and no `**` pattern allowed, but otherwise wildcards as usual). This is only matched against the last component of the pathname, and if it's a directory then it's SkipDir:ed.

**Comment by AudriusButkevicius** [comment]
Great idea, but a breaking API change.

**Comment by calmh** [comment]
For sure, but I'm getting a bit tired of patching the ignore system, which is clearly both confusing and not really all that great... Might be better to just try again. :)

**Comment by cebe** [comment]
Why not copy the .gitignore syntax for this? We have done the same for PHP here: https://github.com/yiisoft/yii2/pull/2059

**Comment by calmh** [comment]
What? There is no gitignore syntax for the problem Audrius notes in the issue above as far as I know. Also, the syntax is not the problem. :)

**Comment by cebe** [comment]
sorry, seems I completely misunderstood the issue then :)

**Comment by calmh** [comment]
If we really do want to support this, which I'm not super duper convinced of, it should be added to #2491.
