### ISSUE TITLE
syncthing changes permissions for sync folder, thereby breaking sync

### ISSUE THREAD

**Issue by midi** [syncthing/syncthing#1186]
i'm using v0.10.17 with syncthing-gtk under ubuntu 14.04 and v.0.10.11 with the play store version under android.

i disabled file versioning and now during the sync, syncthing changes the permission for my sync folder on ubuntu to d--------- instead of drwxr-xr-x. after that syncthing can't sync anymore and displays:
12:23:31: Folder "Sync" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

i can change the permissions, but the behavior happens again, how can i fix this?
is this intended?
if yes, why?

**Comment by AudriusButkevicius** [comment]
This is a known bug which @calmh was trying to solve but was failing to reproduce.
It seems to be caused by the upgrade from Go 1.3 to Go 1.4.
Can you easily reproduce it?

**Comment by midi** [comment]
@AudriusButkevicius yes. in fact i can't get rid of it now, i tried enabling versions on ubuntu again, it still changes the permissions.

just changed the revisions settings back on android too, will see if this fixes it, as this is the only thing i changed and thus likely has triggered the bug.

**Comment by AudriusButkevicius** [comment]
Are you saying that versioning has caused this?

**Comment by midi** [comment]
i believe so, since this problem started appearing after i disabled versioning.

it successfully synced since enabling versioning on android too.
but have not monitored it long enough to say for sure.

of course it also could've been because of a syncthing update, maybe this more likely.

**Comment by gunwald** [comment]
In my opinion it has nothing to do with versioning but rather with Syncthing >  v0.10.13. But if one version in your cluster has the bug it will change the permissions on all devices. In my humble opinion you should work on a better release model with a stable and a nightly version.

**Comment by AudriusButkevicius** [comment]
Yes, cause https://build.syncthing.net is there just for fun.
Show me a piece of software that never had bugs.

**Comment by AudriusButkevicius** [comment]
And if you read the above comments, it seems that the bug is in the standard library.

**Comment by gunwald** [comment]
Hey AudriusButkevicius, don't get me wrong, this wasn't meant to be an assault. Syncthing is a great peace of software and I appreciate the great work of all contributors. The only thing that I wanted to suggest is:
If you care about users that use Syncthing, you should consider stability as one of the most important things. This bug concerns data integrity and is a major bug. I had to shutdown Syncthing on all my computers due to this bug, and can't use it anymore until the bug gets fixed. 
From a user perspective I don't care, where the bug comes from. Or who is to blame, as it's not about blaming someone. 
But a release model where you not push any minor change that was not tested in the wild, to the end users, would be helpful.

**Comment by AudriusButkevicius** [comment]
We do have tests, and we do run the software ourselves, but this seems to be some edge case which the integration tests exposed after the release.
It seems quite hard to reproduce, hence it's hard to fix (any input would be useful).

We're not at v1.0 yet, which for me does not indicate stable, hence :hankey: happens as we are all testers to some extent.
Regardless, the bug is not as dramatic as you are saying, but given you are a clever man with sensitive data, you can always stay a few releases behind to play it safe and follow the issue tracker to see if there is anything major happening.
You did choose to be on the bleeding edge (and as you say, be part of the people testing in the wild), hence face the music.

Life is hard, and then we all die.

**Comment by gunwald** [comment]
I had the same issue with  v0.10.18.

**Comment by calmh** [comment]
Same as in the first report above, on the machine running .18? I can't reproduce it with a test any more with the fix as above...

**Comment by AudriusButkevicius** [comment]
Perhaps you have a mixed cluster of .17 and .18, .17 causes the issue and that propagates to .18.

**Comment by calmh** [comment]
@gunwald Give this build a try, on the affected computer (or all of them), after fixing the chmod on the folder root: http://build.syncthing.net/job/syncthing-branch/1567/

If it is what I suspect, you should see one or more messages along the lines of "Dropping invalid nil filename ..." and the problem not occurring again. If it doesn't, and you don't see that, then it's something even weirder. :)
