### ISSUE TITLE
Entire folder contents disappearing

### ISSUE THREAD

**Issue by ropeladder** [syncthing/syncthing#1221]
I have recently had two synced folders inexplicably empty themselves of all contents on two of my three nodes. (the nodes with the issue were on the same home network; the third node is a computer in a remote location)

Possibly related, since I hadn't made any other recent configuration changes:
I was having an issue similar to [885](https://github.com/syncthing/syncthing/issues/885) in two folders that were being synchronized. There were several temp files with long hashtag filenames that I deleted in several subfolders in one of the synced folders, which I don't think helped. I then tried the solution [mentioned by AudriusButkevicius](https://github.com/syncthing/syncthing/issues/885#issuecomment-68633368), which appeared to work. I used it for two different synced folders since I was getting errors for both of them, and the long filename puller errors stopped.

However, I later noticed I was getting another error for one of the folders, something about not being able to delete a file. Going back into the directory it appeared that the one of them (but not the other) was now entirely emptied of contents. I filled it back up using a backup and took out the "\\?\" prefix from the file headers. (in fact I think I had to recreate the folder info since I was having trouble clicking the "save" button for no reason)

I later realized that another directory had been emptied as well, although I had never tried the "\\?\" trick for this one. This directory was similarly emptied on two computers but not the remote third computer.

**Comment by AudriusButkevicius** [comment]
This needs some steps of reproduction, as it's not clear why this happened.
It could be due to `\\?\` but as you said another directory which didn't have it also had the issue.

Could you check the permissions of the folder and verify that it has readable permissions, also that the files are not hidden?

I wonder why it did not get emptied on the 3rd computer, is the 3rd computer able to connect?

**Comment by ropeladder** [comment]
I am quite sure that the folders have readable permissions and I highly doubt they are hidden but I will double check when I get home.

The 3rd computer (at work) often has trouble connecting with one or the other of the two home computers, but I believe at least one of the synced folders said it was all caught up despite the home nodes being deleted and the work node still having all its contents.

**Comment by AudriusButkevicius** [comment]
We had a bug in 0.10.15 which set the root directory permissions to 0's, causing the folder to become unreadable.

**Comment by ropeladder** [comment]
I've tried re-copying the files into the directory on several of the computers. Syncthing appears to finish updating all directories but does not finish syncing because it is unable to delete (at least) 100 directories that it gives repeated errors for (every minute). The problem is that I don't want to delete these directories in the first place and I'm not sure why Syncthing thinks I do or how to get it to stop.

I can send you logs but they just say:
```[KSCRE] 2015/01/14 18:16:43.152843 puller.go:460: INFO: Puller (folder "Scrapbook", dir "data\\20140620093453"): delete: remove H:\SyncStuff\Scrapbook\data\20140620093453: The directory is not empty.
(and then this for 99 other folders)
[KSCRE] 2015/01/14 18:16:43.152843 puller.go:197: WARNING: Folder "Scrapbook" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.```

It would be immensely helpful to have more options for directionality of syncing and deleting. I want to have a folder that has all my data that *doesn't get deleted* but I don't really understand which nodes and files get priority and how to get them to stop thinking should delete things. On Dropbox having a straightforward synced mirror system works OK, because it's mostly backed up in their cloud and the syncing actually works instead of just giving error messages and not being able to connect.

**Comment by AudriusButkevicius** [comment]
Each change that syncthing detects is versioned. The fact that it wants to delete something means that I has seen some node delete it and is trying to get to that version of that particular set of files/folders.

I guess there are a two possible causes.

Lets call node A the node getting the errors and some other node B.

One of them could happen if there is a `folder master` involved, and it goes like this:
B is the folder master
There is an existing folder X with some files which both A and B have and agree to be in sync
A adds new files to folder X and scans them
A announces that to B but B refuses the announcements as he is folder master.
Now B deletes folder X all together.
B sends the deletion announcement to A
A deletes all files that they agreed with B (including the folder, but not the files that A added recently)
A cannot delete the folder B announced as deleted, as A itself added some files to it which B is not aware off.

Second case involves a large rescan interval at A:
A adds new files to folder X, but doesn't scan them because the rescan interval hasn't yet passed
A announces nothing B as he himself is not yet aware of the new files.
Now B deletes folder X all together.
B sends the deletion announcement to A
A deletes all files that they agreed with B (including the folder, but not the files that A added recently)
A cannot delete the folder B announced as deleted, as A itself added some files to it which neither A nor B is not aware off since the rescan interval hasn't happened yet.

You can trigger to dispatch updates by renaming the folder, which will cause files to be downloaded or renamed. Wait for it to get in sync and then you can rename it back.

Or if you are a bit more skilled, you can bump the mtimes of the files causing them to look "updated".

**Comment by ropeladder** [comment]
Thanks for the reply. I guess case 2 could have possibly occurred while I was messing around with two of the computers.

When you say "rename the folder" to trigger dispatch updates do you mean changing the folder ID in Syncthing or renaming the actual folder on the drive? I was assuming you meant folder ID but Syncthing won't let me rename it.

**Comment by AudriusButkevicius** [comment]
No, I mean renaming the content in the folder.

**Comment by ropeladder** [comment]
So, rename a subfolder on one node, let it sync with all nodes, and then change the subfolder name back on all nodes? Or should it work to rename it on all nodes to start with?

**Comment by AudriusButkevicius** [comment]
Either way. Whats important is to trigger a change.
