### ISSUE TITLE
on QNAP 64-bit-kernels the amd64 build does not run

### ISSUE THREAD

**Issue by trendchiller** [syncthing/syncthing#1260]
the 386-build does run.
the amd64 builds do not resolve hostnames.

could both binaries be built statically so that these problems can be circumvented ?

**Comment by calmh** [comment]
Any details on why it doesn't run?

**Comment by AudriusButkevicius** [comment]
The binary links against libc and somehow dns resolution doesn't work.

**Comment by trendchiller** [comment]
it seems as if the qnap kernel seems not to support nss.
name resolution on the qnap works, but name resolution from within sncthing does not work.

**Comment by oO-Markus-Oo** [comment]
Maybe you should have a look at this thread:

http://forum.qnap.com/viewtopic.php?f=320&t=97035
**************************
NEWS a static version for x64 is delivered in the QPKG folder ... use it if you want to have immediate update in 64 bits mode
... update with shared libraries version supply by syncthing is unable (bad lb . version) to auto-update
... but due to the update site ... it's ONE time, after you can just wait for a new QPKG that add the new static version ...
**************************

I have a TS-670pro which is running the 64bit version and the normal 64build isn't running. If i change to the static build, everything is okay. If i use auto update, syncthing is broken again... Maybe we have to switch to the static builds?

**Comment by calmh** [comment]
It sounds like the qnap QPKG:s should be built statically and with auto upgrades disables - I assume the QPKGs have some way of being upgraded, what with being a package format and such?

**Comment by trendchiller** [comment]
They are updates by hand or via the qnap app store, but auto update of the sync package would work only if you build statically built binaries.

**Comment by oO-Markus-Oo** [comment]
@calmh
Is it difficult to provide an additional 64bit static linux build of syncthing? Do you compile the builds automatically or do you have to compile every build by hand? If there is an automatism, providing a static build shouldn't be a big problem? Sorry, up to now i didn't work with github - that's why the question might be a little bit stupid ;-).

I think auto updates will work, you only "need" the qpkg to do the initial installation with the webinterface. If you did the installation once, updates should be okay with static builds... I think this is the same problem btsync has - and that's why i am now here :-)

Regards from Germany and thank you for all your work,
Markus

**Comment by calmh** [comment]
It is somewhat difficult to provide, at least from the same build environment as the rest. The reason being we only have one environment per os-arch combination, and the linux-amd64 env is already configured differently. I think this is specific enough that it should be handled when building the package for the NAS, as that is anyway a custom thing separate from our builds.
