### ISSUE TITLE
Folder "ххх" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

### ISSUE THREAD

**Issue by stvJnK** [syncthing/syncthing#1278]
Добрый день!
Долго пытаюсь разобраться в проблеме, но решения которые нахожу не помогают.
Есть сетевое хранилище на нем стоит Linux на него копируются документы с компьютеров на Windows (7,8.1) после полной синхронизации получаю такие строки:
12:26:00: Folder "420-a-2" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
![image](https://cloud.githubusercontent.com/assets/9034919/5833908/1fbfa17a-a169-11e4-967e-21cb81d62d50.png)

Возможна проблема из-за невозможности синхронизировать файлы с длинными именами?

Просьба: Можно ли в систему игнорирования добавить возможность игнорировать символьные ссылки.

Заранее спасибо!

**Comment by AudriusButkevicius** [comment]
If you open config.xml, there is a setting symlinksEnabled which you can set to `false` , which will disable symbolic links.

There could be two possible causes for this issue, CreateSymlinks syscall not understanding the encoding (due to Cyrillic), or the path is too long.

If the path is too long, you could try prefixing the folder path with `\\?\` in config.xml so that it would look like: `\\?\C:\My\Directory\To\Sync`.
`\\

**Comment by stephand** [comment]
I have the same issue, causing lack of progress.  All the missing files are symlinks to non-existing sources, but they were not a problem until recently (thinking this might have started with the v.0.10.20 version.  I am running two Linuxes (v0.10.19 and v.10.20 updated to 21) with the problem and have also already removed the index.  Using staggered file versionin.  Error messages in the log:

[IUWPC] 07:46:09 INFO: Puller (folder "foo", file "bar/baz/blip"): shortcut: chmod /home/USER/zomtec/foo/blarb/blip/target: no such file or directory

**Comment by AudriusButkevicius** [comment]
Your issue is a different issue #1276

**Comment by stvJnK** [comment]
AudriusButkevicius, Спасибо. Добавил к адресу \\?\ , \\?\C:\UserDoc на некоторых компьютерах, буду наблюдать за ошибками.

**Comment by AudriusButkevicius** [comment]
It should be `\\?\` not `\?\`

**Comment by stvJnK** [comment]
![image](https://cloud.githubusercontent.com/assets/9034919/5875473/8852efd8-a31e-11e4-9395-dd6ccb576505.png)
![image](https://cloud.githubusercontent.com/assets/9034919/5875478/911d5dce-a31e-11e4-8c44-05026d953417.png)

**Comment by AudriusButkevicius** [comment]
And what does the log say on Linux?

**Comment by stvJnK** [comment]
Добрый день!
По ссылке ниже выкладываю архив с файлами, kern.log и syslog из сетевого хранилища под Linux:
https://drive.google.com/file/d/0BxTuVb4GNXhAdmJtcUtSRU5KRGc/view?usp=sharing

**Comment by AudriusButkevicius** [comment]
It seems that syncthing is getting OOM killed.
What does syncthing's log say (it logs to stdout by default), not the kernel log.

**Comment by stvJnK** [comment]
Добрый день, AudriusButkevicius!
Выслал на ваш E-mail лог файл от syncthing.

**Comment by AudriusButkevicius** [comment]
It seems that some of your filenames are too long. Even on linux. You should rename the files listed in the log.

**Comment by stvJnK** [comment]
Спасибо, буду пытаться решить данную проблему.

**Comment by NielsMayer** [comment]
I have the same problem. The logs indicate it doesn't like some of the characters used in filenames:

[2QJX5] 09:06:07 INFO: Puller (folder "gnuport-Music", file "smythe-midi/Charakterst\xfcck_(Characteristic_Piece)_Op_7_No_7_e-0200BRD.mid"): dst create: open /media/seagate-ntfs/gnuport/Music/smythe-midi/.syncthing.Charakterst�ck_(Characteristic_Piece)_Op_7_No_7_e-0200BRD.mid: invalid or incomplete multibyte or wide character
[2QJX5] 09:06:07 INFO: Puller (folder "gnuport-Music", file "smythe-midi/Danse_Cr\xe9ole-097BRD.mid"): dst create: open /media/seagate-ntfs/gnuport/Music/smythe-midi/.syncthing.Danse_Cr�ole-097BRD.mid: invalid or incomplete multibyte or wide character
[2QJX5] 09:06:07 INFO: Puller (folder "gnuport-Music", file "smythe-midi/Oh Baby! Don\x92t say no, say maybe - 6777W.mid"): dst create: open /media/seagate-ntfs/gnuport/Music/smythe-midi/.syncthing.Oh Baby! Don�t say no, say maybe - 6777W.mid: invalid or incomplete multibyte or wide character
[2QJX5] 09:06:07 WARNING: Folder "gnuport-Music" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

**Comment by rumpelsepp** [comment]
Seems to be related to my issue #1355.

**Comment by calmh** [comment]
@NielsMayer  That error ("invalid or incomplete multibyte or wide character") comes from the OS. Is Windows or NTFS formatted disks involved?

**Comment by NielsMayer** [comment]
Yes, it's a Generic off-the-shelf USB Hard Drive (c.f. /media/seagate-ntfs/) plugged into a raspberry pi2  running syncthing-linux-armv7-v0.10.23.  

My example, IMHO, is the class of errors that would prevent sync completion, and also emits the same warning as result of the problem. Perhaps, in addition to <folder ignorePerms="true"> we also need a parameter to enable some kind of name-remapping between filesystems? I have a sneaky suspicion I'm not the only one that will plug a large USB drive into a computer and think I can use syncthing to backup files to it. :-)

npm@kodipi:~$ sudo fdisk -l
Disk /dev/mmcblk0: 63.9 GB, 63864569856 bytes
4 heads, 16 sectors/track, 1948992 cylinders, total 124735488 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x0002c262
        Device Boot      Start         End      Blocks   Id  System
/dev/mmcblk0p1            8192      122879       57344    c  W95 FAT32 (LBA)
/dev/mmcblk0p2          122880   124735487    62306304   83  Linux
Note: sector size is 4096 (not 512)

Disk /dev/sda: 4000.8 GB, 4000787025920 bytes
255 heads, 63 sectors/track, 60800 cylinders, total 976754645 sectors
Units = sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk identifier: 0x9aa9e656
   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048   976754644  3907010388    7  HPFS/NTFS/exFAT

**Comment by preginald** [comment]
I also encountered this error and was able to solve it.

I had a fresh install v0.10.29 on a debian machine and another fresh install v0.10.29 on Windows 7 32bit.  7061 items, ~65.7 GiB exist on the debian machine and 7060 items, ~65.7 GiB are in sync leaving only one file out of sync.

I renamed the out of sync file on the debian machine and removed around 20 characters making the file a little shorter and restarted syncthing on debian machine.

The final file completed the sync and the error message didn't pop up anymore.

Hope this helps.

**Comment by NielsMayer** [comment]
I don't understand how this issue got closed given that people have to work-around it by moving files out of the way, otherwise anywhere it happens, it seems to hang-up progress -- perhaps on all folders, perhaps all of my folders have misbehaving files. I've kind of given up and gone back to making compressed tar file backups just like I've been doing since I was on BSD 4.2 in college :-(

**Comment by rumpelsepp** [comment]
@NielsMayer: #1355
