### ISSUE TITLE
Exclude Local Network from Bandwidth Limitations

### ISSUE THREAD

**Issue by nille02** [syncthing/syncthing#1336]
I used Syncthing now some time for testing and found a small "issue" The Bandwidth Limitations are Global.

A option for ignore this Limitation in the Private networks seems a goof idea. 
http://en.wikipedia.org/wiki/Private_network

The problem is that many People don't have high bandwidths, e.g i have 16Mbit Down and 1Mbit Upload. So i Limit the Upload to 100kB/s.

Most time i use Syncthing in my Lan (1Gbit) but then the Global Limit hits and i have to deactivate it. If now a external connection comes i have to enable it again manual. 

I guess is would be enough to ignore it only for a Class C Network (192.168.0.0) because Class A and B is often used by Mobil Carriers and in VPN Networks. 

I think that would be a good enhancement for syncthing. 

https://discourse.syncthing.net/t/bandwidth-limitations-in-lan/1804

**Comment by AudriusButkevicius** [comment]
So I guess we should flag addresses depending on how we find them.
If we got the address via local discovery, we should return an extra flag part of the address which would tell us not to wrap the connection in a limiter.

**Comment by nille02** [comment]
But then a manual given IP should still be limited or not? 

e.g. 192.168.0.5:22000,dynamic

**Comment by AudriusButkevicius** [comment]
Well `dynamic` means use all possible discovery clients.
Currently they just return a bunch of addresses, regardless if they are local or global.
We should basically start flagging addresses as global or local (depending on which client discovered the IP) and then wrap the socket in a limiter or not.

Doing it on a subnet basis is no good, as I have `44.44.44.0/24` as my LAN address space.

**Comment by Niranda** [comment]
http://en.wikipedia.org/wiki/Private_network

**Comment by generalmanager** [comment]
@AudriusButkevicius Doing this based on which way we discovered a devices seems to be the smart option. If we think about the future IPv6 will mean many more devices without NAT, even tough it does have a local address range.

I'd love to see this feature because the current design chokes ST to death on local networks and makes the breaks the idea of having one storage pod per physical location for fast local file exchange.

**Comment by AudriusButkevicius** [comment]
Surely if you remove the limits it should perform exactly the same as over WAN?
I think you are referring to stripping of encryption for LAN?

**Comment by generalmanager** [comment]
Sorry, bad wording. I meant that if the local transfer speed is limited (choked) to the same speed as the WAN connections, there isn't really a speed bonus for having a local node which is always on.

I currently have four locations with 2-5 Syncthing devices each plus one "stupid storage node", but right now I can only choose between throttling all upload and none.
While the first option means very slow sync on the LAN, the second one means unhappy family/friends, because their upload bandwidth is completely blocked, meaning calls that "the internet is slow".

I'd never ask to strip encryption anywhere, no worries ;-)

With this I just wanted to underline that it would be very much appreciated if there were a button to ignore the bandwidth limit on local connections. A second set of up/down bandwidths for local connections would probably be too confusing to the average user.

**Comment by AudriusButkevicius** [comment]
Yeah, it's not rocket science to implement, but someone has to invest the half an hour to do that.

**Comment by chucic** [comment]
generalmanager: What about set bandwidth control in router? I have this set up, every computer in my networks use some amount of capacity to internet and everything they can to each other and therefore i'm not using this feature in syncthing. But i still think it is desirable feature and i would even combine this 2 aproaches, so that user could set up limits to both (LAN, internet) and then use a button in device settings to tell syncthing "use LAN limits", which would also eliminate problems with decision whether device is connected via LAN or net.

**Comment by generalmanager** [comment]
@chucic I have BW priorization set up correctly, but even with this http traffic is down to a crawl. Which is an improvement, because before the connections would timeout, but still.

This is also not a solution for most users, because they have no idea this might exist (many routers don't support it) or ever logged into their router. And they don't call it router, it's the little box where all the cables go (not the one for electricity).

Thus I'd like the Syncthing setting to be as useful as possible. 

Regarding your proposal: I think we should try to keep  the UI clutter as low as possible, thus this should only be shown if the user entered an address manually. In this case there was no discovery service involved and we can't classify the device in any other way. But most users will use local and global discovery - they don't need to see this all the time.

**Comment by AudriusButkevicius** [comment]
I think this should just have a single checkbox "Apply bandwidth throttling in local area network" (unchecked by default), and only classify an IP as local if it was discovered via {broad,multi}casts. 

If you manually provided an IP, I guess we should still assume it's WAN, unless someone wants to go the extra mile doing CIDR math.

**Comment by tianon** [comment]
This has interesting implications for VPNs (OpenVPN, Hamachi, tinc, etc.) which will inherently look like LANs at this level (that's the whole point, after all).  Also related to #1305 and #219.

(Not complaining -- I love the feature; just wanted to point out one of the implications of it for future travellers. :+1:)

**Comment by AudriusButkevicius** [comment]
It has a toggle switch in the config.

**Comment by tianon** [comment]
Yeah, I saw. :smile: :+1:  Just wanted to point out what should be obvious, but also include some key terms here for folks searching for VPN (that they probabaly want to either turn this off or manage their VPNs differently via separate `syncthing` instances, etc).

**Comment by generalmanager** [comment]
I really like this functionality. Do you think there is a chance for this to get a checkbox in the web UI? 
I'd imagine this kind of feature would be useful for many users who are not comfortable with digging around in config files.
And if one doesn't know a feature like this exists, most users wouldn't think to search for it in the documentation.
You wouldn't even need to make the settings menu bigger, just put the fields for in/outgoing limits in one line and add the checkbox below.

**Comment by AudriusButkevicius** [comment]
PR's welcome.

**Comment by DASHdatamover** [comment]
I am new to this site and Syncthing but wanted to say to all contributors you are doing some cool stuff! I have been around the data moving space for a while and although Syncthing has features to add, it is an awesome tool as it is! (consider me a low-level technical user)

Throttling is a major, sensitive issue for me as I work with a lot of world destinations that expect me to play nice with their bandwidth (read: don't be a hog). Running most of my services on Gig or 10Gig pipes, it's very easy for me to be the bull in the china shop - not good. And in most cases, the remote sites provide zero help so I need to manage speeds upstream. 

Having experimented with Syncthing for a day now, my use case could see the option to control Device Throttles In/Out which allow me to make decisions on the specific folder behaviors at a certain Device destination. I realize this may be somewhat overbearing considering Syncthing can apparently sync an unlimited number of Folders at a Device Destination but it would solve a major goal for me.

Thanks for all the great, creative effort in this tool!

**Comment by DASHdatamover** [comment]
I am looking for a Syncthing "super-user" to speak with to get more familiar. I am startup that will be willing to pay for this expertise when our funding lands. And, I am not expecting anyone to share for free until then.

**Comment by AudriusButkevicius** [comment]
It's not clear what you are after. If its support, use the forums.

**Comment by DASHdatamover** [comment]
was simply a positive comment. I will refrain from providing input in the future. 
apologies.


Doug Mielke 
+1 818 321 3275 | Skype: dougmielke

**Comment by vfugal** [comment]
A setting that would answer almost all issues here is a simple field to enter subnets on which throttling will not apply, or that will be considered "local".

I have a use case where there are several subnets but only one of them is "remote" and needs throttling between it and the others. Even allowing a single subnet to be set as local would be helpful, though allowing multiple subnets would be more so.

Perhaps have the checkmark on whether to throttle "local" and by default "local" means devices discovered by local discovery and/or within the same subnet (e.g. direct route without a gateway to the destination). Then entering "local" subnets would change or add to what is considered local for that checkbox.

I'm willing to try contributing some code for this if others think it's a good idea, though I don't know anything about go specifically.

**Comment by AudriusButkevicius** [comment]
I think tgere already exists an extra field for including extra subnets as lan. i guess you could add the inverse

**Comment by calmh** [comment]
@vfugal this is sadly undocumented and due to #2267 not visible in the advanced settings, but you can add

```xml
<options>
 ...
 <alwaysLocalNet>192.168.42.0/24</alwaysLocalNet>
 <alwaysLocalNet>10.23.0.0/16</alwaysLocalNet>
</options>
```

to your config and these will be considered local.

**Comment by vfugal** [comment]
That's good enough for me. Thanks!

Incidentally, I also found another undocumented option, <device certName=... />
:smile:

**Comment by lapo-luchini** [comment]
IPv6 local addresses could be there by default. (?)
e.g. `[fe80::204:abc:abc:abc%eth0]`

**Comment by lapo-luchini** [comment]
Uhm, during the startup it seems to see that as a local network by default:
`INFO: Local networks: 192.168.2.22/24, fe80::abc:abc:abc:abc/64, `
but it was still (exactly) limiting to 128 KiB/s (as configured in the options).

**Comment by AudriusButkevicius** [comment]
Also, do this on the forum as that is where we handle support.
