### ISSUE TITLE
Directory auto-complete is case-sensitive

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1347]
auto-complete for directories is a really helpful feature, please make it case-insensitive

```
c:\A
c:\B
c:\C
```

typing "c:\b" results in

expected
`c:\B`

**Comment by calmh** [comment]
(file system specific though)

**Comment by dzarda** [comment]
Maybe I'll have a look at this during the weekend, just to get my head around it.

**Comment by dzarda** [comment]
The matching currently works using [Glob](http://golang.org/pkg/path/filepath/#Glob). This is the culprit, since this is always case-sensitive. It would be rewritten.

Also, is a condition `runtime.GOOS == "windows"` a good enough approximation of "file system specificity" ? I mean, how can I _easily_ and _quickly_ detect if a path is on a case-insensitive partition?

**Comment by calmh** [comment]
You probably can't, but the system type is a good approximation, and probably an even better approximation of what behavior the user expects (i.e. a Linux user is probably not shocked if she gets case sensitive completion on a FAT filesystem; her shell will do the same).

**Comment by sciurius** [comment]
The best test is to create a dummy file FooBar.txt and check for the existence of foobar.txt .

**Comment by calmh** [comment]
A folder may be on a read only filesystem (if the `.stfolder` file has been created manually), or may span filesystems for that matter. But yes, we could do a probe. I've considered it as well for things like whether we should use IgnorePermissions or not etc.

**Comment by edsonmedina** [comment]
Shouldn't a fix for this be done in `Glob`'s repository instead?

**Comment by bennofs** [comment]
shoudn't auto-complete be always case-insensitive? Even if I am on Linux, I usually don't have files that differ only in case so it still can be convenient to only type lowercase to match an uppercase file. Since this is only auto-completion, I think that should be fine as long as we sort exact matches before "fuzzy case" ones?

**Comment by AudriusButkevicius** [comment]
Agree, but this needs a custom implementation of globbing.

**Comment by bennofs** [comment]
OK, i'll try to impment this then
