### ISSUE TITLE
Let people run relay's

### ISSUE THREAD

**Issue by geir54** [syncthing/syncthing#1364]
It would be a nice future to let people run as a realy for other people. This would remove the getting through nat problems. I would have no problem letting others use some of my bandwidth.

**Comment by kozec** [comment]
And make you liable for whatever stuff I decide to transfer under some jurisdictions ;-)

**Comment by geir54** [comment]
Would that be a problem as long as you don't store or decrypt any thing.
There is no way to prove you knew there was any thing illegal in the data

**Comment by calmh** [comment]
This could be done, but requires some integration around discovery and maybe some protocol extension to handle some aspects of. In rough terms, I could envision it like this, given two devices A and B and a relay R;

 - A connects to R
 - R sets up a listening port that is specific to A, and announces this to the announce server
 - B looks up A in the announce server, and gets the address to the above port on R
 - B connects to R
 - R shuffles bytes to and fro so that A talks directly to B

Maybe, possibly, this could be done without any changes by just writing up R correctly. It can't respond to A when it connects, because it has no (correct) certificate to offer, so probably A will timeout and reconnect repeatedly. This may be fine.

The first step ("A connects to R") would need to be either by manual configuration or something else, since R hasn't announced for B at that point...

**Comment by calmh** [comment]
Btw, in case both nodes can do manual configuration towards the given relay, then the relay in question is like 15 lines of code.

**Comment by Zillode** [comment]
@calmh you beat me to it. I tested it using https://gist.github.com/mike-zhang/3853251 and it works.

**Comment by calmh** [comment]
Apparently that idea doesn't work two well, but you'll get two client sides in the TLS handshake.

```
[I6KAH] 11:37:36 INFO: TLS handshake: tls: received unexpected handshake message of type *tls.clientHelloMsg when waiting for *tls.serverHelloMsg
```

There needs to be some code changes to support such a relay.

**Comment by AudriusButkevicius** [comment]
I guess we could have a special set of relay servers configurable in syncthing which act as discovery servers (defining which clients they have online), where all clients connect to them and export a server side socket on them.

**Comment by geir54** [comment]
I'll try to set something up when i get home :)

Pretty new to syncthing, does it use TCP and UDP? Is this described any where?

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/specs

You'll need a change to syncthing to make it work though.

**Comment by geir54** [comment]
Nice I'll look in to it and see how far I get :p never used go so a quick
way to learn it

**Comment by geir54** [comment]
I've startet playing with the code.

I think the first step should be to make the client know if it can be connected two (from the outside). Should be able to use the anounce server for this. The anounce server should also know so it can tell other clients.

**Comment by geir54** [comment]
I'll be going away for a while, so looks like I will not be able to get far on this

**Comment by merlink01** [comment]
What's about switching to UDP and do some hole punching.
In the Tox Project this runs really reliable and no portforwarding is needed.

**Comment by prestonwii** [comment]
I've been looking into this problem and my thought it is extend the protocol and allow a device (A) to communicate to device (B) via a intermediary device (R) that is trusted by both device A and B. My thought is that device R will relay a raw TLS encrypted packets that are destined for device B. This might not be as simple as I think it will be because I don't know how easy it will be to negotiate the connections and such over this relaying mechanism. When I get a spare moment (and go through and understand the syncthing code), I'm going to try to throw something together.

**Comment by calmh** [comment]
@prestonwii It's doable. The proxy could be simple enough to just tie two incoming TCP connections together. The problem you run into is mentioned above - the TLS negotiation isn't symmetric, so two syncthing's both connecting out won't be able to talk to each other, one of them should play the "server" role (accepting the connection). This could be worked around by a config on syncthing to switch the roles around, i.e. connect out to the proxy but from a TLS point of view pretend the connection was incoming. In that scenario one of the devices need to be aware that there is a proxy involved and be configured to play the server role; the other device would not need to know and would just connect to the proxy as usual.

**Comment by prestonwii** [comment]
Those were pretty much my thoughts, one syncthing instance would connect to the relay (or proxy) and tell it that it wants to relay the connection to another device. If the relay device is configured to trust the other device (and already has a connection to it), we can create a connection to that device. It would result in two TLS connections, one between device A to device R and one between device R and device B. Device A is aware of the relay and device B doesn't need to be aware of it (but still could be). I think I'm going to have to play around with code to figure things out. Do you have any sample code for things you've already tried so I can get a good idea on where to start?

**Comment by calmh** [comment]
Actually I wasn't thinking of anything as advanced as that, although it would be nice as it sounds like you may not have to configure the proxy specifically (if the devices tell it who they want to talk to etc). I don't have any relevant code here, sorry. :/

**Comment by prestonwii** [comment]
I'm close to having something working and basically I've settled on opening another port for relaying. After connecting to the port, the device will request a relay be created to a particular device ID. If the relay host is familiar with both the connecting host and the host that the connecting host is requesting a relay to, the connection will revert to a relay connection which we should be able to use as a connection for inserting into the model and getting a functioning protocol connection.

**Comment by prestonwii** [comment]
I've got this working now for trusted devices and they can connect to each other through another Syncthing node via another port (defaults to 22001). The problem that I'm having now that is a trust relationship for allowing others to relay through a Syncthing node is non-existent and it presents a variety of security issues. At the moment, the relay will take a DeviceID, look it up in its list of connected devices, and then set up the relay if it knows about the device. So the trust relationship is the fact that the relay device is connected to it and the device is part of its configuration. Removing this check, opens up the relay system to basically any traffic because there is no way to establish a trust relationship with another Syncthing device short of entering the DeviceID manually.

**Comment by amq** [comment]
syncthing is unusable for me without this.

**Comment by prestonwii** [comment]
I had something that worked, but it was of questionable value because it basically allowed connections to hosts, but it required a host that it could already connect to (making the relay kind of pointless). What is really needed, I think, is a global relay system, or the ability to allow others to relay via someone else (a non-trusted device, basically). The problem with this method is that it opened up a number of security issues that could have allowed spammers to basically get an open relay via a syncthing device. I was working on a method to verify syncthing hosts before creating the relay, but I started making a new protocol for verification, which I don't think would be a welcome change when it could be added to the standard protocol.

**Comment by rumpelsepp** [comment]
Just found this: https://github.com/syncthing/relaysrv
