### ISSUE TITLE
Allow "bad certificate warnings" to be hideable or verified

### ISSUE THREAD

**Issue by bnvk** [syncthing/syncthing#1380]
I recently configured Syncthing to run on a VPS server, as per good security, I checked the "Use HTTPS for GUI" setting to use  a self signed certificate.

However, now my other devices that sync with that VPS are littered with warning messages:

```
11:08:03: Bad certificate from MYYLVO (XXX.XXX.XXX.XXX:8080): x509: certificate is valid for Server, not syncthing
```

This is undesirable UX as it triggers the "something is wrong" response from a user, when in reality, it's not a danger. To me, it seems there are two possibilities:

* Add a way to "hide" this warning from the "device settings" area (easier)
* Add a some rudimentary instructions for a user to "verify" the fingerprint and then confirm (which does the above step)

**Comment by AudriusButkevicius** [comment]
It seems that you've borked up something up, as some random client (from port 8080) is connecting to your syncthing at the other end with a certificate which has not been generated by syncthing.

Syncthing's certificates have to have entity name `syncthing`, so I guess you've replaced the wrong certificate (protocol certificate rather than the GUI certificate).

**Comment by jkaberg** [comment]
Replace the certificate files in your config folder with ones thats verified and restart syncthing, problem solved :-)

**Comment by AudriusButkevicius** [comment]
@bnvk can you respond? Otherwise I am inclined to close as invalid.
