### ISSUE TITLE
Not possible to create Folder ID "watch"

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1387]
"The folder ID must be unique."

I wonder what other names trigger this.

From: https://discourse.syncthing.net/t/new-folder-the-folder-id-must-be-unique/1908

**Comment by cydron** [comment]
Solution #: I think can be solved in windowsby writing af filesystem filter driver (a really simple one) , because it usesanother IDbesidesthe file.

Solution 2  Patch Discourse code to translate paths to POSIX or standard format then hash the values with SHA, and run comparison operators on the hash output in  dictionay rather than thru string compares

(30 Encapsulating files 'in transit or processing into an intermediate container will slow down processing, but wll solve problems such as these.  robably the last resort fix at the moment to createa giant XFS container.

Note:  Bittorrentappendsall filesinnarchive together and sendsthedata all atonce.  themetadtatells the torrentclient how to put the  multiple filesack togetherlikepuzzlepieces.

**Comment by jpjp** [comment]
@cydron are you a bot? :)

**Comment by calmh** [comment]
@jpjp I can't reproduce, do we know what browser etc? I have a feeling this is a property auto-added by Angular or something like that in same cases (although angular specifically `$`-prefixes all it's stuff)...

**Comment by jpjp** [comment]
I'm reproducing the problem on Firefox. Shall I screencast it or something?

**Comment by jpjp** [comment]
![watch](https://cloud.githubusercontent.com/assets/6050800/6432551/d752839c-c055-11e4-9423-f882e40990f6.gif)

**Comment by calmh** [comment]
Yeah, I get the same in Firefox. But not in Chrome or Safari.

**Comment by calmh** [comment]
Classic javascript fail. Just missed the release, unfortunately... Thanks for helping to debug.
