### ISSUE TITLE
[UX] More verbose error reporting in webinterface

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing#1437]
First of all: I'm sure I read something along those lines a few days ago, but I just spent half an hour searching and couldn't find it. If it was in fact on github, feel free to close this one.

There are tons of errors which would be really helpful even to non-technical users. Mostly because it gives them something they can feed google with.

Some things which should be escalated to the web UI:

- Any reason why a folder was stopped.
- ~~Not sure if possible:  errors in programs which access syncthing via the api. For example the "no space left on device" error from syncthing-ionotify would be highly interesting to know about.~~
- ~~Failure to create port mappings via UPnP (this has cost me nearly two hours, because I've been debugging the wrong side :-( )~~

Please chime in with proposals for other errors which deserve their own yellow error boxes!

**Comment by kozec** [comment]
> Not sure if possible: errors in programs which access syncthing via the api. For example the "no space left on device" error from syncthing-ionotify would be highly interesting to know about.

This would require REST API that can client use to send error message and *that* would require client to be able to do anything catching error or even after crashing. It's not impossible, but can be done much simpler on client side.

**Comment by generalmanager** [comment]
@kozec As far as I can see this should already work:
>**POST /rest/error**
>Post with an error message in the body (plain text) to register a new error. The new error will be displayed on any active GUI clients.

From: https://github.com/syncthing/syncthing/wiki/REST-Interface

**Comment by Zillode** [comment]
2/3 are resolved:
- Any reason why a folder was stopped. "The folder isn't making progress. Check logs...." should become "The folder 'picts' isn't making progress because of an error. The error is: File picture1.jpg - permission denied while changing ctime of the file. Check file permissions, making sure the owner of the Syncthing process is allowed to write to the file"
- ~~Not sure if possible: errors in programs which access syncthing via the api. For example the "no space left on device" error from syncthing-ionotify would be highly interesting to know about.~~
- ~~Failure to create port mappings via UPnP (this has cost me nearly two hours, because I've been debugging the wrong side :-( )~~

**Comment by generalmanager** [comment]
@Zillode Thanks for the update. I modified the original post to reflect the current state of development.

**Comment by djtm** [comment]
How about linking error messages to a web page with a summary of more information on what may cause the current error. That could be very helpful and user friendly.

**Comment by generalmanager** [comment]
Good idea, we could use the github wiki for that.

Am 30. Mai 2015 08:57:52 MESZ, schrieb djtm <notifications@github.com>:

**Comment by generalmanager** [comment]
Awesome, thanks!

Will take a closer look when I'm less busy ;)
