### ISSUE TITLE
"Do not send changes" flag for trusted read-only nodes

### ISSUE THREAD

**Issue by StrikerTwo** [syncthing/syncthing#1439]
I originally brought this up in #62.
I'd like to have a flag "do not send changes" that I can set on a node per folder. This would be the opposite of the Master flag, which is really a "do not receive changes" option.

The use case would be trusted nodes that only exist for backup and/or relay purposes. Any local changes on these nodes are accidental and not to be propagated to the rest of the cluster. Optionally they could be overwritten automatically during the next sync.
This is NOT intended to share files with unsecure/untrusted/malicious nodes, because there is nothing to stop people removing that flag and reverting to a full access RW node. This is just a simple workaround in order to have more than one Master for the repository. The effort to implement this should be little more than a checkbox and an if clause. (I still haven't had time to learn Go, otherwise I'd try it myself :) ) 

See https://discourse.syncthing.net/t/infrastructure-syncing/1978 for a similar proposal.

**Comment by bencurthoys** [comment]
I would add (and I'll add it here for the avoidance of strife, though it's W.R.T. #62 =):

Suppose we do think of a way of reliably and securely determining whether a node should be read only, in order to solve #62 properly. 

That information will be used to control whether node A accepts or rejects changes from read only node B (this is the security), but we would also use it on node B to control whether or not to send changes (for the sake of efficiency). We can't rely on node B to be honest, but in the 99% of the time that it is, it should not send changes that it knows are going to be ignored - apart from anything else, that would be a horrible waste of bandwidth. 

Therefore, in a complete solution to #62 we'll require code that makes node B act in a read-only way. All this issue requires is a tickbox to insecurely and manually activate this behaviour in advance of having a secure way of enforcing this behaviour. Implementing this won't be waste, because it will be required anyway eventually.

**Comment by lfam** [comment]
If this capability is added to Syncthing, I suggest presenting it to the user like this. I have found every other explanation of this functionality difficult to read.

Toggles on each device/folder pair:
read from the cluster y/n?
write to the cluster y/n?

**Comment by generalmanager** [comment]
@lfam Yeah that seems like a sensible way to phrase it!

**Comment by lfam** [comment]
And that would also subsume the "Master mode" switch.

**Comment by gijs007** [comment]
Exactly, so this would be more like a bandwidth saver to prevent files from being altered and then having to be resynchronised. As well as automating the resynchronization process if the files have for some reason been edited.

**Comment by calmh** [comment]
This is implemented
