### ISSUE TITLE
Skip temporary file creation if lacking permissions

### ISSUE THREAD

**Issue by 80tf3262p8** [syncthing/syncthing#1461]
This may be related to: https://github.com/syncthing/syncthing/issues/1126

I noticed a minor problem with writing the ignore preferences from the GUI. Even if syncthing has permissions to edit .stignore, the fact that it tries to write to a temporary file first -- e.g., .syncthing.stignore-sharename123456789 -- prevents it from happening, if syncthing doesn't have write permissions for that folder. (I'm trying to set up a read-only share, where syncthing will simply observe the folder for backup purposes, and has limited permissions to that folder, since it doesn't/shouldn't need them.)

I can still edit .stignore just fine with vim. I bring that up because I know vim attempts to write to a backup file first, yet it can still handle writing with no complaints when there's no permission to create a backup file. I don't understand the mechanisms behind that, but it could be a simple exception case.

I can't think of the best solution, since temporary files are used for a good reason... If the syncthing configuration files were confined to their own specific folder, either a subfolder or elsewhere, it would be easier to handle situations like this, but not necessarily elegant...

I left the subject vague, since I don't know if it'd be desirable to extend to other situations, like synchronizing. That seems like it could be a bad idea, to me.

**Comment by AudriusButkevicius** [comment]
Why not just use the master feature?

**Comment by 80tf3262p8** [comment]
I am using that feature... The concern is just not wanting to give any server application more access than it needs. It doesn't need to write, so it shouldn't be allowed to... except to specific files, but that's where this minor issue comes in.

On March 13, 2015 1:01:04 PM PDT, Audrius Butkevicius <notifications@github.com> wrote:
>Why not just use the master feature?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/1461#issuecomment-79317492

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AudriusButkevicius** [comment]
Well, if you don't want syncthing to write anywhere, then don't modify ignore patterns...
Or allow syncthing to do it's thing if you want to modify them...

You yourself know that you are enforcing some state which is breaking the functionality, and ask us to change the functionality, rather than loosening up the restrictions you impose.

AFAIK, this is the only way to do things atomically, write to file, move it to the destination place.
You cannot do that across different filesystems, hence you cannot rely on temp directories etc.

Part of this might get fixed by #1056, but not relying on temp files, I personally feel is a won't fix.

**Comment by 80tf3262p8** [comment]
Fair enough... I think a good solution would involve not storing such a file in a "read-only" location in the first place. Regardless, I don't think this is an unreasonable thing, but it is so minor that I understand not wanting to devote development effort to it, from a wider perspective.

That said, if I created a patch that allowed the .stignore file to be written to, even if there is no permission to make the backup file, would it be rejected off the bat? I just think it would bring the behavior more in line with other software (like vim) where the inability to create a same-directory temp file doesn't entirely break the ability to save that file, which is rarely a desired behavior, especially for something as simple as an ignore list.


On March 13, 2015 3:00:56 PM PDT, Audrius Butkevicius <notifications@github.com> wrote:
>Well, if you don't want syncthing to write anywhere, then don't modify
>ignore patterns...
>Or allow syncthing to do it's thing if you want to modify them...
>
>You yourself know that you are enforcing some state which is breaking
>the functionality, and ask us to change the functionality, rather than
>loosening up the restrictions you impose.
>
>AFAIK, this is the only way to do things atomically, write to file,
>move it to the destination place.
>You cannot do that across different filesystems, hence you cannot rely
>on temp directories etc.
>
>Part of this might get fixed by #1056, but not relying on temp files, I
>personally feel is a won't fix.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/1461#issuecomment-79458744

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AudriusButkevicius** [comment]
Technically, that could break things because one thread has truncated the file and is now writing to the file, while another thread is reading from the file and only getting part of the final content, suddenly ignoring all of your files because the last two characters the other thread has written was `\n*`.

In practice, I feel we have locking around reading and writing ignores, hence the above should never happen.

I don't think this is a pain point for the community, nor do I feel that anybody else has the usecase you do. But given you are willing to invest your time, personally I wouldn't care too much about having this fallback. I guess we should see what @calmh has to say, perhaps he has a strong feeling about this.

**Comment by calmh** [comment]
I think this may be related to #1126 in that we could/should handle syncing of directories where we don't have write permissions better.

**Comment by calmh** [comment]
We use temp files for all our file operations. This is good because on unixlike OS:es renames are atomic, which means that there is one version of the file on disk and in the next instant it is replaced with another version of the file. If we write directly to the file there is an intermediate state where it is not valid. This is when we can be hit by the disk being full, or just plain the computer shutting down. In that case, the remaining file contains bad data. We don't want that happening to user files, the configuration or the ignore patterns. So I think this is a `wontfix` for now.

However, we may redesign the ignore system in the near future, and at that point I'd expect us to move the patterns into the config instead, which would resolve this specific use case.

**Comment by 80tf3262p8** [comment]
Understood... Works well enough for me. Thank you.
