### ISSUE TITLE
Implement scheduling

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1477]
So that it's possible to enable syncing for example "only over night", or during weekend, etc.

**Comment by AudriusButkevicius** [comment]
Just use a OS task scheduler to start and stop syncthing?

**Comment by benapetr** [comment]
What do we have that nice webgui for then? We could technically use CLI or OS features for everything that it already provides now

**Comment by benapetr** [comment]
Also, AFAIK syncthing can be easily started with OS scheduler, but how do I stop it (kill -9?)? And how do I know when should I stop it?

**Comment by AudriusButkevicius** [comment]
We have the web UI to be simple enough for normal users to understand, and not burden them with scheduling.

You stop by sending SIGTERM (15), at the point it goes out of the scheduled time.
If you want to be more clever, and allow it finish syncing before you kill it, you can query  /rest/completion interface for the percentages, or track /rest/events for completion events.

I am sure we would consider accepting a pull request given someone has fleshed out the GUI and implemented properly, but I am definatley not spending any time on this. There are many more useful features not implemented which would benefit the masses rather than individuals.
And as I said, none of the existing solutions implement this (meaning there is not really enough usecases of this), hence I don't see why should we.

**Comment by dzarda** [comment]
While I agree that this would be nice, I don't really see the hard evidence for it. We are trying to be more like Dropbox, rather than uTorrent. / Agreed with @AudriusButkevicius.

**Comment by benapetr** [comment]
I think that especially regular users would benefit from this, as regular users have no idea how to hack out some OS level solution.

Anyway, if you don't want to implement this, it's ok (you can still leave the issue open for some other devs to grab?), but maybe you could at least implement some switch for main process so that it exit after it finishes syncing. Because using cron and then in loop keep grepping some logs and issue kill after I find something in them is just a horrible solution.

**Comment by dzarda** [comment]
Actually, there is the following REST command available:

    POST /rest/shutdown

Use this, if `kill -15` seems too aggressive (I don't think it is.)

**Comment by benapetr** [comment]
Ok, but that still doesn't tell me when I should run it? There just should be option to run-once so that it sync and exit. Without such option any attempts to script this would be horrible hacks only.

**Comment by AudriusButkevicius** [comment]
Just use rsync in that case?

**Comment by benapetr** [comment]
rsync is not bidirectional sync sw

**Comment by AudriusButkevicius** [comment]
Ok, then use csync or unison, which can be invoked on demand?

**Comment by jpjp** [comment]
Related: https://discourse.syncthing.net/t/sync-only-on-scheduled-time-hours/859

**Comment by calmh** [comment]
`wontfix` currently; clean pull requests will of course be considered, as always.
