### ISSUE TITLE
All kinds of problems trying to sync between MacOSX and android

### ISSUE THREAD

**Issue by timuckun** [syncthing/syncthing#1554]
Fresh install of syncthing in both android (oneplus cyanogen 11S) and Mac (Yosemite). 

Launched both apps, entered the device ids in both machines.   Share the drive /storage/emulated/0 with the mac.

Problems:

Mac is unable to open up UPNP (20:07:10: Failed to create UPnP port mapping).

Lots of messages like this on the console indicating it can actually see the phone though.

[64JEL] 00:01:47 INFO: Update for unexpected folder ID "emulated~1" sent from device "XXXXXX"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
[64JEL] 00:04:09 INFO: Connection to XXXXX closed: read tcp 192.168.20.3:43058: connection reset by peer

I then try to delete the folder on android it says it has to reboot, I click OK  at which point it spins forever with the message "waiting for API".  If I kill it manually and relaunch it I get the same message.

**Comment by AudriusButkevicius** [comment]
The UPnP is just a warning, and the error is sort of self explanatory (perhaps the issue is that the settings you've setup via the app did not save) and not a bug.

You can access the web UI on the phone too, in case you are struggling with the app.
Make sure the device which you added is visible from the phone's web ui too.
The waiting for api bug is https://github.com/syncthing/syncthing-android/issues/279
Also, any android bugs should be reported there, which I guess which is this ticket is about.

I don't see anything related directly to syncthing in this issue though.

**Comment by timuckun** [comment]
I installed sync thing on my other laptop to see if I can get IOS to IOS sync and am still having lots of problems, see https://discourse.syncthing.net/t/all-kinds-of-problems-running-syncthing-on-macosx-and-android/2361

I think there is a problem with syncthing and a lot of files on macosx.

**Comment by AudriusButkevicius** [comment]
Switch off the web ui or try the beta for the speed issues.

**Comment by AudriusButkevicius** [comment]
Is this still an issue?

**Comment by timuckun** [comment]
Yes it's still an issue.

Today I downloaded 11 beta4 on both macs and fired them up, I did not keep
the web UI running but I did fire it up occasionally to check on what was
happening.   Immediately the fan on the sending machine started racing as
the scan of the home folder pegged the CPU. The receiving machine CPU was
OK (syncthing using less than 30% most of the time occasionally spiking up
to 70% or so) but the disk io usage was spiking on and off effecting the
performance of other apps.

After about a half an hour of scanning the sending machine was reporting a
global state of 39 Gigs of roughly 100 gigs.  This is on a MacBook Air with
SSD drives.

My home dir is full of small files (Most of it is source code and git
repos) but there are a few virtual machines in there as well.

**Comment by AudriusButkevicius** [comment]
So it will fully utilize the CPU while it finishes indexing.
Indexing involves crypto, hence the CPU usage, and on a weak low power CPU this is just expected.

This also means reading all the files off the disk, and given there is a large amount of small files this is especially noticeable.

I suggest you use nice/ionice to put syncthing on lower priority and let it finish it's thing.
I think the performance you are seeing might be `working as intended` due to us having to use crypto.

Secondly, you shouldn't sync git repos as you are bound to corrupt them.

**Comment by timuckun** [comment]
Just FYI. I let it run for about an hour and a half. It did finish the scan
eventually and started slowly syncing but the battery died.  Normally I can
get all day battery use from the macbook air so your advice about nicing is
pretty much mandatory and should be highlighted in the docs.

Having said that if I can't sync my git repos that definitely puts a
obstacle in my way.

**Comment by AudriusButkevicius** [comment]
It's not that you cannot, you can.
Git creates metadata files all over the place, if you start syncing repos from two separate machines, the metadata will start blending together from two separate machines and can eventually potentially corrupt the checkout.

This is not a flaw of syncthing, as using dropbox or btsync can have the same catastrophic disaster.

**Comment by calmh** [comment]
The problem here seems to be that we use a lot of CPU during hashing and drain the battery, which is true and not something we can/will change in the near future. Please yell to reopen if I've misunderstood.
