### ISSUE TITLE
Unchanged documents showing as Out of Sync and not making progress

### ISSUE THREAD

**Issue by pluby** [syncthing/syncthing#1566]
I have some very old unchanged documents replicated between FAT (no permissions) on Android and ext4 on Linux. Regularly, files that have not been changed (for years), show their original timestamps and when compared in KDiff3 show as being binary equal, show up as "Out of Sync" in the UI and the folder reports that it's not making progress. I'm fairly sure this doesn't happen on EXT4-to-EXT4 but I can set up a test if it would help.

In the logs there's a message saying that the file is not available on the device:

```
[SQPTT] 11:54:56 INFO: Puller (folder "pictures", file "2011/2011-11/IMAG0336.jpg"): pull: no available source device
[SQPTT] 11:55:03 WARNING: Folder "pictures" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
```

Deleting the index on by desktop, where these messages appear, has no effect. Touching the files seems to solve the problem.

PC Version: 0.10.30
Android Version: 0.10.29

**Comment by AudriusButkevicius** [comment]
I feel this is: https://github.com/syncthing/syncthing/issues/831

Android does not support mtime changes, hence whatever gets sent to android gets it's mtime bumped, causing `out of sync` on the metadata.

The no available source is something else, the last device which had the file has gone away.

**Comment by pluby** [comment]
I only get the "no available source" when my Android is connected, and the file (binary equal) is same on all my devices - there are no devices that have gone away - so I don't think that explains this error in this particular case.

On the mtime issue: Maybe it's not practical to assume that we can compare local with global. Instead we could keep a database of last-known local values and only consider the file changed if they differ. Would that solve the problem? I've had similar thoughts about escaping filenames for local compatibility, but that's for another day.

**Comment by AudriusButkevicius** [comment]
Can you do a get for:
```/rest/filestatus?folder=<folder>&file=<relative path from folder root>```
and provide the json output?

**Comment by pluby** [comment]
On my desktop:

```
{
  "availability": [
    "id-of-my-phone"
  ],
  "global": {
    "Name":"2011/2011-11/IMAG0458.jpg",
    "Flags":33206,
    "Modified":1410372178,
    "Version":6161931,
    "LocalVersion":160437,
    "Blocks":null
  },
  "local": {
    "Name":"2011/2011-11/IMAG0458.jpg",
    "Flags":33206,
    "Modified":1410375778,
    "Version":2261,
    "LocalVersion":2257,
    "Blocks":null
  }
}
```

On my phone:

```
{
   "availability":[],
   "global":{
      "Name":"2011/2011-11/IMAG0458.jpg",
      "Flags":33206,
      "Modified":1410372178,
      "Version":6161931,
      "LocalVersion":160437,
      "Blocks":null
   },
   "local":{
      "Name":"2011/2011-11/IMAG0458.jpg",
      "Flags":33206,
      "Modified":1410372178,
      "Version":6161931,
      "LocalVersion":160437,
      "Blocks":null
   }
}
```

**Comment by AudriusButkevicius** [comment]
Does you phone say that you are connected to the desktop?
Does the desktop share the folder with the phone?

**Comment by AudriusButkevicius** [comment]
Does it say connected in the webui (rather than just the app)?

**Comment by pluby** [comment]
Yes, both connected to each other at the time that I did the rest query.
When they're not connected the problem doesn't occur.
Both share the folder with each other, neither are set as master.
All checked in web UI.

**Comment by AudriusButkevicius** [comment]
it seems that the phone never sends it's initial index.
Are you syncing a lot of data? Perhaps the phone is very week, or the network link is very poor?

**Comment by pluby** [comment]
It's an HTC One M8 on home Wi-Fi, IP addresses shown are all on my local subnet. This folder in this example is about 2.86GB in 1650 files, but the initial sync went file and there's been nothing to do for days. It's also happened on a 387MB folder in 1555 files.

Note this affects the odd file or a handful of old files now and then, not a block of files. One thing I'm wondering is why the phone thinks it has a new file in the first place, it's not like the file is new to the phone, the files that suffer all seem to be ones that were sync'd ages ago.

**Comment by bnjmnwe** [comment]
I have a similar problem when trying to sync a folder between Windows (Master repository) and Android. Windows always offers "Override Changes":

![unbenannt](https://cloud.githubusercontent.com/assets/4201484/7441209/98150692-f0dd-11e4-99cd-5cb5afb2a2fe.PNG)

And on Android the progress of the Windows Device gets stuck at a specific percentage, although the folder shows that it is in sync:

![screenshot_2015-05-02-13-47-22](https://cloud.githubusercontent.com/assets/4201484/7441215/e2cb27ca-f0dd-11e4-80d2-907ce6294883.png)
![screenshot_2015-05-02-13-47-33](https://cloud.githubusercontent.com/assets/4201484/7441216/e2d287e0-f0dd-11e4-8ce0-8eebe776071f.png)

This happens directly after initial sync, without any changes made on any side. In addition, it does not seem to depend on the files: When I delete the folders/indexes and add them again, the same thing happens but with different files being out of sync. Hitting the "Override Changes" button temporarily causes the devices to be in sync, but after some time the issue occurs again, with other files.

I don't think that it is the mtime-issue, since mtimes are synced sucessfully and I don't get any warnings about that.

It happens with both the 0.11.1 version and various 0.10 versions.

If I don't set the Windows-Node as Master repository, the problem does not seem to occur.

Using the `browse` rest command, there are differences in the times, but I think it's only the textual representation (e.g. Windows: `"2015-01-22T20:21:13+01:00"`, Android: `"2015-01-22T19:21:13Z"`).

The lists in the answers to the `need` rest command are empty on android, on windows it shows
```
{
   "page":1,
   "perpage":65536,
   "progress":[

   ],
   "queued":[

   ],
   "rest":[
      {
         "flags":"0100666",
         "localVersion":48,
         "modified":"2015-01-22T20:21:13+01:00",
         "name":"8420357776_tom odell another love (dimitri vangelis   wyman remix).mp3",
         "size":8263470,
         "version":[
            "3532595485729995469:1",
            "18420076125609683454:1"
         ]
      },
      {
         "flags":"0100666",
         "localVersion":49,
         "modified":"2015-01-24T13:50:04+01:00",
         "name":"Dash Berlin feat. Roxanne Emery - Shelter (Solis \u0026 Sean Truby Remix).mp3",
         "size":15495835,
         "version":[
            "3532595485729995469:1",
            "18420076125609683454:1"
         ]
      }
   ],
   "total":2
}
```
Any ideas what is happening here?

**Comment by calmh** [comment]
This is a know issue with Android. Basically, Syncthing can't set file time stamps on Android, so files are detected as "changed" even though they are not. Your best bet in this case is to simply ignore the red button.

**Comment by bnjmnwe** [comment]
Thanks for the quick reply :)

Are you sure that this is the reason here?

As I wrote before, I don't get any warning about that in the log. In addition, when I change the modification time on windows, it gets correctly synced to Android, so it looks as if my rom supports changing the modification times.
