### ISSUE TITLE
Android app: Option to exclude hidden files

### ISSUE THREAD

**Issue by anoteng** [syncthing/syncthing#1640]
The android app should have an option to exclude hidden files. Sometimes there are hidden files in the android filesystem that generate permission errors.

Also these permission errors will make syncing stop, and the rest of the folder contents is not synced.
![screenshot_2015-04-14-15-25-22](https://cloud.githubusercontent.com/assets/1189986/7137536/b89c6846-e2ba-11e4-9393-976d28d6dde6.png)

**Comment by AudriusButkevicius** [comment]
So first of all, this is the wrong repo:
https://github.com/syncthing/syncthing-android/

Secondly, there already is a way to hide hidden files or whichever files you want.
Read the Getting started guide/FAQ or the Wiki:
https://github.com/syncthing/syncthing/wiki/Ignoring-Files

Lastly, syncthing requires write access to the directory in order to create a marker file to detect mount failures, so this specific hidden file is actually created by us, and we don't seem to have permission to do so, hence why stuff fails.
