### ISSUE TITLE
The function of sharing

### ISSUE THREAD

**Issue by 3DRaven** [syncthing/syncthing#1691]
Great program! Lacks the ability to provide the address of a file or folder for public access. If you have done it, I would have thrown dropbox and mega! 

Objective:
0. I Open URL and set password to it.
1. A user receives a URL to the resource.
2. We go to URL and downloads a file from my computer.
3. I close URL

This can be done as in mozilla Hello chat (for example)!

**Comment by AudriusButkevicius** [comment]
Just run a webserver which exports your files.

**Comment by 3DRaven** [comment]
If Resource Publishing will not be, dropboks better.

**Comment by AudriusButkevicius** [comment]
Feel free to use Dropbox, we are not trying to compete.

**Comment by Spellshaper** [comment]
Raven, if you are looking at pushing files out to users, there are several existing solutions that do what you want.
On Windows there's [Rejetto's HFS](http://www.rejetto.com/hfs/) which uses http,
on Linux you might want to take a look at ftp with a UI. (Haven't looked at it in a while, but ProFTPD with GAdmin might work.)

**Comment by jkufner** [comment]
On Linux, you don't need any specialised tools. Just install ordinary
webs server (Apache, Lighttpd, Nginx) and point its document root to
shared directory. It is that simple.

**Comment by 3DRaven** [comment]
I think your program would be a lot more users if you wrote "it is only your personal dropbox!". Need users?

**Comment by Spellshaper** [comment]
As far as I understand it, the biggest allure of this project is its promise of privacy and security, and this promise being verifiable through all being open source.
Why throw all that privacy to the wind by serving files to the web? This does not seem to be a goal of this project and will probably not be supported as a built-in functionality.

That said, all the necessary tools for your use case exist already and are freely available. Your solution is just a couple dozen clicks away instead of one, no command-line shenanigans or other complicated stuff involved.
Do it. :smile:

**Comment by 3DRaven** [comment]
I'm just a user. But given me publishing links to files / folders that I can close the back, accessed by a password, this privately.

**Comment by calmh** [comment]
I agree this would be useful, but it's hard, complicated and a lot of work to do right (especially given there is no central server, and you might have a dynamic IP and firewall and so on). There are other solutions to this problem already. I don't think it's in scope for syncthing.
