### ISSUE TITLE
Syncing stuck at 76% on one side

### ISSUE THREAD

**Issue by jchia** [syncthing/syncthing#1693]
Syncing is stuck on one side. The other side is done. The unstuck side is master of a folder that has a red "Override Changes" button. I don't recall doing anything in the user interface or explicit control of syncthing to cause that button to appear.

So, the surface issue is how to get unstuck. Something like this has happened before and I got unstuck by clicking on the red button. I'm not clicking on it just yet in case we need to do any triaging.

The real issue, I think though, is why I can inadvertently get into such a weird state in the first place. There have been lots of issues of people getting stuck synchronization. I haven't seen all of them but the few that I've seen ended up with people doing some non-obvious workaround. For my case, I have to say it's a confusing problem with a non-intuitive workaround. Is there a bug with the synchronization protocol itself that makes such events unavoidable? Or is it a bug with the implementation of the protocol?

**Comment by AudriusButkevicius** [comment]
It's not a bug, it's probably lack of understanding how master mode works.
A is master, B is not master.
A adds some files, B syncs files from A.
Both A and B sees each other in sync.
Later B modifies some files, which makes it see A out of sync (as A refuses to accept updated since it's master)
On the other side A sees B out of sync (and an override changes button) because B has newer versions of the files which A refuses to accept because it's master.

**Comment by AudriusButkevicius** [comment]
Please reopen if I am misunderstanding the issue.

**Comment by jchia** [comment]
On the stuck machine, the log doesn't indicate the reason for getting stuck. There's only the standard stuff aboutt completing scans and connecting to peers.

**Comment by AudriusButkevicius** [comment]
I've explained to you what stuck means, the fact that it does not reach 100% is normal, given one node is master.

**Comment by jchia** [comment]
I get it, I'm just saying that from B's perspective, it's not clear why it's stuck since the the only clue is the "override change" button on A's UI. B may have changed files accidentally (e.g. opening some office-type document with an app that changes some metadata whenever it's opened). It may be clearer to B's user if B's UI has a button "Abandon changes", perhaps with a popup confirmation dialog that achieves the same effect as A. Also, it may not be convenient for B's user to ask A's user to do the "Override changes".

**Comment by AudriusButkevicius** [comment]
Yeah, I agree, but I think there already is a ticket for something similar.
Plus, we are not actually sure if other nodes have the master option enabled or not, so 'Abandon changes` might not make a lot of sense, given the reason stuff is out of sync can be because of two reasons, master mode enabled, and some files simply being ignored, in which case you cannot really abandon changes.

**Comment by jchia** [comment]
Good point. Well, then this could be another case to include in #1437.
