### ISSUE TITLE
Wrong deleting old files with "Staggered File Versioning" option

### ISSUE THREAD

**Issue by Shishking** [syncthing/syncthing#1738]
ST doesn't see difference between files with the same names but different extentions when deletes old files with "Staggered File Versioning" option.

**Comment by Zillode** [comment]
Could you provide some sample filenames?

**Comment by AudriusButkevicius** [comment]
I think the magic here is to blame: https://github.com/syncthing/syncthing/blob/master/internal/versioner/staggered.go#L45

**Comment by Shishking** [comment]
> Could you provide some sample filenames?
I experimented with test.txt, test.bak and test.ini for example

**Comment by calmh** [comment]
So, for the the record, what actually happens here when it fails to see the difference?

**Comment by Shishking** [comment]
*So, for the the record, what actually happens here when it fails to see the difference?*
In my case after several changes in all three files it deletes all versions of three files except one version of one of files (after some time).

**Comment by alex2108** [comment]
probably happens around here: https://github.com/syncthing/syncthing/blob/master/internal/versioner/staggered.go#L163
we probably ignore the extension here and still put everything together in a list, so if versions of `test.txt` and `test.bak` are in the same interval one of them will be deleted.

The part @AudriusButkevicius mentions can probably be removed now since it renames versions with old naming scheme which should not exist any more except someone upgrades from a really old version of syncthing which I doubt will happen too often. It's just a unnecessary walk of the versions dir for all users now.
