### ISSUE TITLE
Linux <-> android syncing generates back traffic

### ISSUE THREAD

**Issue by hhemul** [syncthing/syncthing#1777]
It seems syncing from linux (v0.11.0) to android (v0.11.2) generate back traffic. I.e. new file is sent from linux to android then that file is sent from android to linux as if it updated on android side. Upload and download rates was aprox. equals while syncing.
My case:
In initial state i had previosly synced folder. Then on linux side i copy new directory with aprox. 200 files to that folder. Then launch syncthing on android. While syncing many files on linux side was updated including new files. Moreover it seems linux machine recive the whole file content back not only the metadata.

**Comment by calmh** [comment]
Yeah, Android is broken in how it handles (or doesn't) mtimes, which we need to work around at some point. This is #831.

**Comment by hhemul** [comment]
It is not a feature request just a few thoughts to think about. mtime is a bad for syncing especially for syncing across many platforms. You can't determine which version of file is newer just because system clock can be wrong. And, yes, some platforms can handle mtime in very special way.
There are few patterns for tracking changes and 'mtime' is worst from them. It is program architecture issue. The most simple pattern - Version Vector (http://en.wikipedia.org/wiki/Version_vector).

**Comment by hhemul** [comment]
I'm sorry you already implement Version Vector in protocol (Local Version field?). But why mtime affect syncing? It should exist only for users to see time of modification.

**Comment by calmh** [comment]
It allows us to tell if the file changed since we last looked at it or synced it.

**Comment by hhemul** [comment]
I think that is an issue. Please imagine the case. File can be modified on any member of the cluster including android device. Important changes to file were commited on linux machine. On android device user accidentically change time and launch syncthing. It will overwrite important changes to version of file on android device for entire cluster. And also there is case of cooperative work which is imposible with current sync strategy. But if 'Local Version' would be more important than 'mtime' cooperative work would be possible.

**Comment by calmh** [comment]
No. We have conflict detection and handling. And I don't understand what you mean about cooperative work; we are not a merge tool. Please do some testing on how it actually works, and report any actual issues you detect rather than theoretical ones. But as I said, the mtime handling on Android *is* a problem, as you can see by the linked issue.

**Comment by rolve** [comment]
I also think this is a real issue because it's hitting me constantly. For example, yesterday I was working on a text file on my Windows machine when suddenly the text editor asked: "This file was modified externally, do you want do reload it?" When I hit "OK", I had an older version of the file in my editor. All my changes were gone! The only other device that I'm syncing with is a Android phone.

Similarly, when I'm working on a Powerpoint presentation, it's often happening that after I close Powerpoint, a conflict file appears and when I open the normal file again, my recent chances have been overwritten by an old version from the phone.

**Comment by Zillode** [comment]
Should we enforce 'master' on Android devices? It seems it causes too many issues...

**Comment by rolve** [comment]
'Master' is what I'm using at the moment (as a dirty solution to prevent further trouble), but I'm not sure this is a good idea in general, even in the short term. It would prevent data loss, yes, but it would make the android client much less useful. In the long term, this problem should be fixed for real if at all possible.

Should this issue be reopened?

**Comment by calmh** [comment]
No, as it's a duplicate, as stated above.
