### ISSUE TITLE
UI text explaining "Introducer" setting on devices is misleading

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing#1819]
Currently, the text reads:

> Any devices configured on an introducer device will be added to this device as well.

But that's not actually what happens.  If you have:
- Three devices A, B, and C
- A knows about B and C
- B and C only know about A (not each other)
- C has A configured as a introducer

Then C will only become aware of B if all three devices A, B, and C have _the same shared folder in common between them_.

The UI text appears to indicate that C would become aware of B regardless of any folders configured on any of the devices.  The text should be updated to make the actual behavior more clear.

**Comment by cdhowie** [comment]
Off the top of my head, this is more clear but possibly too verbose:

"Any devices configured on an introducer node will be automatically configured on this device if they have a folder in common with this device.  Common folders will be automatically shared with introduced devices."

**Comment by xHN35RQ** [comment]
I think an image describing the functionality should be created. In the meantime perhaps:

`An Introducer device helps devices connect to one another. It does this by looking for devices with the same shared folder, and introducing those devices to each other. Once the introduction is made, each device seeks to connect to each other directly.`

**Comment by go2null** [comment]
How about *Any devices configured on an introducer device will be added to this device as well, once they share the same folders as this device.*

Or *An introducer will add automatically devices that have share folders in common with this device.*

**Comment by bugith** [comment]
If I understand correctly after reading this \~bug\~ plus the documentation,
P_r_ being the Pairs list at Remote R side for Folder F_lr_ shared with Local L whose pairs list for F_lr_ is P_l_, setting R as an Introducer (let's then call R=I) will populate P_l_ with P_r_-P_l_ subset as long as R remains I, and only as a consequence of this wanted behaviour will the L_g_ local global list of known devices be populated with additional P_r_-P_l_ (to prevent "Folder {folderName}({folderID}) error : unknown device {deviceName}({deviceID})").
I leave beside what happens in the scenario when no longer R=I.
If I explained correctly, you see I've just understood Introducer concept :)
So it appears making the UI text less verbose is not possible (since clarification here requires the additional \~concept\~ of shared folder pairs list) without using a yet known algebra. This is worse if we want to anticipate the questions that raised to my mind when I first wandered what is this, namely the question of time : what will happen later if .....? For this I like the @go2null suggestion using the future (will). Maybe better, the verb could be _will update_, then it slightly addresses/raises questions about removal (both F_lr_ & L_g_ entries).

Or maybe, like we yet have elsewhere for other too complicated options to explain and fit in the GUI, a small "Allow device {deviceName}({deviceID}) to update **all** my shared folder's pairs lists whose it is yet a member with devices it knows and I don't" with a link to the documentation.

Fun to you
