### ISSUE TITLE
Folders path missing when folder path is a junction

### ISSUE THREAD

**Issue by Ascard** [syncthing/syncthing#1830]
Directory junctions is not working in win client. "Folder path missing" error shown. Junction was created from at same drive, Syncthing was started with admin rights.

**Comment by AudriusButkevicius** [comment]
You'll have to put the junction a level higher, as I think Go's stdlib doesn't deal with junctions.

**Comment by Ascard** [comment]
It seems to be working when junction located at root level. But this is not an option :(
Problem my be in internal\model\model.go at 1606 line :
```go
if err != nil || !fi.IsDir() {
```
I'm lame at Go, but it seems to that fi.IsDir returns false for junctions.

**Comment by AudriusButkevicius** [comment]
You could print out fi.Mode() to see which flags are set to see if it's identified as a symlink.

**Comment by Aeyoun** [comment]
Go 1.4 and newer treats junctions the same was as symlinks, as far as I can tell from reading through the Go bugtracker and changelogs.

One of the problem here lies with relying on Syncthing's internal symlinks.Supported bool. It assumes the user always wants to both create and read junctions, where as most of the time it's only useful to read them for unprivileged users. I've got little experience with Golang, but managed to strip out enough of these checks to make junctions work seemingly fine. Wouldn't trust to run this on actual data, though.

I humbly request prioritization of this for a proper cleanup. At least for reading (any user) if not creating new junctions (requires admin).
