### ISSUE TITLE
automatic acceptance of syncs

### ISSUE THREAD

**Issue by skandragon** [syncthing/syncthing#1839]
My use case is:

*  Two large NAS boxes on two US coasts
*  Various laptops, desktops, and servers which need to be backed up to each coast

Ideally, I would like to have a way to say, "If this machine creates a sync, put it here, and if the names conflict, just handle it" so "client" machines can add and remove syncs without any remote access to the NAS boxes, nor without any intervention by another human.

**Comment by dcarosone** [comment]
So kind of like an introducer flag, for shares? I can see the point, but it
might need some careful thought around the edges. What happens if two
clients want to create a share called 'Documents', how to clean them up
afterwards, etc.

Meanwhile, I strongly suspect this could be done - and should be prototyped
- with an external agent using the api.

**Comment by calmh** [comment]
> and if the names conflict, just handle it

Do you mean that you intend for a folder to always only be shared between the server and a single client, and another client using the same folder name should get a separate shared folder? That's fairly contrary to how syncthing works, but the id+label-instead-of-folder-name could help here.

**Comment by AudriusButkevicius** [comment]
Dup #2299
