### ISSUE TITLE
memory use

### ISSUE THREAD

**Issue by skandragon** [syncthing/syncthing#1841]
Syncthing seems to use a lot of memory while doing what it does.  I understand some things need to be kept in ram, but when running on a small home NAS box with 1 GB of ram, it will quickly grow to the point where it swaps, and basically grind the NAS to a halt.

The number of files I am attempting to sync totals only 3,846, but the size of this directory is roughly 3.8 TB.

**Comment by Zillode** [comment]
Please have a look at https://github.com/syncthing/syncthing/blob/master/CONTRIBUTING.md#reporting-bugs
> What operating system, operating system version and version of Syncthing you are running

**Comment by AudriusButkevicius** [comment]
You can also adjust GOGC environment variable (read about it on Golang MAN pages), but that will increase the CPU usage as the garbage collector will be invoked more frequently.

**Comment by calmh** [comment]
Also, how much memory *does* it use, and doing what?

**Comment by raichu** [comment]
I've been running syncthing (0.11.6) on a Raspberry Pi, with a directory containing 10000+ files and it's using around 70MBs (I'm not setting GOGC).

It's quite strange that the memory usage skyrockets with file size; with go, it shouldn't normally be an issue since the norm in the stdlib is to work with streams.

> Also, how much memory does it use, and doing what?

wot?

@AudriusButkevicius go doesn't have any man pages. The document for GOGC is the runtime package documentation.
