### ISSUE TITLE
'Disappearing' files result in puller pause on other devices

### ISSUE THREAD

**Issue by hashworks** [syncthing/syncthing#1922]
When I add /.config/pulse to .stignore on device A, device B will produce the following errors:
```
INFO: Puller (folder "home", file ".config/pulse/a569e851e314484ba25702ea5b1b6fb6-device-volumes.tdb"): pull: no available source device
INFO: Puller: final: no available source device
WARNING: Folder "home" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
```

However, the .stignore file will soon be synced to the other devices, and once they reload it the warning will disappear. 

What would be a good way to solve this?

**Comment by AudriusButkevicius** [comment]
So .stignore is not synced (unless you're using the `#include` directive), and it seems that you've ignored the file exactly while it was being synced, hence the error just says `there is nobody who has this file anymore` and should go away after the device with the new .stignore entry rescans, hence it's just a harmless warning that the file has disappeared while we were trying to get it in sync.

**Comment by hashworks** [comment]
Yup, I'm using the `#include` directive and sync the included file.

IMO device A should be able to respond with 'I'm don't care about this file anymore, stop this sync action'.
The same thing occours when one removes a file on device A, I'm having this situation daily.

**Comment by AudriusButkevicius** [comment]
Well ignore means `I don't see the file anymore`, hence replying, `I have no such file` is perfectly reasonable. 

The puller pause part is expected/defined behaviour, syncthing always did that, and this is just to allow the other peer to do a scan to realize it doesn't care about that file anymore, so that it would advertise that to us.

Yes, the messages could be improved, but there already exists an issue for that.
