### ISSUE TITLE
Could the "add node X" to syncthing? prompt ask for a name too?

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1929]
It would remove an extra step from the process. Maybe the remote host could suggest a name in its config.

**Comment by calmh** [comment]
Yeah... Let me explain why it is how it is and then we can see. :) When we get an incoming connection, we get their certificate as part of the TLS negotiation. If we don't recognize that certificate we drop the connection, and we pop up the question in question. The name does gets sent in the first message of an allowed connection. But so far it's a nice safety net that we don't interpret any data sent by unrecognized devices. Perhaps we have a protocol parser vulnerability where a malformed message can cause us to crash, expose private data or do bad things. Of course we do our damndest to avoid that. But as it is, by avoiding to even peek at data sent by someone we don't explicitly trust it's much *much* harder to exploit any vulnerability we might have.

One possibility that came to mind now that we *could* use is to set the name in the certificate from the hostname at generation time. That way the name is available to the recipient, but the name wouldn't be changeable by the user other than by regenerating the certificate (thus getting a new device ID). It might still be better than nothing.

**Comment by jpjp** [comment]
Makes sense :) An unchangeable name sounds like an issue waiting to happen though... :)

How about no magic then: when you are prompted to add the node that is suggested also allow text entry for the name of that node, with a default node name of what already happens now.

**Comment by calmh** [comment]
Yeah. Also needs a text that if they don't set a name, it will be updated to whatever the remote sends when it does connect. Same as I think we already have in the add device dialog.

**Comment by andersonvom** [comment]
What do folks think of this?
![new-device-layout](http://i.imgur.com/ZhxjZMD.png)

**Comment by AudriusButkevicius** [comment]
So if the name is left empty, its populated by the name the device advertises as they first connect, and providing a default would break that feature. Perhaps adding a device should present the add device dialog with values prepopulated, same like we do for folders.

**Comment by andersonvom** [comment]
We could check if the names has been changed (i.e. name != 123ABC). If it's been changed, we use it; otherwise we keep it blank (existing behavior). This would keep things backwards compatible. It does have one down side: it leads people to think the name will necessarily be the one in the box, which could be different (?) from the name the device advertises.

I like the idea of presenting the other dialog too, but it adds complexity and one extra step.

Thoughts?

**Comment by canton7** [comment]
I wouldn't mind having a little "Device added, set name / add folders" message when a newly-added device connects, with button(s) to open the device settings dialog. Since you're going to have to add folders to it anyway, but as well combine with setting a name...

**Comment by AudriusButkevicius** [comment]
We could just have 'Add and edit' button which opens the device edit modal after adding.

**Comment by canton7** [comment]
Is that too early? I'm a little fuzzy on when exactly we connect to the other device and it tells us its name, but we'd have to prompt the user to edit it *after* we've got its name (or we're missing the point of this issue IMO).

**Comment by AudriusButkevicius** [comment]
No, we'd have an emptu edit box, providing the option to specify a name.

**Comment by canton7** [comment]
Then we end up with the situation where there's a potential conflict between the name they entered and the name presented by the device. That's the thing I was trying to avoid.

**Comment by AudriusButkevicius** [comment]
There is no conflict. If they entered a name, the name that is presented by the device is ignored.

**Comment by andersonvom** [comment]
I think @canton7 means the user would have to choose a name without knowing what the advertised name was.

Having an empty box after clicking "accept" seems to just add complexity without adding too much value (since the user can change the name already in the alert box before accepting it (not necessarily the layout above, but you get the idea).

Ideally we should have the advertised name before prompting the user to either accept that or override it, but we'd have to have an extra step before adding the device, which feels complex. =(

Given the user needs to know who the device is beforehand (otherwise they'd just be accepting random requests), I would lean a bit more towards the simpler case.

**Comment by AudriusButkevicius** [comment]
It's impossible to do that, as the prompt to connect is raised by the TLS handshake, which gets refused  as the device is unknown, and the name is only known some undefined amount of time later after we've actually added the device as an acceptable one, and reconnected.

The edit device prompt has a tooltip saying leave this box empty to use the name advertised.

**Comment by andersonvom** [comment]
Yeah, that's why I mentioned an extra step: we'd have to accept the device, add it to some whitelist and then prompt for the final name. But that feels too complex for the added value.

There's also the solution @calmh suggested in his first post, but that seems far down the road, if we ever choose to go down that way.

Alternatively, we could have the same help text in the add device dialogue as well: "this will be updated to the advertised name, but you can override it if you want to" or something like that.

**Comment by AudriusButkevicius** [comment]
I imagine we'd reuse the existing dialog, which already has the text.

**Comment by andersonvom** [comment]
Oh, I see what you're saying.
The only thing that bothers me is having one extra step (=[). At the same time, it makes the experience more consistent. (=])
I'd say yay to that. What do others think?
