### ISSUE TITLE
Ignore pattern (?i) not working correctly for subfolders

### ISSUE THREAD

**Issue by eyeson** [syncthing/syncthing#1953]
Trying to create an ignore pattern that ignores all variants of Thumbs.db and Desktop.ini files.

On one of my windows machines:

Pattern used:

"(?i)thumbs.db
(?i)desktop.ini"

This ignored all thumbs and desktop files within the root of the folders, but didn't exclude files within sub directories. 

 output of http://localhost:8384/rest/db/ignores?folder=folderid

{"ignore":["(?i)thumbs.db","(?i)desktop.ini"],"patterns":["(?i)^thumbs\.db$","(?i)^.\\\([^\\]i\)thumbs\.db$","(?i)^thumbs\.db\\.$","(?i)^.\\\([^\\]i\)thumbs\.db\\.$","(?i)^desktop\.ini$","(?i)^.\\\([^\\]i\)desktop\.ini$","(?i)^desktop\.ini\\.$","(?i)^.\\\([^\\]i\)desktop\.ini\\.$"]}

This is the thread where I first brought this up: https://forum.syncthing.net/t/ignore-pattern-permission-question/2897/13

As mentioned in the thread, also potentially a second bug, when creating the ignore pattern the .stignore file isn't hidden by default, when I then hide it manually and edited it as per calmh's suggestions it became unhidden once more.

**Comment by Zillode** [comment]
For excluding files in sub folders you need ** I believe.
So try ```(?i)**desktop.ini```

**Comment by eyeson** [comment]
From the syncthing docs:

Regular file names match themselves, i.e. the pattern foo matches the files foo, subdir/foo as well as any directory named foo. Spaces are treated as regular characters.

So surely the double * is not required?

**Comment by AudriusButkevicius** [comment]
Yeah, but that doesn't seem to be true, as the patterns generated have the ^ anchor.

**Comment by eyeson** [comment]
Okay - So previously I'd removed the (?i) from the windows machine (this led to the windows machine being ~15 files out of sync all thumbs)
Now I've added (?i)** to the Pi and this has bought that local sync status to the same as the windows machine (both machines are still 1 file out of sync [thumbs again], I assume this if from a FreeNAS machine I won't have access to until next weekend) - Do I need to add ** or remove the (?i) from the Freenas side?

**Comment by Zillode** [comment]
As stated before, try ```(?i)**desktop.ini```

**Comment by simplypeachy** [comment]
On Windows the ignore pattern `thumbs.db` ignores thumbs.db and Thumbs.db in both the repo root and subdirectories, without any "out of sync" warnings. It seems to me that eyeson's quote from the documentation "foo matches the files foo, subdir/foo" is accurate, at least on Windows systems.

When using `(?i)thumbs.db` then the pattern is only applied to files in the root.

It strikes me that the documentation is correct (except for a note that Windows systems do not need case insentitvity) and that https://github.com/syncthing/syncthing/issues/2102 does in fact need fixing, using the case insensitivity modifer for the entire regex rather than just specifying the mode change inside the expression.

The problem with `(?i)**foo` "fixing" this is that it matches `barfoo`, which will not be what the user wishes.

**Comment by calmh** [comment]
What the hell? `foo/*.txt` should be exactly identical to `(?i)foo/*.txt` on Windows - that's a bug if it isn't...

**Comment by calmh** [comment]
I'm retitling this to the title from the duplicate, as that one is actually accurate. The thing is that all of our regexp translations are anchored; `foo` only matches at the root, while `**/foo` matches everywhere. However, `foo` is *supposed* to match everywhere. So the ignore file parser automatically adds `**/foo` to the patterns when it sees `foo` (but not for an explicitly anchored `/foo`). However, when you do `(?i)foo` it helpfully adds `**/(?i)foo` which is broken and doesn't match anything. :bug: :beetle:

**Comment by simplypeachy** [comment]
Dare I suggest we consider simply using un-interpreted regexes for ignore patterns? (Now we have two problems)
Or possibly just do very basic interpretation like automatically escape `.`, convert `*` to `.*` and `?` to `.?`

**Comment by Zillode** [comment]
There is simply a problem of providing both a `textual` and a `regex` description of the ignore patterns at the same time. This is confusing for users and causes bugs

**Comment by calmh** [comment]
We've discussed it before and generally decided that regexes are too much of a footgun to be good for most users, even though it would make the implementation trivial. On the other hand, people are fairly used to glob matching á la `?` and `*`, and for those who are familiar with neither the latter is easier to explain.

There should be no mention of regexes anywhere near the current ignore systems, because there's nothing regexy about it form a user point of view. The `(?i)` prefix does come from there, but is as good or bad a prefix as any for glob patterns as well.

**Comment by Zillode** [comment]
:+1:
