### ISSUE TITLE
Continuous stat'ing of the .stfolder file

### ISSUE THREAD

**Issue by plouj** [syncthing/syncthing#1965]
While running syncthing-inotify I noticed that syncthing is continuously stat'ing the .stfolder files in all of my shared folders.

Strace output for the syncthing process:
```
$ sudo strace -t -f -p 1460 2>&1 |grep "Public/\.stfolder"
[pid  1464] 15:25:21 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1474] 15:25:28 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1471] 15:25:35 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1470] 15:25:51 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1465] 15:25:57 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1465] 15:26:03 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1460] 15:26:09 lstat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
[pid  1464] 15:26:15 lstat("/home/plouj/Public/.stfolder",  <unfinished ...>
[pid  1464] 15:26:15 stat("/home/plouj/Public/.stfolder",  <unfinished ...>
[pid  1464] 15:26:15 stat("/home/plouj/Public/.stfolder", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
```

In syncthing-inotify this shows up as changes to the .stfolder file which I believe are causing my laptop's battery to drain more than necessary:

```
[OK] 15:29:56 Syncthing is indexing change in public-test: [.stfolder]
```
Maybe this is because I'm also sharing ~/ as another syncthing folder?

I'm running my own build of syncthing from commit 197bfa9f1.

**Comment by Zillode** [comment]
This is triggered by syncthing-inotify.

**Comment by AudriusButkevicius** [comment]
Why though?

**Comment by Zillode** [comment]
Inotify will post `/rest/scan?folder=.&sub=.stfolder&next=<delayvalue>` to extend the rescan interval of Syncthing. I'm using .stfolder because this is known to be an ignored/empty filename.
However, the logic is a bit too simple at the moment: if there are no further changes, inotify will execute this delay request and go to sleep for a very long time until FS/Syncthing changes wakes it back up.
In @plouj 's case, the FS system is changing all the time, so I will need to add a little bit of logic to only invoke the delay when really needed.
