### ISSUE TITLE
Setguid permission is not preserved on new subfolders

### ISSUE THREAD

**Issue by brgmnn** [syncthing/syncthing#2012]
The setguid bit on new folders created by syncthing is not preserved when those new folders are created as children of a folder with the setguid bit enabled.

My system is Debian Jessie 8.1 and I'm running Syncthing v0.11.10 (from the debian release channel).

I expected the setgid bit to be preserved as it is when using `mkdir` from the command line. This is a problem as I have a shared folder between multiple users all in a common group and I would like to keep all newly created folders owned by that group. As it stands, I have a top folder called `music` with permissions `drwxrwsr-x+`, when Syncthing creates a sub-folder `Queen` that folder does not inherit setguid and instead has permissions `drwxrwxr-x+` (note that it should be `drwxrwsr-x+`). This is a problem as when Syncthing creates a sub-folder of `Queen`, `Queen/Jazz` that folder now has syncthing as it's group as opposed to `media`, the shared group I would like. Now other users cannot access `Queen/Jazz`.

I have tried creating folders and files on the command line under different user accounts and everything is working as I expect so I'm confident I've set up my permissions, groups and ACLs correctly and hence why I suspect this is an issue in Syncthing.

I may also be able to submit a pull request to fix this but I would greatly appreciate a few pointers towards the relevant areas of code that I should look at.

**Comment by calmh** [comment]
We filter out permissions bits not in 0777, so that causes this. It should probably be fixed - grepping for 0777 or 0666 in places is probably a good start. Need to make sure it's covered by IgnoredPermissions and Windows etc

**Comment by brgmnn** [comment]
I've had a little play around with two nodes and as a temporary fix setting the "Ignore Permissions" flag on the machine receiving the files and writing the wrong permissions seems to work.

I've looked through the code and tried a few things like removing the masking from rwfolder.go and walk.go however I don't think either case is right. It seems that when syncing permissions the permissions we really care about are user/group/other read/write/execute permissions and not necessarily the other permissions like setgid or setuid. In my case I would want setgid and setuid to be set to the default values on the system, however others might want them synced across machines. What is the correct behaviour here? As at the moment all those values are set off as opposed to their default values.

**Comment by calmh** [comment]
> In my case I would want setgid and setuid to be set to the default values on the system, however others might want them synced across machines.

I don't think there is a system default other than "off", is there? I think we should sync these bits when we can. However, since we don't sync user or group ownership we can't successfully sync an existing tree structure set up like this. It should however be fine to chgrp it afterwards, and if we do sync the setgid flags the group should continue to be correct.

**Comment by brgmnn** [comment]
It varies I think but on Linux if the `setgid` bit is set on a folder, then newly created subfolders of that folder inherit the `setgid` bit. So the default value for `setgid` is off unless the parent folder has `setgid` on.

I think not syncing the user or group ownership is probably correct, as otherwise there's a whole host of issues opened up like running Syncthing under different users on each node or the same user with different groups.

I'm not sure which other file mode bits should be synced apart from the permissions. There's quite a few[1] but some like `ModeDir` I don't think need to be explicitly synced. I would also add that in my use case I actually don't want `setgid` to be synced, I just want it to assume the correct default value when folders are created by Syncthing.

I think the reason that I get the desired behaviour with "Ignore Permissions" on is that Syncthing no longer calls `os.Chmod` on files (in rwfolder.go). A reasonable fix might be to OR in the local files `setgid` bit with the file permissions received from the block protocol. That way the default value for `setgid` would be preserved.

If you opt to add in syncing of all filemode bits, it might be an idea to add an option to ignore those extra file mode bits, just like you can ignore permissions.

I'll test adding in an OR of the local files `setgid` bit and see if it fixes things.

[1] https://golang.org/src/os/types.go

**Comment by calmh** [comment]
Yeah... As I see it,

```
ModeDir  // "read only", in that it's set on directories and otherwise not
ModeAppend  // requires chattr on Linux, no idea about others, anyway probably not compatibly with us
ModeExclusive // ??? no idea
ModeTemporary  // ??? no idea
ModeSymlink  // as ModeDir, already handled
ModeDevice  // we don't sync device nodes
ModeNamedPipe  // likewise
ModeSocket  // likewise
ModeSetuid  // should be inluded in the synced set
ModeSetgid  // should be inluded in the synced set
ModeCharDevice  // don't sync devices
ModeSticky  // should be inluded in the synced set
```

so thats ModeSetuid, ModeSetgid and ModeSticky to handle.

**Comment by brgmnn** [comment]
I agree that those are the only three file mode bits that it makes sense to sync.

I still think that the "Ignore Permissions" flag should be effectively three choices now: sync all permissions, sync only user permissions (no setuid/setgid/sticky) and ignore all permissions. Alternatively only expose the "don't sync setuid/gid/sticky" as an advanced option. What are your thoughts?

**Comment by jorangreef** [comment]
I noticed that Unison: `does not synchronize the setuid and setgid bits, for security.`

http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#caveats

No more explanation is given. What security implications would syncing setuid and setgid have?

**Comment by AudriusButkevicius** [comment]
Bob the evil guy has a non-root account on machine A
Bob shares a folder with machine A which he can access from a non-privileged account.
Because A is syncing setuid setgid bits, it needs to run Syncthing as root.
Bob places a malicious binary with locally setuid/setgid bit set in the share which gets synced, this way getting a malicious binary on machine A, which he now can run under root privileges with a non-privileged account.

**Comment by brgmnn** [comment]
Hmm that's a fair enough security issue but surely running Syncthing as root is already not safe? Also you don't need to be root to set setuid, setgid or the sticky bit (on Debian linux anyway) so you could sync them with Syncthing running in a non-root account. You're right though it still opens the possibility of a user executing code as another user.

That said, I'm honestly struggling to think of a good use-case for syncing these file modes. They're just rarely used and for me anyway I use them for specific setups on a machine with multiple users on that machine.

Seeing as Unison don't sync them, perhaps it's best Syncthing also doesn't sync them. Though the issue of Syncthing forcing them all off as opposed to their default value is still a bug that I would like to fix.

**Comment by dcarosone** [comment]
The issue here is *not* to sync the set-id bits. The issue is to
*avoid removing them* (with chmod) after they're added automatically
by the filesystem on creation of new directories, because the
containing directory has setgid.

In the use case in question, it's perfectly fine to have setgid dirs
on host A, and not on host B:

**Host A** will be a shared fileserver, where many users create files
under their own UIDs. On A:
* relevant users are members of a unix group for access to the data
* the directories will be group-writable, so users can add files
* directories are setgid, so that new files added will also have that
  group set
* new directories made will also be made with setgid, so that the
  behaviour propagates.

These semantics do vary by unix variant (and filesystem type), but are
generally a SYSV-ism that has been broadly adopted.

**Host B** will be the personal workstation/laptop of one of said
users, who runs syncthing. Files there will all be owned by that user.

The problem here is that, when a new directory gets created on B and
sent to A via syncthing, syncthing on A will try to chmod it, and
clobber the setgid bit.  Then other directories and files created
inside there won't have the right group membership. They will have the
default group of the user running syncthing, and other users won't be
able to work with those files or add more.

So perhaps syncthing just needs to include setgid in the list of
allowed permissions when masking *for directories only*.  We don't
want to be creating setgid (or setuid) files.

However, all that said, the workaround is simply to set
IgnorePermissions on Host A, because in addition to the above, there
is *another* problem. When files on A are not owned by the user
running syncthing, syncthing can't change their modes or mtimes, and
will complain about 'folder not making progress'. Setting
IgnorePermissions avoids both problems.

When I first saw this issue, I wondered why I hadn't seen it, since
I'm user B in this scenario, but I already had IgnorePermissions set.

**Comment by brgmnn** [comment]
Yes thank you @dcarosone you've perfectly described the problem and my usecase, better than I could have! I also currently work around this issue by marking the folder on my server with "Ignore Permissions".

The place where this will be a problem is when syncing a folder where you do want to preserve the permissions. An example might be a bash scripts directory where the files are marked executable. Now a user will have to manually update the files as executable again on the server **Host B**.

I think the fix is, when syncing a folder with permissions on, don't mask out the setgid bit on directories locally. I'm trying to think if there's a good reason to do the same for sticky or setuid. Neither of them are inherited? So I don't think there will be a problem exactly like this one.
