### ISSUE TITLE
Syncthing shouldn't start syncronizing untill all machines are done scanning

### ISSUE THREAD

**Issue by roberth1990** [syncthing/syncthing#2024]
I have two devices, one has all the data it is suposed to have, the other is suposed to have all of it too, but it has only a partial amount of it.
When I started syncthing on both devices and connected them, they started uploading and downloading data to each other before both of them were done scanning. So I had to run syncthing on only one of them at a time and let them scan all the data they had before connecting them again.

Syncthing should wait untill both are done scanning before any of them start syncronizing data both ways.

In this case if I let them syncronize the device with the incomplete data, would needlessly upload a lot of data to the device which has all, and the other way around. Which would lead to syncthing syncronizing data that is allready syncronized. Sorry if this is unclear.

**Comment by calmh** [comment]
This should indeed be the case - a scan is done at startup and syncing doesn't start until it's complete. Pulling files from other devices while also scanning is not possible. Can you reproduce this behavior?

**Comment by roberth1990** [comment]
It happens every time I have tried now. It starts syncronizing as soon as the folder is added and syncthing is restarted it starts to syncronize all data in the folders on each device as soon it is added, while it is being scanned.

**Comment by calmh** [comment]
If you mean that a device is *uploading* data while it's scanning, then yes that's the intended behavior. But "scanning" and "syncing" (i.e. *downloading*) are distinct phases - I don't see how it could be doing both at the same time, sorry.

**Comment by roberth1990** [comment]
Well my server uploaded 30 mb this last time I tried to my desktop before I got shut down syncthing on my desktop which took just a few seconds to happen, is that normal?

**Comment by AudriusButkevicius** [comment]
The 30mb might just be index exchange.

**Comment by AudriusButkevicius** [comment]
Also, the scans after it was completed once might take less than a second to complete, so the scan might already be over at the point you see it. I think it says when its done in the log.

Is there actually an issue here, because to me it just seems as a bunch of claims with nothing to back them up.

**Comment by roberth1990** [comment]
Scanning of 450 gb of data with syncthing takes well over an hour. It was then I noticed it.

But what really has happend is that since the webui only tells what the bandwidth is used for when it actually syncronizes data(which I notice just after filed this issue) confused me to be honest. There is no place in the web ui that tells what it actually did with certainty.

**Comment by AudriusButkevicius** [comment]
Scanning 450GB for the first time might take an hour, scanning 450gb afterwards can take 0 seconds if none of the files were modified.

The bandwidth numbers show all traffic, including protocol chatter.
As syncthing instances connect, they exchange their databases (roughly as much data as index folder in syncthings home directory holds),  which is why you might see bandwidth when you are not expecting.

**Comment by roberth1990** [comment]
No the only issue was that I was confused by the info the webui provides.
