### ISSUE TITLE
web interface says "up to date" but details shows out of sync

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2026]
the web interface says "up to date" but details show a number of files and an amount of date out of sync. 
(could be that a sync ignore pattern was added - how is this handled? it is unfortunate that sync ignore patterns cannot be added when adding a folder initially). 

thank you for a good tool!

**Comment by joepalma** [comment]
Since updating to 0.11.13 I'm also getting every Out of Sync alerts on files that I have ignored. Before the upgrade from 0.11.11 they were fine. .desktop, desktop.ini, etc.

**Comment by larroy** [comment]
Hi

I think the problem is when there are .syncthing temporary files, the Puller then says:

[ILGFA] 17:52:41 INFO: Puller: final: open /home/piotr/oneplus/music/asot/Armin Van Buuren - A State Of Trance 691 (2014-11-27) (Inspiron)/.syncthing.33 Armin Van Buuren Pres. Rising Star - Touch Me (Armin Van Buuren Remix) [Asot Radio Classic].mp3.tmp: file exists

[ILGFA] 17:53:41 INFO: Folder "oneplus" isn't making progress. Pausing puller for 1m0s.

**Comment by calmh** [comment]
Pretty sure this is taken care of a while back.
