### ISSUE TITLE
new GUI

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2032]
hi guys,

First of all: I'm loving syncthing and will support the project  as much as I can by translating and helping out in the forum.
My other love is to layout GUI's :) hoping to reach the right ones here :)
I already posted my thoughts of a new GUI of syncthing and hope to find some developers, that would attend to developing a new GUI. I know that a new GUI hasn't the pole position of priorities - but maybe there is someone who has the skills to develop this piece of code for the project.
https://forum.syncthing.net/t/my-thoughts-for-a-gui-2-0-looking-for-a-frontend-developer/3002/39

I'm updating the mockups in the forum and my git folder "mockups (https://github.com/Eddy2909/GUI4syncthing) once there are updates

thanks much!

**Comment by AudriusButkevicius** [comment]
Please carry on the discussion on #1381, no need for a separate ticket

**Comment by gillisig** [comment]
@AudriusButkevicius I'm confused though. this is a completely different UI than the other issue refers to so I'm not sure if these issues should be combined.

**Comment by AudriusButkevicius** [comment]
I agree, though the issue is the same issue, which is syncthing's ui not being good enough. I think whichever version we go for is an implementation detail, not a separate issue. 

Unless we implement switchable ui's, then this could be a separate issue asking for this theme.

I don't mind reopening if you or @calmh has a strong feeling abiut this. This was just an attempt to consolidate for the sake of keeping the issue count down and discussion in the same place.

**Comment by gillisig** [comment]
Yeah good point. Keep it closed :)
