### ISSUE TITLE
suggestion: open ignore patterns directly from web gui

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2037]
the method to show the out of sync files is very efficient and useful - thank you!
could be the same direct access to ignore patterns be added? the current method to open first the edit folder window and then to show the ignore patterns is cumbersome, takes time (especially on slow connections and/or very busy sync nodes) and sometimes does not open at all. (unclear when).

thank you

**Comment by AudriusButkevicius** [comment]
We tend to not include stuff in the UI that is not set.
For example if master folder is not set, we don't explicitly have a line saying it's not set.
This would require us to explicitly say that `Ignores -> No` so that you'd be able to click on the `No` to add them, cluttering the UI for every folder.
