### ISSUE TITLE
Advanced Configuration dialog: impossibility to show parameters of folders with dot in name

### ISSUE THREAD

**Issue by ZdenekBrichacek** [syncthing/syncthing#2059]
In the Actions/Advanced Configuration dialog is impossible to show parameters related to the folder containing dot character in the name (by click on it). For example "test.fr".

This isn't problem of main dashboard. There it's working.

Related to v0.11.12 - v0.11.15 (latest).

**Comment by canton7** [comment]
Changing `<div class="panel-heading" role="tab" id="folderfoo.barHeading"  data-toggle="collapse" data-parent="#advancedAccordion" href="#folderfoo.barHeading" ...` to `<div class="panel-heading" role="tab" id="folderfoo.barHeading"  data-toggle="collapse" data-parent="#advancedAccordion" href="#folderfoo\.barHeading" ...` "fixed" this for me. Not sure why the anchor needs to be escaped: the spec indicates that periods are valid in anchors

**Comment by uok** [comment]
I guess because - unless you escape it - in jQuery a `.` is a class selector, e.g. `$("#folderfoo.barHeading")` finds `id="#folderfoo" class="barHeading"` - recommended is `_`in CSS ids

see http://stackoverflow.com/questions/12310090/css-selector-with-period-in-id and http://stackoverflow.com/questions/350292/how-do-i-get-jquery-to-select-elements-with-a-period-in-their-id/28321594#28321594

**Comment by canton7** [comment]
Aha, jQuery must be looking at the `href`, that figures

**Comment by uok** [comment]
yeah, some frameworks use `data-xxx` attributes, some use the href
