### ISSUE TITLE
Version checking

### ISSUE THREAD

**Issue by basickarl** [syncthing/syncthing#2104]
I just spent the last three hours trying to figure out why my laptop and smartphone wasn't syncing even though they both saw each other and all the folders were setup correctly.

I finally realized that I haven't updated my smartphone syncthing app for ages, as I do not have wifi and do all my interneting via 3g google app stores does not automatically update software for me. After the update it all works. Perhaps the devices can check and message the user when inconsistent versions (versions that do not work with each other) are detected and advise updating device X.

**Comment by canton7** [comment]
There was an update which broke protocol compatibility, and which prompted a minor version bump. Since the different Syncthing versions couldn't event communicate, there was no way for them to establish that they were incompatible. Since Syncthing is still in beta (1.0 hasn't been released), maintaining backwards compatibility isn't a priority.

There was a lot of publicity both in the forums and here on GitHub at the time.

**Comment by calmh** [comment]
Perfect summary by canton.
