### ISSUE TITLE
Warn when GUI is bound to non-localhost without username and password

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#2139]
- Add a wizard to set a username and password
- Announce warning via GUI (see https://github.com/syncthing/syncthing/pull/2131)

**Comment by generalmanager** [comment]
Nice one! Thanks for making a real effort to improve the security of the enduser. :+1:

**Comment by didtoo** [comment]
Nice, but how can I switch it off? For local (closed/NAT) LANs with trusted users this is not a risk, so where is the checkbox to turn this space consuming message off?

**Comment by AudriusButkevicius** [comment]
Advanced config has a checkbox

**Comment by didtoo** [comment]
Indeed I found it, 'insecureAdminAccess' in Advanced-GUI setting. Was not mentioned in this thread, so I missed it. Thanks.

**Comment by ikogan** [comment]
So I'm building a docker a infrastructure to allow Syncthing to be used by multiple users behind a reverse proxy. I've created a static Docker network that's internal only on which I'm running Syncthing and I've put a reverse proxy with SAML in front of Syncthing.

Since this means that syncthing isn't running on 127.0.0.1 (it's in a container), there doesn't seem to be any way to remove this message. Is there anything that can be done short of hacking on the codebase?

**Comment by calmh** [comment]
See the post right above yours, and the advanced configure section in the GUI.
