### ISSUE TITLE
Changing a large number of small files takes a really long time to update global state

### ISSUE THREAD

**Issue by sreynen** [syncthing/syncthing#2148]
I have a synced folder on two OS X machines that previously contained around a million files. Scanning takes forever, so I attempted to mitigate this by zipping up the files I'm not actively using, which reduced the number of files to under 500k. 48 hours later, this change still hasn't synced on a local network. It's about 8GB of changes, but sync speed doesn't even seem to be the bottleneck. The machines haven't yet figured out what's different between them. The updated machine says "Global State 597461 items, Local State 492169 items" while the other machine says "Global State 1018928 items, Local State 1020770 items." The numbers are gradually getting closer, but it seems like it is going through iterations of seeing changes, syncing them, seeing more changes, syncing those, etc.

When each machine has completed a local scan and discovered which files it has, I would expect the other machine to acquire the full list of changed files in minutes, not days.

**Comment by xJMV** [comment]
Seems you are having same problem as I had (#2080). While testing it just fixed out by itself.

However it gets back once in a while. Having added a lot of files in the last 15days (over 8millions) I started to get the same results as you are.

Also both instances do not shows matching global/local states.

Folder master:
Global State 	5211358 items, ~11.1 GiB
 Local State 	5209884 items, ~11.1 GiB

Folder slave:

**Comment by xJMV** [comment]
I may have found a clue about this issue along with mine (#2080).

I was tweaking settings in windows and realized that since the W10 update, Indexing has been re-enabled to all folders. I disabled indexing for my large file storage folders and restarted Syncthing.

It now complete its scan in less than 30minutes! instead of several hours! I never touched OsX but if similar index exists, just shut it down to test...

**Comment by calmh** [comment]
> it seems like it is going through iterations of seeing changes, syncing them, seeing more changes, syncing those, etc.

This is probably fairly accurate too, for large change sets such as these. Index updates are sent in batches of a few hundred to a thousand or so files, and processed as they arrive. So it's likely a device would be pulling changes at the same time it was receiving information about more changes. 

Since the pulling mechanism tries to get a lot of data in flight (to fill long pipes), index updates would get delayed and queued behind actual file data. All in all, the end result ought to be the same though - both the index and file data need to be sent at some point.

**Comment by sreynen** [comment]
>  Index updates are sent in batches of a few hundred to a thousand or so files, and processed as they arrive.

Hmm, that should have finished in one batch in my case. Unless maybe syncthing doesn't take directory hierarchy into account? My changes were taking a couple dozen directories, archiving them into a couple dozen archive files, and deleting the original directories and the thousands of files within. That would be less than 50 change records if syncthing is transferring a deleted directory change as the parent directory. If syncthing is sending every file that was deleted, I can see why that would take a while, but that also seems unnecessary.

Beyond speeding up the global status, the interface should probably also indicate when the global status is incomplete so it's not misleading users.

**Comment by AudriusButkevicius** [comment]
It does send every file inside the directory, and then the directory itself.

**Comment by dschoeni** [comment]
It is an issue though - I have deleted a folder with tmp-files generated from one of my projects (I did not notice it was there when syncing initially) that consists of approximately 70k files but only about 20-30mb in total.

My laptop is still syncing the changes (deleting the files locally) after a whole afternoon, running the CPU at 50%. I don't think this is intended behaviour?

**Comment by AudriusButkevicius** [comment]
I think the reasons for the behaviour are explained above. I do not think it's intended, but I am not sure its completely fixable. Even old-timers such as rsync struggles with many small files, due to per file overhead which is unavoidable. I guess rsync is all in memory and doesn't need to update/check an on disk database, hence why it deals with it much better.

**Comment by dschoeni** [comment]
Still, it takes about 10 seconds on my laptop to delete 10 files. There are still ~4500 files left for deletion. I don't know how the underlying protocol works, but is there no way such actions could be batched, at least if no files are being ignored in this specific folder? I don't have any files ignored at all for example.

**Comment by AudriusButkevicius** [comment]
Is there anything actionable here? The problem here is overhead per file, and I don't think there is a way to get rid of it, hence nothing todo here?

**Comment by calmh** [comment]
Yeah, no. We've done a lot of optimizations the last year or so, as well. If there is something pathological remaining here, reopen or refile I think.
