### ISSUE TITLE
Per folder "pause sync" toggle

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#215]
When sync is paused, no data should be transmitted.

There should also be a Rest API for this (pause and resume).
#192

Edit: I think there should also a `-pause` command line flag to launch in paused mode (and/or remember the state on shutdown).

**Comment by ozra** [comment]
Yes, pausing is essential, and I agree, it should pause network traffic. One important missing feature in pausing in other sync systems is a timeout. Say, "Timeout for 4h". Otherwise one _always_ forget to start it again until a couple of days later when it's to late and you computer and house has exploded (Murphys law.. ).
Most oftenly pausing is done under critical conditions, you've just added 1GB of files and you realize network is choking, and you've _got_ to deliver some file on deadline, low battery, etc. etc. So being able to say, "hey, pause for a few hours, and cut some slack". Or minutes..

**Comment by calmh** [comment]
We're probably better equipped to handle this now.

**Comment by noener** [comment]
The ability to pause syncing is a must for managing remote instances - rendering syncthing unusable.

**Comment by calmh** [comment]
> Yes, pausing is essential, and I agree, it should pause network traffic.

Network traffic isn't tied to a folder though, it's tied to a device. We might be able to pause a folder (as in we don't scan it or sync files in it), but we can't prevent other devices from doings to and sending us updates or file requests for it. Other than by closing the connection, that is, in which case we might as well shut down...

**Comment by jerryjacobs** [comment]
Per-folder pause/resume syncing makes sense for me. If you look at bittorrent sync it has support to Pause specific folders.

**Comment by MartBlur** [comment]
How hard is to implement a way of sending some specific status info between nodes, so not only knows the folder-pause status of each other, but also their ignore-files, thus reacting more accordingly, and even fixing the showed percentages?

There are some things that can't be implemented flawlessly just because of the lack of any kind of "master node" or at least "partially synchronized configurations".

I hope this makes sense. I'm newbie on github (and programming).How hard is to implement a way of sending some specific status info between nodes, so not only knows the folder-pause status of each other, but also their ignore-files, thus reacting more accordingly, and even fixing the showed percentages?

There are some things that can't be implemented flawlessly just because of the lack of any kind of "master node" or at least "partially synchronized configurations".

I hope this makes sense. I'm newbie on github (and programming).

**Comment by Getron** [comment]
Pausing per folder, and to, per device feature would help a lot! Maybe to add a option to restrict a down-upload, for example, the sync should not use more than 200 KB/s of internet bandwidth, or somthing like this, to able to chose manually, how much of bandwidth should sync take.

I have this problem, scenario:

i have a server on my home, which is in other country, where the internet is not so fast, and i can see this server just over the internet, for example, with teamviewer, or NoMachine, or somthing like this.

Now, i want to add to my Syncthing on this far away server on other country allmost 20-30 shared folders.
I added today 5 shares, and tomorrow i should add more, but, no chance anymore. I was not able to put the shares on pause, to not take the full bandwidth of my internet where the server is, in other country.

The Sync start immediately after i have add a share, and restarting syncthing. Now the internet is fully accessed by syncthing, and i'm not able to connect to my server with other softwares, like teamviewer, anymore. There is no more internet bandwidth to connecting on.

I think, this is one of most improvment of syncthing, if be able to add.

The btsync has this option to pause full sync, or per share. With btsync, i was able to connect to my servers without problems, and menage shares without problems of internet bandwidth.

Would be very thankfull, if you can adding some such options on it. I think, most people would like to have this options.

**Comment by AudriusButkevicius** [comment]
Check the options, throttling is already there...

**Comment by Getron** [comment]
Ah, yeah, i see it now, the throttling... but the pausing per folder and per device would be great functions, if is possible to add.

**Comment by bmedicke** [comment]
I can easily teach someone to press pause in a web interface when they are travelling with their laptop. But if I ask them to run `sudo launchctl unload -w /System/Library/LaunchDaemons/syncthing.plist` or something to that effect I'm sure all I'll get is blank stares. Plus now they need a root password and the web interface is "broken".

And even for myself it would be easier to pause all traffic over a web interface whereas stopping (and starting) requires me to ssh into the box.

**Comment by sisu4syncthing** [comment]
Just want to add my wish, that a (UN)PAUSE ALL button would be needed too, because if users have >10 folders in their setup it'll quite a lot of clicking (on a slow/sluggy webgui).

**Comment by Eddy2909** [comment]
I'd love to have this option too :+1:

**Comment by jdavidbakr** [comment]
Another reason to have pause instead of shutdown - if you have syncthing running under launchctl or supervisord or whatever the Windows equivalent is where the system automatically restarts it if it shuts down, but want to temporarily pause it to conserve the resources for something else without having to go in and re-configure those programs.

**Comment by newearthmartin** [comment]
Pause/Unpause per folder is absolutely essential!
When you are on the go or limited bandwidth you want to just focus on the folders that really matter

**Comment by akohlsmith** [comment]
Agree that an API call to pause/resume (with optional per-folder or default behaviour of "all") would be a godsend. Simply killing the binary is actually quite problematic from an overall usability perspective. having a CLI option and a way to hit it from the web interface allows third party software to make the decisions, opening up a lot of new behaviours that I doubt you'd care to support or develop.

**Comment by newearthmartin** [comment]
It boils down to this:
if you are really serious to having a product that competes with btsync and many people use, you can't just expect people to go killing binaries or setting throttle to zero when they want to pause.

**Comment by Getron** [comment]
@newearthmartin Fully agree with you.

It should have per folder pausing, per device pausing and Pause All funktion.

If this someone would implement, this Sync product will beat all other out there.

Please, add it, i need it so much, and i hope, other, no-devs people to. Thank you in advice.

**Comment by dcarosone** [comment]
As a point of (hypothetical) implementation, would this be easier / better
done as a new toggle switch, or by allowing transfer rate limits be
share-specific and using the existing enforcement of those limits?

**Comment by newearthmartin** [comment]
If you want to use rate limits, will the system be able to tell the
difference between pausing and someone dropping the limit to zero?

On Thu, Aug 20, 2015 at 10:51 AM, Daniel Carosone <notifications@github.com>
wrote:

> As a point of (hypothetical) implementation, would this be easier / better
> done as a new toggle switch, or by allowing transfer rate limits be
> share-specific and using the existing enforcement of those limits?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/215#issuecomment-133014154>
> .
>



-- 
Del Amor, de la Paz, en el Mundo. - Of Love, of Peace, in the World.

**Comment by generalmanager** [comment]
@newearthmartin Why would it be necessary to be able to differenciate from the outside? I imagine with system you mean the operating system?

**Comment by calmh** [comment]
Thanks guys, the requirement is understood.

**Comment by calmh** [comment]
Retitled as we have per-device pause now.

**Comment by mrbrahman** [comment]
If there is vote for the "pause per folder" feature, I would do a +1 :+1: 

I see a huge benefit of this feature especially for mobile devices, where we may want to sync some lightweight folders over the data connection, and keep the rest for WiFi or WiFi + charging.

**Comment by dcarosone** [comment]
+1

**Comment by AudriusButkevicius** [comment]
Please use the emote buttons, otherwise we'll be forced to lock conversations on the issue due to +1 spam.
