### ISSUE TITLE
Handle conflict for files

### ISSUE THREAD

**Issue by arthurlutz** [syncthing/syncthing#220]
When two nodes modify the same file, one of the two gets overwritten. It is not always the same. There is loss of data here!

This is a serious feature lacking in syncthing. A number of scenarios need this handling : 
* a node is offline and does some modifications
* multiple users on multiple machines

I don't exactly know how btsync/dropbox/sparkleshare/etc handle this usecase but all the versions of the file should be kept for example filename.ext.name_of_node

**Comment by cooperbattersby** [comment]
Syncthing should never allow data to be overwritten when there is a conflict. I would vote for the Dropbox style solution. Renaming the older conflicted file in place. eg:
foo.bar
foo (conflicted 2015-05-14).bar

This bug is a showstopper for me. It took me a week of happily using syncthing before i realized that this was the behavior. This behavior should be documented in the FAQ:

> What if there is a conflict?
>
> Syncthing does not recognize conflicts. When a file has been modified on two nodes since the last sync the newer file will be synced over top of the older file.

**Comment by lb1a** [comment]
+1 this issue should get a higher priority, because it causes me hours
of headache trying to sync e.g. keepass databases that not overide other
modifications...

**Comment by majorsl** [comment]
I would also advocate for a "yellow box" notification in the GUI with the file name(s) in question. If you have a lot of shares, and a lot of files, you may not notice a renamed file having to trudge though all of that.  Possibly some sort of conflict resolution within the GUI could be handy e.g. "File xyz on device1 and device2 has been modified and is in conflict. Would you like to keep the file on [device1] [device2] [keepboth]"

**Comment by donnex** [comment]
:+1:

**Comment by jpambrun** [comment]
The FAQ was recently changed to :

>> Syncthing does not recognize conflicts. When a file has been modified on two devices simultaneously, **it is not deterministic which file will get synced** by peer devices. Also, **different peers might end up with different version** of the file (different side of the conflict). Versioning can be used to retain old data.

Now this is just scary.

**Comment by AudriusButkevicius** [comment]
Updated the FAQ once more to explain the issue a bit better.
This is quite a hard problem, given there is no central authority to decide what's new and what's old, especially when nodes can modify files while they are offline.

**Comment by merlink01** [comment]
+1 Must be fixed fast. Dataloss is a nogo.

**Comment by timss** [comment]
In the mean time a differential backup or snapshot using rsync might be a good idea:

https://wiki.archlinux.org/index.php/Rsync#Differential_backup_on_a_week

https://wiki.archlinux.org/index.php/Rsync#Snapshot_backup

**Comment by devurandom** [comment]
IMO this should have highest priority, since how well a solution recovers from conflicts should be the primary reason for people to decide for or against it.

**Comment by Zillode** [comment]
@devurandom : patches welcome;)

**Comment by adamralph** [comment]
Would this really be regarded as just a 'patch'? To the untrained eye, it would appear to require some thought about the way syncthing works, fundamentally.

Moreover, I'd expect it would be something that the collaborators would want to be involved in, rather than just throwing it out the community?

**Comment by lb1a** [comment]
@AudriusButkevicius maybe i don't understand your concerns correct, but isn't it irrelevant which one of 2 concurring versions was the first and which the second(or old and new)? if a file is incoming that is different from a file that is already present in a folder and locally modified since the last sync with that other node and has the same filename, there should be some way to "deal with it".
And by "deal with it" i mean not to override one of the files.
If i recall it correctly, there was some thing like a counter, that counts up with every modification of a file that is recognized by syncthing? Could that be used to determine if a file was modified since last synced with another node?
I understand that it is a hard thing to implement, but for me it is the real showstopper for using it. It's simply not an alternative to dropbox etc. if i get dataloss and maybe don't realize it until i want to use the data in some way...

**Comment by Zillode** [comment]
@adamralph Yes definitely, and you are welcome in our irc channel and discourse forum to discuss the options and how to proceed with an implementation.

**Comment by adamralph** [comment]
@Zillode that's good to know, thanks. Unfortunately I've never touched Go so I'm unlikely to be of much help with implementation, but I'm glad that the collaborators are taking this issue seriously.

IMHO, and only IMHO, this should be on the v1.0 milestone rather than v1.0-maybe. Personally I find it hard to see syncthing as a viable solution until this is addressed.

**Comment by adamralph** [comment]
This issue is (in a way) a superset of https://github.com/syncthing/syncthing/issues/439, which is already on the v1.0 milestone.

**Comment by AudriusButkevicius** [comment]
I admire how everyone jazzes in and starts putting `This is a show stopper for me`, `IMHO this is critical`, `We need to get this fixed`, and then gives excuses why they can't help.
+1'ing doesn't solve anything, people who write code do, hence if we could focus the energy on writing code rather than comments, we'd be feature full by now.

In this case the collaborators are just members of the community. Just random people fixing random stuff in their random spare time. Usually the only reason stuff happens is because somebody is bothered enough to implement stuff, or wants it fixed, not necessarily because enough people have +1'ed the issue.

**Comment by adamralph** [comment]
@AudriusButkevicius would you prefer to only receive comments from developers who can help implement changes? Are you not interested in feedback from non-technical users?

I sympathise with the fact this is community driven. I spend most of my free time working on open source projects on other platforms. No one is *demanding* that is done. I'm chiming in simply to give feedback as, effectively, a non-technical user. If you'd rather not have this kind of feedback, then I'll keep quiet going forward.

**Comment by AudriusButkevicius** [comment]
Feedback is critical, so is knowing the pain points the community has, but I guess I prefer people doing something about the stuff they don't like, rather than just expressing how syncthing doesn't solve all your problems. We are aware of the issue
I guess what I am trying to achieve is to encourage people to get involved.

**Comment by adamralph** [comment]
Fair enough, encouraging people to get involved is definitely a good thing and I'm all for it. I think we're in agreement that there are different levels of involvement (non-technical feedback being one of them).

I think it's important, however, to reply to a thread in such a way that you don't put off people who are only able to participate in a non-technical manner. As an OSS journeyman I'm relatively thick skinned, but others may easily receive your above comment very negatively.

**Comment by AudriusButkevicius** [comment]
I agree that I've overdone it, as I always do... Another bad attempt trying to emphasize that the best way to get stuff done, is to sit down and do it.

**Comment by adamralph** [comment]
No hard feelings :smile:

I'll keep an eye on the thread and, if I ever get my hands dirty with Go (which I intend to) I may jump back in and help!

**Comment by lb1a** [comment]
@AudriusButkevicius i can understand your feelings about people always complaining about stuff that doesn't work. And the statistics show that you put a lot of effort in this software and i really like to thank you for that. I'm using syncthing for non critical stuff, i've setup a "Master" node that doesn't allow incoming deletions for stuff i care about. I help with the translation on every release, but i don't understand Go in any way. So i just can't help on this unless i learn Go...
So a :+1: only for your efforts and work which i appreciate. 
Please consider this issue an important one for many users out there.

**Comment by Zillode** [comment]
Note that it is not as bad as you think it is. All files that are overwritten will be archived if you enable a versioning scheme. So you'll always have a way to recover from such a conflict, albeit this could be done nicer, hence this is an open issue.

**Comment by adamralph** [comment]
Yep, true. I think the main issue with that is *knowing* there has been a conflict (without manually polling the archives).

**Comment by jedie** [comment]
>  Note that it is not as bad as you think it is. All files that are overwritten will be archived if you enable a versioning scheme. So you'll always have a way to recover from such a conflict, albeit this could be done nicer, hence this is an open issue.

Because of this: I would prefere that versioning is enable by default, see: https://github.com/syncthing/syncthing/issues/368

**Comment by calmh** [comment]
I'm actually sitting down to do something about this. Locking as the issue is clear and further +1's are just noise.
