### ISSUE TITLE
optionally move index.db folder

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#2228]
Hello,

I remember a discussion a while back about moving the index folder to .cache (in Linux), can't seem to find it now though. I have a similar/other suggestion about that too and would be interested in hearing opinions.
How about an optional key in the config.xml for an alternative database location, so I could move the database out of ~/.config/%appdata% (or whatever it is on windows) to wherever I wanted? The reasons being:

a) Right now we use .config (which is for configs) to store a (potentially) relatively large database. So if I wanted to backup my configs, I definitely need more than a few kB but instead a few (hundred) MB. databases and the like are better off in .cache in general....
b) for a multiboot environment, where I store all my synced data on a different partition (say ntfs formatted) so I can access it from more than one OS it would be helpful to keep seperate "config.xml"s but the same database. My experience is, that I get lots of conflicts on "OSshared"-repos on such partitions otherwise (for reasons known to me, that could be avoided with a common db)
c) -this is somewhat similar to a) but a more pressing matter to me- The database can get *really* large. I share about 500GB with my server on my laptop - I just saw that syncthing died on windows, leaving me with a 15GB database. It does the same on Linux occasionally (wrote about it on the forum after seeing other people with similar problems). It shrinks back once I restart syncthing (if I can- if there's no space left, it won't startup to clean it's own mess)

I know I can change the home-directory to achieve something similar. Doing so would have a few drawbacks though: 1. It wouldn't work well for the configs in case b) due to different repo-paths, 2. I like synctrayzor in windows or syncthing gtk- not sure howto give syncthing any arguments with it (didn't try, I admit) 3. integration with systemd/upstart would require me to change the parameters in the according service files  4. it wouldn't solve a) 5. It'd feel like a real messy solution

I probably wouldn't really care for all this so much if syncthing wouldn't grow it's database so much from time to time - so, if you don't think moving the db out of the config folder is a good idea, I'd be interested to know what causes this uncontrollable growth...

**Comment by AudriusButkevicius** [comment]
Symlinks solve this.

**Comment by calmh** [comment]
I can sort of agree that at least on unixes, .config might be the wrong place for a large database. On Windows and Mac I think the existing locations are appropriate?

However,

**Comment by calmh** [comment]
This has been up for discussion before by the way, and got kind of derailed by my hating on the XDG "standard"... I still think ~/.local/share/syncthing is a crap location to put stuff in. If anything, I'd probably rather sanction a move to ~/.syncthing/config and ~/.syncthing/index or something.

**Comment by arneko** [comment]
Do you have any clues as to why the database grows so large at times? I am a little confused because that never happens on my servers/arm machines, that sit on a 16GB SD-Card and share by far the most data with even more devices.

I will try to get the symlinks working. I was a little surprised that that should work, because I think you check the config file for being an actual folder, but then again, you can specify an alternative location for that....

**Comment by AudriusButkevicius** [comment]
Config file is a file, index directory is a directory, hence can be linked.

**Comment by AudriusButkevicius** [comment]
As for large index, I can't really explain it.if you could copy it when it happens, we couls take a look at what it consits off. My guess it it will be growing large due to compaction not kicking in due to how the OS schedules threads Go has running. Or due to the compaction routine not getting any run time by the runtime.

**Comment by arneko** [comment]
Ok, I do have an example zipped and ready, but as I said- it's pretty large (13.7 GB zipped, vs. 15.something before). I'll send you a message once I have it some place where you can download it at "reasonable" speeds...

**Comment by dcarosone** [comment]
I like the idea of ~/.config/foo and ~/.cache/foo (whatever the specific
names), since I have ~/.cache as a separate zfs dataset. There's generally
a lot more churn in there, so having a different snapshot retention policy
for cache really helps keep smaller/more/longer snapshots of my
real/important data.

**Comment by calmh** [comment]
> ~/.cache/foo

It's not a cache. Wherever we might put it, it's not going to be there. XDG dictates ~/.local/share/syncthing, but XDG is a freedesktop thing and we're both not very desktopy and also run on lots of platforms we freedesktop is not a thing anyway.

**Comment by dcarosone** [comment]
> It's not a cache.

True, which is why I didn't want to quibble about names.

It's a derived collection of metadata, that can be regenerated on demand
without loss (not counting time and extra work).  Akin to something like
image thumbnails, it does not contain important permanent state.

At least, that's my understanding, based on the ability (and occasional
need) to drop the db and rescan. I don't see we're in a hurry to lose that
ability?

Anyway, having a class of data with this property is common enough for many
apps, that being able to collect all the things of that class together and
apply specific policy (backup, version control, replication, storage device
speed, whatever) to the class is appealing and useful. A high churn rate
and possibly significant size makes it even more so.

The names, defaults, conventions on different platforms, etc is a separate
mess, mostly because those entangle different attempts at some implied
policy and moving context. I'm happy to edit config files, or even use
symlinks if confident they work, and accustomed to having different ideas
of policy than most defaults.

The most important thing, even if I can't change the location (to take
advantage of path-based policy inheritance) is to understand what the data
is when writing explicit policy (mostly ignore files).

**Comment by calmh** [comment]
Dropping the db incurs a rescan, yes, but more importantly it loses your sync history. If your file on disk doesn't match what the rest of the cluster has, we don't know if that's because you have an older version or a newer one. Hence we have to handle any difference after a database removal as a sync conflict. This is the aspect that makes it not a cache. 

(Also not a configuration file, so not saying this means the current location is correct.)

**Comment by dcarosone** [comment]
I was suspicious that the version vector stuff might have implications
along these lines, and that my understanding wasn't quite accurate. Thanks
for the confirmation, I'll be much more careful about dropping index db in
future.

I've dealt with similar issues before in other projects, particularly BSD
unionfs whiteouts and monotone version control. Handling delete vs change
conflict is especially tricky and does need external state.
