### ISSUE TITLE
Minimum free disk space should default to a saner value

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2234]
When setting the default minimum free disk space threshold, we should aim for a percentage that

 - Is not higher than 1%
 - Doesn't represent more than 10 GB
 - Is a power of ten

I.e. 1%, 0.1%, 0.01% and so on.

The value can of course be adjusted by the user afterwards, but this ensures we don't attempt to enforce terabytes of free space on very large volumes.

**Comment by uok** [comment]
does the GUI in the folder edit modal know the disk size of each folder? because besides `min` and `max` input type=number also has a `step` attribute - maybe we can use that with a dynamic step size depending on the disk size? or set `max` in % so the result never exceeds 10GB. next to the input field we could show a text field of the resulting size (= % * disk size) in GB.

easier alternative: 
set free space in GB not % and simply calculate max. GB (not higher than 1%, max. 10GB) on startup if it has not been set to 0 before

**Comment by calmh** [comment]
I don't think we need to tweak the default here. We have a default, the config is adjustable in as small increments of a percent as you'd like.

**Comment by uok** [comment]
I thought it is easier for the user to set a size instead of determining the disk size and calculating percentages.
