### ISSUE TITLE
upstream congestion, is there a way to use UTP?

### ISSUE THREAD

**Issue by donbowman** [syncthing/syncthing#2277]
https://en.wikipedia.org/wiki/Micro_Transport_Protocol is the uTP transport protocol used by bittorrent. If latency starts to go up, it slows down. This avoids causing congestion with TCP.

With syncthing, if i plug my laptop into hotel wifi after a couple of days of working offline, the latency goes to ~2s for as long as the syncing is in progress... nothing else gets through.

Although syncthing has an 'upstream cap' config variable, this is impossible to figure out and set, its different per network, and not really knowable.

So, can syncthing either use uTP, or, can it calculate the peak rate it is achieving and auto-throttle to some percentage of that? As an enhancement request.

**Comment by AudriusButkevicius** [comment]
There is already a ticket on reliable UDP, though that doesn't do any traffic shaping. Your comment about traffic shaping can go there. uTP is written in C and is no good for us, as it kills crosscompiling.

**Comment by donbowman** [comment]
uh, ok.
and on the idea of auto-pacing w/ tcp?

to bad go is not compatible with other languages, so closed.

**Comment by AudriusButkevicius** [comment]
Also, the current version uses TCP, and TCP has traffic shapping internally (search TCP sawtooth), so there is nothing we need to do in the current implemenatation as its already as efficient as it could be in terms of link speed. In terms of bandwidth sharing with other applications, I am not aware of any application which allows setting a percentage based cap, only a hard fixed limit in bytes

**Comment by AudriusButkevicius** [comment]
Go is C ABI compatible, and can consume C ABI, though we would not be able to compile to as many platforms as we are able today if we were to use that. Currently we can build for all platforms on any platform, that's the beuty of it. I know uTP is an algorithm, but a pure go implementation does not exist, so I say in C as that's the only usable implementation.

**Comment by donbowman** [comment]
i think u miss my point on the tcp part. its efficiently using all the bandwidth, and his prevents the link from working for anything else. e.g. skype breaks, my email breaks, etc. I think this app would be more useful for nomadic users (which is a primary target) if it were to share the link.
i can set the upstream to 10kbps, and be hugely pessimistic. or i can run speedtest first on each new network, then open he web interface and set the upstream speed to 80-90% of that. But this is kind of a hassle and defeats the purpose of having an auto-sync thing that is fully automatic.

so an algortihm that could be coded into syncthing would be: when starts syncing a new file, keep track of the max upstream speed achieved over 10s, then auto-set the 'peak upstream speed param' to 90% of that.

**Comment by donbowman** [comment]
Also, QUIC is an alternative to uTP to control the buffer-bloat. And its avail for go (goquic)

**Comment by AudriusButkevicius** [comment]
goquic uses CGO and links against OpenSSL which as I've suggested kills cross compiling.

I understand what your original request is about, and usually OS scheduler should deal with that and give a fair share to every process. I have not seen a piece of software which implements what you suggest. uTorrent, which is implemented by the uTP people doesn't even have this feature.

I am not saying that this is not possible, but there are a lot of edge cases which make it tricky, for example:
1. You might be limited by the remote ends link speed, throttling yourself pointlessly, especially as new nodes connect.
2. Having to re-evaluate the situation probably means it will be bursty, and will make your Skype call drop out every N seconds rather than not working at all.
3. If two nodes use this, they can potentially keep dropping speed one after another eventually dropping down to zero.

I could probably come up with a few more cases.

**Comment by calmh** [comment]
> OpenSSL

No, thanks. We've avoided at least two very bad and high profile vulnerabilities just during Syncthing's lifetime by not using OpenSSL.

**Comment by dcarosone** [comment]
It may be possible for Syncthing to set socket options that translate to
appropriate ToS or DSCP markings on the traffic, which could then be used
to help share the link more appropriately.

Not all networks will implement useful QoS, and I have no idea if Go makes
these options accessible or functional on all platforms, but I thought the
idea worth noting.
