### ISSUE TITLE
suggestion: a new way to expand folders?

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#2288]
For the visually impaired the folders list is workable, but some might have trouble expanding the folder heading to reveal the table with all the options and the edit button. On the mac I can just hit control command option plus space but having tested just space with NVDA, a free and open source windows screen reader, I don't see a way to do this. Can their be an alternative way such as hitting enter or clicking a link? So far the program is pretty much usable for the visually impaired.

Take care.

**Comment by tech10** [comment]
I agree with this, as I have some difficulty when using NVDA, and a browser like FireFox. Since it shows as only text in a heading to the screen reader, the focus doesn't go to it all the time on such browsers, so pressing enter on them doesn't always work, and dealing with putting the focus where it ought to be, then clicking it, can be a bit difficult. Making the headings with the folder names links would help significantly, as they could then be put in the links list of a screen reader, or tabbed through in the browser window.

The devices list also has this same problem, as it behaves as the folders list does. I'd propose that whatever accessibility enhancement is done to the folders list, the same is also done to the device list. It would make the WebUI a bit more accessible, and a lot easier to use.

**Comment by marrie** [comment]
I agree. I hope this can be looked in to. It's not a rank 1 bug, but it is still quite annoying. Clicking the text works for me all the time in osx, but we need a different solution for the beginners out there who don't want to take the time, or have the time to explore. Plus tabbing would be nice even though I don't really do that anymore. I could bring it up from the item chooser and just search and then click.

hope that helps a bit.

**Comment by tech10** [comment]
The item chooser does seem to work most of the time, though since I've got ten folders and as many devices connected, when I start getting to the bottom of the list, I've got to manually move the mouse focus again. So it's still not the best solution. Links would be far more screen reader consistent, especially if you're arrowing down through the items on the page and want to click on one. Also, as it is now, it's just reported as a heading, so I could see where some could be confused by the screen reader not reporting it as an item that's clickable to bring up other options, which could make it difficult for some to operate until they're told that, yes, you can actually click on the heading to pull up a status table and the edit and pause buttons for devices, or to edit folders that way, etc. Links would fix that difficulty, too.

**Comment by marrie** [comment]
That's  true. Actually I meant the item chooser in osx. It shows me everything and i can filter by typing. I then vo space twice, once for focus, once to "press" the item. But links would probably look better visually especially if you organised them in to subheadings.

**Comment by tech10** [comment]
That's a good idea. Where it says folders and devices, those could remain level three headings. The folders and devices themselves could be level four, or something. But, you'd need to make sure it would visually look good throughout all of these modifications, too.

**Comment by calmh** [comment]
Thanks @marrie, @tech10 for bringing this up and @wweich for making it happen!

**Comment by tech10** [comment]
Indeed, thanks! I hope this will be in the next release, perhaps 0.12.20.1 or 0.12.21. It'll certainly make things much easier and more accessible, I'm eager to try it out in a stable release!
