### ISSUE TITLE
RFE: -restart option to mirror the web gui

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#2297]
Would be nice.

**Comment by AudriusButkevicius** [comment]
Use syncthing-cli

**Comment by jpjp** [comment]
Why though? What is the boundary between things that belong in syncthing, and things that belong in syncthing-cli? Surely if the web gui offers the option then it belongs in the syncthing binary for the cli too?

**Comment by AudriusButkevicius** [comment]
No, because in that case we'd have to add functionality for adding devices from cli, changing config options, etc blowing up the -help and the code in general. 

At the point I was implementing the cli, @calmh decided against that.

Syncthing provides the rest API to be controlled, not a bunch of command line switches, and syncthing-cli just helps you with that.

I'd be keep to scrap all the upgrade bullcrap from it too, and move that to cli.

**Comment by calmh** [comment]
Syncthing doesn't have a CLI. It has a few flags that affect it's execution if given at launch, and then it has `-version`, `-generate`, `-upgrade`, `-upgrade-to` and `-reset`, all of which are *offline* things, i.e. you run syncthing with that and it does it thing and immediately exits. The odd one out is `-upgrade` which has fairly recently gained the ability to talk to a running syncthing. It's the only thing that does that... And it's a bit hacky...
