### ISSUE TITLE
Scanning and deletes should be processed even when above the free space limit

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#2370]
Not sure if it is a bug or not, but it's better to write it down:
- I am running into the free space limit and I get these messages: `[TYZZZ] INFO: Skipping folder dokumente scan due to folder error: insufficient free space`
- Due to the limit currently my sync stucks at 59 % (at that box where the limit has been hit)
- I have deleted the big file, that is being pulled on another node
- Syncing stays at 59 %

---

After restarting syncthing it recognizes that there is not more file to pull; that's fine. But because of the free space limit it keeps stopping that particular folder, so it does not delete the file, hence it keeps stuck.

**Comment by rumpelsepp** [comment]
OK, lets sum up my weird brain after I slept about it: when you run into the free space limit, the folder is stopped and you can't delete any files on that node by deleting them on other nodes. I consider this as a bug.

**Comment by MyPod** [comment]
Has the stopped instance restarted? I'd ingenuously think it needs to sync
the index before realising that the file that caused the stop is gone. If
that index pulling isn't done because of the stopped state, a reboot
might/should work (?)

**Comment by calmh** [comment]
This is a bug. We need to separate the error handling more.

- We should not stop scanning because of a lack of free space. We don't need free space to scan.

Maybe:

- Should we pull but and only handle deletes when we are below the free space threshold? *Usually* deleting files will give us more free space but this is not *always* the case, so there should probably be an advanced option `handleDeletesWhenOutOfSpace` or something that defaults to true...

**Comment by rumpelsepp** [comment]
> Usually deleting files will give us more free space but this is not always the case

In case of enabled versioning deleting files won't generate more free space. :/

**Comment by calmh** [comment]
Yeah, and with filesystem snapshots and so on, hence usually. But that's a good point, in that we *know* when versioning is enabled, so doing this to try up free space then would be pointless.

**Comment by calmh** [comment]
I'll retitle this issue to refer to the main problem, if you don't mind.

**Comment by calmh** [comment]
Well, maybe that wasn't the main issue that you were running into...

**Comment by calmh** [comment]
There. Even in the versioning or snapshots case, a delete/rename doesn't take up that much more space and it's worth trying.

**Comment by rumpelsepp** [comment]
Yeah, that is the issue. I am really bad at finding descriptive titles...

**Comment by vontrapp** [comment]
This is an important issue for me. Enough so that I might contribute a patch.

What normally happens when:
1) A large file is currently downloading from A to B
2) A deletes the file
3) B has versioning enabled?

Depending on the answer to the above situation, the same thing might happen when a folder is out of space for downloading yet a delete is allowed to propagate through.

But more importantly for me is to take folders where there is no versioning and "unstick" dozens of nodes by deleting large unneeded and perhaps partially synced files from a node that is fully synced, rather than manual intervention on a dozen individual nodes.

Perhaps a config option in the folder that says to allow deletes when the folder is otherwise in error state.

**Comment by imsodin** [comment]
In your scenario A would send a index update saying that the file is now deleted. I don't know what exactly happens to the file being downloaded, but eventually it will be deleted.

I don't think this would need any config option, in my opinion it would always be desirable that deletions can be applied when there is too little disk space at the folder root.

**Comment by vontrapp** [comment]
I did look into the code a little bit. Seems that the insufficient space error is lumped into all "folder errors" which all cause the folder to be paused until the error is resolved.

Seems like the insufficient space condition would have to be pulled out of this group (perhaps becoming its own special status?) OR the folder management that pauses a folder on error checking if the specific error is a space issue and not pausing the folder

In either case, the pullers would want to be denied, paused, or stopped in some manner (and copiers as well?) with item level errors showing for those files. While meantime deletions can still be applied.

Additionally, the size of the file being pulled could be checked and the file denied for space constraint before pulling any of it if pulling the whole file would reduce the free space past the threshold. Not sure if this last bit is desirable behaviour or not.

Any objections to this line of thinking?

**Comment by vontrapp** [comment]
I think you may be right about not being an option at all.

It was mentioned that there are several scenarios where deletion will not be expected to actually free any space (are there cases where deletion would increase used space? I don't think there is...) However, most if not all cases where deletion doesn't free any additional space _at the time of deletion_ the files are nonetheless deleted, and thus treated as deleted files, which typically means they will age off _eventually_, and when eventually happens, more syncing can proceed.

And besides when a node is doing snapshots/archives/file versioning it really should have enough space to do so, and failing that it will remain stuck even after deletions are "applied". In this scenarrio the right thing is to get more storage space on that node.

In scenarios where the node space is rather limited and things can "accidentally" get too full, the right thing is to undo the accident (delete the file). It would be **_very_** nice to be able to resolve the whole cluster from a single point.

**Comment by imsodin** [comment]
Separating the folder size error wouldn't be a problem, keeping scanning seems like not that much work either, but handling pulls only partially needs some thought. Having a different "modus" where only deletes are allowed in one puller iteration is one thing, but you also need to handle the scheduling of pulls (as they will never complete when free space keeps being below limit) and presentation of the error on command line and the UI. It must be apparent that the issue is with disk space, as opposed to e.g. missing peer device. And there will probably be corner cases that didn't come up yet.

**Comment by Ferroin** [comment]
@vontrapp If reflinks are involved (as is possible on XFS, BTRFS, or OCFS2 on Linux, or when using deduplication on ZFS), then there's no guarantee that deleting a file will _ever_ free space, as all the (filesystem-level) blocks in the file may be reflinked by other files on the volume.  However, I don't think Syncthing should care about that (since it's not hugely likely, and there is no sane way to care about it), and agree that it should still process deletions and scanning instead of pausing the folder.

@imsodin For the UI part, perhaps turn the folder name yellow to indicate soft-failures like this that don't prevent the folder from being paused?  I can think of a couple of other situations that might be handled similarly if partial pulls were possible (for example, getting an index update telling you to update a file that you don't have permission to access).

**Comment by imsodin** [comment]
I think there may a misconception about the folder stopped state: It isn't really stopped, if the error goes away, it will recover by itself. It's just that by checking folder health before pulling and subsequently deleting we prevent this particular error from going away by remote action. So in my opinion there doesn't need to be an additional state, that would be unnecessary increased UI complexity, it should just give the appropriate reason for the error state in the expanded folder pane. The way I see this issue, it is less about a change of sync behaviour but about keeping as much operations up and running as long as possible (thus allowing certain scenarios to get unstuck where today they keep stuck until manual intervention).

**Comment by Ferroin** [comment]
@imsodin You're right, I did misunderstand this a bit.  I was under the impression that the 'Stopped' state was functionally equivalent to 'Paused', as I've never seen it recover by itself when I fix the issue that stopped it (it's also been a while since I ran into such an issue, and I've been in the habit of forcing a rescan after fixing the issue though).

Given that, I would tend to agree with your assessment.

**Comment by vontrapp** [comment]
So there are already per file error states. Examples are:
"file went away on remote server while syncing"
"remote server that has file went away"
"symlinks not supported"

Errors like these show up under an error count link under the folder. Expanding the link lists each file in error state and an explanation of the error (with strings like the above)

Folder state is to be stuck at a certain percentage of sync and not progressing, along with this file error count.

Is this the direction we want to go with free space errors? That is the file puller generates an error for that file that says it can't (or refuses to) pull the file for lack of space. And the folder remains out of sync, with explanations, but doesn't have a folder health level error?

**Comment by Ferroin** [comment]
From a UX perspective, that's not all that user friendly.  As an example, I've got folders with two thousand files in them, and that's not even the fiftieth percentile according to https://data.syncthing.net.   This means in turn there is the potential for thousands of 'error' entries to sift through (and in fact, I'd argue that's probably pretty likely, the most likely case to hit this is a large folder with lots of actively modified files), which has the potential to slow down Syncthing significantly (I'd be more than willing to be that the code surrounding reporting of errors isn't hugely time optimized, since it's not a common code path), and possibly hide (at least temporarily) other error conditions from the user.

Unless I'm mistaken, Syncthing won't try to pack-in smaller files right up to the threshold (and if it does, I'll probably be opening an issue asking for a switch to disable that behavior), it will just stop processing things until there's enough free space.  Given that, combined with the UX issue mentioned above, and the fact that the threshold is configured per-folder, I think it does warrant an error state at the folder level if at all possible, even if it doesn't behave like the other folder-level error states.

**Comment by calmh** [comment]
As is, there are two checks. One is the general free space threshold, defaulting to one percent of the disk. When exceeded the folder is stopped - nothing happens until space is freed up. There is also a per file check, where sync is not attempted if the temp file can’t possibly fit, even if the general threshold is satisfied.

I think we only keep or track the first n file errors, on the assumption that wading though thousands of them is never pleasurable.

I could see the general threshold thing just affecting file operations that require significant space, like the extra check we already do per file.

**Comment by Ferroin** [comment]
OK, that dispenses with most of my arguments against it showing up as a per-file error.  The only other UX issue I can think of with that is one I forgot to mention:  There's no clear indication just looking at the folder status that there are file errors, you have to be paying enough attention to realize that it's not actually making any progress syncing.  I'd personally like to see that improved a bit in general, but it's kind of orthogonal to this issue to be honest.

**Comment by nekr0z** [comment]
I think the issue original reporter was complainig about is really about the fact that failed generla free space check stops the folder altogether, and whatever happens to that folder globally (i.e. deleting files on other nodes) can't change this state (in this example I'm assuming there's only one folder and there are no file deletes elsewhere on filesystem). My experience shows that per file check is unreliable and Syncthing as of 0.14.41 tends to happily sync files beyond free space limit, then suddenly find out the limit has been exceeded and stop the folder, thus requiring manual intervention on system (i.e. manually freeing up space) before synchronization can be resumed.

**Comment by AudriusButkevicius** [comment]
Isn't that what it's supposed to do, as in stop when the limit is breached? Not sure I understand your comment.

**Comment by nekr0z** [comment]
@AudriusButkevicius Well, stop when the limit is breached is the expected behaviour, but not the desired beraviour. This is exactly what this bug is about.

1. After the limit is breached folder is now in _Stopped_ state. In this state all sync is stopped, so deletes are not synced either. Deleting files on other devices wouldn't get this folder out of _Stopped_ state. This is exactly the issue original reporter was complaining about.

2. As @calmh pointed out, we have per-file checks that prevent a file from being synchronized if the said file woudn't fit on the filesystem. It would make sense to use same per-file checks to make sure the file is not downloaded if downloading it results in breaching the free space limit, but somehow this behaviour is either not implemented or not working.

The desired behaviour as I see it would be:
1. If downloading the next file will cause breach of free space limit - don't download the file in the first place. We already do that partially (for when downloaded file would not fit to filesystem), so why not check it against limit, too?
2. If however the limit is breached, continue monitoring for deletes on remote systems, as deleting some files can free up space and allow for un-breaching the free space limit (now, granted, it might as well not, for example with versioning on, but it wouldn't hurt to try, would it?)

**Comment by Ferroin** [comment]
I think I've already made my views clear, but just to reiterate:

* When the free space limit hit, Syncthing should stop trying to add new data to the folder.  Whether this means stopping all syncing that requires downloading data, or just stopping syncing that adds new files and increases the size of existing files is up for debate, but I think the first case is easier, while the second would provide theoretically better UX (because it allows users to truncate things like append-only files on the source node as a fix instead of having to delete them or truncate on both nodes).
* File deletions should still be processed even if the free space limit is hit, as this allows one to fix things on the source node (and makes sure that stuff that does a replace-by-rename of a big file doesn't wedge a remote node).
* Syncthing shouldn't care about the possibility that a deletion won't free up any space, wheter or not it does does not change the fact that it still needs to be synced eventually, and syncing it won't take up more space (with the possible exception of having versioning enabled and some complicated setup with reflinks).
* There should ideally be a much clearer indication that an error has stopped a folder from syncing in the Web UI.

**Comment by AudriusButkevicius** [comment]
@nekr0z this is just pushing the warning to pop up earlier, which is all down to interpretation of the setting. Not sure why this matters so much?

**Comment by nekr0z** [comment]
@AudriusButkevicius This is not just pushing the warning to pop up earlier, this has direct impact on whether files get downloaded at all.

**Comment by AudriusButkevicius** [comment]
I am not sure I follow.

1. If I download A I will be over limit so I don't download it.
2. I downloaded A, now I am over limit so I won't download B

In both cases it stops downloading files, earlier in case 1, later in case 2.

**Comment by nekr0z** [comment]
Allright, I'll lay it out for you for these two scenarios:

1. If you download A you will be over the limit so you don't download it. Folder is _Out of sync_, all operations continue except for those that cause errors (i.e. you don't download B either to keep under the limit). C, D and E get deleted globally, you delete them locally. Now you can download A and B and still have space to go. Operation normal. As intended. THIS IS THE DESIRED BEHAVIOUR

2. You downloaded A, now you're over the limit. Folder is _Stopped_, you don't download B. Again: folder is _Stopped_, you don't do anything. C, D, E, F and H (and a two-terabyte M - but who cares) are deleted globally. You don't delete them. because you're _Stopped_. You could download B and Y and Z if you did, but you don't, because you're _Stopped_. Now you wait for the user to come and manually free up the local filesystem. Forever. THIS IS THE CURRENT BEHAVIOUR

Case 2 is bad UX. Case 1 is much better UX.

**Comment by vontrapp** [comment]
I *really* want this fixed,  and I'll contribute patches. I just want some direction in an agreed approach to fixing this. 

A) out of sync state on files (even their tmp files) that would violate the *free space* requirement (as pointed out this is already done for total space?) these operations continually retry continually fail, until other operations that can succeed are performed and *happen* to remove the condition.

B) current behaviour except that deletes are somehow managed to get through anyway. 

C)  something else? 

I'm inclined to A, paying attention solely to the top file and whether it violates the reserve space condition.

If the top file violates the condition but would no longer violate the condition once replacing *another* file... So what? I think this is preferable to the current behavior. Block the file whose tmp would exceed the reserve, with a message that says why. The user action is still to free up space,  but now that space can be freed on *any* node.

For some background my use case goes like this:

Many nodes share a folder. Most of these are workstations and a couple are large storage servers. The outstations all have different storage capacities.

Someone drops some very large files in server a. Server b syncs those files and later another user does something with the files and deletrs/moves them from the sun folder. 

Half the workstations remain completely wedged because they ran out of space. One must now lost all the workstations that are not synced and log into each one and free up space in the folders by deleting (hopefully!!) files that *were already deleted* elsewhere. I've already made mistakes in this regard and deleted files that were NOT sleepy delete elsewhere, syncing resumes, and now those files are deleted everywhere! Doh!

This is extremely frustrating.

**Comment by vontrapp** [comment]
Tmp file,  not "top file"

**Comment by Ferroin** [comment]
I'm inclined to favor option A as well, simply because that's how I would expect it to work if I had no programming background.

**Comment by AudriusButkevicius** [comment]
So to me your furstration sounds like a Henny Youngman problem,  yet I welcome any contribution.
The general approach I'd take with this is to remove folder size check from CheckHealth, and move it into the puller in lib/model/rwfolder.go, potentially erroring out the file somewhere in copier (after shortcut) and passing it straight to the finisher.

Repulling happens multiple times in a row in case of errrors, so in case deletes that make enough space get processed in previous pull, this should eventually recover.

**Comment by vontrapp** [comment]
OK,  I'll attempt a solution A approach. Probably over Christmas break. If anyone wants to collaborate, hit me up.

**Comment by vontrapp** [comment]
Thanks! Sorry I never got to it myself, but this totally rocks!
