### ISSUE TITLE
Stuck scanning folders

### ISSUE THREAD

**Issue by danilvoe** [syncthing/syncthing#2378]
If you open the Web page management on the status inquiry scan time scanning freezes.

**Comment by AudriusButkevicius** [comment]
Scanning does not freeze, as when running with STTRACE=scanner you will see it contintinues scanning. The reason the UI is not updated is because the scanning has not finished yet, hence I don't really see a bug here. You just need to give it more time, or get a faster disk. Lets continue the discussion on the forum thread before opening issues.
