### ISSUE TITLE
Allow better peer connection control #suggestion 

### ISSUE THREAD

**Issue by ISJ-439** [syncthing/syncthing#2427]
Would it be possible to allow us to clear the meta-data from a peer without removing and adding that peer? It seems that sometimes every device can connect to that peer but one and it just sits there doing nothing. Maybe?

**Comment by AudriusButkevicius** [comment]
Metadata has nothing todo with ability or inability to connect.

**Comment by ISJ-439** [comment]
I figured it was caching bad info such as a IP address. I'm not a programmer, sorry.

**Comment by ISJ-439** [comment]
For instance, 3 of the 4 devices in this image are certainly online http://i.imgur.com/w5keZDy.png

**Comment by AudriusButkevicius** [comment]
So I am closing this, as your issue is definitely not caching etc, but connection issues.
It could potentially be due to IP addresses changes being cached in the discovery server, but even then it's very unlikely, as it returns all the IP addresses seen in the last 30 minutes.

I think your issue is most likely being behind a firewall/NAT and not being able to establish a direct connection.

I suggest you consult the docs:
http://docs.syncthing.net/users/firewall.html

And if you still have issues, open a thread on the forum asking for support.
