### ISSUE TITLE
Cannot write .stignore on Android devices

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#2472]
Syncthing cannot write/update .stignore on Android due to failed chmod operations.
In mode.go we use CreateAtomic that relies on chmod operations which are not permitted on Android. See the following error:

```
[BH4HG] 03:33:26 WARNING: Saving .stignore: chmod /storage/1AF9-2A10/DCIM/.syncthing.tmp.190076736: operation not permitted
```

**Comment by kluppy** [comment]
So what would be the preferred way of dealing with this?

Allow a nill to be passed as the permissions and not chmod in that case.

Return the fd from Atomic along with an error and let the calling code decide if it would like to progress.

Not use Atomic when creating these files?

**Comment by calmh** [comment]
I suggest modifying CreateAtomic to ignore the error return from chmod if the platform is android.

**Comment by kluppy** [comment]
I thought chmod would fail on any fat32 mount not just Android.

**Comment by calmh** [comment]
No, chmod works perfectly fine on FAT. It doesn't store all the bits of course, but that's something else.

**Comment by Nutomic** [comment]
@calmh We currently build Syncthing with `GOOS=linux` because of [build problems](https://github.com/syncthing/syncthing-android/issues/640#issuecomment-218369098). So this check is currently not working.

As a workaround/solution, you could just log the error instead of failing. Alternatively, we could pass the fact that we're running differently, eg via build flag. But this seems to be the only place where you check for `GOOS == "android"`, so it's probably not worth the effort.
