### ISSUE TITLE
Out of sync page should mention what machine the conflict comes from

### ISSUE THREAD

**Issue by flz** [syncthing/syncthing#2476]
I've got a cluster with about 40 machines and one has a file that's causing a conflict on my master (readonly=True) but I've got no way to figure out which without logging on each host and looking for the file myself.

**Comment by andrewufrank** [comment]
i have the same problem (with 10 machines). the issue is usually a problem caused by changing a .syncignore file (and a new software inventing yet another way of naming backup files).
would it be solved if all machines had the same syncignore? would this be desirable - in my case, it would.
thank you for considering!

**Comment by Nutomic** [comment]
Looks like a duplicate of #2327.
