### ISSUE TITLE
Can't set ignore patterns when adding a folder

### ISSUE THREAD

**Issue by fatek** [syncthing/syncthing#2496]
The "Ignore Patterns" button is missing when I'm using the "Add Folder" menu.

To add ignore patterns, I must first finish with "Add Folder" and then click the edit button on the folder I just added.

**Comment by wweich** [comment]
The ignore patterns are currently saved in a file inside the folder independently of saving the folder config in Syncthing.
So adding ignore patterns while adding the folder would leave the file inside the folder when you decide to cancel the addition. Or delete the file when canceling; but does Syncthing know if it was there before?

IMHO This will/should be fixed with #2491.

**Comment by AudriusButkevicius** [comment]
We don't know where the folder is until its added, but yes, the ticket above should fix it.
