### ISSUE TITLE
Linux amd64 build could potentially be fully static

### ISSUE THREAD

**Issue by johnjelinek** [syncthing/syncthing#2555]
I'm not sure what dependency I'm missing, but it doesn't on alpine 3.2 for me.

**Comment by AudriusButkevicius** [comment]
whats alpine

**Comment by calmh** [comment]
I'm guessing this: http://www.blang.io/posts/2015-04_golang-alpine-build-golang-binaries-for-alpine-linux/

I see that as a quirk in Alpine; someone who uses it needs to create a build for it.

**Comment by johnjelinek** [comment]
Huh? Build a static binary like in your link: `CGO_ENABLED=0 go build -a
-installsuffix cgo` and then deploy everywhere.

**Comment by johnjelinek** [comment]
@calmh: I think the quote you're referencing won't matter if you build a static binary to deployed everywhere.

**Comment by AudriusButkevicius** [comment]
Well there are reason why we dont build a static binary.

**Comment by johnjelinek** [comment]
Can you please elaborate?

**Comment by AudriusButkevicius** [comment]
I think if we provide a fully static build, that potentially raises the bar of what's the minimum requirements required to run it, but @calmh knows better.

**Comment by calmh** [comment]
So my reaction was the same, and I've been doing a bit of digging. The main thing we lose with a static build is access to the OS resolver library. This is an issue on Windows and Mac where somewhat exotic name lookup techniques are commonplace. On Mac we also lose access to the certificate store, which is critical. This is why we have native builders there.

However it doesn't seem like we lose anything relevant on Linux so we could potentially go fully static there. The 32 bit build already is, because it wants to run on peoples crappy NAS distributions that have libc from the 19th century or thereabout.

**Comment by johnjelinek** [comment]
Ya, I was meaning static just for the linux binaries, not for all
builds/platforms.

**Comment by calmh** [comment]
The linux builder now builds statics. Lets see how that works out.
