### ISSUE TITLE
Clean up "master" terminology

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2679]
I.e., the concept of a folder that does not accept changes from the other devices in the cluster. Started as "read only" but no-one understood what is was read only against. Became "master" as in "master copy" or "golden master", but is still confusing for many. The config option is still called "readOnly". In discussions about folders that act the opposite way, "slave" is invariably proposed.

I suggest that we should clean all this up to a terminology centered around "changes" (or similar) which is what happens to files or directories, and is what we synchronize between devices. We then have folders which "send changes" and "receive changes". The current "Master" checkbox then becomes "Don't receive changes", or possibly "Only send changes" (but the "only" is ambiguous there), with a help text like "Don't receive changes to files or folders sent by other devices. Changes made locally are always sent." or so. The config option would be "sendChanges", true by default.

The "Override" button would become "Overwrite remote changes", "Force send changes" or something similar.

Possible new folder modes would be expressed in the same terms, e.g. "Don't send changes" for something where we expect no local changes to happen.

Feel free to bikeshed.

This changes our external API so would be a major version change.

This ticket obsoletes #1731.

**Comment by generalmanager** [comment]
I think this is the only reasonable way to phrase this. Especially with additional features like "don't accept/receive deletes" the current phrasing would be very ambiguous and lead to even more support requests based on misunderstandings.

**Comment by CoupeWare** [comment]
I've always wondered what happens if you have 2 master folders. I've been meaning to test this. Based on what you have written here I suspect they "Don't receive changes" from each other.

I use master folders when I'm using Syncthing for backup. In most cases the master syncs to 2 or more backup devices located in different places. I think of the backup folders as "Archive Folders" rather than the source folder as a "Master Folder". One thing I would find very useful is an option to have normal folders on more than one source device that sync with each other in read/write mode and one or more devices with the folders set as "Archive Folders" which get changes from both source devices and never send changes. The downside to this is that multiple Archive devices would not be able to share with each other and keep each other up to date when the source devices are offline.

As things are I would like to be able to override changes on the Archive devices. I don't always have access to the source devices but I can always get to the various Archive devices.

**Comment by BethAr** [comment]
Here is a suggestion:

Text on folder --> "Master Out of Sync" / "Slaves Out of Sync"
Yellow Button --> "Override Slaves" (no confirmation)
Red Button --> "Override Master" (open confirmation dialog)

**Comment by Tralen** [comment]
Wouldn't be better to drop the "Master" terminology altogether?

The checkbox instead could refer to: "Manual Sync", as opposed to "Automatic Sync". It could even be a dropdown with the two options. The tooltip could then say: 
"When the folder is set to Manual Sync, changes to this folder must be accepted manually by using the "Accept Changes"  button, or rejected with the "Reject Changes" button.

The Master terminology could then be saved to an option where all changes are rejected automatically, if people still need it. Perhaps, it could be an additional entry to the above dropdown: "Never Sync" or "Protected Sync".

**Comment by jkufner** [comment]
Manual and Automatic are wrong words in this context. Also the "force" button is very confusing.

Sync type should be one-way or multi-way. One-way sync would have source and destination. Multi-way sync would have peers.

So I see three modes for a shared folder:

**One-way sync - Source:** Source is never modified by syncthing, all changes are sent to Destinations. When multiple Sources are detected, an error is shown and sync aborted.

**One-way sync - Destination:** All changes from Source are sent to all Destinations. Destination should not be modified by anything else but Syncthing. Any local changes in Destinations are overwritten by Syncthing without asking.

**Multi-way sync - Peer:** Changes are propagated to all other peers. When a file is added on one peer, it should appear everywhere. When file is deleted, it should disappear from everywhere.

**Comment by larslemberg** [comment]
Josef,
That is a very good explanation of how I envision the Synching Master
working, and your terms of Source, Destination, and Peer are clear. Another
scenario is a cluster that contains one or more Destinations but no Source.
Should that also abort the sync?
Lars

**Comment by Tralen** [comment]
The problem with 'Source' and 'Destination' is that the meaning changes depending on your perspective.

*This* computer may be the source of changes for *that* computer, in my perspective. But the source of changes for this computer can be another computer and also itself.

'Local' and 'Remote' is clearer in that respect.

**Comment by jkufner** [comment]
@Tralen No. It is always about data transfer. Data are flowing from source to destination. These are not relative terms, they do not depend on point of view. Local and remote are relative, they depend on location of speaker/observer.

**Comment by jkufner** [comment]
@larslemberg If there is no Source, then sync will not start. The Source may be offline, so Destination should simply wait for the Source. Destinations shoud show a status message like "Waiting for Source.", it is not an error. Once Source appears, it will say how data on all Destinations should look like and then sync should start. When desired state is known, data may flow between Destinations to speed up the sync (like BitTorrent does).

**Comment by Tralen** [comment]
Aren't you removing functionality? In the current setup with the Master Folder, the user can at least protect itselft from change without having to reconfigure the whole setup.

**Comment by calmh** [comment]
You guys... This ticket is about the terminology used to describe the existing concepts. Source, Destination and Peer are useful here, that's fine. The debate about what should happen when in some hypothetical future when the concept of "Destination" devices is supported is way out of scope here.

**Comment by CoupeWare** [comment]
I think the existing terminology is OK as far as explaining the current function. I don't think there are 1 or 2 words that will make this clear without the detailed explanation below the "Master Folder" checkbox. 

"Files are protected from changes made on other devices, but changes made on this device will be sent to the rest of the cluster."

I suggest changing the words to (assuming this is true):

"Files are protected from changes made on other devices, but changes made on this device will be sent to the rest of the cluster except for other master folders in the cluster."

I think part of the reason it's confusing its because of how it's designed. BTSync used read/write keys and read only keys and it was clear if you gave someone the read only key they could not write back to others in the cluster. I'm not suggesting that you go that direction, after using BTSync for a while I find Syncthing much more flexible.

I think maybe the reason this is confusing is because you are assigning the direction of the sync to the folder rather than to the connection. The more I think about a way to do this the more complicated things get (the cost of flexibility) and the happier i am with what you have given us.

**Comment by camsteffen** [comment]
My two cents: Pick a simple, concise terminology and have it well documented. I think "master" is perfect.

**Comment by entonio** [comment]
I think either the master / 'read only' concept is kept, or the system must be complex.
If it's to be complex, what about having a whole section like this:

- Accepts changes from other nodes:
  - new files: Always | Ask | Never
  - change in file contents: Always | Ask | Never
  - file deletes: Always | Ask | Never

- Sends changes to other  nodes:
  - new files: Always | Ask | Never
  - change in file contents: Always | Ask | Never
  - file deletes: Always | Ask | Never

'Ask' means the UI would show a button to do it.

As to what happens (now or later on) with more than one master, my understanding is that each will ignore the changes made by everyone else. Nothing serious.

**Comment by generalmanager** [comment]
@entonio This would be a new feature and would need a new feature request ticket. There is some history to this discussion in the forum as well as other tickets on github. This is basically a reminder to implement what was agreed upon earlier.

As was discussed previously (can't find it right now) the one solution with basically no possibility of misunderstandings is to describe what happens to the files/folders in terms of "send changes" and "receive changes".

**Comment by entonio** [comment]
@generalmanager I understand that. What I'm saying is that imo either the current terminology is kept, or the new one should take all these cases into account even if the granularity itself is not implemented at this point (notice my comment is pretty much in response to @calmh's OP). That would mean I'm voting for 'Accepts changes' | 'Sends changes'. (I would prefer 'Broadcasts' to 'Sends', but I haven't seen anyone propose that.)

**Comment by calmh** [comment]
I think we've reached maximum bikeshedding on this issue; we'll open for comments again once an actual proposal/PR is on the table. :)
