### ISSUE TITLE
meta data folder place

### ISSUE THREAD

**Issue by eschnepel** [syncthing/syncthing#2716]
As I have to stick to android 4.4 I cannot write to the sd card. Root permission does not work either. In order to sync the camera folder the meta data needs to be written somewhere. Why not using the app specific folder on the same sd card? I activated master folder as well as do-not-delete settings so remote changes won't effect the data folder.

**Comment by wweich** [comment]
What metadata specifically?
The file `.stfolder` must be inside the folder itself, because this is the only way for syncthing to know if the folder is really there, so it will not delete all files on the other nodes when you remove your SD card or the drive in the PC is unmounted.

**Comment by AudriusButkevicius** [comment]
Try the android repository

**Comment by eschnepel** [comment]
@wweich can i create the file on my own? and syncthing will do everything right? Should be any content in or is it empty?
@AudriusButkevicius: what did you mean with "android repository"?

**Comment by wweich** [comment]
He meant, that this is the issue tracker for syncthing, not for syncthing-android. You should have posted your issue here: https://github.com/syncthing/syncthing-android/issues

You can create the file manually. It should be empty. But AFAIK it doesn't matter. As long as it is there, all is good ;).
If you want to have ignores, you need to create and edit the `.stignore` file manually as well.

There is no need to enable both master folder and ignore deletes, as master folder will ignore everything.

Future versions of syncthing might store ignores and other meta data inside the db, which leaves only the `.stignore` file.

I have also read, that in future the master folder might not need an `.stfolder` file anymore.

**Comment by eschnepel** [comment]
Thanks a lot @wweich. I have touched .stfolder and it worked as expected.
