### ISSUE TITLE
Provide secure hashes in sha256sum.txt.asc

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing#2773]
Is there a good reason why we are still using SHA1 hashes for release signing? Even the sha256sum.txt.asc contains only SHA1 hashes, which many users probably won't notice.

If they've heard about SHA1 beeing insecure/not recommended and SHA256 beeing secure, they'll likely assume that the sha256sum.txt.asc file actually contains SHA256 sums. SHA512 would be even better of course, but I don't want to appear greedy ;)

**Comment by calmh** [comment]
So, there's a few different points and some confusion here. I'll try to address and clear up.

- The sha256sum and sha1sum files are for humans only. The auto upgrade process never looks at these files. The auto upgrade process uses a 521 bit EC signature of the binary located inside the release package.
- The sha256sum file indeed does contain sha256 sums. It says "Hash: SHA1" at the top, but that refers to what GPG is using when it signs the text file. That's apparently the default; I hadn't noticed or cared. I don't think it's a big deal.

I think both sha1 and sha256 are plenty secure for the purpose; even if we are approaching some sort of point where there might theoretically be collisions against sha1 with 2^88 attempts or whatever, creating such a collision that is still a valid release package and contains a presumably malicious but otherwise working syncthing release doesn't seem feasible.

**Comment by generalmanager** [comment]
Oh yes indeed, I'm working mostly with sha512sum and thought the hashes looked very short. Together with the Hash: SHA1 I simply assumed them to be SHA1.

>I think both sha1 and sha256 are plenty secure for the purpose; even if we are approaching some sort of point where there might theoretically be collisions against sha1 with 2^88 attempts or whatever, creating such a collision that is still a valid release package and contains a presumably malicious but otherwise working syncthing release doesn't seem feasible.

Agreed, it's more nice to have/best practice to upgrade. There are collisions today, but there isn't yet a public & cheap enough possibility to forge those. It's not really clear how far ahead of public research some agencies are. At times they were two decades ahead, giving them a lot of wiggle room. This is probably one of the reasons why chrome and firefox will stop accepting SHA1 signed certs soon.

So if it's just a flag in some compile routine, I don't really see why we shouldn't do it. If it's for some reason a lot of work, we can probably put it off for another year or so.

**Comment by generalmanager** [comment]
Just wanted to check on this issue again after Google announced their SHA1 collision of a PDF document created with ~10^19 calculations (https://news.ycombinator.com/item?id=13713480) but I see you already upgraded the GPG signature of the text content to sha256.

Maybe we should drop sha1sum.txt.asc altogether so nobody can overestimate the security of their verification method. I don't see any real drawbacks in dropping the sha1 checksums. What do you think?
