### ISSUE TITLE
Debian SysVinit Script

### ISSUE THREAD

**Issue by typomedia** [syncthing/syncthing#2990]
I am wrong here, but I have a SysVinit Script for Debian :)

https://gist.github.com/typomedia/3fe16c0e8214ce60b0b2

**Comment by AudriusButkevicius** [comment]
I don't think this does everything the monitor process does, so it's fairly racy by relying on pid files.

**Comment by calmh** [comment]
It looks like it launches syncthing *with* the monitor process, and as init scripts goes it's among the least horrible I've seen. It could potentially live in etc/ somewhere. Pull request?

**Comment by georgespatton** [comment]
Should we put this in etc/linux-sysv directory perhaps?

**Comment by mjk-gh** [comment]
Just wanted to let you guys know that the existence of above SysV init
script was very helpful for someone installing syncthing in Devuan
(SystemD-less Debian fork).

After ...

- saving above script as `/etc/init.d/syncthing`
- executing as root:
  - `chmod 755 /etc/init.d/syncthing`
  - `adduser syncthing`
  - `update-rc.d syncthing defaults`

... syncthing seems to work perfectly.

**Comment by phloggu** [comment]
Relay Server is missing the System V init script too. It would be nice if startup-scripts for different init systems would get packaged, as mentioned above, Devuan users e.g. rely on that.

The relay server is a bit more complicated than the syncthing client, because it might need an iptables port redirection. I've tried to script this; it runs for me. If it helps anyone, find [syncthing-relaysrv_sysv-init.tar.gz]( https://ente.limmat.ch/ftp/pub/software/bash/syncthing-relaysrv/syncthing-relaysrv_sysv-init.tar.gz) for download to use as a starting point.

The init script uses pipexec and is logrotate safe. Use /etc/default/syncthing-relaysrv for configuration.

**Comment by ecxod** [comment]
> * saving above script as `/etc/init.d/syncthing`
> 
> * executing as root:
>   
>   * `chmod 755 /etc/init.d/syncthing`
>   * `adduser syncthing`
>   * `update-rc.d syncthing defaults`

works perfectly
