### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by mneiger** [syncthing/syncthing#3002]
Lately on my Raspberry pi2 I noticed a few "panic files" in the syncthing configuration folder. 
Operation resumed transparently which is why I did not notice on the spot.

For the time being, I have no idea about triggering condition. It happened both with 0.12.21 and 0.12.22.

### Version Information

Syncthing Version: v0.12.21 and 0.12.22
OS Version: Linux gamliel 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

I include here 2 such panic logs

[panic-20160420-213748.txt](https://github.com/syncthing/syncthing/files/231640/panic-20160420-213748.txt)
[panic-20160422-112416.txt](https://github.com/syncthing/syncthing/files/231641/panic-20160422-112416.txt)

**Comment by AudriusButkevicius** [comment]
Thanks for this

**Comment by calmh** [comment]
I don't immediately see the cause here. It's clear that it's a map in an event that gets concurrently modified with printing the event... But in almost all cases the event data map is a literal we declare at the point of creating the event. There are a few exceptions but they all look sane. The more complex one is the ConfigSaved that attaches the actual config - but the config doesn't contain a lot of maps, and it looks correctly copied as well... Tricky.

**Comment by mneiger** [comment]
the panic happened again once today on Syncthing 0.13.2

I can't tell whether it related or not. Its' the same little pi. 
Linux gamliel 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

Thanks a lot

[panic-20160524-170631.txt](https://github.com/syncthing/syncthing/files/279943/panic-20160524-170631.txt)

**Comment by mneiger** [comment]
I had it 3 times again

[panic-20160525-110642.txt](https://github.com/syncthing/syncthing/files/282752/panic-20160525-110642.txt)
[panic-20160525-135831.txt](https://github.com/syncthing/syncthing/files/282751/panic-20160525-135831.txt)
[panic-20160525-154715.txt](https://github.com/syncthing/syncthing/files/282753/panic-20160525-154715.txt)

**Comment by AudriusButkevicius** [comment]
Thanks, found it.

**Comment by mneiger** [comment]
Great :-) congratulations.
