### ISSUE TITLE
Russian ranslation "This Device" and "Remote Devices"

### ISSUE THREAD

**Issue by anton-petrunin** [syncthing/syncthing#3013]
"This Device" and "Remote Devices" appear without translation in Russian

**Comment by anton-petrunin** [comment]
As well as "Add Remote Device"

**Comment by canton7** [comment]
Anyone can make changes to the translations - please use the [Syncthing Transifex project](https://www.transifex.com/projects/p/syncthing/).

**Comment by canton7** [comment]
... although Transifex claims that Russian is 100% complete. Odd.

**Comment by anton-petrunin** [comment]
Thank you, maybe it not yet in 0.12.22 yet.

**Comment by runical** [comment]
I have seen a similar thing with the Dutch translation and after close inspection it turns out that there are only 4 languages which have a translation:

- Chinese (China)
- German
- French
- Hungarian

I don't see why this is that case. In Dutch, the strings have been translated, but not reviewed. But a quick look at the French translation also marked the strings as not reviewed. Maybe the sting was not yet translated by the time this version was released?

**Comment by canton7** [comment]
>but not reviewed

Whether a string's been reviewed or not makes no difference.

> Maybe the sting was not yet translated by the time this version was released?

That's the most likely explanation

**Comment by calmh** [comment]
Yep. They'll be in the next release.

https://github.com/syncthing/syncthing/blob/master/gui/default/assets/lang/lang-ru.json#L214
