### ISSUE TITLE
File locations

### ISSUE THREAD

**Issue by claytondukes** [syncthing/syncthing#3053]
Is it possible to specify the location for .stignore, sync conflict files, etc.?
I would like to keep my directories clean so those files don't show up during a browse. How about a single file in the syncthing directory that specifies all of these instead?

**Comment by AudriusButkevicius** [comment]
No, it's not possible.

**Comment by claytondukes** [comment]
Short and sweet :)
Could you consider it for a future release at least? It sure would be good to have.
Also, thanks for making this, great work!

**Comment by AudriusButkevicius** [comment]
Best way to make things happen here is to make a pull request implementing the feature you are after.

**Comment by claytondukes** [comment]
Sorry, user here, not programmer :)

**Comment by wweich** [comment]
First of all: This files are hidden. If you tell your file manager to show hidden files, you want your folders not to be clean ;)

A new ignore system is in planning, which will not use the `.stignore` file anymore.

The `.stfolder` has to be where it is to make sure, that Synchting knows, that the folder is still mounted. If you remove an external drive, which you are syncing, Syncthing knows, that the complete folder is gone (because no `.stfolder`) instead of all files deleted (which would be replicated to the other nodes).

Conflicts are created where they happen, which (imho) is how it should be.

**Comment by AudriusButkevicius** [comment]
And there already exists a ticket about renaming .stfolder I believe.
