### ISSUE TITLE
Override changes shows very often

### ISSUE THREAD

**Issue by damintsew** [syncthing/syncthing#3078]
I have big folder 533 Gb on my Windows machine. And I want to have backup on my linux laptop with external hard drive.

So almosts every 5 minutes I receive message 'Override changes'. After pressing this button it dissapears bug then it shows again.

I attached two screenshots that shows you that synctcing asks me abut changes. Difference between screenshots is 1.5h
![screenshot_1](https://cloud.githubusercontent.com/assets/1108336/15160203/46bd7a54-1701-11e6-899d-4eb2eb0c9af9.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/1108336/15160204/46d633f0-1701-11e6-80d5-f53c304ace68.png)

### Version Information

Syncthing Version: v0.12.23, Windows (64 bit) 
Browser Version: Chrome the latest

Syncthing Version: v0.12.22, Linux (64 bit) Ubuntu 12.
Browser Version: Chrome the latest

**Comment by AudriusButkevicius** [comment]
Something on the other side is modifying the files (or metadata of the files, such as modification timestamps) 
If you are running on a networked storage (or some ancient filesystem) this also could be caused by the filesystems not having perfect mtime accuracy.

Regardless, if you click on "Out of Sync Items", pick one item, compare the content + modification timestamp, you will see that it's different, hence why it keeps popping up.

It's not really our bug, you need to find out why the modification is happening.
