### ISSUE TITLE
Upgrade to minor and major versions

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#3163]
For some users it may be helpful if Syncthing also offers to (auto)upgrade to minor versions:
e.g. user is at 0.12.23 and wants to stay at 0.12.x path. Currently Syncthing only shows upgrade to 0.13.x but not other releases like 0.12.25 (which is important security fix)

**Comment by calmh** [comment]
Hm. Yes. The upgrade system only selects one "best" version. This should be improved.

**Comment by calmh** [comment]
In fact, I think we should always prefer a smaller upgrade first when it is available. That is, if I'm `v0.12.23` and I see `{v0.12.24, v0.13.1}` then `v0.12.24` should be the "best" version.

**Comment by uok** [comment]
thanks, this should help in the future as e.g. right now [it seems](https://data.syncthing.net/) people who are still on 0.12.x are not updating to 0.12.25

**Comment by bminer** [comment]
First of all, I should say, please keep up the great work!

So this is just a thought... why not use [semver](http://semver.org/) for versioning and bump the major release number for each major update instead of the minor version number?  Node.js fell into this strange pattern of keeping everything 0.x.x for the longest time.  Then, they suddenly decided one day that it was "1.x worthy", and the version numbers quickly moved to 4.x, 5.x and beyond.  What's the point of the major release number if it always stays at 0?  When is a project "1.0 worthy"?  When it's bug-free?  Hint: nothing is ever bug-free.  :)

IMHO, Syncthing has been 1.x worthy for a while now...

Bump major version number for breaking changes (i.e. version 2.x won't work with 1.x)
Bump minor version number for significant, non-breaking, backwards-compatible changes
Bump revision version number for bug fixes or very minor changes

In this way, you can always safely auto-upgrade to the latest minor release, which is currently not the case with Syncthing (version 0.13 does not work with 0.12)

Thoughts?

**Comment by canton7** [comment]
The forum is probably a better place for this discussion.

(There was actually a big discussion on this last year, in the contributors section. Dunno whether it's worth making that public, or whether it would lead to endless bikeshedding).
