### ISSUE TITLE
GUI "Out of sync" modal uses massive amounts of CPU in browser

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3322]
I don't know what's going on here. Is it the animated progress bars? Polling and parsing updates? When showing this:

![screen shot 2016-06-17 at 08 53 05](https://cloud.githubusercontent.com/assets/125426/16142850/3f12c2f2-3469-11e6-9a50-3e89597f1e1b.png)

That browser tab uses almost a full CPU core (constantly):

<img width="815" alt="screen shot 2016-06-17 at 08 53 18" src="https://cloud.githubusercontent.com/assets/125426/16142856/4bb7db1e-3469-11e6-8817-b843c6f22177.png">

After closing the modal, usage is reasonable:

![screen shot 2016-06-17 at 08 53 35](https://cloud.githubusercontent.com/assets/125426/16142871/621515ac-3469-11e6-84ec-85e775a9b383.png)

<img width="815" alt="screen shot 2016-06-17 at 08 53 37" src="https://cloud.githubusercontent.com/assets/125426/16142876/6c763274-3469-11e6-8e37-2dfae7caf7b3.png">

v0.13.7, Safari/Mac latest

**Comment by norgeous** [comment]
confirmed in Firefox. I think its not platform specific.
had a look at this today and I think I have located it... the animation believe it or not...

procedure:
1. with only one tab (the gui) open I observe 4% on my machine (after the interface has had a while to settle), also at about 4% with a modal open
2. open web dev console (F12) and type `$('#needed').modal()`
3. empty modal in question is spawned and CPU shoots up to typically >40% on mine.
4. open the inspector tab and delete the html element with `class="progress-bar progress-bar-danger progress-bar-striped active"` (the animating one) - CPU drops back down to about 7%

i used https://addons.mozilla.org/en-GB/firefox/addon/cpu-usage-monitor/ to get CPU values in Firefox. Originally I thought this was probably due to some js loop running (or `$watch` maybe), but testing suggests animation - could this be true?

**Comment by wweich** [comment]
I can confirm, when removing the `active` css class (removing the animation) the CPU usage drops to "normal" levels.

**Comment by Ferroin** [comment]
I can confirm that the equivalent procedure to what @norgeous did in Firefox gives similar results in Chrome on Linux, although the usage values appear to be lower on my system.

**Comment by norgeous** [comment]
Yes @wweich you are more accurate. Taking this further, the `active` class has a css animation (`animation: progress-bar-stripes 2s linear infinite`) and this is the cause.

options:
- remove the `active` css class
- swapping the css animation for a `gif` styled to look similar

I just tried the latter (with a [random gif](http://heart.no-ip.com/Blog/Buena/data/icon/fly_09.gif)) and the performance gain was some but minimal.

**Comment by Ferroin** [comment]
Just a general thought, but is there actually any benefit to having this animated?  I mean, yes it looks nice, but it doesn't really add anything from a UX perspective other than eye-candy.  In something like a file copy dialog it makes sense to have the progress bar animated because it shows the suer things are still working.  Here though, the web UI will report if Syncthing is dead or hung because it won't be able to connect, so the argument for providing feedback that things are still working isn't anywhere near as strong.

**Comment by calmh** [comment]
We should clearly remove the animation, to start with.

**Comment by calmh** [comment]
Yes, the 1.15.1 milestone became 1.16.0, which is reflected if you look at the top left on this page but not in the history a few lines up. GitHub 🤷

**Comment by yashpalgoyal1304** [comment]
ohkayyy. yeah, got it. (just for records, for the history entry, the link is still pointing to right milestone - 63 in url)
