### ISSUE TITLE
Snap package feature request

### ISSUE THREAD

**Issue by ThrowAwayUser123** [syncthing/syncthing#3412]
I personally think that sync thing will benefit greatly if it was package with the new snap universal package manager by canonical, A universal package manager will allow me to install this software on all my linux distros easily, please consider it - thanks =)

**Comment by AudriusButkevicius** [comment]
Nice marketing Canonical. User created today.

**Comment by aviau** [comment]
Snap packages don't affect golang packages. The way syncthing is currently distributed, it already embeds all libraries, so there won't be a difference.

**Comment by ilmaisin** [comment]
@AudriusButkevicius I think you are being somewhat too paranoid about that marketing thing. The current package managers like apt, when used with third-party repos, are problematic since they provide no security or isolation at all, don't allow per-user installation, do not gurantee any cross-distro compatibility and the repositories can get into package conflicts with each other.

While third-party apt repos "work" if you happen to have low enough requirements, it does not mean there is no room for improvement at all or that all new developments were just some marketing gimmicks.

@aviau Syncthing seems to provide standalone binaries. It's a good thing and I appreciate that. But do the binaries really embed "all" libraries, including glibc? AFAIK statically linking glibc is a bad idea and can make compatibility worse, not better. On the other hand, some more exotic configurations can have a non-GNU userland and thus no glibc available. But if you provide snaps or flatpaks, you can assume there is some standardized runtime infrastructure available. Correct me if I am wrong, I am definitely not a very experienced developer.

**Comment by calmh** [comment]
We already package snaps. Don't revive old, dead issues.

`snap install --candidate syncthing`

**Comment by AudriusButkevicius** [comment]
The user was created on the day this issue was opened. The user has also opened issues with identical text on multiple other projects on the same day, confirming it's a user used for generating spam.

We use statically compiled binaries that do not depend on anything, especially anything from C land as far as I understand.
