### ISSUE TITLE
Force auto-updating to incompatible versions

### ISSUE THREAD

**Issue by StrikerTwo** [syncthing/syncthing#3430]
While I see the motivation behind blocking non-backward compatible updates from auto-updating, it causes me a lot of trouble. I have a lot of devices in my syncthing mesh (some of them not under my control, some of them not regularly online) and it's a pain in the ass to get them all manually updated to a new version.
Please provide an option to always auto-update to the newest version. If there already is something like that, I couldn't find it.

**Comment by calmh** [comment]
Fair nuff :)

**Comment by Revertron** [comment]
May be with some timeout, like 3 days after the release?
Because, for example, the Android version is not synced in releases with the Windows and Linux version. It may be updated after a couple of days. (It's normal, but we must remember that)

**Comment by Getron** [comment]
+1 It would be great to have this option. I have to many, too many devices, and to go with manual update on every machine, every client machine, it is a realy pain in the ass.

This with +- 3 days it is a good idea to.

**Comment by calmh** [comment]
I could see the auto update selected being a bit more granular, with a drop down like

```
Automatic upgrade: [All versions       ]
                   [Minor versions only]
                   [Disabled           ]
```

**Comment by lkwg82** [comment]
@Getron @Revertron We rather should address the issue with the delayed release than delaying updates on the syncthing release side. It is a human problem the android build is kind of flaky so we can not full rely on that before release. This should be solved. I started but ran out of time. If this is solved the releases could be made in time.

**Comment by calmh** [comment]
I think this is no longer a thing. Since a couple of years we're at 1.x and releases are always protocol compatible. If/when we do 2.x it will be for a *very* incompatible reason and lack of auto upgrade will be correct. (Back when this issue was created we released incompatible versions every couple of weeks probably.)

**Comment by jms19** [comment]
This is very much a thing.

I installed 1.12.0 (what you get from ports quarterly at the time of writing) on FreeBSD in the autumn, got mum to install it on her Macs and had some home directories synching.

Among the problems encountered on the way were the FreeBSD server (strictly receive only) running out of file handles when the limit was _only_ around 170,000 and the constant scanning and general thrashing. Dtrace shows it's almost constantly doing fstat, fstatat and getdirentries at several tens of thousands per second.

I also see constant re-writing of old files by the tens of thousands. I have absolutely nothing going on at the receiving end. I find .stversions accumulating a staggering amount of data.

She has recently upgraded one machine and also Syncthing to 1.140 and shortly after the flow stopped.

I know the version is the problem since I have _just_ installed 1.14.0 on my MacBook and it just won't connect to the FreeBSD machine. I mean it connects but won't push any data.

Macbook Pro (on 1.14.0) says
[Z42EP] 15:39:44 INFO: Failed to exchange Hello messages with x at [fe80::etc.]:22000/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256: write tcp [fe80::etc.]:22000->[fe80::etc.]:22000: write: broken pipe

The GUI says Syncing (0% 148GB)but just won't push anything. Nor does it tell me of incompatible versions.

Are 1.12.0 and 1.14.0 protocol incompatible and if so why am I not told ?

**Comment by AudriusButkevicius** [comment]
You are barking up the wrong tree, support happens on the forum.
