### ISSUE TITLE
Device name in conflicts?

### ISSUE THREAD

**Issue by Lillecarl** [syncthing/syncthing#3524]
When conflicts occur, we get a file & timestamp like this: Testfile.sync-conflict-20160818-134336.txt and the original Testfile.txt

What would be cool would be (at least as an option) to include the device name in the conflict file, so that you can easily determine which file is from "your node" so to speak.

This would be useful since we don't know who "initated" the file changes first (if there's a conflict).

This will also be useful for GUI tools that, so they can tell which is "your" file.

Best regards
Carl Hjerpe

**Comment by AudriusButkevicius** [comment]
I am pretty sure it's a duplicate, yet I can't find the original ticket.

**Comment by calmh** [comment]
There was a pull request. It's not super trivial. We could add the local device name to the conflict file when creating it though, which could be useful when it's synced to other devices.

**Comment by Lillecarl** [comment]
@calmh I haven't read any code yet in Syncthing, I'm thinking about a way for all syncthings to know which file is which (as in renaming both files to wherever they came from). But i don't yet know how things work, so i can't say too much.
But indeed, creating the file with the devicename could be v0.1, there can always be further improvements lateron :)

**Comment by AudriusButkevicius** [comment]
I actually think it''s impossible in some cases, as we don't track where the file originated from, and if you were offline for N hours, come back online, there are 10 other devices which have a conflicting copy which would be considered inferior to the one you have, which device are you conflicting with? All 10 of them?

**Comment by AudriusButkevicius** [comment]
Also we would never use device name, as these things vary between devices and can be user adjusted, so might make no sense on other machines. Lastly when we create a conflict it becomes just "another file" with a different name, so having different names on different sides makes no sense, as the conflict resolution logic is the same on all devices, therefore the outcome is also the same on all sides, hence the name should be the same.

**Comment by Lillecarl** [comment]
@AudriusButkevicius When a device detects a conflict, it creates another file. Which will be synced with everyone, then including some kind of name would help others know who it originated from.

Imaginary example:
User 1 has his computer offline, writes things to document & save, then comes online (without instantly noticing the conflict).
User 2 has his computer online, writes things to document & save.
User 3 has his computer online, sees that there's a conflict, sees that the conflict is with User1, which is a respectable member of this folder family, and therefore he manually merges them, then remove the conflict files.

I think it could be valuable, but might not fit syncthings goals :)

**Comment by AudriusButkevicius** [comment]
It's hard to understand if you are describing of how you think it works, or how youdl'd loke it to work.

Read the scenario I described. We do not track who created/last modified the file, so we only know that 10 other devices have a conflicting version. Also if we'd embed something as part of the name, ot would probably be first 5 characters of the device ID, which I am not convinced is immensly useful.

**Comment by Lillecarl** [comment]
It could be used by a guy such as synctrayzor to know where it's originated
from?

**Comment by canton7** [comment]
I'd suggest finding the original PR. There was an awful lot of discussion in there.

**Comment by canton7** [comment]
Yes, if the device(s) which created the conflict were named in the conflict file name, SyncTrayzor would display it. Doesn't make implementing it any more possible :P

**Comment by uok** [comment]
I found PR #2559 and #2577

**Comment by AudriusButkevicius** [comment]
Actually, I'm talking rubbish, we probably have what we need in the vector

**Comment by calmh** [comment]
Yes, but I wonder if the simplest approach á la Dropbox `Foo (abc123's conflicted copy).txt` would do, where `abc123` is the device where the conflict was detected/handled, i.e. the local device whenever the conflict is handled.

**Comment by AudriusButkevicius** [comment]
I am not sure I understand? You are saying that each would mark the others file as conflicted, essentially nodes having resolution logic that is dependant on the node it runs on?

**Comment by calmh** [comment]
Nah, I'm just saying that we could, instead of going with `foo.sync-conflict-$date.txt` go with `foo.sync-conflict-$date-$myShortID.txt` and that should be good enough for most cases. Or maybe my device name in some escaped format instead of short ID, but similar.

**Comment by AudriusButkevicius** [comment]
I bet people won't like it, because if someone is misbehaving, it's hard to identify who.

**Comment by calmh** [comment]
I guess the other option is the set of devices involved in causing it, which is "me" and one or more other devices. As you say we should be able to tell that from the version vector and I guess could then go with `foo.sync-conflict-$date-$myShortID-$otherShortID-$thirdShortID-...-.txt`...

**Comment by AudriusButkevicius** [comment]
We only have two conflicts at a time, and versions could not be the same for two ids so where does the third id come from?

**Comment by calmh** [comment]
I was thinking every device that have changed it since. Consider that we are `A` and there are two other devices `B` and `C`. We have

`{A: 10, B: 20, C: 30}`

and now we suddenly find out about and want to sync

`{A: 8, B: 50, C: 50}`

It's based on something older than our version, so it's a conflict, but it's been updated by both A and B

**Comment by AudriusButkevicius** [comment]
But I thought it's never B: 50, C: 50, as next different version is always max(across all devices)+1, so in the case of:

`{A: 10, B: 20, C: 30}`, when B syncs the file from C, B's version is still 20, yet when B modifies the file it becomes 31?

**Comment by calmh** [comment]
Sure. But you might have the three devices connected and in sync:

A: `{A: 8, B: 20, C: 30}`
B: `{A: 8, B: 20, C: 30}`
C: `{A: 8, B: 20, C: 30}`

Now A disconnects from the world. Two local changes happen.

A: `{A: 10, B: 20, C: 30}`

B makes a change, C makes a change, B makes a change and so on, and they are connected

B: `{A: 8, B: 21, C: 30}`
...
C: `{A: 8, B: 21, C: 31}`
...
B & C: `{A: 8, B: 50, C: 50}`

Now we connect to A again.

A: `{A: 10, B: 20, C: 30}`
B: `{A: 8, B: 50, C: 50}`
C: `{A: 8, B: 50, C: 50}`

A is in conflict against both B and C.

**Comment by AudriusButkevicius** [comment]
of B makes a change again, it would have thought it becomes 32. If both b and c are at 50, whoever receives the update and does the &, should resolve the conflict and send out B50, C51 or B51, C50, no?

**Comment by calmh** [comment]
No. Maybe my example is unclear. There is no conflict between B & C, that's just two devices updating a file repeatedly. I picked 50 because it was a nice round number, but the procession

`{A: 8, B: 20, C: 30}` -> `{A: 8, B: 21, C: 30}` (updated by B) -> `{A: 8, B: 21, C: 31}` (synced to C, updated by C)

and

`{A: 8, B: 20, C: 30}` -> `{A: 9, B: 20, C: 30}` (updated by A, in isolation)

is enough for it to be in a state where A is in conflict with the version that both B and C have, and from A:s point of view the cause of the conflict is edits made by *both* B and C. It can't know which of those edits were first, and it doesn't matter at the point it gets to do the conflict resolution.

**Comment by nrm21** [comment]
Sorry, I'm late to this... Those were my PR's from a while back.  Also my memory is a bit fuzzy on all this but here goes:

IIRC, I also originally wanted to put the shortID in the filename but was having a problem carrying it from one class to the other (think it was from model class to fileversion or versionvector or something like that)

What I DID end up doing however was putting in code that would (if -audit flag was enabled) cause each client to write down if an add/change/delete to a file was because of it's own local scan of the hard drive OR if it came from another device.  My thoughts then were that we could eventually take all these messages (that are currently written to the audit log of each client) and correlate them into a central synced db so we could know who made the original change of a file.  That part never got added but it should be easier to do with the base code in there.

The commits Im describing are these I think:
https://github.com/syncthing/syncthing/commit/5a7fad0bcdc3e3ae18e0ecdd3f4d9e92c6f38920
https://github.com/syncthing/syncthing/commit/86ca58e2a96c01d1d67435602443c35b050ee322

**Comment by nrm21** [comment]
> I actually think it''s impossible in some cases, as we don't track where the file originated from

That's correct from what I found in my pouring through this problem a few months ago.  But as I stated above I wrote some code to write in the local audit log whether an add/change/delete of a file was done on the local drive or from someone else on the network.  This logic could easily be used to determine who the ultimate modifier was.

But of course that assumes most/all clients are online and fast convergence, OR that many others don't modify this file while everyone else is offline.  Otherwise the complexity of "who made the change" becomes bigger fast.  :)

**Comment by Lillecarl** [comment]
I'm thinking that the device that generates the conflict file can just include the name when the file is created, easier to know which version is which then. We don't need everyone elses names to do this.

**Comment by nrm21** [comment]
Jakob/Audrius can correct me if my understanding is wrong here...

If I understand how it works, the problem with that approach is that the device that actually generates the conflict is all the receiving devices, not the sending one.  So if they attach their own name to the conflict file it will not only NOT correctly identify the computer that made the change, but will also make (say you have 8 nodes in a swarm) 7 different conflict files each with a different computer name in the filename.  Only the real one that changed won't make a conflict file.  Or maybe he will also... I don't remember.

Otherwise... yes... this would be a much easier problem to solve then.  :)

Someone smarter than me is welcome to give it a try in the code.  God knows I'm not the greatest programmer out there lol.

**Comment by hackel** [comment]
I'm confused about the accepted solution to this.  Today I got a conflict file (.git/index.sync-conflict-20180308-142906-FICRGNZ).  I have only modified (as far as I know) the git index on one machine (FICRGNZ).  So does this mean the conflict file *is* that newly modified file and I should overwrite the "old" index file (which has a later timestamp)?  Or does it just mean that FICRGNZ generated the most recent change, but we still have no idea which actual data came from FICRGNZ or not?  If I check my git status/logs, they are correct on *both* machines, suggesting the index file is in fact the later, correct one, and not he index-conflict file.

Obviously a git index is rather critical, and I don't want to inadvertently loose it, particularly if other files in the repo have changed causing them to become out of sync.

**Comment by AudriusButkevicius** [comment]
You should not sync git repos, git repo is not a single file but a collection of files. Different devices might modify different files at different times, causing them to "merge" different branches or states together from different files leading to corruption. The id is the device the conflicting modifcation came from (local version won), which happens to be synced back to conflicting device. Global change log in the UI is your best bet to understand the origin.

**Comment by calmh** [comment]
Use the forum for help and discussion, not the bug tracker. Oh, and don’t bidirectuonally sync git repos :grin:
