### ISSUE TITLE
Bug: removing several folders without restart

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#3567]
Remove two folders A and B.
Then restart.
Folder B appears not removed

ST v. 0.14.6

**Comment by scienmind** [comment]
I faced some variations of this issue many many times before, especially when modifying many folders at once.

In scenarios such as - setting all folders to master (to avoid mess when joining some old semi-out-of-date device back to the cluster, etc.), or adjusting versioning scheme for all repositories. Very often after the modifications, I'll let it settle for few seconds and then restart ST, and then after it's back up - some portion of folders' configs seem not to be affected by the modifications.

My guess would be that sometimes ST fails to write changes to the config file. Maybe there is a room for some validations of write success there...

(most of my struggles were pre-0.14.5, I haven't experimented with that since 0.14.5)

**Comment by calmh** [comment]
I can't reproduce this. Is there some trick to it in addition to the original description?

**Comment by scienmind** [comment]
Can't speak for OP, but in my case I've seen it on Win7 and Win10, chrome+standalone ST, SyncTrayzor. So I think it's browser/wrapper and windows version agnostic.

Once, I've failed to do any modifications at all, with many retries. Disabling the antivirus (Avast) fixed that then, even though all AV logs were clear of any ST mentions (I also manually whitelisted ST there)
Once I also had some very hard time unlinking a device, it succeeded to do so on about (no JK) 20th attempt (can't recall what exactly i tried to do).

But normally its not a complete modification block:
If I would like to update smthn for 25 folders - I'd do it one by one via GUI (which is a PITA on its own...), waiting for sometime between each folder to let it settle. After all is modified, I'd verify that all changes are as should be, and restart ST. Then - something like 3-5 folders would be reverted back.

And as i said before, my impression is that ST fails to write it on disk (or unaware of a failure). AVs tend to make it worse. I haven't experienced something similar on other SW, so idk, maybe ST lack some tighter file write validations...

**Comment by calmh** [comment]
This all sounds very odd, as any error on saving is propagated back to the UI as a response to that POST, and should trigger a "woops syncthing is down" or similar error (even though that's not really correct). I can enable some more logging in those paths, and then perhaps you guys can run with some trace options and try to provoke this again as I have no idea what could fail here.

**Comment by calmh** [comment]
Please try to reproduce this using https://build.syncthing.net/job/syncthing-windows/243/ and watch the console for warnings in the meantime.

**Comment by scienmind** [comment]
Thanks!
Unfortunately, I'll be able to test it only the next week, and will update my findings here.

**Comment by calmh** [comment]
Not enough info / not reproducible
