### ISSUE TITLE
Synthing 0.14.6 debian package is broken

### ISSUE THREAD

**Issue by skibbipl** [syncthing/syncthing#3573]
Hello,
What happened: I've upgraded my debian syncthing version from 0.14.3 (debian package) to 0.14.6 (syncthing deb package)

What you expected to happen instead: expected to see upgraded synthing console, instead I've got "Host check error" message. Also deleting synthing data didn't help - with fresh config it's the same.

Steps to reproduce the problem: install 0.14.6 debian package from syncthing repository.

Downgrading syncthing to 0.14.5 fixed the issue.

Syncthing Version: v0.14.6
OS Version: Debian Testing
Browser Version: N/A

**Comment by kozec** [comment]
Just quick check, are you using Syncthing-GTK or another wrapper?

**Comment by skibbipl** [comment]
Nope, just syncthing

**Comment by hadret** [comment]
I can confirm the bug and it's happening not only on Linux/Debian, it also affects SmartOS/Solaris and possibly any other OS. For me downgrading to 0.14.5 also did the trick. I'm not sure whether it's the case for you, but I'm using web interface through nginx reverse-proxy -- there's no problem with the nginx configuration whatsoever (it did work just fine for plethora of previous Syncthing versions) and when tunneling the port via ssh to access the application directly it also works fine. So at least in my case it's quite obvious that the issue lies in connection between nginx & syncthing. My wild guess is that it might be related to the CORS change recently introduced: https://github.com/syncthing/syncthing/pull/3541

**Comment by AudriusButkevicius** [comment]
The reverse proxy needs to supply a host header.

**Comment by calmh** [comment]
Yes. When running on 127.0.0.1, it expects to receive requests on 127.0.0.1. To use being a reverse proxy now, set `insecureSkipHostcheck` in advanced config.

**Comment by skibbipl** [comment]
Thanks for clarification. This nginx change made it:
```
#old  proxy_set_header Host $http_host;
#new  proxy_set_header Host 127.0.0.1;
```
