### ISSUE TITLE
Route through TOR in-app for Windows

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3582]
FEATURE REQUEST:

I know Syncthing has the ability to be routed through TOR (see issue 2748), but Syncthing for Android and ARM has TOR routing built-into the app natively without the need for an extra app, proxy, or VPN under the Settings < Experimental options.

I really would like this exact same native option built into the Windows app and GUI too. It is much easier for common folk like myself yet still offers advanced users the advanced configuration functionality.

**Comment by AudriusButkevicius** [comment]
It doesn't have it built in, it uses the app that already has to be installed on the phone, same goes for windows.

**Comment by jebeld17** [comment]
My bad.
Which app would that be for both OSes?

**Comment by AudriusButkevicius** [comment]
I don't know, I don't use TOR, and I have no clue how people interact with it.

**Comment by scienmind** [comment]
On Android it uses Orbot, which acts kinda as VPN.
 
For windows, I'm not familiar with any SW that'll route syncthing "easily" over Tor. AFAIK, on "Easy to use" side, I  there's only the Tor Browser Bundle, but thats just a browser. 
In order to route external apps through tor, you should look into it on Tor's site

**Comment by Ferroin** [comment]
The easiest method on stuff like Windows is to set Tor up normally and then use it like a proxy.
