### ISSUE TITLE
Report free space on file system of the shared folder after scan

### ISSUE THREAD

**Issue by joseluisll** [syncthing/syncthing#3620]
I think that it would be very useful to add a field to the shared folder section, so that the user can see the amount of free space on the file system where the shared folder is located.

The free space can be computed as the latest action of the scanning, or each certain amount of time.

**Comment by calmh** [comment]
We do a free space check at some point anyway so this is doable.

**Comment by AudriusButkevicius** [comment]
Why? Should we also what's the current weather in your location?

**Comment by joseluisll** [comment]
No, I don´t see the point on weather local weather check, nor is it related to syncthing or the issue.

However, syncthing does consume disk, and I think it would be useful to report the disk usage and free space through the GUI.

**Comment by AudriusButkevicius** [comment]
Syncthing does not consume space, your files consume spaces, and your operating system already provides you ways to check how much space they take.

The argument of nice to see is relative, to me it's just cluttering the UI with information which is already easily accessible elsewhere.

**Comment by calmh** [comment]
We show the emoting of data *in* the folder, I don't see how this is conceptually different.

**Comment by AudriusButkevicius** [comment]
What about folders with bindmounts, etc, etc.

**Comment by Ferroin** [comment]
I would tend to agree with @AudriusButkevicius, there are correct ways to get this info, it's not exactly  in scope in Syncthing, and it really is pretty trivial on most platforms (IOW, everything but Android, it's possible on Android, it's just a pain because of going through multiple menus) to get the info through those correct means.

Now, if there was a way to see on a given node that a _remote_ node was not accepting changes because it has no free space, I could see that as being useful.

Also, I don't really see the concept as being the same as the amount of data in a folder unless it's on a dedicated FS, or you've got per-folder usage limits that get reported instead (but I only know of one FS that can do that (BTRFS), and it doesn't even work reliably there).  In those two cases, the two are different ways of reporting the same thing, in the regular case of having a folder on a filesystem that is used for other things, showing disk usage of a given folder is showing part of a larger picture.  Having 100GB of free space in that case doesn't mean that we actually can (or even should) accept 100GB of data, it just means that as of that instant, there was 100GB of space on that FS not being used (because you can't at all assume that other things aren't causing that to fluctuate).

**Comment by joseluisll** [comment]
That is the point @Ferroin, If I have a system where several devices are syncing several folders, and I would never do any SSH to any device, I don´t care. They just push stuff, syncthing replicates the information. Yes, it is possible to enter into the SO, but hey, it would be nice not to do it just for checking free space. Maybe to troubleshoot, to replace failing hard disk. 

@AudriusButkevicius totally agree with you, syncthing does not consume disk, my data beign replicated does consume the space. Currently I know what space is beign consumed, but I don´t know the amount of disk that is avaible or free, maybe to estimate when it will be full.

**Comment by calmh** [comment]
I don't think this is an essential feature, but given that we have lots of code and logic internally dedicated to tracking exactly this metric and acting on it in various ways, and we have config thresholds related to it visible in the GUI, I think it's hard to argue that it's clearly useless. Hence, `enhancement/unplanned`.

**Comment by spectras** [comment]
I would second @AudriusButkevicius with the out of scope issue. And add that if one sets out to provide the amount of free space, for it to be useful it should also verify how much of that free space is actually available (most *nix filesystems reserve some space to only be usable by root) and check user's quotas. 
Free space is hardly useful if you are not allowed to write into it.

**Comment by AudriusButkevicius** [comment]
I think we're not going to do this, as we've removed CPU, memory usage under the notion that syncthing is not a monitoring app, hence we should not provide monitoring features.
