### ISSUE TITLE
Usage reporting update

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3628]
I'd like to make some additions to the anonymous usage data. Since this will require re-asking for permission, and thus likely losing a significant base of our current reporters, we should make it count. I want the following data:
### Ignore patterns
- [ ] Number of patterns (i.e., lines in the ignore file plus all included files).
- [x] Whether `#include` is used or not

We report one data point, the max of any folder, and the "or" of the "uses includes" flags.
### Connection statistics
- [x] Direct vs relay connections. I want to gauge how much devices are connected over the various connection types we have. For this purpose I think the metric we want is something like connection-minutes, not connection events or bytes transferred. 
- [ ] Max number of established connections. I.e., how many devices are we connected to at most, reset per connection report.
### General data
- [ ] Uptime. (Syncthing's, not the system's.)
- [ ] Has used external scanner, i.e. inotify? Just a boolean that gets set when the REST method is called. 
- [ ] CPU utilization, as some sort of max, average or percentage...
### GUI settings
- [x] localhost only listening or wider?
- [x] Password set or not?
- [x] All the various booleans (TLS, skip host check, ...)
- [x] Selected theme
### Puller stats
- Separate ticket on what we should track here because it will require some implementation on its own. But generally speaking data on pulled vs reused blocks and stuff like that. 

#3806

**Comment by uok** [comment]
That's a lot of (additonal) statistics... Do you plan to remove features/functions if they do not show up as used?

**Comment by uok** [comment]
That's a lot of (additonal) statistics... Is there any part of the software left that is not tracked? 
Do you plan to remove features/functions if they do not show up as used?

**Comment by AudriusButkevicius** [comment]
memory usage

**Comment by Ferroin** [comment]
Memory usage is already reported.

**Comment by AudriusButkevicius** [comment]
Yes, I am a muppet.

**Comment by calmh** [comment]
@uok is there something in these metrics that you see as a concern in collecting?

**Comment by nrm21** [comment]
Direct vs relay connections:
Might want to check first if at least one one the clients in a connection has manually disabled relay.  No point in skewing the stats with a lot of obvious "100% direct" entries of those.

Or maybe you do... if those are the kinda stats you're looking for... but I'm guessing not.

**Comment by Ferroin** [comment]
For CPU usage:
Both max and average would be useful, but for them to really mean anything, we need to associate at least with the CPU architecture.  In theory, even with that association, they're still not hugely helpful, but I'm hesitant to suggest we start collecting info on stuff like CPU frequency and memory speed...

**Comment by calmh** [comment]
> Direct vs relay connections

I'm really only interested in to what extent clients are stuck using relay connections. If they are configured to not use relays and hence get only direct connections or nothing that's perfectly fine by me.

> CPU usage

A pure percentage tells us how well Syncthing is performing compared to the device it's running on, and so approximately how much impact it has on any other operations the device may be performing. Lower is better for all devices. We could correlate with the hashing speed (even if that is not a complete metric of the CPU speed of course) to give rough guidance of the kind "should be this tall to ride".

**Comment by Ferroin** [comment]
@calmh Ah, that makes sense.  It's worth pointing out though that 1% utilization on a single core system is going to have a lot more impact than 1% on a 16 core system.  It may make sense to correlate with hashing speed, platform, core count, and memory usage to provide a more complete estimate of what's needed on each platform, since requirements on android-arm are obviously not going to be the same as on windows-amd64 (for example).

It may also be useful to differentiate between CPU utilization while scanning, while syncing, and while idle, as that will give a better idea what's actually using the processor time.  At a minimum though, I still think that reporting both max and average is useful (on my laptop for example, I get an average of less than 1%, but sometimes see spikes of up to 20% when syncing, scanning, and viewing the GUI all at the same time).

**Comment by MikeLund** [comment]
@uok if you don't like statistics being reported, just leave them disabled -- they're off by default.

Statistics are very useful, both for "fun", but also for giving insight into any contributors on a lot of information about how the program is used.
How else can the project continue to grow and improve if the only metrics received is from people who get annoyed enough to bother to make a issue report?

**Comment by Aranjedeath** [comment]
localhost-only listening check may not capture all that you want, especially in cases like mine where it listens on localhost but is forwarded elsewhere via web serving daemon. (I pipe it to the world through nginx so that I can use my tls certificate to secure the connection).

**Comment by rumpelsepp** [comment]
@uok It is opt *in*

**Comment by AudriusButkevicius** [comment]
Max download speed
Max upload speed
Temp index hit rate

**Comment by bugith** [comment]
GUI language ?
Maybe an extension to the current Yes/Nothing answer to whether we accept to send stats would be Yes(+expand details)/Nothing (expand option grayed), the expanded list would show each item with an "send" checkbox beside, plus a global "Send all".  The problem might be more people to refuse sending stats instead of spending some time to wander yes/no for each item, eventually falling in trouble/confusion and ending checking "Send Nothing". On the other hand, wouldn't this way to do show ST team more care (if ever needed) with users privacy, so in turn bring to ST more confidence (if ever needed) from the users. After all the code is open source. But how many of us read it? A stat would be nice on this matter : "Do/did you read the source?" ;-) On the third hand, maybe partial stats would skew all them (alleviated by a "Not transmitted" value for unselected data?)

**Comment by scienmind** [comment]
I like the idea of allowing "partial" statistics collection. I'd actually expect more users contribute stats (at least partially) this way. Some that opt out now may not mind sharing a smaller subset of data points.

And to minimize confusion, instead of throwing 10^n check-boxes at new users, we can show a "blanket" prompt as we do now with a button/link/whatever to "customize data choices" or something like that.

**Comment by bugith** [comment]
Yes, simpler with only one check box per category of data is that makes sense, e.g: one for number of files (regular, dirs, repos), one for network (speed U/D, upnp etc), one for clusters (numbers, devices per..)

**Comment by calmh** [comment]
The stats are only useful as long as they are comparable. I will not implement an advance partial usage reporting selector thingy, and I'm not aware of any other program that has this either. We're being more transparent than many already here.

**Comment by AudriusButkevicius** [comment]
Is this still relevant? I think we now have most of these.
