### ISSUE TITLE
[feature request] --daemonize | -d

### ISSUE THREAD

**Issue by meoso** [syncthing/syncthing#3675]
Please consider a `--daemonize` or `-d` parameter.

I run syncthing on ARMv5 Synology/BusyBox and the `command&` (ampersand) does not properly background the task, (logout kills the task).  I've crontabbed it as a solution, but would like the -d for interactive shell sessions.

**Comment by AudriusButkevicius** [comment]
Because you are doing it wrong. 

You need to `command & disown`

**Comment by calmh** [comment]
Or, better, one of the service managers like runit, upstart, systemd and so on.

**Comment by meoso** [comment]
i use your provided systemd service file on debian which is flawless, but the Synology Diskstation (NAS) is quite a bastardized OS -- none of those apply.  i'm using [my own script](https://gist.github.com/meoso/5fcbe1787dd50c2b39c21b1ef3cf58e8) to solve it as a cronjob. 

Also the `command & disown` does seem to work; When i have time i intend to test `nohup`.

**Comment by tsaridas** [comment]
I would like to raise my concerns about this and maybe reopen the issue as a feature request.

Most applications that are meant to run as a daemon have this option and its fairly easy to implement.

I do understand that demonizing works differently in other OSs but it should be fairly standard for windows/linux/macosx if you fork/create new process in the beginning and should not  interfere with the rest of the process start up.

Disowning does not help much since the script that will start the app will have to hang waiting for stdout/in/err.

**Comment by AudriusButkevicius** [comment]
That's why you can redirect them if you care about them.

**Comment by tsaridas** [comment]
Exactly why I am asking for the feature. This is something that the application should care and not the user.

Syncthing to my knowledge is used as a long running process and it would make sense to demonize itself and also take care of the stds.

I dont really understand why you are not positive about this.

The only thing that I can think of is compatibility between syncthing clients.

**Comment by AudriusButkevicius** [comment]
I am not positive about this is because it's a solved problem by using the features your shell provides. I see exactly zero benefit duplicating the features of your shell.

Why would the application care where it's output goes? It's meant for the user to consume so the user is the one deciding what he wants to do with it.

**Comment by Ferroin** [comment]
@tsaridas Compare for reference how BOINC handles logging.  It's pretty similar in the intended environment (daemon that runs as an individual user, not a system user), and has pretty similar stances on logging.

**Comment by tsaridas** [comment]
Guys, its common practice to demonize the process if its a long running one and doesn't expect user input. Has nothing todo with the user permissions running the app.

Taking the example if nginx you can imagine that it provides both options and ppl usually run it without the demon mode for debugging purposes.

Disowning the user shell is a hack imho.

Nevertheless Im not asking you to fork the process by default but only provide the option to do so.

I think its a valid feature request.

**Comment by calmh** [comment]
No. Daemonizing is outdated and wrong. The correct solution is for a service manager to start the long running process, monitor it by waiting for it to exit, and respawn it when it does.

**Comment by AudriusButkevicius** [comment]
If you want to follow up on this, for starters I suggest you follow up with a pull request, oppose to trying to convince that the things we are proposing are hacks and that we should follow the bandwagon of (in my opinion) poor decisions made by others.

Especially because you haven't answered how is this is better to what we are encouraging users to do in the first place.

**Comment by Ferroin** [comment]
Also, if you decide to go the way of a pull request, make sure you understand how to daemonize something properly, just calling fork() and redirecting output absolutely doesn't cut it.

**Comment by calmh** [comment]
I strongly recommend not going down that route. As mentioned it's not trivial, and I'm not likely to appreciate the extra complexity of doing this right for essentially no gain.

**Comment by tsaridas** [comment]
Im not going to create a pr if you have no intention of merging it and it does look that way.

You are also suggesting that I install systemd or something similar to all my OSs which still use system v. Also that you do not support system v in any way.

I am a supporter of the application handling stderr correctly in case of misconfiguration or a blocking resource instead of having a process manager doing it in a dummy way.

I do understand that newer systems have a process manager though and it would be extra work to support old ones.

To my understanding golang has libraries that perform the forking so there is no need to complicate things for the programmer.

Anyway, I do appreciate the time you provided for this and thank you for it.

Regards,

**Comment by Ferroin** [comment]
You don't need systemd, go look at DJB's daemontools or all the various derivatives of it, or if you're on a Debian or Gentoo derived system (or possibly some others, I don't have enough background with most other distros to know if they have it or not), check `man start-stop-daemon`.  There is no requirement that you use systemd, or launchd, or any other arbitrary service manager.  You're acting like Syncthing depends on systemd on Linux when you obviously have not done your homework to see what tools exist for doing _exactly what you want_ without you having to write more than a half dozen lines of shell script.
