### ISSUE TITLE
Is there any plans to add character escaping in ignore patterns in windows?

### ISSUE THREAD

**Issue by ruifortes** [syncthing/syncthing#3725]
This would be great.

**Comment by calmh** [comment]
This would be relevant only for [ and ] right? What would we a good escape character?

**Comment by calmh** [comment]
To be most windows compatible it seems we should simply disable []-patterns:

https://technet.microsoft.com/en-us/library/bb490639.aspx

**Comment by ruifortes** [comment]
Unfortunately I started using an exclamation point to mark files (or folders) that I don't need to synchronize because it is less likely to be found.
In .gitignore I just use `\!*`

**Comment by calmh** [comment]
Hmm. .gitignore seems to not process paths with backslashes in them, requiring Windows users to always use forward slash and thus leaving backslash as an escape character. I'm not sure we can do the same.

**Comment by ruifortes** [comment]
why not?

**Comment by Ferroin** [comment]
Backwards compatibility would be my guess.

IOW, it was done wrong in the first place, and thus can't be changed because it will potentially break things for existing users.

**Comment by calmh** [comment]
You could say that. I'd argue that letting the user use the native form of directory separator is the right way to do thing, as the opposite is confusing. Git gets away with doing it differently because fuck Windows, right? :) (Not my opinion, but the way Git was developed for quite a few years...)

That said, the current way we do it certainly leaves something to be desired.

**Comment by Ferroin** [comment]
Just to clarify, I'm not saying it was done wrong because of the use \ on Windows as a path separator (that was Microsoft's mistake, not Syncthing's) in ignore patterns, but because there's no escape character at all on Windows.  Because of that, repurposing _any_ character as an escape character for Windows runs the risk of breaking existing users.

**Comment by ruifortes** [comment]
I vote shiming microsoft :-)

**Comment by calmh** [comment]
What is he desired functionality here? Spec it out, someone, please.

**Comment by ruifortes** [comment]
This minimatch [PR](https://github.com/isaacs/minimatch/pull/103)  added the options 'allowWindowsEscape'

**Comment by calmh** [comment]
So...

- Asterisk and question mark are not allowed in file names in Windows so are a non issue
- Exclamation point is only relevant when it's the first character, so if you want to unignore the file `!Syncme` you can match it by `/!Syncme` or `**/!Syncme` depending on what depth it's at
- Square brackets are trickier but can in a pinch be matched by `?` instead

So I think there exists workarounds as is? Enabling backslash-escaping by requiring the use of forward slash seems like just a workaround as well to me, as backslash *is* the directory separator on Windows. We could invent something different and special like using `|` as an escape character, but really... :/

**Comment by ruifortes** [comment]
I don't understand. Can I already use `**/!Skipme` on windows?

**Comment by calmh** [comment]
Sure.

**Comment by ruifortes** [comment]
should `**/!/!*` ignore all files (and folders) starting with `!!`
It doesn't seem to be working

**Comment by imsodin** [comment]
That would be `**/!!`, your example matches all files/folders starting with "!" in a directory named "!".

**Comment by ruifortes** [comment]
Ahh!! That's more like it :-)
Thanks

**Comment by calmh** [comment]
It looks to me like we're good here.
