### ISSUE TITLE
Symlinks are deleted on 0.14.14 upgrade

### ISSUE THREAD

**Issue by ghalfacree** [syncthing/syncthing#3802]
Updated Syncthing on both my desktop and server - both Ubuntu 14.04 64-bit - this morning, and it appears that it doesn't like the new symlink patch. Things appear to be syncing, but the log is absolutely stuffed with:

```
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Puller (folder "Music", dir "music"): incompatible symlink entry; rescan with newer Syncthing on source
[PW634] 16:06:23 INFO: Folder "Music" isn't making progress. Pausing puller for 1m0s.
```

After the minute pause, another batch of errors appears. Oddly, the directory in question - which is itself a symlink to another directory called "My Music" in the same parent directory, for historical reasons - appears to be syncing OK in both directions.

The error indicates that it's running into the "symlinks can't be synced between 0.14.14 and older versions" problem, *except* that both devices are running 0.14.14 just fine. The errors only appear on the desktop client; the server shows nothing strange in the logs.

### Version Information
Syncthing Version: v0.14.14
OS Version: Ubuntu 14.04 64-Bit

**Comment by canton7** [comment]
Have you tried rescanning on the source side (i.e. not the device whose logs you posted, but the device it was trying to fetch the symlink from)?

**Comment by ghalfacree** [comment]
@canton7: Yes. The rescan completes suspiciously quickly (within ten seconds), and it makes absolutely no difference: the desktop (the device on which the errors are appearing) still reports the same "incompatible symlink entry" error.

**Comment by davidak** [comment]
I have the same error.

```
[*****] 22:07:34 INFO: Puller (folder "Sync", dir "TMP/krautleaks reste/fäden/kc-b-2479161/*****.net/thumbnails/1293714318003.png"): incompatible symlink entry; rescan with newer Syncthing on source
imac:~ davidak$ file Sync/TMP/krautleaks\ reste/fäden/kc-b-2479161/*****.net/thumbnails/1293714228003.jpg
Sync/TMP/krautleaks reste/fäden/kc-b-2479161/*****.net/thumbnails/1293714228003.jpg: JPEG image data, JFIF standard 1.01
```

The files are actually files and no symlinks.

**Comment by kaey** [comment]
Same error here. Syncing between linux and freebsd.
Rescanning and restarting on both sides doesn't help.

**Comment by calmh** [comment]
This'll happen when there is a symlink that wasn't synced before the upgrade. A symlink doesn't have a modification time on it's own, so forcing a rescan of it is somewhat tricky. My best suggestion is to remove it, let Syncthing realize it's gone, then recreate it.

**Comment by ghalfacree** [comment]
@calmh: Found the symlink in question - for some reason I had a symlink called ``music`` which led to ``/home/user/music`` but only on the server, not the desktop - and deleted it. Rescanned on the server, restarted the daemon on the desktop, and boom: no more errors.

I didn't bother recreating the symlink, because it served no purpose and shouldn't have even been there.

Happy to mark this as resolved and close from my perspective, but perhaps it's best to keep it open to see if @davidak, @kaey, and @bradbulger can resolve their issues with the same fix.

Oh, and here's a handy-dandy way of finding all the symlinks recursively from the current directory: ``ls -lR ./ | grep ^l``.

**Comment by javmorin** [comment]
I ran into this as well, but with existing symlinks (not just new ones as @calmh described). I upgraded one machine (the always-on server) to 0.14.14 and booted up my desktop machine to upgrade it. I have syncthing set to launch on login and started getting notices of files deleted. Thinking this odd as I hadn't deleted anything since the machines were connected last, I stopped syncthing and upgraded to 0.14.14. Now I was seeing reports (like above) of invalid symlinks (even though they were present on the server side).

Cut to 12+ hours later, and I am in front of my laptop that is part of the sync group, disabling syncthing before allowing it to connect to the internet. I have 83 symlinks in the synced directory. Checking on the desktop, I have zero. Syncthing had removed all the symlinks on the desktop.

As a recovery measure,  I tarballed up all the symlinks on the laptop before letting it sync, then manually removed the symlinks on the server (where they were still present) and restored the tarball and now the 3 machines all show as "Up to date" and have their 83 symlinks.

Some things I have noted about the symlinks:
- some were dangling symlinks to either files or directories
- some were to valid files or directories
- age of the symlink seems to have nothing to do with which ones were listed as failed
- only some of the list (53 iirc) were shown as "Failed" in the syncthing UI despite none of them being synchronized.
- all had been synchronized prior to the upgrade, none were "new" to be synced

I still have one further machine (another laptop) which needs to be updated to 0.14.14, and I am wondering if it will cause me trouble. Will actually hold off on booting and updating it now in case I can test something for @calmh, but a bit concerned that a "fix" introduced a (if not for the gtk gui) quiet data-loss in my environment. Fortunately I had a way to recover, but seems like the upgrade needed more safety code added to either cause syncthing to stop on boot, or fail to sync rather than wiping out data.

**Comment by bradbulger** [comment]
I removed the offending links on the master and left it for the rest of that day. It cleared on all syncing systems. I've been adding them back on the master now, and so far it seems to be syncing them successfully.

**Comment by pwlaz** [comment]
I confirm the problem described by @javamorin In my situation there was three machines, one with 0.14.13 and two upgraded to 0.14.14. 
All of the symlinks were suddenly deleted. I had about 8 hundred of symlinks (I like symlinks). Thank God I had another computer offline and managed to restore the symlinks (and before that I went back to 0.14.13 on all of the machines). I think that using 0.14.14 is _very dangerous_ for symlinks fans. I will wait for 0.14.15.

All of my systems are 32bit linux.

**Comment by calmh** [comment]
What's the OS type on these symlinks-deleted boxes?

**Comment by pwlaz** [comment]
Mine OS type is linux, 32 bit.

**Comment by AudriusButkevicius** [comment]
on both sides?

**Comment by pwlaz** [comment]
On all sides.

**Comment by hubertbanas** [comment]
Real pain ... 
- source - docker ubuntu 16.04
- comp1 - linux mint
- comp2 - linux mint

updated source from 0.14.13 to 0.14.14 
updated comp1 from 0.14.13 to 0.14.14; noticed exclamation point between source and comp1 due to symlinks
fixed all symlinks by deleting on source and comp1
created new symlinks on comp1
source and comp1 in sync

brought up comp2 running 0.14.13 (was offline during source and comp1 upgrade)
updated comp2 to 0.14.14
noticed most symlinks got deleted; one symlink left but marked in conflict
deleted conflicting symlink on comp1, comp2 and source
recreated all symlinks again; this was done on comp1

all in sync between the source; comp1 and comp2
back in business

**Comment by javmorin** [comment]
@calmh Linux / 64bit (Arch Linux to be specific) on all machines.

**Comment by kozec** [comment]
Having 0.14.13 on one and 0.14.14 on another machine, all symlinks from 0.14.**13** are gone and lots of same errors are logged:

```
[FRZMY] 18:21:09 INFO: Skipping folder svn scan due to folder error: folder path missing
[FRZMY] 18:21:27 INFO: Puller: final: symlink  /data/Sync/titulky/worker.php: no such file or directory
[FRZMY] 18:21:27 INFO: Puller: final: symlink  /data/Sync/titulky/worker.php: no such file or directory
(repeated 9 more times)
[FRZMY] 18:21:27 INFO: Folder "titulky" isn't making progress. Pausing puller for 1m0s.
[FRZMY] 18:22:27 INFO: Puller: final: symlink  /data/Sync/titulky/worker.php: no such file or directory
[FRZMY] 18:22:27 INFO: Puller: final: symlink  /data/Sync/titulky/worker.php: no such file or directory
(repeated 9 more times)
[FRZMY] 18:22:27 INFO: Folder "titulky" isn't making progress. Pausing puller for 1m0s.
```

But machine with **.14** kept all symlinks.

**Comment by calmh** [comment]
Good news is I think I understand what's happening, bad news is that the bug is on the .13 side and may be difficult to fix without gutting the changes we did in .14. Essentially,

- Things are in sync, one side is upgraded to .14 and one remains on .13
- .14 rescans and notes the symlinks have changed, since it does not have their target info in the field it expects.
- .14 sends out new symlink entries with the added date, and lacking the old block hashes
- .13 attempts to sync the new symlinks, but can find no data on what they're supposed to point to. For new symlinks this is not an issue, it simply fails to sync them. But due to how the old "temp file converts to symlink" system worked, if the symlink is already there it removes it in anticipation of the new one, but then fails to create it again.
- .13 rescans and notices the symlinks are missing, flags them as deleted
- .14 deletes them

This ought to be a conflict on the .14 side, but apparently it isn't...

**Comment by calmh** [comment]
I can envision a workaround though

**Comment by calmh** [comment]
I pushed a workaround in 0.14.15. Doesn't fix it for those already affected, but for those who have symlinks and haven't upgraded yet this should protect them over the transition.

**Comment by cowai** [comment]
Is there any way I can restore the old symlinks? I only read this now and my backups are simply too old now to restore everything.

**Comment by dajiahao** [comment]
I deleted the symlinks on both devices but how to get rid of the out of sync and failed sync items?
rescan didn't help ...

**Comment by donnex** [comment]
I'm also having the same issue. I removed the symlinks on all my machines but my main node is still saying "out of sync" for a lot of the removed files/symlinks. Can't seem to fix it. FreeBSD + OSX here.

**Comment by calmh** [comment]
@cowai; If versioning was enabled, though ought to have been versioned.

@dajiahao, @donnex; Have you upgraded both sides? And have no symlinks? And one side still things the symlinks are out of sync? Is one of them "master"?

**Comment by donnex** [comment]
@calmh Yeah, I'm running 0.14.16 on my three nodes. One is the central node that shares a folder with my two other nodes. I manually removed the symlinks on all three machines but my centreal node (not setup as a master) is still complaining "Out of Sync Items	31667 items, ~0 B". It also has the state "Out of Sync".

**Comment by dajiahao** [comment]
I tried this: make the host out of sync and with the many errors to the master, then use the override button on this host and the out of sync items vanish
only problem stays that even after some hours the second device in the "remote device" section writes "sync 95%" at 0 B/s

both sides have no symlink, tried set them to master etc (both have last syncthing version)

**Comment by calmh** [comment]
I think this is an unrelated issue to the one of symlinks being deleted though, whatever it is.

**Comment by calmh** [comment]
When 0.14.17 is released to tomorrow, run it once with `-reset-deltas` to clear this out, hopefully.

**Comment by dajiahao** [comment]
yes, solved it 
tnx

**Comment by donnex** [comment]
I tried to start my node with `-reset-deltas` but I'm still seeing the same errors.

Out of sync items: `31667 items, ~0 B`
Failed Items	`31667 items`

All of them with the same error I think, `parent is not a directory`.

**Comment by calmh** [comment]
Probably #3838 but definitely not this issue any more.
