### ISSUE TITLE
[Wishlist] SLAVE-mode, readonly, no scanning

### ISSUE THREAD

**Issue by MartinX3** [syncthing/syncthing#3893]
Similar to the MASTER-Mode, there should be a SLAVE-Mode.
Read-only, no scanning.
Should save cpu cylcles and BATTERY (on smartphones).
The battery drain of this app on android is quite high, even without any scanning.
(Yeahr, i know, i could set the scan intervall incredible high, but in my opinion, thats not user friendly.)

**Comment by Ferroin** [comment]
There's already a generic pull-request for a slave-mode folder, check #3780 

The idea of having an option to never scan that folder automatically would be nice too, but that's probably going to have near zero impact on the Android app, since that already defers scanning and uses inotify to get update notifications.

**Comment by MartinX3** [comment]
Aye aye, thank you for the information!
#3780 sounds nice!
Weird that this Syncthing App eats many CPU Cylcles even without syncing.
(I saw it in HTop and the battery statistics place syncthing on the first place).

**Closed, reference to #3780!**

**Comment by Ferroin** [comment]
FWIW, regarding the Android app, I'm pretty sure based on my own testing that most of the power consumption when it's not actually syncing is network communication to other connected devices.  Syncthing's protocol can be rather chatty even when there's nothing to sync because the devices maintain connections to each other most of the time.

**Comment by MartinX3** [comment]
Hmmm, there are 1 only device and 3 offline devices.
The timeouts could achieve this?

But there are already discussions how to optimize the standby communication?
