### ISSUE TITLE
Feature Request: Option to attach person information to device

### ISSUE THREAD

**Issue by conrad-heimbold** [syncthing/syncthing#3898]
I am also using Syncthing to sync aka share folders with other people than just me (not only my own devices). 

It would be a really cool solution if you could attach a person information to every device. That information can stay local and does not have to be synchronized. 

That would allow you to 
1. Sort your devices by owner (your devices, person1's devices, etc.) in the device list
2. Sync a folder with ALL the devices of another person by ONLY selecting that person in the share option dialog of a folder. Of course, so that this works, you need to have all the necessary devices of that other person in your list. 
3. Revoke access to your own folders for all the devices of another person AT ONCE by just removing that person from your list. You would not have to revoke access for every device manually. 

In the future, person information could maybe be synchronized across all your OWN devices. (Your own devices can also be marked with that person information, of course)

**Comment by conrad-heimbold** [comment]
Also, if I want to share a folder with another person, I am not interested in which devices that other person is using. I want to share with a PERSON, not with a DEVICE.

**Comment by conrad-heimbold** [comment]
I think this feature request is one partial solution for issue #2070 , am I correct?

**Comment by conrad-heimbold** [comment]
I also think that using person information is much more intuitive and understandable for the everyday user than creating "device groups" with some special syntax in the device name.

**Comment by AudriusButkevicius** [comment]
Sorry, this is out of scope of syncthing. You can build identity management on top of it if you wish

**Comment by conrad-heimbold** [comment]
Why is grouping devices by some name (see issue #2070 ) inside the scope of Syncthing, but grouping devices by owner not inside the scope of Syncthing? That sounds not very reasonable to me!? Also, I didn't request some huge identity management. Just some simple person information attached to devices, which can be used for simplifying a lot of stuff. The person support could be implemented very easily: in the XML file ~/.config/syncthing/config.xml , every device tag <device id="..."> "</device> could include a <person> ... </person> tag, with just some string. That string is gets only read by Syncthing's WebGUI , which sorts the listed devices with it and offers to sync a folder with multiple devices at once, by just selecting all devices that have this string. Nothing more. No big identity management. Just some simple Strings.

**Comment by calmh** [comment]
Devices have a simple string attached to them - the name.

**Comment by conrad-heimbold** [comment]
Sorting a lot of devices can be a PITA - if you have multiple users on the same machine, and you use a multi-boot environment with linux and windows on the same machine; things can quickly get really complicated. Also, if the device string name gets too long, the description is garbled. Just have a look at this: 
![bildschirmfoto vom 2017-01-13 18-27-58](https://cloud.githubusercontent.com/assets/17474312/21939012/20be75da-d9be-11e6-88e0-1b8610d4d264.png)

**Comment by conrad-heimbold** [comment]
Only the device name is NOT ENOUGH!

**Comment by AudriusButkevicius** [comment]
It's your choice to use an absurdly verbose naming scheme. There are 2 pieces of information that uniquely identifies each device, which is name and OS, you can include brand later, yet it has no significance.

**Comment by conrad-heimbold** [comment]
So you can identify you device only by the ID? You really always remember your ID? Please don't tell jokes! If you want to make syncthing more user-friendly (so far, almost exclusively nerds and geeks are using syncthing), I would suggest you to implement that. Otherwise, I would say, it is no wonder, that only those kind of people are using Syncthing.

**Comment by conrad-heimbold** [comment]
My naming scheme is not 'absurd'??? It just takes into account: 
- multi-user operating systems (on desktop computers)
- multi-boot environment (windows and linux on the same machine, the desktop computer). 
- multiple devices (modell name are the last strings - e.g. Acer Aspire M3870 is the desktop PC, Moto G my smartphone. I will buy a new smartphone in the near future for myself, again with cyanogenmod. What name should I choose then?)

**Comment by conrad-heimbold** [comment]
By the way, thank you for telling me that my way of using Syncthing is stupid and absurd! One of the four rules for free software (according to Richard Stallman) is, that you are allowed to use the software for ANY PURPOSE, and that free software should NOT FORCE you to use it in a PARTICULAR way. You however obviously think, that Syncthing should only be used in some very particular ways.

**Comment by Ferroin** [comment]
Device name can be any arbitrary string, and it gets pre-filled when an introducer is adding the device to what the introducer has for the device name.

In my case, I just use host names, I only have one OS on each device (technically my laptop has 2, but I only run Syncthing on the Linux side because I only use Windows for gaming and ST trashes my network latency), and all the devices are functionally single-user.  For a case like yours, it would not be hard to just label each device with a name that describes OS, the user, and a hardware identifier (for example based on your use case, you could use 'Linux Desktop (conrad)' for your desktop when booted into Linux, 'Smartphone (conrad)' for your phone, etc).  You already functionally have the ability to do this, the fact that Syncthing itself does not store such info independently from the device name is irrelevant.  For most people, such a scheme is absurdly verbose, because most people aren't multi-booting and dealing with multiple individual users per-device in one cluster.  Whether it's absurd for most people does not mean that it's an absurd usage in general, just that most people don't use it that way.

**Comment by conrad-heimbold** [comment]
I already tried to make the device names as short as possible: 
- "desktop computer" got shortened to "desktop"
- "smartphone" got shortened to "sphone"
- "Windows" got shortened to "WNDW"
- "Acer Aspire M3870" got shortened to "Acer Asp M3870"

However, I also tried to make the same parts in multiple device names align to each other, if written in Monospace fonts under each other (That looks much nicer!). 

By the way, the last parts after the "@" are indeed mostly the host names of the machines (if possible - only windows had problems with it, because NetBIOS limits the hostname to 10 characters...).

**Comment by Ferroin** [comment]
OK, so looking back at your example screenshot, there's two things that I notice:
1. You can functionally truncate the username to a unique yet still descriptive prefix (for example, instead of conrad_heimbold, you could cut that to conrad_h, since the likelihood of there being another conrad_h involved is pretty slim).
2. Given just that example, you could theoretically eliminate the hardware info.  Generic system type (smartphone/desktop) and OS already uniquely identify each device you're using, and that would cut down on how long the device names are significantly.

As far as the long device name issue, that's a functionally independent bug by itself (it impacts this, but this is not the only usage that is impacted), and should probably have a separate ticket opened for it.
