### ISSUE TITLE
selective syncing of subfolders/files on devises (feature request)

### ISSUE THREAD

**Issue by seb-1204** [syncthing/syncthing#3940]
Scenario: 3 devices A,B,C

- A and B have a large set of folders in sync. All folders are subfoders to 'F'
- Device C has limited storage capacity but also needs only a subfolder of 'F'.

It would be good to be able to select only some subfolders for syncing on a per device basis.

e.g. I have a folder with invoices with an subfolder for every year. On my phone I only want to sync the current year where as on all other devices I want the full set.

**Comment by calmh** [comment]
Covered for the future by #2491 (duplicate)

**Comment by paoletto** [comment]
What's the status on this? I also have the same setup as seb, syncing only a subdirectory of the main sync repo on some devices. Currently using Unison, but looking for a more automated solution (that does the syncing as soon as something changes instead of "when i click sync").
Is this scenario now solvable using syncthing?

**Comment by AudriusButkevicius** [comment]
Read the docs, you can already do that.

**Comment by imsodin** [comment]
@paoletto This issue is closed. Please post support questions on the forum (and yes of course that is possible and has been since ignoring stuff is possible - read up on it in the docs).
