### ISSUE TITLE
Stuck at 99%

### ISSUE THREAD

**Issue by Confuset** [syncthing/syncthing#3979]
Hey everyone,
i have two device which share the same folder.

One of these devices displays a status of 99% for the other device and never gets to 100%/Complete.
Iam not really sure where to start investigating so let me know what you need or where to look at.
The other device seems to be totally fine, nothing to sync. Also no folders are in the state of syncing on both devices.
the up and download indicators are 0B/s

### Version Information
Syncthing Version: v0.14.23
OS Version: Windows 10 / Raspbian GNU/Linux 8 (jessie)
The raspbian is the one showing the 99% for the Windows 10 device. 

![99](https://cloud.githubusercontent.com/assets/7592535/22809230/0cca0156-ef31-11e6-8637-a32ebbac6cf2.jpg)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
