### ISSUE TITLE
A default folder should be provided for new shares.

### ISSUE THREAD

**Issue by jcelerier** [syncthing/syncthing#3988]
By default, the UI when adding a share starts sharing the *whole* home folder, if nothing is entered.

There is a first small UI bug : it does not display the red warning in case the default (home folder) is a parent of another share.

Couldn't there be a default placeholder folder, such as "New share", "New share (1)", etc.  so that the home isn't synced by default if somebody clicks quickly without reading too much the text ?

**Comment by bugith** [comment]
Yes, some path configurable like ~/Sync/ as a default parent, then when one "Add" the GUI would propose ~/Sync/New

**Comment by calmh** [comment]
> By default, the UI when adding a share starts sharing the whole home folder, if nothing is entered.

The "add folder" dialog can't be saved/closed without entering a path, so not sure what you mean here really?

**Comment by bugith** [comment]
> By default, the UI when adding a share starts sharing the whole home folder, if nothing is entered.
I can see this only when typing "~", (which fills the field with /home/me <-note the missing trailing "/") AND I then can go to the "Save" button **without** picking "/home/me/" (<- note the trailing "/") from the drop-list.

> There is a first small UI bug : it does not display the red warning in case the default (home folder) is a parent of another share.

I don't see this as long as the path in the field (ends with a "/" and is a parent) or (ends with last character before the trailing "/" and is a parent).
Although, this is true that the red warning won't show when the field is empty : instead I have a strange/puzzeling message "<red>/home/me</red> . The path to the folder can't be empty"

> Couldn't there be a default placeholder folder, such as "New share", "New share (1)", etc. so that the home isn't synced by default if somebody clicks quickly without reading too much the text ?

Where should it be created? Whatever it is IN the home or some other already exiting _default_  subdir (the one I talked in my previous post), the _place holder_ would need to be calculated so that the target path doesn't already exist... OK you said this already (I read too fast ;-) ). But as long as you don't accept this "New share (n)" and browse one step up to the parent this **will** trigger the red warn, (which is current behaviour). This is not to say I don't love your idea.
Also, keep in mind there is still a bug somewhere that keeps the red warn remaining from the previously discarded creation (creation discarded at the time the red warn is displayed).

**Comment by calmh** [comment]
Dup #2157 apart from the other oddness
