### ISSUE TITLE
 When a share is removed from one device, other devices should be notified

### ISSUE THREAD

**Issue by alessandro-g89** [syncthing/syncthing#3993]
I noticed something unexpected when I remove a shared folder from a device (let's call it A): soon, all my other devices that share the same folder try to push it again to A, as if A never had that folder in the first place. The only way to stop them sending notifications is to go to each device's UI and un-select A from the list of devices sharing the folder.

I believe this behaviour is troublesome and counter-intuitive: to stop one device from sharing that folder, I also need to tweak all the other devices. A non-expert user could get very confused and not know how to fix the issue at all. What I would expect is for device A to tell the others: "I had that folder, I don't want it anymore, stop sharing it with me".
Technically, I'd say that upon deletion, A should remember the devices that were sharing the folder at that time, and try to notify each of them of the deletion. When a device is actually notified, A can forget about him having the folder. When all the devices are notified, A can finally forget about the folder altogether.

I experienced this with device A being an android smartphone, with syncthing-android v0.9.6 (latest on f-droid) and syncthing v0.14.22-rc.1+12-g5a1ee7c. Other devices are laptops and ARM devices with auto-update enabled (currently using syncthing v0.14.23).

I did some searching before posting, but I didn't find any reference of what should happen in this case, either confirming or disproving my experience.

**Comment by calmh** [comment]
Just thinking out loud, we could have each device also mention folders it knows about but *does not* share, in the initial cluster config message. That way the other side can know which folders are "symmetrically" shared, which are intentionally not shared, and which are pending. It could display that on the device in the gui. It would mean that when deleting / unsharing a folder we would need to save that somewhere instead of just remove it like now.

**Comment by dcarosone** [comment]
No thanks. I don't particularly want to leak the existence of other shares
to peers that shouldn't know about them.

Not every network is single user, single purpose, or fully trusted for all
data sets.

On 20 Feb. 2017 14:58, "Jakob Borg" <notifications@github.com> wrote:

Just thinking out loud, we could have each device also mention folders it
knows about but *does not* share, in the initial cluster config message.
That way the other side can know which folders are "symmetrically" shared,
which are intentionally not shared, and which are pending. It could display
that on the device in the gui. It would mean that when deleting / unsharing
a folder we would need to save that somewhere instead of just remove it
like now.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/syncthing/syncthing/issues/3993#issuecomment-280982700>,
or mute the thread

**Comment by calmh** [comment]
In my case it would only leak if the folder was once shared and then unshared/removed, not in the general case. But there is certainly case for keeping this as close as possible to a need-to-know basis, and there is no strict need to know of folders that exist but are not shared.

**Comment by alessandro-g89** [comment]
Yes, that's quite excactly what I had in mind. So, do you plan to do it this way?

**Comment by calmh** [comment]
No plans to act on this at the moment, but that would seem to be a way forward.

**Comment by blindchimp** [comment]
When I read this, it reminded me that this kind of thing (re-presenting remote folders after a folder "unshare") can lead to the sorts of issues mentioned in #3876 ... especially if you accidentally click and re-add something. Sounds like a thorny problem...

**Comment by Raven38911** [comment]
I have the same problem. It is mostly annoying because it happens again and again - the remote side keeps trying until I manually tell it to stop. However this could be solved relatively easily.

In the dialog "XYZ wants to share folder ABC. Add new folder?", we need an option "No, and please tell device XYZ not to try again!". Then the remote node XYZ would remove me from the list of nodes to share this folder with.

In the long term it would be really nice if syncthing had an internal mechanism that allowed certain devices to remotely manage other devices, so we could decide who shares what with whom at a central location.

**Comment by AudriusButkevicius** [comment]
That mechanism more or less already exists as the introducer feature. Also, this central location idea you are suggesting implies that you are the one owning all devices, which is not always the case.

**Comment by Raven38911** [comment]
> That mechanism more or less already exists as the introducer feature.

Not sure what you mean. How can the introducer feature stop remote devices from sharing a folder with me?

> Also, this central location idea you are suggesting implies that you are the one owning all devices, which is not always the case.

But in many common situations it would be very helpful. I have about a dozen Syncthing devices at different locations running different OSes. Confirming each change on each affected side is quite cumbersome and can take weeks as I don't visit each device regularly.

**Comment by AudriusButkevicius** [comment]
I suggest you read/try out introducer, as I suspect it handles your usecase.

**Comment by Raven38911** [comment]
Thanks for the suggestion. 

I have now read the documentation again and messed around with the introducer feature. This sentence appears promising: "If an introducer adds or removes any devices or shares, or changes device-share settings, however, this change will be reflected to devices upon their next connection." 

Playing around with it, I have for example found out that things can get messy, if you build circles of introducers.

But my primary scenario did not work: 
Device A is the single introducer in the network (and every node knows this).
Device B had a share once, but the share was removed. The introducer has also been configured, not to share it with B any more.
But still everyone else tries to share it with B. Also restarting syncthing several times on all devices did not help.

My feeling is that - contrary to the sentence from the documentation quoted above - introducers can only add shares and not remove devices from a share.

I also feel that the introducer feature should be more clearly documented, including the explanation in the UI.

**Comment by nickmdowson** [comment]
I'm also having this trouble

**Comment by nrm21** [comment]
If the endgame is to keep from bugging the user at the GUI to readd and readd a folder.  Then why not just have the "Deleter" of the share keep track of what he no longer wants and suppress all messages to readd that particular folder.

No need to tell others (let them keep sending invites occasionally and we just ignore them and don't present to user).  No protocol changes.  No extra data leakage (for the security minded).

**Comment by calmh** [comment]
Yeah. We already do that for devices, just need to add the same functionality for folders.
