### ISSUE TITLE
New metalinter issue

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4026]
Tests are failing due to metalint, maybe because of new go 1.8?

```
+ go run build.go metalint
lib/config/folderconfiguration.go:95:18:warning: HideFile is a pure function but its return value is ignored (SA4017) (staticcheck)
lib/versioner/simple.go:60:19:warning: HideFile is a pure function but its return value is ignored (SA4017) (staticcheck)
lib/versioner/staggered.go:256:19:warning: HideFile is a pure function but its return value is ignored (SA4017) (staticcheck)
lib/versioner/trashcan.go:65:18:warning: HideFile is a pure function but its return value is ignored (SA4017) (staticcheck)
lib/model/model.go:1302:17:warning: HideFile is a pure function but its return value is ignored (SA4017) (staticcheck)
```

**Comment by calmh** [comment]
Yeah I noticed, it's metalint that got smarter and noticed that in the unix case that function does nothing but return a value, which we ignore. I think the best solution is to remove the error return from HideFile because we never care about it. At least in the unix case, although it's a bit weird to have different function signatures per platform.

**Comment by calmh** [comment]
Seems buggy, I disabled the check in 4e3fdfa
