### ISSUE TITLE
syncthing is slow, when file is large.

### ISSUE THREAD

**Issue by fanux** [syncthing/syncthing#4081]
We test syncthing on 7 nodes, the file size is 300G, it takes four hours and not complete yet...

Our machine and network performance is very good, syncthing suit big file and a large number of nodes situation?

Syncthing Version: latest
OS Version: Centos7.2
Browser Version: (if applicable, for GUI issues)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
