### ISSUE TITLE
Device stats "items" should show the same kind of data as the folder stats

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4100]
<img width="1169" alt="screen shot 2017-04-14 at 17 50 38" src="https://cloud.githubusercontent.com/assets/125426/25048173/37545520-213b-11e7-91ba-56034f597122.png">

**Comment by wweich** [comment]
I suggest changing it to the per folder way. Files, directories, size (with icons instead of "Items").

**Comment by snugghash** [comment]
Greetings, I'm a new contributor, and I'm wondering where the needed changes are:
I've changed the code in [index.html](https://github.com/syncthing/syncthing/blob/master/gui/default/index.html) and added 'directories' attribute to the localStateTotal in [syncthingController.js](https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/syncthingController.js) which populates the template engine's variables (I assume). 

Also, what about analogous changes in syncthing-gtk and so on?

P.S: It appears the build instructions suggested still result in a bad version check when running /bin/syncthing: exiting because Version != 'unknown-dev'. 
I'll rebuild with that check disabled to check if these two commits solve the issue.

**Comment by snugghash** [comment]
It appears it does indeed solve the issue, the $scope.model[f].localDirectories has the correct values:
![syncthing issue 4100](https://user-images.githubusercontent.com/4134288/26872961-dcab6a62-4b67-11e7-8402-4b792402c5df.png)

Any tests, etc. to be written before submitting a PR?

**Comment by canton7** [comment]
> Also, what about analogous changes in syncthing-gtk and so on?

Don't worry - that's maintained by someone separate.
