### ISSUE TITLE
Sync between Linux and OS X causes massive unicode errors

### ISSUE THREAD

**Issue by juh2** [syncthing/syncthing#4134]
v0.14.27, Linux (64 bit) 
v0.14.27, Mac OS X (64bit)

File names with special characters causes unicode errors and file duplications with error:

`has UTF8 encoding conflict with another file; ignoring.
`

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
