### ISSUE TITLE
No .stversions on macOS

### ISSUE THREAD

**Issue by dodekeract** [syncthing/syncthing#4150]
### What happened?

No `.stversions` gets created on macOS. I **think** I lost some data due to syncing issues, it's a huge folder (~2 TiB) and I stopped it very early. Can't verify this 100% yet, looking into it.

### What you expected to happen instead

Since I enabled "Trash Can File Versioning for 30 days" I expected to not lose any data due to syncing errors.

### Steps to reproduce

Not sure yet. Will add further information if I find out what triggers this.

### Version Information

Syncthing Version: v0.14.27
OS Version: macOS Sierra 10.12.3

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
