### ISSUE TITLE
HTTPS connection to web UI is not secure

### ISSUE THREAD

**Issue by RenaKunisaki** [syncthing/syncthing#4169]
Having just installed syncthing, Chromium complains that the web UI connection is insecure:

> Your connection is not private
> 
> Attackers might be trying to steal your information from 127.0.0.1 (for example, passwords, messages or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
> 
> This server could not prove that it is 127.0.0.1; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.

### Version Information

Syncthing Version: v0.14.28
OS Version: Arch Linux AMD64
Browser Version: Chromium Version 58.0.3029.110 (64-bit)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
