### ISSUE TITLE
Relay server should be more verbose with the -debug option

### ISSUE THREAD

**Issue by Avamander** [syncthing/syncthing#4180]
When setting up syncthing relay it outputs "Failed to join due to IP address not matching external address", the issue is I don't know what IP address the relay is seeing, it should output the IP the server got and what was passed to it with parameters. 

Though neither should it even output that line because the relay responds from the IP and port(s) specified by -ext-address, -status-srv and -listen. I suspect it might have something to do with the same interface having multiple IP addresses and it's wrongly making requests from some other (default interface) IP than the one specified by -ext-address.

Syncthing Relay Version: v0.14.29
OS Version: Ubuntu Server 16.04

**Comment by AudriusButkevicius** [comment]
Agree, this could be better.

**Comment by wwwutz** [comment]
I got `Failed to join due to IP address not matching external address`  because the *default* settings of `statusAddr=:22070` which is transferred to `relays.syncthing.net`.

I fixed this by adding a valid IP:port to the correspondig `-status-srv` commandline option.

Anyways, this opens a new issue, since in a firewalled setup I need a `-ext-status` option like `-ext-address` for the status page.

**Comment by wwwutz** [comment]
I think the issue mentioned here was fixed with https://github.com/syncthing/syncthing/commit/a27032f09e572dc92fbc69690e519a98164d0634 so maybe there is no need to make it more verbose anymore.

**Comment by AudriusButkevicius** [comment]
Yeah I think this was fixed.
