### ISSUE TITLE
File case change (and other unknown condition) causes sync issue

### ISSUE THREAD

**Issue by sebastianlau** [syncthing/syncthing#4181]
Syncthing Version: v0.14.29
OS Version: Windows 10 Enterprise x64

Ended up in a loop of:
[CBBTP] 01:37:34 INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later
[CBBTP] 01:37:35 INFO: Folder "Standalone_Applications" isn't making progress. Pausing puller for 1m0s.
with a single file refusing to update.

I'm currently unable to reproduce from scratch, however can see that this stems from the peer machine attempting to update the file where the file casing has changed.
(Master) file name is "npEagleGet.dll"
(Peer) has an older existing file with name "npEagleget.dll"

Peer also ends up with "~syncthing~npEagleget.dll.tmp" file.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by AudriusButkevicius** [comment]
Also #1787
