### ISSUE TITLE
Could not join relay Server

### ISSUE THREAD

**Issue by rocketdoge** [syncthing/syncthing#4275]
### Version Information

Syncthing Version: v0.14.18
OS Version: Debian 9

What happened:
Synthing doesn't connect to any relay servers, it just spams the logs with it trying to but failing (apparently EOF errors)
`[GRAGZ] 2017/07/26 23:40:52.868905 static.go:81: INFO: Could not join relay relay://176.31.181.189:22067/?id=3NWGDQV-2LIQVXO-PCZRZ5B-XIVQ2&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Bl0tz4: EOF`

What I expected to happen:
Syncthing connecting to a relay server to allow Synchronisation between my server and my computer

Steps to reproduce:
Start syncthing

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
