### ISSUE TITLE
Fail sync on an abc*df*dat.sch file

### ISSUE THREAD

**Issue by De-Backer** [syncthing/syncthing#4282]
- what happened,
Fail sync on an abc*df*dat.sch file

If * is removed or replaced it sync

On Android  0.14.32v

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
