### ISSUE TITLE
Syncthing Issues in FreeNAS

### ISSUE THREAD

**Issue by bfitec** [syncthing/syncthing#4292]
I have installed Syncthing ( v0.14.35, Linux (64 bit) ) in a jail through the plug-in interface in FreeNAS and it is failing to recognize other devices trying to connect to it. I figured this issue probably had to do with the jail so I installed Ubuntu Sever in a Beehyve VM inside of the same FreeNAS and then installed Syncthing ( v0.14.35, Linux (64 bit) ) in that and got the same issue except the Ubuntu VM could connect to the FreeNAS Syncthing plug-in jail. This obviously is not a Syncthing having issues but instead I've probably just mis configured FreeNAS networking, I've been stuck on this for a few days and I don't know what to do other than just setup an independent system and I do not want to do that... If you need more information about my setup let me know, I didn't know what would help and didn't want to bog down the post. 

Thanks in advance!

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
