### ISSUE TITLE
Syncthing should offer fixing UTF-8 encoding issues/conflicts

### ISSUE THREAD

**Issue by endolith** [syncthing/syncthing#430]
I got the error 

> File "..." contains non-NFC UTF-8 sequences and cannot be synced. Consider renaming.

many times on many files.

1. I don't know what non-NFC means.  Message should be more clear.
2. Syncthing should sync all files regardless of their names.  These are both Windows 7 machines, so there's no compatibility problem between the OSes.  If there is a problem, like Linux using ":" in filenames and syncing with Windows, it should sync the files anyway and sanitize the names for each OS.

**Comment by klenamenis** [comment]
Sadly, this is the only issure that keeps me from migrating from BitTorrentSync. Any information about when this will be fixed?

**Comment by mauro3** [comment]
What does the automatic fix do to the filenames?  Does it rename them to conform to the system standard on syncing?  Presumably it does not rename files which are present locally, right?

**Comment by calmh** [comment]
It renames files that are UTF8 but in the wrong normalization form for the current system, yes. This is something that pretty much only happens when files are moved on USB sticks and similar without conversion between PC and Mac, and when the filenames contain accented characters (or some other special cases).
