### ISSUE TITLE
Keeps getting error: Stopping folder "MyPictures" (Pictures) - folder path missing

### ISSUE THREAD

**Issue by Avelec** [syncthing/syncthing#4337]
Hi, I'm running the latest syncthing on Windows 10 pc, Raspberry-Pi3, and Android phone. What is the reason for the "folder path missing" error that keeps popping up. Thanks in advance!

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
