### ISSUE TITLE
Symlinks as folder root broken on Windows

### ISSUE THREAD

**Issue by PrototypeNM1** [syncthing/syncthing#4353]
After updating to 0.14.37, all root folders which are referenced by symlink result in "Failed initial scan (rw) of...". Verified by creating two new sync folders, one referencing an actual folder's location, the other a symlink to a folder on another drive.

A current workaround of the problem is to set the path directly to the folder (no symlink).

Syncthing Version: v0.14.37
OS Version: Windows 10

**Comment by calmh** [comment]
Thanks. This sounds like something we should fix.

**Comment by calmh** [comment]
However, I can't reproduce.

```
jb@unu:~ $ pwd
/Users/jb
jb@unu:~ $ ls -ld t?
drwxr-xr-x  4 jb  staff  128 Sep  7 08:10 t1/
lrwxr-xr-x  1 jb  staff    2 Sep  7 08:09 t2@ -> t1
```

<img width="567" alt="screen shot 2017-09-07 at 08 11 30" src="https://user-images.githubusercontent.com/125426/30148543-3146bf70-93a4-11e7-8c38-db947b9db88f.png">

I suspect this is something specific to symlinks on Windows, which makes it out of my immediate jurisdiction...

**Comment by Catfriend1** [comment]
Hi,
I am having problems with the following scenario. I'm on Windows 10 running syncthing with high privileges. Now I have a directory structure on the windows machine like:
C:\Videos
-- Archive
-- Personal
-- Friends
C:\Music
-- 1
-- 2
-- 3
-- 4
C:\Pictures
-- 2010
-- 2011
-- 2012
-- 2013
-- 2014
-- 2015
-- 2016
-- 2017
C:\Documents
-- House
-- Garden
-- Ebay
-- Tickets
I really need a view of all that folders (well organized and referenced by a lot of windows links (.lnk files) to each other for documentation. I do not like to rearrange them into another directory structure because its proven optimal for my office work and everything is linked with explorer links. Some folders contain sensible private data and others don't

I'd like to sync some of the folder from first and second level of C:\ to my sdcard using syncthing. My view should be like this:
C:\_virtual_folder_phone_sdcard_view
-- Documents
---- Tickets
-- Pictures
---- 2016
---- 2017
-- Music
-- Videos
---- Personal

I already managed to allow syncthing to access the full sdcard with write access under android - works fine. But the more folders I have, the more I have to separately fill in and handle and document within syncthing. I dont need special settings like free disk space, smallest first, ignore fat fs rights, ... different for each folder. My best way to achieve this was writing a self-documentary batch script with "mklink /d TARGET SOURCE" commands to create real links (symbolic directory links) within "C:\_virtual_folder_phone_sdcard_view" containing above subfolders (parseable by explorer and sync software like syncback free).

Syncthing 14.26 and 14.37 were tested by me and count 0 files and folders in the virtual folder so I suspect syncthing not parsing the symlinked folders. I need this feature and would like to suggest an improvement at this point for the syncthing project. Basic parse support would be sufficient. So no exact copy of symlinks between different file systems or OS is needed. Just the way, windows explorer also travserses the symlinked content and represents this to apps like SyncBack Free, Word, ...

The workaround I tried with the ignore list also does not fit very well.
I have one Syncthing Folder "C:\" containing all my stuff without exceptions and this is linked with my second windows machine. (It should keep the second machine up2date with the masters data excluding OS folders). Yesterday I tried to create a second syncthing folder in the library called "C:\_to_phone" and tried to set the ignore patterns so the above mentioned folders only get synced without using the C:\virtual_phone_view folder. But then I noticed I can always have a single ".stingore" pattern for one and the same directory in syncthing leaving me again with the need to make a virtual folder containing symlinks and having the chance, to make a view of the filesystem in order to sync it with syncthing. (and plus having a stignore file when needed).

Can you please give me a hint what I can do or if I can support those feature enhancements positively?

Kind regards

**Comment by calmh** [comment]
@Catfriend1 https://forum.syncthing.net

**Comment by PrototypeNM1** [comment]
Just to clarify, the symlinks were generated with "mklink /d [source] [destination]". The symlink was pointed to two different drives, I didn't test a symlink on the same drive but I assume that's highly unlikely to be related to the issue.

**Comment by koppor** [comment]
I have the same issue here:

I get outputs like

    [4QJNC] 10:50:35 INFO: Puller (folder BTSync, dir "software-portable\\JabRef-dev-fat.jar"): not a directory: .

I cannot follow the suggestion at https://forum.syncthing.net/t/how-can-the-folder-path-be-changed/1153, because syncthing crashes:

    panic: bug: remove non existing folder

<details>
goroutine 902 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).RemoveFolder(0xc04207a6c0, 0xc04311e43a, 0x6)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/model/model.go:348 +0x305
github.com/syncthing/syncthing/lib/model.(*Model).CommitConfiguration(0xc04207a6c0, 0x17, 0xc043592b40, 0x1, 0x1, 0xc042c13860, 0x3, 0x3, 0x1, 0xc04311e4e0, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/model/model.go:2399 +0xa90
github.com/syncthing/syncthing/lib/config.(*Wrapper).notifyListener(0xc0420f4c00, 0x109ed20, 0xc04207a6c0, 0x17, 0xc043592b40, 0x1, 0x1, 0xc042c13860, 0x3, 0x3, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/config/wrapper.go:171 +0x16d
created by github.com/syncthing/syncthing/lib/config.(*Wrapper).notifyListeners
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/config/wrapper.go:165 +0x1ff
goroutine 1 [chan receive, 8 minutes]:
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc04200c640, 0x35, 0x0, 0x0, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:943 +0x1ba8
main.main()
</details>

**Comment by calmh** [comment]
@koppor your traceback is truncated and doesn't say what happen, but that looks like #4405 which is solved in 0.14.40-rc

**Comment by koppor** [comment]
@calmh Yeah, that solved the removal. The RC also outputs following:

    2017-11-03 11:04:51: Error on folder BTSync: C:\Users\Oliver\BTSync: not a directory

Maybe, this check can be modified so that symlinks are followed **on Windows**, too?

**Comment by calmh** [comment]
@koppor could you download this utility: https://kastelo.net/t/stfileinfo.zip

and run it in a terminal on the *folder root* and paste or screenshot what it says, exactly?

**Comment by koppor** [comment]
```
Oliver@LLARDANA C:\Users\Oliver\BTSync
> c:\Users\Oliver\Downloads\stfileinfo.exe .
File:
  .

Lstat:
  Size: 0 bytes
  Mode: 01000000666
  Time: 2017-03-24 12:26:58.0046192 +0100 CET
        1490354818.004619200

Stat:
  Size: 8192 bytes
  Mode: 020000000777
  Time: 2017-11-03 11:17:09.7060052 +0100 CET
        1509704229.706005200
```

**Comment by koppor** [comment]
Seems that the first output block is the symlink and the second output block is the file info of the target folder.

**Comment by PrototypeNM1** [comment]
The original error is not replaced with the "not a directory" error for the symlinked root folder, same conditions for the original bug.

**Comment by AudriusButkevicius** [comment]
Your config probably somehow contains a trailing slash,try removing that from your config.

**Comment by PrototypeNM1** [comment]
Not likely the issue, verified with/without trailing slash and with ~ and absolute path to the symlink, also verified that the equivalent config works under Ubuntu. The path displayed with the error message looked correct.

**Comment by AudriusButkevicius** [comment]
We have a test case, so if you could expand it to repro, it would be great. Also, make sure that the symlink is valid and points to a directory. Windows symlinka are typed.

**Comment by calmh** [comment]
Reopening as this is clearly not fixed.
