### ISSUE TITLE
Excessive memory use on FreeBSD 11, Syncthing v0.14.37

### ISSUE THREAD

**Issue by kpuc** [syncthing/syncthing#4359]
I don't know if you've been made aware, but Syncthing v0.14.37's memory use on FreeBSD is a little out of control.  My other nodes (Windows 7 64bit, Linux 32bit and 64bit) don't seem to exhibit this issue.

After an hour or so of uptime memory use has grown from an initial couple hundred meg to over a gigabyte.  An hour or so later it's two gigs.  Twenty hours later and it's about fifteen gig and i'm running out of swap.   Restart Syncthing and this behavour has repeated itself twice now.  

Just moments ago Syncthing restarted itself, presumably detecting a low memory situation? I wasn't quite out of swap yet, but it was close. 
[monitor] 08:01:52 INFO: Syncthing exited: exit status 3

Anyhow, I can write a cronjob to restart syncthing every day, but I figured you'd want to know about this issue. 

[RTBSN] 08:01:53 INFO: syncthing v0.14.37 "Dysprosium Dragonfly" (go1.9 freebsd-amd64) teamcity@build.syncthing.net 2017-08-24 04:26:12 UTC

 uname -a
FreeBSD lela.dax 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by calmh** [comment]
That sounds wrong, and not immediately reproducible. My main server is on FreeBSD and

```
jb@pseudo:~ $ uname -a
FreeBSD pseudo.nym.se 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

<img width="570" alt="screen shot 2017-09-09 at 18 58 10" src="https://user-images.githubusercontent.com/125426/30242127-f0ad854a-9590-11e7-973f-47bfe5602bf7.png">

Is there anything of note logged? Errors? Otherwise we can try grabbing a heap profile to see what's going on.

(Exit status 3 is restart - from GUI, SIGHUP, or auto upgrade.)

**Comment by kpuc** [comment]
re: status 3: Hm, I intended to restart Syncthing; perhaps I did and forgot.  

I don't see any errors.  It is complaining about peers with a file having vanished, or the file has changed while syncing, but that's normal.  (i'm sharing several firefox profiles between nodes, and files come and go).  

Synthing has been up for a bit over two hours, and hasn't yet broken a gigabyte of ram.  It's probably a little high (I seem to recall hovering around 400MB being normal), but if that's the new-normal I can cope with it.  

I have acquired a heap profile.  Do you want it now, or should I wait an hour and get a second so you have something to compare?  (presumably Synthing will have grown a fair bit more by then...)

Nice hostname, 'pseudo.nym', btw. :D

**Comment by calmh** [comment]
Yes, please do hand over the profile...

**Comment by kpuc** [comment]
[SyncthingHeap201709a.zip](https://github.com/syncthing/syncthing/files/1305110/SyncthingHeap201709a.zip)

**Comment by calmh** [comment]
The first profile in the zip file is largest one (`Showing nodes accounting for 1880.40MB, 97.63% of 1926.04MB total`), and appears to show Syncthing currently attempting to sync (pull) files, with several hundred thousand files in the job queue. That latter number might be wrong, it's a bit hard to tell the exact object types from the profile and I may be misinterpreting, but all in all it looks like a large queue of potentially large files to sync, and that queue takes up space. Potentially we could improve things here, but as is I think that falls under "expected".

**Comment by kpuc** [comment]
ok...   I don't think I had this problem with v0.14.36.   
I'll try going back a version and pay attention..   v0.14.37 is definitely restarting on it's own -- I don't know if it's the oom killer and the second syncthing process is starting a new one, or what.  

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME     CPU COMMAND
37426 kpuc        102  23    0  4513M  4515M uwait   2 270:36  42.06% bin/syncthing/syncthing

I've doubled the swap space on the system so it takes longer to restart, but it definitely does -- new PID, resets TIME, etc.

**Comment by kpuc** [comment]
I apologize; it's slowly creeping in memory use and restarting itself with v0.14.36 too.  
I'll give v0.14.35 a try, and then .33 -- I'm pretty sure this behavior is reasonably recent.  

Have any other suggestions?  Should I try passing GOGC some value smaller than 100 (right now I have been leaving it at the default)

**Comment by kpuc** [comment]
[RTBSN] 02:27:54 INFO: Folder "censored" isn't making progress. Pausing puller for 1m0s.
[monitor] 02:28:50 INFO: Syncthing exited: signal: killed
[monitor] 02:28:51 INFO: Starting syncthing
[RTBSN] 02:28:51 INFO: syncthing v0.14.36 "Dysprosium Dragonfly" (go1.8.3 freebsd-amd64) teamcity@build.syncthing.net 2017-08-10 15:31:25 UTC


I don't think I was awake at 0200... I didn't cause this restart.

**Comment by AudriusButkevicius** [comment]
It was most likely oom killed.

**Comment by kpuc** [comment]
I suspect so, yes.

**Comment by kpuc** [comment]
Lived for about 26 hours with v0.14.35.  This time it says it restarted with status 3, but I didn't issue a restart instruction.  

Time for a day with v0.14.33....

**Comment by kpuc** [comment]
v0.14.33 has been up for about 26 hours, but it's out of control with the memory usage too.  

My apologies for blaming v0.14.37

Any suggestions?   I'd paste another heap pprof, but it's not working.

**Comment by kpuc** [comment]
From `top`:
 1365 kpuc        127  29    0  9252M  7104M uwait   0 450:52  24.49% ./syncthing
from the webui:
RAM Utilization | 8.55 GiB

**Comment by calmh** [comment]
Going by the heap profile it was simply syncing a large queue of files. You haven't commented on this.

**Comment by kpuc** [comment]
It does have a large quantity of files in it's many folders (323560 files, ~1.1TB of data...), but I didn't think there are many pending files for transfer.  All the folders (except one) show "Up to Date", but some of the nodes say "Syncing", with 100% or 99%.  
The one folder is held up on symlinks, so I'll update to v0.14.38 (from .33) and see if that goes away (I seem to recall there was some symlink stuff done between .33 and .37).

**Comment by calmh** [comment]
Status? I think the continually syncing state may be related and should be solved for this.

**Comment by kpuc** [comment]
Eventually I removed a Folder with ~14700 directories and ~105000 files (only ~8GB), leaving this node with ~12200 directories and ~213600 files (~925GB).  It has been well-behaved ever since; consuming <300MB of ram (the http UI says 57.8 MiB, but `top` says 295M) and many days of uptime (until I updated to v0.14.39 last night).

The node that was having the memory issue had a rescan period if about a year -- the point was files were to come from my source (which was configured send-only).  On the source I had the rescan period set to ~1 day, and perhaps enough files were changing that the 'puller' was accumulating an ever-growing list that couldn't ever be satisfied?  (My source certainly didn't have a copy of the non-modified file any longer, and it wouldn't detect changes until the rescan period)
I also had a crontab on the source issuing a Force, because it often needed it. I think that was set to run every three hours. :/

**Comment by tomachinz** [comment]
I know I'm on Mac and this issue is for FreeBSD, but since Mac kinda uses a BSD based kernel maybe this can help? I believe Syncthing needs an option to "sleep" for say 100ms (maybe allow this to be adjusted) inbetween **files**. This will let me bring it back from 100% CPU use.

The weird thing for me is the 530 GIGABYTES of virtual memory in use. My biggest share is 2.94 TERABYTES on HFS+ usb volume containing 602,000 files! Mostly mp3 (71,000 files and 440 GB), wave (30,000 files 332 GB) and then Aif (19,839 264 GB).

The resultant load is partly understandable but making me think about other solutions due to high CPU: 

13inch Macbook; sierra 10.12.6 (16G29) 
  Processor Name:	Intel Core i5
  Processor Speed:	2.8 GHz
  Memory:	16 GB


  1  [####################*******   72.4%]     Tasks: 372 total, 6 running
  2  [#############****             45.0%]     Load average: 5.30 4.00 3.35
  3  [####################******    68.9%]     Uptime: 09:42:05
  4  [###############****           51.0%]
  Mem[||||||||||||||||||||||11811/16384MB]
  Swp[||||||||||||||||         443/1024MB]

  PID USER     PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
   71 root       4  20 5030M  156M     0 R  0.0  1.0  0:12.51 /Applications/CrashPlan.app/
 2431 tom       31  20 530.8G 96980     0 R 114.  0.6  0:03.83 /Applications/SyncThing/syn
  539 tom       47   0 2840M  203M     0 S  7.0  1.2  0:00.83 /Applications/iTerm.app/Cont
  943 tom       46   0 3753M 57956     0 S  0.0  0.3  0:00.48 /Applications/Atom.app/Conte
  939 tom        4   0 3811M 88796     0 S  0.0  0.5  0:00.38 /Applications/Atom.app/Conte
  111 root      20   0 2472M 39480     0 S  0.0  0.2  0:00.30 /Library/Little Snitch/Littl
  728 tom        4   0 4121M  157M     0 S  0.0  1.0  0:00.23 /Applications/AirDroid.app/C
  547 tom        4   0 3114M 78064     0 R  0.0  0.5  0:00.15 /Applications/Viber.app/Cont
  682 tom       46   0 2504M 30648     0 S  0.0  0.2  0:00.11 /Applications/OTP Manager.ap
  472 tom       20   0 2456M 19568     0 S  0.0  0.1  0:00.10 /Applications/TeamViewer.app
  536 tom       46   0 2581M 66988     0 S  0.0  0.4  0:00.10 /Applications/Utilities/AppP
  126 root      20   0 2438M  8900     0 S  0.0  0.1  0:00.08 /Library/PrivilegedHelperToo
   86 root      20   0 2412M  2992     0 R  0.0  0.0  0:00.06 /Library/Application Support
  495 tom       46   0 3568M 42552     0 S  0.0  0.3  0:00.06 /Applications/Utilities/Flux
  465 tom       20   0 2577M 52272     0 S  0.0  0.3  0:00.05 /Applications/TeamViewer.app
  374 tom       20   0 2547M 40996     0 S  0.0  0.2  0:00.04 /Library/Little Snitch/Littl
  458 tom       20   0 2470M 20928     0 S  0.0  0.1  0:00.02 /Library/Little Snitch/Littl
 2607 root      28   0 2403M  6100     0 R  3.0  0.0  0:00.02 htop
  144 _mysql    31   0 2762M  5104     0 S  0.0  0.0  0:00.02 /usr/local/mysql/bin/mysqld
 2497 tom       46   0 2593M 66204     0 S  0.0  0.4  0:00.01 /Applications/Intel Power Ga
   83 root      20   0 2460M 11868     0 S  0.0  0.1  0:00.01 /Library/Application Support
   89 root      20   0 3478M 20992     0 S  0.0  0.1  0:00.01 /Applications/TeamViewer.app



Also, my Core2 Duo based iMac looks like:

  1  [###########********           49.3%]     Tasks: 220 total, 1 running
  2  [##############****************81.0%]     Load average: 1.92 2.12 2.14
  Mem[|||||||||||||||||##### 5928/12288MB]     Uptime: 21:55:31
  Swp[|                          0/1024MB]

  PID USER     PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  929 tom       46  20 530.8G  297M     0 U 99.0  2.4 10:58.76 /Applications/SyncThing/syn
  656 tom       48   0 2607M  186M     0 S  0.0  1.5  2:16.61 /Applications/TeamViewer.app
 1311 tom       33   0 3379M  189M     0 S 20.0  1.5  2:07.10 /Applications/Google Chrome.
  140 root       4  20 4988M  294M     0 S  0.0  2.4  1:40.10 /Applications/CrashPlan.app/
  280 root      79   0 3163M  150M     0 S  0.0  1.2  0:39.49 /System/Library/Frameworks/A
 1378 tom       33   0 3459M  197M     0 S  0.0  1.6  0:26.75 /Applications/Google Chrome.
 1263 tom        4   0 3420M  304M     0 S  0.0  2.5  0:17.12 /Applications/Google Chrome.
  581 tom       48   0 2469M 15004     0 S  0.0  0.1  0:05.04 /Library/Little Snitch/Littl
 1307 tom       33   0 3420M  222M     0 S  0.0  1.8  0:03.96 /Applications/Google Chrome.
  574 tom        4   0 2690M  186M     0 S  0.0  1.5  0:03.89 /System/Library/CoreServices
    1 root      31   0 2399M  5404     0 S  0.0  0.0  0:03.77 /sbin/launchd

**Comment by AudriusButkevicius** [comment]
Sorry, but what does your post have to do with this. This is talking about memory on freebsd, you are talking about cpu usage on mac. Cpu usage is explained in the faq

**Comment by tomachinz** [comment]
Sorry perhaps I was wrong to post that Mac junk in this BSD thread (but main reason was I see 540 GB of virtual memory used on my systems using htop, but in activity monitor is only 102 MB) I am starting to think this bug is cross platform. Perhaps the hashing algo is too heavy?

**Comment by calmh** [comment]
There is no bug. Virtual memory is *virtual* and this is how all Go programs look to the platform.
