### ISSUE TITLE
Problem when syncing files with "ignore patterns" used.

### ISSUE THREAD

**Issue by olober** [syncthing/syncthing#4366]
Syncthing Version: v0.14.37
OS Version: Windows 7 / MacOS

Three persons with computers **A** (mac), **B** (win) & **C** (win). They share folder with just 2 files.
All in sync. Person **C** decided to ignore one of the files, entered its path to "Ignore Patterns" and deleted the file from his computers. Person **B** (me in fact, not sure if A has the problem) has a problem with computer **C**: my syncthing B is **permanently** trying to sync with computer **C** (blue progress bar on comp. **C** in Remote Devices panel, everything else is Up To Date, also on comp. **C** everything looks perfectly fine), because I have that file, and I'm not ignoring it. 
I think syncthing **C** should inform other computers "I don't want it, skip it"

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
