### ISSUE TITLE
GUI should indicate which files are out of sync on remote devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4369]
Roughly similar UI to the local out of sync modal, per remote device. Helps solve 99% synced crap.

**Comment by calmh** [comment]
`planned` because lets just get this done. 10 internet points to whoever gets there before me.

Here's a diff on the required API method to get started, I just didn't have the stamina to do the UI

```diff
commit 00da16125ab4648ce76d82e41d8a595322ef5add
Author: Jakob Borg <jakob@kastelo.net>
Date:   Fri Feb 10 11:30:40 2017 +0100

    wip

diff --git a/cmd/syncthing/gui.go b/cmd/syncthing/gui.go
index c6bd3a965..08ee41eb5 100644
--- a/cmd/syncthing/gui.go
+++ b/cmd/syncthing/gui.go
@@ -79,6 +79,7 @@ type modelIntf interface {
 	Completion(device protocol.DeviceID, folder string) model.FolderCompletion
 	Override(folder string)
 	NeedFolderFiles(folder string, page, perpage int) ([]db.FileInfoTruncated, []db.FileInfoTruncated, []db.FileInfoTruncated, int)
+	RemoteNeedFolderFiles(device protocol.DeviceID, folder string) []db.FileInfoTruncated
 	NeedSize(folder string) db.Counts
 	ConnectionStats() map[string]interface{}
 	DeviceStatistics() map[string]stats.DeviceStatistics
@@ -704,6 +705,17 @@ func (s *apiService) getDBNeed(w http.ResponseWriter, r *http.Request) {
 		perpage = 1 << 16
 	}
 
+	if device := qs.Get("device"); device != "" {
+		id, err := protocol.DeviceIDFromString(device)
+		if err != nil {
+			http.Error(w, err.Error(), http.StatusBadRequest)
+			return
+		}
+		res := s.model.RemoteNeedFolderFiles(id, folder)
+		sendJSON(w, res)
+		return
+	}
+
 	progress, queued, rest, total := s.model.NeedFolderFiles(folder, page, perpage)
 
 	// Convert the struct to a more loose structure, and inject the size.
diff --git a/lib/model/model.go b/lib/model/model.go
index 7f69c2056..a81166e44 100644
--- a/lib/model/model.go
+++ b/lib/model/model.go
@@ -681,6 +682,29 @@ func (m *Model) NeedFolderFiles(folder string, page, perpage int) ([]db.FileInfo
 	return progress, queued, rest, total
 }
 
+func (m *Model) RemoteNeedFolderFiles(device protocol.DeviceID, folder string) []db.FileInfoTruncated {
+	m.fmut.RLock()
+	defer m.fmut.RUnlock()
+
+	rf, ok := m.folderFiles[folder]
+	if !ok {
+		return nil
+	}
+
+	ignores := m.folderIgnores[folder]
+	var res []db.FileInfoTruncated
+	rf.WithNeedTruncated(device, func(f db.FileIntf) bool {
+		if ignores.Match(f.FileName()).IsIgnored() {
+			return true
+		}
+		ft := f.(db.FileInfoTruncated)
+		res = append(res, ft)
+		return true
+	})
+
+	return res
+}
+
 // Index is called when a new device is connected and we receive their full index.
 // Implements the protocol.Model interface.
 func (m *Model) Index(deviceID protocol.DeviceID, folder string, fs []protocol.FileInfo) {
```

**Comment by AudriusButkevicius** [comment]
It's about time you drove some feature all the way home ;)

**Comment by imsodin** [comment]
I'd like to get this done - @calmh did you do any more work on this and/or are you fine with me taking this over?

I am wondering which version would be better:
1. An "Out of Sync Folders" row with a list of folders that aren't in sync on the remote and make each folder clickable, showing the list of items that are out of sync
2. Analogously to the folders: An "Out of Sync Items" row showing the number and size of all currently out of sync items on the remote. On click it opens a list of all out of sync items ordered by folder.
3. Something completely different?

**Comment by calmh** [comment]
I haven't, and you're more than welcome to take it over. I was imagining something like your alternative two.

**Comment by generalmanager** [comment]
As far as I understand this was meant to be a "per device" option, so
whatever interface you implemement would only be presented after
clicking on the "out of sync" message in the device details. In that
case I'd think the second version to be better from a usability
perspective as this sounds closer to what the user already knows from
experience.


Personally I'd prefer this not to be a per device option, but a per
folder option really similar to the current "out of sync UI". This way
it would look exactly the same as it does now. Only after clicking on
the "out of sync files list" link in the folder details we could show a
split-screen version of the current interface with the local state on
the left and the remote state on the right. On devices which are too
narrow we could have two tabs for local and remote.

As this would be identical to what we do now, just with a second tab or
the local list on the left and the remote one on the right I'd imagine
it to be exactly the same file-based list with several devices and only
files as it is now.

This way we'd have only minimal divergence from the current workflow and
no further UI clutter inside the device details.

To me it'd be confusing if the local out of sync UI would stay
folder-based while the remote UI could only be found inside the device
details and would look different, because we would have to create a
second decision layer for the folders.

If you prefer this to be device-based I don't really grasp the upside of
doing something different than what we do now. The only argument I can
think of is that it'd be easier to see which devices are "making
trouble", maybe because they have a slower network/internet connection
than others. But then one could argue the same for the current local OOS UI.

If you'd like, I could create a mockup of what I described. But
essentially everything would be the same with either two lists or two
tabs to switch between the local and remote lists.

**Comment by AudriusButkevicius** [comment]
Having to click somewhere within some folder to check why your remote device is out of sync is a bit strange, especially when your folder is locally "Up to date"

**Comment by imsodin** [comment]
@generalmanager I don't really understand what you mean. The information about the status of the remote folder is already there on the right, this just "completes" this information by giving a means to see what files exactly are not yet in sync. This has nothing to do with the local folder state on the left.

**Comment by AudriusButkevicius** [comment]
His comment is that he'd rather see the info of what's missing per folder, as in:

For folder F, I am missing File1, Device A is missing File2, B is missing File3

Rather than:

For device A, I am missing File1 from folder F, File 2 from folder J.
For device B, I am missing File2 from folder F, File 3 from folder J.

It's essentially reconciling folders versus reconciling devices.

**Comment by generalmanager** [comment]
@imsodin I get that the information in the folder details currently displays only the local state and the info in the device tab is about the remote device not beeing in sync. 

I'm just trying to think of the most intuitive way to present both. Because the local status is folder based and the remote status is device based we'd have to "reinvent the wheel" because we need to create a second logical layer indicating the status of all folders connected to the device (which is what you proposed two different ways for). 

@AudriusButkevicius Well, the same could be said about having not just two different places to look for information on an "out of sync" status, especially because we'd also be forced to create a different logic to order by folder. Which is something new each user has to learn/adapt to. But you certainly have a point. Also showing a red "out of sync" message inside the folder if only on one of maybe 200 remote devices is out of sync would lower the urgency of the out of sync messages in the folders, because most of the time the local version would be perfectly fine. I'll get to that in my last paragraph.

So IF we went with my proposal, it would be important to make clear on first sight that only a remote device is out of sync and that locally everythin is a-ok. The most intuitive way I can think of is to show a green "out of sync" message in the folder when only local devices are affected. As soon as the local folder is out of sync, the current red "out of sync" message would be shown.

This way the users wouldn't be alarmed when only remote devices are affected, so the urgency of local OOS messages is retained. And one wouldn't have to take a second look to grasp the different ordering types (by device or by folder). Also the specific devices which are "troublemakers" are easily identifiable on the right.

What do you think?
