### ISSUE TITLE
System-dependant case-insensitivity of ignore patterns prevents deletion

### ISSUE THREAD

**Issue by nalt** [syncthing/syncthing#4374]
- A folder project/demo/.../icons with multiple files exists (on all clients)
- There is an ignore pattern: (?d)Icon?
- project/demo is deleted on a Mac client
- On a Linux client, this resulted in several errors: delete: remove project/demo/...: directory not empty

The reason was that the icons folder was not deleted on the Linux client. I assume this is because the ignore pattern applied to icons on the Mac, but not on Linux.

Adding (?i) before every ignore pattern should fix this. But since many cross-OS syncs have this problem - is this really intended?

**Comment by calmh** [comment]
You assume and think that should fix it - but did you confirm? The error just means there is a file in the way.

**Comment by nalt** [comment]
This observation was confirmed 3 times on 2 systems, and in a minimal test case. Feel free to ignore my assumptions.

**Comment by calmh** [comment]
You're not showing the test case so I can only guess what you're seeing. Are you saying that the ignore pattern `(?d)Icon?` doesn't match a file called that on Linux?

**Comment by nalt** [comment]
I did the test case as outlined in the initial post with the following file structure, created both on the Mac and the Linux client:

```
mkdir demo
mkdir demo/d1
mkdir demo/d2
mkdir demo/d2/icons/
cd demo/d2/icons/
touch 1.png 2.png 3.png
```

According to the docs, (?d)Icon? matches icons on Mac, but not on Linux, right?

**Comment by calmh** [comment]
Correct.

The pattern `Icon?` is mentioned specifically because custom folder icons on Mac are stored in a file called `Icon\r` (with a carriage return at the end).

I'm not clear on what you think is the problem here, sorry.

**Comment by imsodin** [comment]
Isn't this just https://github.com/syncthing/syncthing/issues/2739?

**Comment by nalt** [comment]
@calmh, you could really be a bit more constructive here. Maybe everything works according to the definition, but the result is a far from a good user experience.

The problem: Folder deletion is not propagated where it can be expected to be. Furthermore, but this is technically another issue, the aggressive retrying behavior of syncthing when such errors happen.

Now, how can user experience be improved? With a clear hint that (?d) is likely to fail on Linux-Mac-Windows syncs and should not be used. With a new prefix (?D) that implies (?i) to be used in such cases. With a hint in the UI which folder has to be deleted manually. Or, with #2739, "maybe". ...

**Comment by calmh** [comment]
I'm not being deliberately obtuse here, I generally wasn't sure what you considered the issue. I'll agree with you that it's not obvious what the issue is when a directory can't be removed because there's something in it. Mismatching ignore patterns can make that more confusing.

At the moment there are two relevant ignore prefixes:

- `(?d)` to indicate that an ignored item can be deleted if necessary.
- `(?i)` to indicate that an ignore pattern is case insensitive.

Case insensitivity is the default on systems that are traditionally case insensitive (Windows, and Mac) and *not* the default on systems that are traditionally case sensitive (all other unixes). This would change if we moved to case insensitivity everywhere, but we haven't done so.

The prefixes can be combined: you probably want `(?d)(?i)icons` on Linux if you want a case insensitive ignore of all case variants of `icons`. You can have the same pattern Mac-side if you like, the `(?i)` is harmless.

All in all this is as designed at the moment. There are many problems that can happen when syncing files between systems with different case sensitivity, some of them serious. This isn't really one of them in my opinion.
