### ISSUE TITLE
Implement delta-only index exchange at connect

### ISSUE THREAD

**Issue by sf** [syncthing/syncthing#438]
As stated in BEPv1, every connection has to start with an index exchange.
Every index exchange contains a BlockInfo structure for (almost) every 128KiB in the repository. A BlockInfo structure has a size of (currently) 40Bytes. This results in an initial transfer of data according to ~1/3276 of the repository size. That doesn't sound like a lot, but repositories can and will be quite large.

Isn't this a huge problem for the scalability of BEP? A repository with 4GiB of data in it will result in the transfer of roughly *a Megabyte* of information at the beginning of every connection. In *both directions*. Depending on the connection speed, this may take quite a bit of time (e.g., 5 seconds on ADSL2 at full speed).

One of the bigger problems of this is, that people don't expect to have a scalability issue with the size of their content. "It's only a few files ... why does it struggle with that?"

Of course, this isn't easily changeable in v1. But, perhaps for BEPv2, it would be necessary to look into tree hashes (e.g., Tiger Tree Hash as used in Bittorrent). That would reduce the overhead to a constant hash per file and not per block. Telling people that it takes a while because they have millions of files is easier than telling them, that it takes so long because they have one large file in their repository.

**Comment by AudriusButkevicius** [comment]
Why is this not marked as protocol?

**Comment by calmh** [comment]
It's already implemented in the protocol, just not in the code. :)

**Comment by AudriusButkevicius** [comment]
Yeah, but this would break protocol compatibility.

**Comment by calmh** [comment]
No, not really. The intention is that if you send a non-zero `MaxLocalVersion` in the handshake, you get a delta update. If you send zero `MaxLocalVersion` you get the full index (or delta since the beginning of time, depending on viewpoint). We currently send zero and expect the full index, which is what any future version implementing this would respond, so that's backwards compatible.

**Comment by generalmanager** [comment]
If this doesn't break compatibility, is there anything apart from the complexity of the implenentation why this is not tagged v1.0? 
Apart from the prohibitively high index exchange traffic for use on mobile (even with conservative amounts of data), I think also average to power users would profit immensely from a low-bandwidth index exchange.
Having 50~200GB per node is not too uncommon (seems to be supported by https://data.syncthing.net), because many people use it to have a synchronized backup of all their pictures and videos. 

But that means 12.5 to 50MB on each connect/disconnect. DSL lines are still disconnected daily, which often means several devices uploading dozens of megabytes, blocking the upstream for several minutes to half an hour.

**Comment by AudriusButkevicius** [comment]
I don't think there is much complexity involved either, @calmh has already done it I think.
It's the fear of it not working properly :dancer:

**Comment by generalmanager** [comment]
I see. Maybe we should have a beta release for fearless testers at some point, with it's own github entry. This would mean even better stability for the average user and @calmh and you could share some of the testing workload with the community?

**Comment by chucic** [comment]
generalmanager: I like this idea, I would be happy to help beta test new features and upgrades.

**Comment by zukoo** [comment]
@generalmanager Looking forward for this too, I'll be happy to help test it.

**Comment by fbreve** [comment]
Me too.

**Comment by fti7** [comment]
+1 :-) i think this is very important for Mobile Users (Or <2Mbit DSL Users like me...)

**Comment by DavidOliver** [comment]
I'd be happy to test this, too. I'm hoping to be syncing ~864 GiB, and the index exchange which happens on each connection seems to be about 235MB.

**Comment by jangrewe** [comment]
+1

**Comment by calmh** [comment]
https://github.com/syncthing/syncthing/pull/2020 is the place to be for beta testing.

Not complete yet, there are corner cases not covered yet (actually sending the full index if the database has been reset on the sending side and things like that). Clicking "Show all checks" to the right of "All checks have passed" at the bottom, and then "Details" next to `pr-build` gets you to where there is a download with the preview. It needs to be running on both sides to be effective, and the first time they connect is still a full index exchange. Don't run it unless it actually *says* "All checks passed".

Rolling back to the normal release gets you the old behavior in case of problems, no harm no foul.

**Comment by generalmanager** [comment]
q

**Comment by fragtion** [comment]
Hi All. Excuse my potential ignorance as I am fairly new to github and don't quite understand how it all works. Just wanted to find out if there is any chance on a rough ETA regarding the implementation of the new delta index syncing mechanism into the release/master build, or at least the priority being given to this right now? While I can appreciate the extra file integrity safety and peace-of-mind when re-transferring all file indexes each time the peer connections are re-established, this method is unfortunately proving to be a impractical for our setup running over ADSL. We have about 700GB of files being synced, which causes our line to be congested for a few minutes each time this happens. I was able to alleviate the impact a bit by using traffic shaping on the port, but have ultimately resorted to moving back to BTSync until the delta-indexing functionality can be incorportated into Syncthing. It seems BTSync can reliably restore a consistent synchronized folder state on re-connection with very little bandwidth requirements, so the intuitive assumption is that there should be no reason why Syncthing can't manage this too

**Comment by calmh** [comment]
> rough ETA regarding the implementation of the proposed delta index syncing mechanism into the release/master build, or at least the priority being given to this right now?

No ETA, sorry. It's one of multiple parallell things I'm working on. I ran into one annoying case that requires a bit more extensive rewiring than I had expected...

**Comment by fragtion** [comment]
Thanks for the relpy calmh! Ah, ok  - well it's definitely good to hear that this is being actively considered and worked on at least. Hopefully someone can offer some assistance if you're so busy juggling between the other aspects of the app... Syncthing is just getting better by the day, and has an awesome future ahead especially once these smaller quirks can be elegantly ironed out. I had great hopes for BTsync and it was so close to being perfect... I don't like comparing the two and I know their intended applications are somewhat different after all - but Syncthing already has most of what it takes to be the go-to "swiss army knife" or "jack of all trades" to finally fill that 'gap in the market' for a perfect, cross-platform, reliable and efficient sync tool. Good things lie ahead I hope! Thanks & Good luck :D

**Comment by pjorquera** [comment]
Do you plan to include this feature in the next mayor version of Syncthing (i.e. version 0.12.+)

Currently we are using BTSync because we need to synchronize multimedia contents in near hundred of devices that are using 3G / 4G connections (multimedia servers located in bus vehicles). Content are roughly 200 GB size for each bus and changes rarely during a month so each time some device losses connections (very frequently, typically once every ten minutes), indexes must be transferred spending our 3G / 4G data plan.

We'd love to use Syncthing (instead BTSync) if this feature were implemented in some version of the software.

**Comment by generalmanager** [comment]
@calmh Just wanted to note that "Implement delta indexes" (#2020) is tagged 1.0 and this is tagged planned without a version. Could you clear up the intended milestone?
