### ISSUE TITLE
Syncing conflits on one-way sync.

### ISSUE THREAD

**Issue by WestFlame** [syncthing/syncthing#4399]
I'm ocassionally experiencing sync conflicts even though the files are changing only on one mashine.

I have this setup:
`Ubuntu desktop <---> Linux server <---> Windows desktop`

There is git repository which changes only on Ubuntu. But sometimes, the sync conflict files appear. How is that possible? It occured several times, each time with newest stable Syncthing version.

Ubuntu and Windows machines are never running at same time. Also I think that the conflicts appear only after I do update on the git repository. The notable thing is that there are many other files and folders synchronized both ways. But afaik there was no sync conflict in them.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
