### ISSUE TITLE
huge ram memory usage

### ISSUE THREAD

**Issue by MasterDimmy** [syncthing/syncthing#4403]
syncthing v0.14.38

i have index-v0.14.0.db size 712MB.
8 syncthed folders, total size of 512 GB little files (1KB - 50MB each).
Local state, files:  615885 , folders:         39914, total size :  ~464 GiB

ram: 16GB, syncthing eats 14GB of memory in my PC during syncronization, so it becomes system crash by out of memory.

**How can i set up RAM memory usage limit in syncthing?** 

You can do sync folder by folder step by step, controlling memory usage, when it less then limit, then sync other files\folders, when not - stay in wait, when the memory frees by other sync goroutines.

But do not eat all available memory please.

![11](https://user-images.githubusercontent.com/10881942/30981859-53a9b130-a48e-11e7-8e9c-17b6fe7ace98.png)

**Comment by calmh** [comment]
It needs to keep the list of changed files in RAM in order to do ordering between them; as such this is expected for the initial sync or when very many files have changed. It is not expected once in a steady state, which I assume is what you're then showing in the "backup" part of the screenshot (not sure)
