### ISSUE TITLE
Reduce Size of Syncthing Release binaries

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#4429]
I just came across this blog post about reducing Golang binary size, and gave it a try: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Turns out that simply compiling with `-ldflags="-s -w"` reduces the binary size by ~8%. From what I understand, this only removes information needed  for debuggers, which doesn't belong in a release build anyway. 

It is also possible to compress the binary with the [upx tool](https://linux.die.net/man/1/upx). With the default setting of -8, this saves an additional ~28% compared to the ldflags version. This also results in some slowdown on startup, so a lower compression setting would probably be better.

I've tested the size with Android builds because I had them around. I haven't done any performance testing, other than making sure it still runs.

```
-rwxr-xr-x  1 felix felix 16307636 Oct 17 12:42  libsyncthing-original.so
-rwxr-xr-x  1 felix felix 14970576 Oct 17 12:41  libsyncthing-ldflags.so
-rwxr-xr-x  1 felix felix 10823436 Oct 17 12:41  libsyncthing-ldflags-upx.so
```
### Version Information

Syncthing Version: master (cdbb32d0)
OS Version: latest Manjaro

**Comment by calmh** [comment]
We already build with -w, could potentially add -s depending on what it actually removes (we need profiling symbols and such). I don’t think it’s worth the complexity of adding upx.

On 17 Oct 2017, at 05:51, Felix Ableitner <notifications@github.com<mailto:notifications@github.com>> wrote:


I just came across this blog post about reducing Golang binary size, and gave it a try: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Turns out that simply compiling with -ldflags="-s -w" reduces the binary size by ~8%. From what I understand, this only removes information needed for debuggers, which doesn't belong in a release build anyway.

It is also possible to compress the binary with the upx tool<https://linux.die.net/man/1/upx>. With the default setting of -8, this saves an additional ~28% compared to the ldflags version. This also results in some slowdown on startup, so a lower compression setting would probably be better.

I've tested the size with Android builds because I had them around. I haven't done any performance testing, other than making sure it still runs.

-rwxr-xr-x  1 felix felix 16307636 Oct 17 12:42  libsyncthing-original.so
-rwxr-xr-x  1 felix felix 14970576 Oct 17 12:41  libsyncthing-ldflags.so
-rwxr-xr-x  1 felix felix 10823436 Oct 17 12:41  libsyncthing-ldflags-upx.so


Version Information

Syncthing Version: master (cdbb32d<https://github.com/syncthing/syncthing/commit/cdbb32d0f043c56c6787df3f036feabc8891fd3c>)
OS Version: latest Manjaro

**Comment by Nutomic** [comment]
Oh right I missed the -w flag. But that means that setting -s will still save another 8%. Agreed about upx, it was just an idea.

**Comment by AudriusButkevicius** [comment]
-s strips symbols which makes panics unreadable AFAIK

**Comment by calmh** [comment]
I've toyed with upx myself earlier, but in general it doesn't matter as we distribute in compressed archives and the extra megabyte or so after installation is a non-issue on most systems (I have applications installed that are literally gigabytes in size). If it matters more on mobile you could do the compression in that build process, maybe obviating the need for -s.

**Comment by Nutomic** [comment]
@AudriusButkevicius The blog post says that stack traces are still readable, but I haven't confirmed that.

@calmh The decompression is pretty slow on my Nexus 5, so if you tried it already, it's probably not worth it. And downloads are compressed on Android, too.

**Comment by spectras** [comment]
FWIW, the policy of many Linux distributions is to not only compile with all symbols, but keep debugging information as well. The rationale is they only consume disk space, which is really cheap, yet provide useful information to investigates bugs. (For very large binaries, they are sometimes distributed as a side file that can be installed separately).

On the other hand, what might be actually worth the effort, would be to build dynamically-linked packages. Not only that makes smaller binaries, but it uses less memory as well, since shared libraries are only loaded once for all programs using them.
Now, I don't know the Go ecosystem very well, if that binary would actually just link to some Go runtime that's otherwise mostly unused, the effort wouldn't be that worth.
