### ISSUE TITLE
Folders with trailing spaces causing trouble?

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#4472]
Hello,
I just noticed that one of the folders on my server reports a failed item:
" The following items could not be synchronized. They are retried automatically and will be synced when the error is resolved. " 
/Folder directory not empty

That folder exists on my server and has a subfolder with a trailing space (and a dot):

[user@server Folder]$ ls -l
insgesamt 0
drwxr-xr-x 1 user user 24  5. Okt 18:44 'Wichertstr. '

So one of my users created that folder on his machine and it has been synced to the server - and is now causing trouble.

Let me know if you need more information.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
