### ISSUE TITLE
unknown device(v0.14.39)

### ISSUE THREAD

**Issue by gouez** [syncthing/syncthing#4473]
Error occurred when connection to remote device.  
**what happened?**
Connection from xxxxxxxxxxxxx at xxxxxx (tcp-server) rejected: unknown device

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
