### ISSUE TITLE
resolved external address

### ISSUE THREAD

**Issue by signalguest** [syncthing/syncthing#4495]
```
INFO: kcp://0.0.0.0:22020 detected NAT type: Port restricted NAT
INFO: kcp://0.0.0.0:22020 resolved external address kcp://x.x.x.x:22020 (via stun.x.com)
```
why is that with v0.14.40?
i use syncthing only in lan. i don't have anything related to global enabled
it even resolve again every time my tablet wakeup (and it does a lot)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
