### ISSUE TITLE
The invalid global stuff results in a full index exchange

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4524]
Only looking at the debug logging when testing is a bad idea, you miss the obvious:

```
Nov 17 17:58:36 homeserver syncthing[16593]: [BPDFD] INFO: Device CBBHGDL- folder "Dokumente" (Dokumente) is delta index compatible, but seems out of sync with reality
```

That happened on all folders after updating to the new RC.

<strike>The problem is pretty obvious in hindsight: I was overeager when doing the database transition: I should only have modified entries from the local device and leave remote devices alone.

PR incoming.</strike>

No, not that obvious: I don't yet know why the sequence gets updated.

**Comment by calmh** [comment]
File the pr by all means, but since this is a one time thing (and I’ve had a few beers) I don’t really care.

On 17 Nov 2017, at 18:22, Simon Frei <notifications@github.com<mailto:notifications@github.com>> wrote:


Only looking at the debug logging when testing is a bad idea, you miss the obvious:

Nov 17 17:58:36 homeserver syncthing[16593]: [BPDFD] INFO: Device CBBHGDL- folder "Dokumente" (Dokumente) is delta index compatible, but seems out of sync with reality


That happened on all folders after updating to the new RC.

The problem is pretty obvious in hindsight: I was overeager when doing the database transition: I should only have modified entries from the local device and leave remote devices alone.

PR incoming.

**Comment by imsodin** [comment]
@calmh No worries, enjoy some more beers - in the edit I changed the PR part: No idea what causes this - which makes it worse I guess, but also means there is no PR right now until its clear what is going on.

**Comment by calmh** [comment]
FWIW this message hasn't been logged for me, on either the old or new side, as far as I can tell.

**Comment by imsodin** [comment]
Thanks for the heads up. Together with nobody else complaining, me not understanding how my code should ever cause it and having switched between versions (I thought I was careful this time) this is probably a false positive. Maybe there should also be an "invalid" label so you can sort issues like this out too.
