### ISSUE TITLE
Remove Devices

### ISSUE THREAD

**Issue by Photographix** [syncthing/syncthing#4530]
Hi, I have been using syncthing since version **0.12** and have added and removed many PCs over the years. Currently there are 17 computers on three continents. Under the master / introducer you can see only the current PCs. But among the clients can see all the other PCs that are no longer available. Is there a possibility to delete old entries from v0.12 and synchronize them with the master / introducer list? As far as I know, version v0.12 did not have this functionality yet. According to the documentation the devices should be removed if they are no longer present on the master / introducer. All PCs are connected at least once a week and reconnect. They all share the same folders.
### Version Information

Syncthing Version: v0.14.41-rc.3
OS Version: Windows 10 / OSX 10.12 / Android 6

**Comment by calmh** [comment]
Automatic removal works for devices added by the introducer feature after removal was implemented. Older entries will not be removed automatically; you will need to remove them manually.

The reason is that the removal is based on recording the fact that the device was added by an introducer. For older entries we don't have that, so we don't know who added them. Hence we cannot remove them automatically.
