### ISSUE TITLE
UI for filesystem watcher

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4552]
Now that we have the watcher code in place, let’s add the UI. There’s a couple of different parts to that:

- enabling it to begin with
- showing its current status
- showing a reasonable error when it doesn’t work

The enabling part is fairly simple. I think we’ve already mostly agreed on a checkbox, and when ticked it will also automatically increase the rescan interval to something high. This happens in the config UI, so the user can change the interval if they want, and in the code it’s still the same interval mechanism as usual. When the watcher is disabled we suggest the usual default interval of 60 seconds. One thing to note here might be a documentation link or comment about why rescans may still be necessary. As far as I know, permission only changes are not picked up by the watcher? Mtime only changes? May need some investigation.

The folder status thing on the left should have a row for the fs watcher status. For most things we don’t show a row unless the value diverges from the default. Nonetheless I think the fs watcher row should always be present and probably replace the rescan interval row. Having it there with “Watcher: On (rescans at 7200s)” or whatever even in the default case gives peace of mind that it’s actually running.  

When it’s enabled but not running we should show an error indication similar to when a folder stopped. (XXX: and change the scan interval...? Not a UI question)

If there are cases when it’s “half running” we need to figure that out. For example if it’s running fine and I copy in a directory into the folder and now it exceeds the system max number of open watch frobbits. 

We should not, at this time, automatically enable watches for existing folders. We may want to have it on by default for newly created folders?

**Comment by uok** [comment]
Thanks for working on this feature!
My suggestion is to have setting to enable either "interval" OR "watcher" to not confuse the user. In the UI it could be displayed as "rescan interval: 60s" vs. "rescan interval: automatic". I don't like the idea of enabling it for existing folders, but for new folders it makes sense (maybe take it out of advanced settings? not everybody has a bullish cpu or changes files that often)

**Comment by imsodin** [comment]
The one thing that isn't addressed: What will we call it? We kind of delayed this before. Given "watch" is already in the config names and it is actually descriptive (it watches out for changed files), I think we should keep that. In the UI we could add/focus on "change" instead of "FS" as it is probably easier to grasp what it does to the user.

Permissions are picked up by all platforms except mac. It may be possible to do there too, but the native event names aren't conclusive and I didn't dive deeper into it. I don't know about mtime only changes. In any case having no rescan intervals at all isn't a good idea in general, as watcher relies on various different backends which may have deficiencies (and for some of those, I heard that they do).

A fallback seems like a good idea. It might be problematic for cases where the fallback (e.g. 60s) is way too short, e.g. on a low-resourced device where this could clog up the machine. Maybe just a warning on the folder suffices.

If it is possible that it is "half-running", we have no way to detect it. Watches are a fire-and-forget type of service.

I think it is a good idea to somehow combine the status indication for interval scanning and watching, as both are about the same thing. It could be renamed to just "Scanning" with possible values like "interval 60s", "watching & interval 60min", just "watching" when interval is 0.

If we do the automatic switching of rescan interval when checking the watcher checkbox, then the checkbox must be above the rescan interval. Otherwise it is very annoying if the interval is reset after you set the interval to the desired value and then toggle the watcher.

Another nice thing to have in the UI: Indicated when the watcher isn't supported. If javascript can detect the underlying OS, this can be hardcoded there, otherwise it could be new REST endpoint which gives this information (by setting a random watch and checking for the unsupported error).

**Comment by AudriusButkevicius** [comment]
Is there am OS where it's not supported? Only mac requires cgo, and we have a builder for that.

The rescan interval thing can be above the checkbox and we just do UI tricks to set the interval to something else and disable the input.

I think half running calmh means out of watch handles bla bla. We should be able to detect that.

**Comment by calmh** [comment]
Solaris, and maybe the exotic BSDs I'm not sure. An yeah.

**Comment by basnijholt** [comment]
> We may want to have it on by default for newly created folders?

This makes perfect sense!

Is it already possible to enable this? We are running Docker images with Syncthing and I just removed inotify from the image. I would like to set "FS watcher" to enabled by default, such that I won't have to tell all my colleagues how they have to do it themselves.

**Comment by martinrotter** [comment]
How does this come to place with Syncthing GTK "file watcher" feature (I mean the checkbox in File -> Settings -> Folders). Is this just a new GUI to same feature or Syncthing GTK has its own "watcher" backend functionality?

**Comment by calmh** [comment]
Weird edge case; increase the scan interval again to taste.
