### ISSUE TITLE
adding option to stop syncing when running on battery or trying to save power

### ISSUE THREAD

**Issue by hujun-open** [syncthing/syncthing#4556]
I'd like to see an option that automatically stop syncing when system runs in a particular power saving mode (e.g. laptop running on battery), just to save power since syncthing is quite power hungry;
This should apply to all supported OS;
and automatically resume syncing when the laptop is plugged in 

right now, I have to manually stop/resume every time, bit annoying

**Comment by calmh** [comment]
This is very platform specific and somewhat niche. I think it's out of scope for what should be in Syncthing proper, although an extension could do the thing via API. Pausing folders and devices would have the same effect as stopping and be potentially quicker to start up again.

**Comment by AudriusButkevicius** [comment]
Agree with above.

**Comment by Ferroin** [comment]
For those who have interest in this on Linux, you can do it by hooking into UPower or acpid and running a custom script to poke the Syncthing API when the AC adapter state changes.

**Comment by hujun-open** [comment]
Thanks Ferroin for the tip; unfortunately I am using a windows laptop, which is more difficult, with a few quick search, it seems I might be able to use [Service Trigger Events](https://msdn.microsoft.com/en-us/library/windows/desktop/dd405513(v=vs.85).aspx)
For me this is about user friendly,  one key reason I uses syncthing is simple setup, intuitive UI ..etc; easy for mind, if syncthing could do this directly, it would be very nice;

**Comment by calmh** [comment]
You might want to check if this is a valid request on SyncTrayzor as well. That's where I would prefer Windows specific things to go. @canton7 may disagree. :)

**Comment by canton7** [comment]
To be honest, pausing devices as a way of responding to things like battery or a metered connection is a PITA, because the user can pause/unpause devices at will as well, so you end up having to keep track of whether the user's manually paused/unpaused something, and whether that overrides whether you told the device to pause or not, etc, and this needs to be persisted over restarts.

Pausing devices based on a metered connection turned out to be far more effort than it was worth, so it's very unlikely I'll take on pausing based on battery as well 😄
