### ISSUE TITLE
High CPU with 0.14.41 on Windows 10 64bit with no current activity

### ISSUE THREAD

**Issue by ikarstein** [syncthing/syncthing#4609]
I have several devices that sync since some days with SyncThing 0.14.41.

I use synctrazor on clients and I have a central server for backups that I use as "Introducer" device.

I have >20 shared folders with > 200GB and > 100k files (count). 

Not all folders are synced between all devices.

On 1 device I have constantly very high CPU usage, also if there is only 100mb memory used an no current disk activity. (Seen in Resource Monitor of Windows).

Any ideas?

Regards 
Ingo

### Version Information

Syncthing Version: v0.14.41
OS Version: Windows 10 64bit

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
