### ISSUE TITLE
ST randomly disconnects and stays that way for good

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4626]
For some reason one of my machines decided to refuse being connected to anything.
The disconnect started around 12:55 (nothing special occurred at this time, no one touched the machine for couple of hours) and continued this way for a day, until ST was manually restarted. Here are some logs:

Normal ST log: [st_log](https://gist.github.com/anonymous/4ef10cef243bb900760c4360cf0a5c11)
SyncTrayzor log at the time of disconnect: [synctray_log](https://gist.github.com/anonymous/ccaba83b6baf12cf7e8f19d8f6dca73f)

Then I enabled few connection-related tracings and let it run for a while: [st_log_sttrace](https://gist.github.com/anonymous/5eb2c20a90e5b64be6e1856e10d5585d)
Seems like it does discover clients and addresses, just doesn't bother to connect.

So far, it's a one-off, but maybe something useful can be spotted in logs.

### Version Information

Syncthing Version: v.0.14.42 (Running under SyncTrayzor v.1.1.18)
OS Version: Windows 10x64

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
