### ISSUE TITLE
Set background priority / niceness

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4628]
Per #3212 it is desirable to set the process priority down by default. I think we should do that as well, with an off switch.

- New config option: `options.setLowPriority` which defaults to `true`
- When this option is true, at startup, we:
  - On Unixes, set our niceness to 9.
  - On Windows, set priority class PROCESS_MODE_BACKGROUND_BEGIN

It would be nice to also set I/O priority on Linux, but honestly the `ioprio_set` API is annoying to use from Go and I'm not going there at this point.

@canton7 any concerns here for you? You wanted to know what the outcome became, and you already set something by default?

We might want to take care to not *raise* our priority as part of this, though, by checking if the original priority is default or not. But on the other hand I think that on at least Unixes it's not possible for the process to raise its own priority so this comes automatically.

**Comment by AudriusButkevicius** [comment]
ioprio_set should be easy on unix, as it's just syscall.Syscall6 or whatever.

**Comment by canton7** [comment]
Yeah, I have a setting where the user can set the priority of the Syncthing process, so there will be a race where we both try and change the priority.

The best thing for me to do is probably remove that bit of functionality when you release this, which is fine. People who use it can migrate their config over themselves...

Although, I do allow people to raise the priority of the Syncthing process, and I'm reasonably sure that's because someone asked for it. So I'm not sure that avoiding doing this is necessarily the right thing to do.

**Comment by AudriusButkevicius** [comment]
```
syscall.Syscall(syscall.SYS_IOPRIO_SET, ....)
```

**Comment by calmh** [comment]
@AudriusButkevicius 

> The ioprio argument given to ioprio_set() is a bit mask that specifies both the scheduling class and the priority to be assigned to the target process(es). The following macros are used for assembling and dissecting ioprio values:
>
> `IOPRIO_PRIO_VALUE(class, data)`
> Given a scheduling class and priority (data), this macro combines the two values to produce an ioprio value, which is returned as the result of the macro.
> `IOPRIO_PRIO_CLASS(mask)`
> Given mask (an ioprio value), this macro returns its I/O class component, that is, one of the values IOPRIO_CLASS_RT, IOPRIO_CLASS_BE, or IOPRIO_CLASS_IDLE.
> `IOPRIO_PRIO_DATA(mask)`
> Given mask (an ioprio value), this macro returns its priority (data) component.

We'd need to figure out what those macros do and how that bitmask works, replicate it, and hope it never changes...

@canton7 

Cool. The "avoid to raise" thing is just that if someone already set nice level 19 we should not raise it back to 9 due to `setLowPriority=true`, for example.

**Comment by AudriusButkevicius** [comment]
```
/*
 * Gives us 8 prio classes with 13-bits of data for each class
 */
#define IOPRIO_CLASS_SHIFT	(13)
#define IOPRIO_PRIO_MASK	((1UL << IOPRIO_CLASS_SHIFT) - 1)

#define IOPRIO_PRIO_CLASS(mask)	((mask) >> IOPRIO_CLASS_SHIFT)
#define IOPRIO_PRIO_DATA(mask)	((mask) & IOPRIO_PRIO_MASK)
#define IOPRIO_PRIO_VALUE(class, data)	(((class) << IOPRIO_CLASS_SHIFT) | data)

#define ioprio_valid(mask)	(IOPRIO_PRIO_CLASS((mask)) != IOPRIO_CLASS_NONE)

/*
 * These are the io priority groups as implemented by CFQ. RT is the realtime
 * class, it always gets premium service. BE is the best-effort scheduling
 * class, the default for any process. IDLE is the idle scheduling class, it
 * is only served when no one else is using the disk.
 */
enum {
	IOPRIO_CLASS_NONE,
	IOPRIO_CLASS_RT,
	IOPRIO_CLASS_BE,
	IOPRIO_CLASS_IDLE,
};

/*
 * 8 best effort priority levels are supported
 */
#define IOPRIO_BE_NR	(8)

enum {
	IOPRIO_WHO_PROCESS = 1,
	IOPRIO_WHO_PGRP,
	IOPRIO_WHO_USER,
};
```

**Comment by calmh** [comment]
Is this the same on ARM/MIPS/PPC 32/64 and BE/LE? If it is I think we can just set `2 << 13 | 5` and be done with it.

**Comment by AudriusButkevicius** [comment]
Yes, as it's from a generic .h file with no ifdefs, so it should be.
The syscall number does differ between arches, but that's autogenerated in Go stdlib for each arch anyway, so you shouldn't need to be concerned.

I'd be a good citizen and make a {syncthing/calmh}/ioprio package (or osutil I guess) with the necessary utility functions that match the linux man page.

**Comment by calmh** [comment]
Awesome

**Comment by Ferroin** [comment]
Just a few comments on this:

1. The classes you listed are how Linux implements things, I'm not sure that it's the same on other UNIX systems, and it might be good to double check for at least FreeBSD (the other BSD's should be similar enough to FreeBSD to not matter).
2. IO class is by default set by the process scheduling class on pretty much all UNIX systems in existence.  For Linux for example, if you set a process's nice value to 20, it will automatically get the lowest best-effort scheduling class for I/O, set it to -19 and it will automatically get the highest best-effort class, set it to real-time scheduling, it will get a RT I/O scheduling class of appropriate proportionate value, and set to the idle CPU scheduling class and it will get the idle I/O scheduling class.
3. The 'idle' scheduling classes on Linux aren't actual idle schedulers, they will still preempt other things on occasion, they just get the lowest possible scheduling priority (which is good on the CPU side, but probably bad on the I/O side for most people as it will increase the time it takes to actually sync things).
4. Only some schedulers on Linux actually support I/O priorities handled this way.  Some don't support priorities at all, others only support them through control groups.  I would be very careful about how this change of priority is documented, as otherwise you will get people complaining about it having no impact on anything on distros that use such schedulers by default (which is most big distros right now actually).

**Comment by calmh** [comment]
My obvious approach didn't work because the available APIs are thread based and we don't control threading. I suspect another possibly valid approach would be to do it in the monitor process as part of launching the real process. Obvious drawbacks with that approach though.

**Comment by AudriusButkevicius** [comment]
I thought there were flags to apply it per thread or per process group, in which case all threads get marked.

**Comment by calmh** [comment]
If so I didn't find them.

**Comment by AudriusButkevicius** [comment]
setpriority syscall

**Comment by calmh** [comment]
Right, that actually does work for Linux, which I didn't think it would. ("Process" is supposed to cover it, but Linux isn't POSIX compliant.) It's still not the case for Windows though, which is arguably where it's more needed.

**Comment by AudriusButkevicius** [comment]
Whats the windows issue?

**Comment by AudriusButkevicius** [comment]
Windows has two calls, one per process and one for threads. End result is base value for process + value for the thread for each thread. We just need to drop the priority for the process and that's it.

**Comment by calmh** [comment]
Downside of the process group approach is that it's a pretty large sledgehammer. For example Syncthing-GTK that launched us will get niced as well unless it takes care to create a new process group for us when launching.

Windows looks like I misunderstood SetPriorityClass vs SetThreadPriority. I'm not sure if we should aim for BELOW_NORMAL_PRIORITY_CLASS or PROCESS_MODE_BACKGROUND_BEGIN (and never _END) though.

**Comment by AudriusButkevicius** [comment]
No, we don't need to do it for group, we can do it for our own pid. Or to be honest, who cares if gtk runs on lower priority? We should probably go for below normal priority or make it adjustable.

**Comment by Ferroin** [comment]
Adjustable (or at the very least a simple boolean toggle to turn off the priority reduction code) would be greatly preferred.  Having an easy way for regular users to simply keep Syncthing out of their way is nice, but I for one would like to have the custom priority settings I run Syncthing under honored (at least on Linux systems).

**Comment by calmh** [comment]
In Linux, `syscall.Setpriority(syscall.PRIO_PGRP, 0, 9)` where `0` is the "self" process sets all our threads and every other process in the same process group to niceness 9. This should mean even for example Syncthing-GTK unless they do the process group dance. I don't *think* it behaves differently if given our PID instead of zero, it should be the same.

`syscall.Setpriority(syscall.PRIO_PROCESS, 0, 9)` *should* set niceness on all the threads in our process, but doesn't.

**Comment by AudriusButkevicius** [comment]
Can you verify that specifying our pid (or -ourpid in case of group) doesn't do what you expec? I think setting it for the whole group is still ok/better than nothing. We could create a new group in the monitor process, and hope that gtk does that (or is jot affected by niceness).

**Comment by calmh** [comment]
`syscall.Setpriority(syscall.PRIO_PGRP, os.Getpid(), 9)` does nothing

`syscall.Setpriority(syscall.PRIO_PGRP, -os.Getpid(), 9)` does nothing

`syscall.Setpriority(syscall.PRIO_PROCESS, os.Getpid(), 9)` sets the niceness on one thread

`syscall.Setpgid(0, 0); syscall.Setpriority(syscall.PRIO_PGRP, 0, 9)` appears to do exactly what we want

**Comment by AudriusButkevicius** [comment]
So, we should make a small package that deals with this pain (or atleast osutil), so that other Go users could use it, given we've gone through the pain of working it out.

 Also probably sync.Once that pgrp.

**Comment by calmh** [comment]
It's in osutil, the amount of code is minimal, more in comments :)
