### ISSUE TITLE
The number of "Out of Sync Items" is growing even when they are unchanged files

### ISSUE THREAD

**Issue by jdevora** [syncthing/syncthing#4651]
Since a few weeks ago my local machine is showing me the message 

`The following folder  has faulty file transfers: Stuff.  Please, check the GUI or the console for clues `

I see the following counts when I go into the folder's details:
![imagen](https://user-images.githubusercontent.com/10220619/34635286-545619a8-f285-11e7-8a6c-4885e26c25d4.png)

And the console is full of errors of the type 
`INFO: Puller (folder "Stuff" (fm9jx-v5h4r), file "Subversion\\Project\\\\trunk\\SECTOR\\.idea\\compiler.xml"): finisher: file modified but not rescanned; will try again later`

If I check the timestamp of those files they are months old but they have a "companion file" 
 `~syncthing~compiler.xml.tmp`  that has been modified a few seconds before.

I don't see any other errors.

Syncthing Version: v0.14.43-rc.1
OS Version: Windows 19

Any idea what is happening?
Is there a work around for this?
What extra information could I provide?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
