### ISSUE TITLE
Memory and CPU usage is prohibitively high

### ISSUE THREAD

**Issue by pedrocr** [syncthing/syncthing#468]
I've been testing syncthing across 3 machines, a laptop with 8GB of RAM and two NAS-style servers with 1GB and 2GB of RAM. My repositories have the following sizes:
- 19 items, 536 KiB
- 83471 items, 16.2 GiB
- 181482 items, 387 GiB

To sync these three repositories syncthing 0.9.0 uses a bit over 700MB of RAM and while syncing continuously pegs the CPU at 150% on all nodes.

While the CPU usage I could manage during the initial sync the memory usage is simply too high. A typical NAS server like the two I have holds >4TB of storage. At the current level of usage that would require ~8GB of memory just for syncthing.

Without looking at the code I assume an index is being kept in memory for all the repository contents. 700MB is 2.6kb per item on disk, which seems way too high. The index should only really need to store filename, parent, permissions, size and timestamp. On average (depends on filename sizes) that should only be 50-60 bytes per item which would only be 13MB. Moving that index to disk would also make a lot more sense. 

I assume the CPU usage is hashing lots of files. There I assume using librsync might be a better option.

**Comment by ropeladder** [comment]
Syncthing is baking my CPU on my new quad core i7 Windows 8.1 laptop, with 400-600% load any time everything is not fully synced. I just made a .pprof file with the STCPUPROFILE command. Does anyone want it?

**Comment by AudriusButkevicius** [comment]
Well, it will be hashing that's burning your cpu, so the pprof won't say much.

**Comment by ropeladder** [comment]
So it's normal that it's using so much CPU? For hours on end?

**Comment by AudriusButkevicius** [comment]
Depends on which state it's in.
If it's scanning for the first time yes, as it has to hash all the files.
Given the files are not changing it should go back to idle. At the point it notices the files have changed, it will have to hash the file again, bringing the CPU load back up.

It also hashes when downloading files, so CPU load might go up as well, but I guess the network speed should be the bottleneck in that case, causing the CPU to be underutilized.

**Comment by ropeladder** [comment]
It's finished with the initial scan, so I guess it's hashing while downloading. But my download speed is generally in the in the B/s range (possibly because it's a lot of very small files?), so should the CPU still be getting so much use?

**Comment by AudriusButkevicius** [comment]
There is a known bug on some platforms causing slow speeds while Web UI is open (#867) hence you might want to check speeds via some external set of tools.

I wasn't able to reproduce it, and I am not sure under what circumstances it happens exactly.
What device are you running on?

**Comment by ropeladder** [comment]
The home computer with the high CPU usage I'm referring to above is a new i7 Win 8.1 laptop.

Unrelated: Is there an easy way to have Syncthing write new log files each time using the -logfile switch, instead of just overwriting?

I've been playing around on my work computer and noticed a few things:
-The work computer had been giving several warnings (pause puller for 1m, I think b/c it couldn't find the file). On the log file it said "it was unable to delete directory X because it is not empty". I don't think it should be deleting any of the directories. I'm assuming this deleting is related to [#1221](https://github.com/syncthing/syncthing/issues/1221) somehow.
-When I restart Syncthing and it reconnects to my home computer and tries to finish syncing (it's around 98%) the CPU use is very high (around 300% on an i3 desktop) even though none of the directories say they are scanning and only one of them is syncing.
-On my latest restart of Syncthing it has been unable to connect for some reason, but after the scanning finishes the CPU use does decrease to around zero (in the absence of any syncing).

I'll try it with the GUI closed as well.

**Comment by bigbear2nd** [comment]
May I ask which folders you are syncing?
Are there any programs running on your home-pc which change the files in your sync folder?

**Comment by ropeladder** [comment]
The main folder that seems to be having trouble is the folder for the Scrapbook plugin for Firefox. It saves websites in subfolders inside a data directory and has some .rdf index files that are infrequently updated. (I think it only rebuilds the index when you search it, which is infrequent) (I'm running the extension in Firefox right now and none of the core files have been modified since last week)

**Comment by pedrocr** [comment]
I was curious if new releases had made this any better so tried 0.10.20 on the same set of files. I'm still seeing ~800MB RAM usage on ~430GB/400k files. The CPU (i5-3320M) is also completely pegged on the sending node even after all the scanning is done (so no more hashing should actually be needed). While this is happening the sync is making very little progress (~40kB/s transfer rates).

**Comment by alex2108** [comment]
close the GUI and it should be better, there is already a issue about that https://github.com/syncthing/syncthing/issues/867
the RAM usage should also go down after a while of not having the GUI open and not syncing.

**Comment by roberth1990** [comment]
How on earth is it acceptable that syncthing uses 10-25 % cpu when syncronizing?

**Comment by AudriusButkevicius** [comment]
Sorry but crypto is not free. Read the FAQ.

**Comment by pgrm** [comment]
@AudriusButkevicius crypto isn't free, but it can be much cheaper: https://en.wikipedia.org/wiki/AES_instruction_set or is syncthing already using a library which takes advantage of AES-NI?

**Comment by AudriusButkevicius** [comment]
No, because Go's crypto is implemented in Go mostly, rather than ASM. If you can point me to a library which provides a cross-platform, cross-arch AES instruction set based cross-compileable, statically linkable library, we'll swap right away.

**Comment by pgrm** [comment]
So, if you're go's crypto is being used, the one mentioned here: https://github.com/golang/go/issues/11929 than it should already take advantage of AES-NI, and according to that issue it should even speed up faster with 1.6 - or am I getting something wrong?

**Comment by AudriusButkevicius** [comment]
Potentially for some parts, as TLS is not the only thing we use, we also use SHA256 which obviously has a cost.

Also the CL only seem to relate to amd64, so it's not an improvement across the board, but probably for newer CPU's which aren't maxed out that much anyway.

**Comment by AudriusButkevicius** [comment]
Actually SHA256 already seems to be written in ASM, so perhaps that's the last leg of how good it could be ;)

**Comment by pgrm** [comment]
@AudriusButkevicius I actually came here because I had a huge problem with my syncthing running as a docker container. It was constantly eating 100% of the one CPU to which I restricted it (this was going on for few weeks even though syncthing had nothing to do).

Turns out, if you limit syncthing to less memory than it needs, it goes berserk. I had my container limited to 512MiB of memory. Because before that it was eating giga bytes of RAM. After removing the limitation and letting it run for few hours, the container is using ~750MiB of memory and syncthing reports to use only half as much, 360MiB - that part is ok since I have in total roughly 215k files. Anyhow, now the CPU even during syncing is back to max 20% and usually <1% when nothing is going on. 

Any idea why it was constantly consuming 100% cpu when it was running out of memory? Syncing worked, just my computer was slightly unusable.

**Comment by AudriusButkevicius** [comment]
So I think there are two factors. First, cgroups does not change what memory is reported by the machine, hence things such as database probably tries to allocate more than it's allowed, causing issues.
Secondly, probably asking to allocate more memory, and mallocs failing potentially kicks off GC.
A CPU profile (check -help) will probably tell you the truth in whats actually consuming the CPU.
