### ISSUE TITLE
global gt local when 0 files exist anywhere 

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4696]
3 devices : Two of mine DD (deskop), DL (laptop), one friend DF
freshly sharing a bunch of files.
Added a [folderRoot]/YetThere/FLAC subfolder with 16 files in DD for DF, after adding a simple `FLAC` ignore in DL as I didn't want these in my laptop.
When upload to DF was done, I removed all the stuff in [rootFolder] knowing DF has a TrashCan set for the folder, then I removed stignore in DL.
Now all 3 devices are `UptoDate`, DF shows local=global=0/0/0, but my 2 DL & DD show local=0/0/0 global=16/1/438MiB

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
