### ISSUE TITLE
Suggest setting up auth on initial startup

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4703]
We could use the persistent notification thingy to display a notice that explains that a username and password should be set when on a shared computer. I don't want to make this a hard requirement so a notification that is displayed until acknowledged would be fine with me. 

Relates to #3357.

**Comment by EserGozcu** [comment]
Would it make sense to have this without checking if a computer is shared or not? I think it is nice to see a notification window saying that GUI Authentication User/pwd has not been set, until user clicks on OK or Don't Show Again.

**Comment by calmh** [comment]
Yes

**Comment by EserGozcu** [comment]
![whatsapp image 2018-09-21 at 12 22 17 pm](https://user-images.githubusercontent.com/9316467/45877005-b9874d00-bd9c-11e8-81e6-5bc969894f76.jpeg)

We found the relevant piece of code at index.html already however it seems like this will never be triggered since ng-include directive is not there.

existing relevant code: 

`   <div ng-if="openNoAuth" class="row">
      <div class="col-md-12">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">
              <div class="panel-icon">
                <span class="fas fa-exclamation-circle"></span>
              </div>
              <span translate>Danger!</span>
            </h3>
          </div>
          <div class="panel-body">
            <p>
            <span translate>The Syncthing admin interface is configured to allow remote access without a password.</span>
            <b><span translate>This can easily give hackers access to read and change any files on your computer.</span></b>
            <span translate>Please set a GUI Authentication User and Password in the Settings dialog.</span>
            </p>
          </div>
          <div class="panel-footer">
            <button type="button" class="btn btn-sm btn-default pull-right" ng-click="editSettings()">
              <span class="fas fa-cog"></span>&nbsp;<span translate>Settings</span>
            </button>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>`

is this on purpose or are we looking for a more graceful msg there which  does not enforce the user to go to the settings but can also pass by clicking on OK ? and if yes, i guess old one needs to be cleaned up?

**Comment by calmh** [comment]
This is different but related. This triggers when the admin interface is bound to something other than localhost, when auth should *really* be configured. This ticket is about something softer and easier that would trigger even when still on localhost, to guide rather than admonish.

**Comment by Yithis** [comment]
Is this issue still open? And if so, can I work on it? I might need some help, since I'm new to the project

**Comment by imsodin** [comment]
It is, and sure, no permission required ;)
