### ISSUE TITLE
Feature Request: Option for "Rarest First" for File Pull Order

### ISSUE THREAD

**Issue by zatricky** [syncthing/syncthing#4724]
*If* this is feasible, it would theoretically improve swarm performance for Folders with many small files added in large batches.

**Comment by lkwg82** [comment]
So far I know we'd like to get rid of pull order.

On the other side, I dont know a valid use case where we would like to improve cluster-build-up time.

**Comment by AudriusButkevicius** [comment]
Random is better in this context as if everyone is pulling the rarest, everyone ends up downloading the same file and not improving anything in terms of general availability of other files.

**Comment by Ferroin** [comment]
That assumes though that everyone starts pulling at the exact same time, which isn't usually the case in my experience.  Assuming files have varying sizes, starting with a random selection and then selecting the rarest each time one is done should in theory provide better load distribution.  Overall though, the bigger issue is that it won't likely have any net benefit unless you've got a large number of devices pulling a large number of files (it has zero benefit if you've only got one device pulling, should theoretically have zero benefit for two devices, and for any benefit with 3 or more you would need to have a lot of files simply because the performance improvement is likely to be miniscule per-file).

That said, load distribution could also be pretty easily improved by selecting blocks to pull instead of files, and randomizing things completely there, though that is of course impractical for other reasons...

**Comment by AudriusButkevicius** [comment]
That's not true, as we "don't know" what other are pulling until they are done.
We already randomise blocks we pull.

Don't know in quotes because we do but that is not in the index and is very latient, hence cannot be used to make a good decision.
