### ISSUE TITLE
Remove KCP

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4737]
The KCP implementation didn't live up to our expectations and should be removed. We will aim to add TCP hole punching when the required support in standard library is available, and monitor for other suitable technologies in the meantime.

**Comment by blindchimp** [comment]
Thank you :-) I've had similar experiences in the past implementing streaming with UDP/STUN, et. al...

It was complicated, flakey, and didn't perform very well. We eventually nixed it because of the increase in tech support issues it caused compared to just straight TCP. 

I could go on about the technical reasons, but I'll just say I share your thinking on this and you are making the right decision based on my experiences. And I look forward to getting rid of my hacked up stdiscosrv that throws away the kcp addresses...
