### ISSUE TITLE
Does not synchornize eml files

### ISSUE THREAD

**Issue by gagomezdevesa** [syncthing/syncthing#4746]
### Problem.

 - Syncthing does not synchronize "eml" files.
 - This problem occurs from several PCs.

Example: File name: Windows Mail\Storage Folders\Sent Items\7FFD1D84-000001F9.eml (not synchronized)

### Version Information

Syncthing Version: 0.14.44
Synctrayzor Version: 1.1.18
OS Version: Windows 10 in all PCs

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
