### ISSUE TITLE
mac -no-console from code how to set

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/syncthing#4817]
### Please do post actual bug reports and feature requests.
 - what happened :  i want to hide console default from coding but not work in mac user because non technical person don't like if console seen.

 - what you expected to happen instead : from coding if we ser default hide console then it will work for all platform instead of windows only
 - any steps to reproduce the problem. : 
i think according below code need to write some code for mac/linux console hide
./cmd/syncthing/main.go 
if runtime.GOOS == "windows" {
              // Allow user to hide the console window
              flag.BoolVar(&options.hideConsole, "no-console", true, "Hide console window")
        }

### Version Information

Syncthing Version: v14.45
OS Version: Mac

**Comment by calmh** [comment]
There is no way to hide the console on Mac like on Windows, because the console is not a part of Syncthing. It's another program that just displays the standard output  from Syncthing.

There are however ways to run Syncthing in the background without any window, see the etc/macos-launchd directory in the distribution, or there is a mac specific GUI wrapper that shows a menu icon instead.
