### ISSUE TITLE
XDG_CONFIG_HOME in Snap should point to $SNAP_USER_DATA

### ISSUE THREAD

**Issue by 3v1n0** [syncthing/syncthing#4827]
Using syncthing from snap causes it to run with these environment variables set:

`"HOME=$SNAP_USER_COMMON" "XDG_CONFIG_HOME=$SNAP_USER_COMMON"`

A part that these should now moved into the `environment` stanza in the `snapcraft.yaml` file, the main issue here is that the configuration files should be versioned and thus saved in the `$SNAP_USER_DATA`. Also this is causing issues if you've a `syncthing` folder inside your `$SNAP_USER_COMMON` like i did.

If you don't want to keep these versioned, you should at least set `XDG_CONFIG_HOME` to a dotted file (or just leave it unset, so it will be `$HOME/.config/syncthing`),

**Comment by calmh** [comment]
Versioned they should not be, because the index database lives in the same place. As for the rest I'll leave it to someone who knows snap better than me to make a determination.

**Comment by 3v1n0** [comment]
well, what I mean by versioned is that in that way the index will be copied when going back and forth in snap revisions, and so you don't have to care about format changes... 

But if you think this is not needed, it's ok.

**Comment by calmh** [comment]
It’s not just not needed, it would totally undermine the sync operation and cause data loss.

**Comment by calmh** [comment]
Re-reading this I fail to see the problem with how our setup is currently handling config files in the snap setup. If I'm just misunderstanding, feel free to clarify.

**Comment by 3v1n0** [comment]
The fact is that here you define `XDG_CONFIG_HOME="$SNAP_USER_COMMON` while instead should be something like `XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config`,

Also you should use the `environment` stanza in the snapcraft.yaml instead of the `env` command

**Comment by calmh** [comment]
So the thought when packaging this is that SNAP_USER_COMMON is where the snap stores it's data, while the user will presumably be syncing files that they have somewhere else

**Comment by 3v1n0** [comment]
This is possible, but with this configuration, the default sync dir will be under SNAP_USER_COMMON, and so the config files. This is confusing, as the config files should generally be under something that is hidden from user visibility, while in this case it just goes under `~/snap/syncthing/current/snap`.

Now doing a such change should of course involve adding a wrapper script that does the migration at startup.

**Comment by calmh** [comment]
I think the problem here is the default folder, probably the snap run script should set STNODEFAULTFOLDER. I doubt anyone wants to have their files live under ~/snap/syncthing/current/whatever.

On 20 Apr 2018, at 19:26, Marco Trevisan <notifications@github.com<mailto:notifications@github.com>> wrote:


This is possible, but with this configuration, the default sync dir will be under SNAP_USER_COMMON, and so the config files. This is confusing, as the config files should generally be under something that is hidden from user visibility, while in this case it just goes under ~/snap/syncthing/current/snap.

Now doing a such change should of course involve adding a wrapper script that does the migration at startup.
