### ISSUE TITLE
Unclear error message about failed watcher when running out of inotify watches

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [syncthing/syncthing#4833]
Syncthing shows the following notice after a short time after starting the web interface:

2018-03-22 15:12:10: Failed to start filesystem watcher for folder "Myfolder" (MyfolderID): error while traversing /home/username/documents/folder: no space left on device 

The file or folder which is mentioned by the message is changing from time to time/reboot to reboot.
There are >200GB space left on my device.

System: Manjaro XFCE 17.1.6
Syncthing V0.14.45, Linux (64 bit)

I have searched for the problem with google and in the github issue tracker but couldn'd find anything similar.

**Comment by imsodin** [comment]
This is because you run out of inotify watches, see https://github.com/syncthing/syncthing-inotify/#troubleshooting-for-folders-with-many-files-on-linux for how to fix this.

However it is intended that there is a more helpful error message, but that's broken. I did fix it upstream (https://github.com/rjeczalik/notify/pull/134) but forgot to adjust our own code accordingly...

**Comment by java-py-c-cpp-js** [comment]
Thank you for your quick reply. But if I click the link I'm redirected to a deprecation issue according sxncthing inotify. And I thougth that I'm not using inotify anymore because it is not installed througth the manjaro package manager and I've activated the build in FS-watcher in the advanced settings.

**Comment by imsodin** [comment]
That's no rerouting, that's just the explanation on the site of syncthing-inotify. The built-in fs watcher uses the same backend as syncthing-inotify, so the problem is the same. If you prefer, you can also read the instructions in this PR (will be published in our official docs soon):  
https://github.com/syncthing/docs/pull/381/files#diff-21f22f7105f5ee02c16e47bd53743dc8R500

**Comment by java-py-c-cpp-js** [comment]
Thank you for your help. Now everything is working again.
