### ISSUE TITLE
Override Changes still broken after 3 years, aka AudriusButkevicius closing tickets without fixing

### ISSUE THREAD

**Issue by Sod-Almighty** [syncthing/syncthing#4872]
You have a ticket #2914 which describes an Override Changes bug. AudriusButkevicius closed it without addressing the problem.

You also have a [forum post from 2015](https://forum.syncthing.net/t/what-is-the-purpose-of-override-changes-button/1818/7), where you arrogantly insist that you have already answered the question (you haven't!), and closed the ticket.

So, three years later, I experience difficulty with the Override Changes button, and I google for solutions. And the first two things I find are similar issues reported by other users, several years ago, and this Audrius fellow shutting them down and closing the tickets. Dude, that is not helpful!

Anyhow, leaving aside for the moment my views on Audrius's attitude, I have two important questions about SyncThing:

1. Why doesn't the master *always* override clients when set to Send Only mode? Under what *possible* circumstances would you want a client to remain out of sync with the master? If you have one machine set to Send Only, and the other machines are set to Send and Receive, then you self-evidently expect all the other machines to mirror the master. Always.

2. I have been running SyncThing on three machines in the same room for many months. Why is it that my directories are *still* not synced, after all this time? I have one master, and two slaves. The directories shared with one of the slaves are very large - over two terabytes - but after several months it says 115,161 out-of-sync items, and "syncing 100%". This makes no sense to me.

**Comment by calmh** [comment]
The linked ticket explains how things work. The linked forum post does as well, and was closed after two years of inactivity, not by Audrius. There are more forum posts on the topic if you search, with quite extensive discussion on why overriding changes does not work like you want. Here are some references to get you started: [1](https://forum.syncthing.net/t/always-override-tick-box-ticker/5789), [2](https://forum.syncthing.net/t/automatic-overrides-for-folder-set-as-master/6338), [3](https://forum.syncthing.net/t/please-can-we-make-the-override-changes-button-on-the-master-node-optional-so-syncing-becomes-automatic-in-one-way-master-to-normal-node-set-up/8624/2), [4](https://forum.syncthing.net/t/please-can-we-make-the-override-changes-button-on-the-master-node-optional-so-syncing-becomes-automatic-in-one-way-master-to-normal-node-set-up/8624/2).

In the issue template that you were presented with when opening this issue we say

> ### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER
> Please use the forum at https://forum.syncthing.net/ where a large number of
helpful people hang out. This issue tracker is for reporting bugs or feature
requests directly to the developers.

Given that this issue is two broad "why?!" questions, with the latter being obviously of a support nature, that is where it fits. Hence I'm going to close this issue and refer you to the forum - and I'm going to lock it to prevent further discussion as this already started out personal and in anger and can only get worse.
