### ISSUE TITLE
Android FsWatcher Transition

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4882]
Syncthing 14.47-rc2 was tested with a debug build of syncthing android according to pr 
https://github.com/syncthing/syncthing-android/pull/1051
During app upgrade from st 14.46 to 14.47 the app modifies the config.xml to turn on fs watcher as suggested by Nutomic and AudriusButkevicius. Then, the unackedNotification for the fswatcher is dismissed by the app via config.xml
Problem here is, the web gui notification is popping up on first run of st 14.47-rc2 binary even if all folders are already set to fswatcher enabled at that time.
Could this please be made like the notification popping up if there is (on any platform) at least one folder present on an older config revision before v28 that has fswatcher=false? This would simplify things on android because if it is like now with rc2, the app would turn fswatcher on, start syncthing, the unackednotification gets written, app stops Syncthing, removes notification from config and starts syncthing again.

**Comment by calmh** [comment]
The notification for the fs watcher stuff is added as part of the migration from config version 27 to config version 28, and this is the only change in that migration. Since you are manually/externally doing the fs watcher stuff, set the config version to 28 on writing. No notification will be shown on the next startup.

**Comment by Catfriend1** [comment]
Good Idea! Ok I'll do that.
