### ISSUE TITLE
Directories not ignored despite .stignore pattern "*"

### ISSUE THREAD

**Issue by TheRealMarnes** [syncthing/syncthing#4905]
Android 7.1.2 LineageOS
Syncthing 0.10.8

I created a folder for `/storage/emulated/0` (internal storage root) along with these ignore pattens:
```
!/Pictures/**
*
```

The goal being to sync the /Pictures directory and everything inside it (and possibly other dirs in the future), but nothing else.

Problem: all other directories in the root are synced as well, albeit without their content. I expect my other devices to which I sync this folder, to end up having this for content:
```
Pictures/
  foo.jpg
```
But instead they have 
```
Alarms/
Dowloads/
...
Pictures/
  foo.jpg
Stash/
...
```

Is `*` not supposed to ignore directories? I tried adding `*/` instead but that didn't help.

I took a look at the log but there was nothing helpful in there. Do you want me to enable any of the debugging facilities and post it after trying again? I'm not sure which one(s) to enable.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
