### ISSUE TITLE
size.go basic AppData\Local\Syncthing Usage <nil>

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4943]
With fs log enabled, I get the following line repeatedly every few seconds:
2018-05-11 14:02:05 size.go:85 basic C:\Windows\system32\config\systemprofile\AppData\Local\Syncthing Usage . {39156707328 72475471872} <nil>

Which information has to be provided to dig deeper into the cause? Syncthing is running as a service.
Is this just informational or may point to a bug?

ST version is 0.14.47, Windows 10x64.

**Comment by imsodin** [comment]
Why do you think this is a problem?

**Comment by Catfriend1** [comment]
I currently dont have visible problems. Just looks weird to me that a Syncthing Usage file/folder that is not there is referenced secondly.

**Comment by imsodin** [comment]
> [...] Syncthing Usage file/folder that is not there [...]

Don't take this the wrong way, but I still don't get what's "weird" and "not there". This is simply a debug line due to a call to the filesystem abstraction for the Syncthing config folder. I don't know when it is called, i.e. how often, but why should one care about that. Debug logging is extremely verbose (and not an indication of a problem), that's kind of its point.

**Comment by calmh** [comment]
This is probably the free space check for the config dir. and yeah, not a problem.

**Comment by Catfriend1** [comment]
Thanks for the feedback.
