### ISSUE TITLE
Distributed Hash Table for discovery instead of central server

### ISSUE THREAD

**Issue by ptman** [syncthing/syncthing#5]
I'm not sure how to implement it, or if it even makes sense, but I'm under the impression that this is what BitTorrent Sync does.

**Comment by GeoffMaciolek** [comment]
Regarding this (old) issue, I think @calmh has a solid point about "until it's needed."  I too would like increased decentralization, but it may well be premature, and the [discovery server](https://github.com/syncthing/discosrv) and [relay pool server](https://github.com/syncthing/relaypoolsrv) are themselves open source, which helps prevent "lock-in."

It also turns out there are beautifully presented usage statistics at https://data.syncthing.net/. Question: do the data *start* then, or is that just the viewable window?  (I think it's all the data based on my reading of the code, but...)  ([0.10.0 release notes](https://github.com/syncthing/syncthing/releases/tag/v0.10.0) don't seem to mention adding the usage tracker.)

Also - I think it would be useful to see some reporting of the load on the various servers; then if us geeks see the load going up too much over time, we can get cracking on implementing DHT!

**Comment by PrototypeNM1** [comment]
Quick ping to mention that the central server is down at the moment, would a DHT have prevented downtime?

**Comment by AudriusButkevicius** [comment]
Discovery is not down. We have 3 redundandt servers in 3 continents.

**Comment by PrototypeNM1** [comment]
My mistake, sorry.
