### ISSUE TITLE
Snap build is broken

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5000]
As of recently, the snap build process creates "amd64" snaps regardless of the architecture given to the build script. Looks like something has changed in how the toolchain works. I glanced at the documentation and it looked like `architectures: [arm64]` in snapcraft.yaml should still be the way to mark a snap as `arm64` but it seems that doesn't work.

Blocks releasing stuff to snap channels.

**Comment by calmh** [comment]
So, apparently things have changed and we need to pass `--target-arch` to get a snap for the desired architecture. This, however, triggers snapcraft to start installing libc cross compiling packages for arm and whatnot, which fails in our build environment and should absolutely not be done. I haven't found a way to disable that behavior.

Here's a commit that almost fixes the situation, apart from the above: https://github.com/calmh/syncthing/commit/6e0326cc4a7e66e5301b70a91b7084c72e92fe3b

I can't fix this, so until someone snapcraft-savvy takes it on we will not publish snap builds.

**Comment by anonymouse64** [comment]
I'm not sure how the CI is set up for syncthing, but there are a couple ways you can handle this depending on whether you do cross-compilation or not.
If you're doing all native builds on different architectures, just remove the `architectures` key entirely -  the snap file produced will have the architecture set for it automatically.

If you're cross compiling, which I think the project is, you have a few options.
1. You can specify inside of snapcraft the names of the files to pull into the snap. I.e. if you cross compile the syncthing binary on x86, arm, arm64 and i386 as `syncthing-x86`, `syncthing-arm`, `syncthing-arm64`, and `syncthing-i386` respectively the snapcraft.yaml would simply have logic to pull in the specific architecture binary into the snap. 
2. Remove the `architectures` key, call `snapcraft --target-arch=...` and build the syncthing binary inside the snap. I think this is potentially the simplest and will get you additional architectures for free if that becomes a thing later on (such as s390x, etc.). When the target-arch is set, the go plugin for snapcraft sets the appropriate environment variables so that the go build runs for that architecture, i.e. `GOARCH`, `GOOS`, and `GOARM`. 

I also would point out that in order to avoid the libc problem, the best way is to use `snapcraft cleanbuild`. `cleanbuild` will start an Ubuntu 16.04 lxd container, bootstrap it with the build environment necessary, performs the build, and then extracts the build artifacts out of the container into the snap. It is the preferred way to build snaps on systems other than Ubuntu 16.04 and also when cross-compiling. Primarily it ensures that your snapcraft.yaml has all the real build dependencies enumerated in it and as such will work on all user machines, and secondarily it ensures that there's no leakage from snapcraft installing things like libc onto the build host. Lastly it can handle unexpected and difficult to debug errors from using the incorrect version of libc for say Ubuntu 17.10 when that's your build host, when snaps need to be built against Ubuntu 16.04 (although in the coming months a new option of Ubuntu 18.04 will be available if you so choose). Note that then the full call to snapcraft becomes `snapcraft cleanbuild --target-arch=armhf`, etc.

**Comment by calmh** [comment]
All I want snapcraft to do is take the `syncthing` binary that I built for arm64 (for example) and put it in a snap file, having that file tagged as being for arm64. I don't want snapcraft to install anything, extract anything, start any containers, or build anything.

**Comment by anonymouse64** [comment]
I think what you need to do then is take advantage of the new grammar for `architectures` (which inconveniently is what caused this to break originally anyways) and write it like so:
```
architectures: 
  - build-on: [{{.HostArchitecture}}]
    run-on: [{{.TargetArchitecture}}]
```
What this says to snapcraft is that the current architecture that it's running on doesn't need to cross-compile and it's compatible with the `run-on` architecture by default. So for example if your build host is x86 and your target is arm64 you'd have `HostArchitecture=amd64` and `TargetArchitecture=arm64`. I can contribute a patch for this if you like (let me know if you want it in my other PR or a new one). Note that then you don't need to call `snapcraft --target-arch=...` in this case and just call `snapcraft` normally.
