### ISSUE TITLE
reports files with long filenames as out of sync

### ISSUE THREAD

**Issue by alvg** [syncthing/syncthing#504]
the files themselves have been copied over.
but in the webUI, the repo status says those files are out of sync.
(platform windows7).

mostly web pages with very long titles.
when renamed to a smaller name,  the out of sync notification goes away.

**Comment by borissamardzija** [comment]
Hello @calmh, please let us know how we can help with this issue and what you mean by exploration?

I am also hitting this problem on Windows 8.1 x64

```[7DEKR] 23:22:40 INFO: Puller (folder "Cloud", file "Dropbox\\Apps\\Money by Jumsoft\\com.jumsoft.money3.sync\\Documents\\45454E72-D091-449A-9307-52D4E13A8F1B\\SyncChanges\\B2E23A5C-17A1-4962-B1DC-BEB9E4654180-222-000000498A607DDB\\0449506206,232756-A818A4BC-778C-417F-B4DC-1494DC77E4E0-12129-000002B35CDCB703.syncchg"): dst create: open D:\Cloud\Dropbox\Apps\Money by Jumsoft\com.jumsoft.money3.sync\Documents\45454E72-D091-449A-9307-52D4E13A8F1B\SyncChanges\B2E23A5C-17A1-4962-B1DC-BEB9E4654180-222-000000498A607DDB\~syncthing~.0449506206,232756-A818A4BC-778C-417F-B4DC-1494DC77E4E0-12129-000002B35CDCB703.syncchg.tmp: The system cannot find the path specified.```

I am transitioning from BTsync, and this worked fine. I also *think* this is because of `~syncthing~` added to file name, making invalid file name from what has been valid before.

This is also causing `23:32:04: Folder "Cloud" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.`

**Comment by calmh** [comment]
@borissamardzija From what I hear the `\\?\` trick works fine (people have been running with it for a while), so we just need a patch to add that to paths at some suitable point in the code and some testing of that on windows.
