### ISSUE TITLE
Support for easy, one-way backup solution

### ISSUE THREAD

**Issue by adamemrts** [syncthing/syncthing#5060]
Tried twice to configure Syncthing to avoid and replace priopertary/hosted solutions like Google Photos or iCloud. Idea is to configure one-way folder sync from mobile device (Android) to backup server (Ubuntu). 

With simple configuration Syncthing works like a charm, but taking inspiration from Google and Apple backup solutions I've tried to configure it this way, that data on mobile device can be deleted and kept safely only on backup device. This configuration is theoretically possible with some Syncthing options, but finally failed to work in two of my tested installs and few config versions and attempts. It was always deleting files in both places, no matter how hard I've tried.

I know it may look like some edge case, but form my point of view it is the simplest and most desirable configuration option for non-technical end users in times of mobile devices usage. Also option for easy configure this type of syncing from mobile device app to already accessed hosted Syncthing server, could be deal breaker for some of them.

If it's not a place for non technical feature request I'm ready to redo my tests and make full specified bug report. But hoping that clue of the problem was explained properly enough to understand the need for such an option.

**Comment by AudriusButkevicius** [comment]
Syncthing is not a backup solution to start with, it's a bi-directional sync solution, which implies that you are using the wrong solution.

If you need help or want to discuss this further, forum is the right medium for that.

**Comment by Erudition** [comment]
I can't imagine wanting a fully bi-directional sync solution on a smartphone (which all still have limited space and reliability compared to stationary pcs, nas, etc) more than wanting this feature, because a huge reason people want to "back up" their phone is to _make more room_ on the devices, not just for disaster recovery. For this reason @AudriusButkevicius  I think we're getting too hung up on the word "backup".

This problem, of _offloading_ files from a small device, that is solved by the likes of Google Photos, is a common one - and where does the FLOSS solution lie? We can't have both the backup software communities as well as the sync software communities telling us it's "out of scope", or to look to the other for a solution (such as "which implies that you are using the wrong solution", which could be said by the backup people as well).

By the way, 
> [_some software_] is not a backup solution to start with, it's a [..] sync solution
Is a category error to start with. The famous "sync"-ing application `rsync`, for example, is suggested by experts as one of the best among _backup solutions_. It could even be argued that any good sync software should be good backup software.

**Comment by calmh** [comment]
As noted above, the forum is the ideal place for general discussion of what direction you think things should take, as well as arguing wording and semantics (as much as any place is desirable for that). The issue tracker is not a great place, however.

**Comment by Erudition** [comment]
@calmh That makes sense, assuming this was actually about taking syncthing in a new direction, rather than merely documenting a missing feature. And that opinion was justified with little more than "arguing wording and semantics", as you put it, but was apparently enough for dismissal and closure of this issue - which is premature unless you share that opinion. But of course, if we'd like to pivot to a sound _technical_ reason for closing this issue so quickly, that would be fine. 

Point is, discussion about what the scope/goals of a project _should be_ can reasonably be kept out of the issue tracker, sure. But when merely discussing whether a particular issue is out of scope, there is no better place than the issue itself - and this is certainly the convention elsewhere on GitHub.

**Comment by calmh** [comment]
This issue is to (improve) "Support for easy, one-way backup solution". This is not the direction we want to take Syncthing, because Syncthing is not a backup solution and we don't want to "market" it as one. There are some options that make it more like one such that it might have worked for the OP (except something didn't), and Syncthing can support some of the offloading you're requesting. (I personally *use* Syncthing as *part* of a backup system, so it's certainly not forbidden. :)

I can understand frustration from being showed towards the sync camp from the backup camp and vice versa - but we're not optimizing for the unidirectional backup case. Among other reasons for this is that we have absolutely zero to offer in terms of a "restore" story, something quite essential to a backup solution.

I think the option the OP is referring to is "ignore deletes" which does indeed have some flaws. One of them is that it's hard to find. The other is that it breaks some assumptions that the rest of Syncthing depends on and can have odd effects in some cases. (These two are not unrelated.) If there is something actionable here that we could do to improve that, that would probably be a good separate issue. I'm not exactly sure what the desired action is here, which is part of the reason for the initial "if you need help or want  to discuss this lets take it to the forum" response.

**Comment by xorgy** [comment]
There is certainly (including on this GH org) interest in partial-node applications. I personally think that for this to work well, there needs to be commodity Syncthing hosting (like Dropbox/Drive) out there, and there needs to be a hint for this in Syncthing proper (so that you don't have those permanent "Syncing (0%)" things everywhere there's a partial node).

https://github.com/syncthing/syncthing-lite
https://github.com/burkemw3/syncthingfuse

**Comment by Erudition** [comment]
> Among other reasons for this is that we have absolutely zero to offer in terms of a "restore" story, something quite essential to a backup solution

Agreed. Which is exactly why I mentioned that using the word "backup" may be misleading here. 

When you use Google Photos, you save space on your phone by offloading pictures to the cloud server. That's it. It stays there. You view them later, still on the server - no restoring needed. Sure you can download individual photos back to your device, and that is handy sometimes, but it's perfectly fine for Syncthing not to support that. In terms of syncthing, you offload photos to some other device like a desktop PC (the "server") and that device keeps them. For good. That's it.

I can see why calling that "one-way backup" would lead one to think about "restoring", but hopefully I've painted a clear picture of why this framing is misleading. The framing of "one-way sync" fits perfectly however and makes it clear that it's not really some out-of-scope "backup solution" we're looking for. 

(In fact, this could be a killer feature that gets people to use more libre software where currently only proprietary software with corporate clouds exist. Otherwise, using syncthing means you necessarily have to play disk-space-police, which probably impairs mass adoption.)

Perhaps a separate issue should be opened strictly about "one-way sync".
