### ISSUE TITLE
Add support for TLS1.3

### ISSUE THREAD

**Issue by otbutz** [syncthing/syncthing#5065]
TLS1.3 support should land in golang [1.11 or 1.12](https://github.com/golang/go/issues/9671) and would improve connection security/latency.

Check the following blog posts to get a grasp of its benefits:
https://www.cloudflare.com/learning-resources/tls-1-3/
https://kinsta.com/blog/tls-1-3/

**Comment by calmh** [comment]
We will use it when it’s available.

**Comment by AudriusButkevicius** [comment]
I think we'll get it out of the box, nothing needed from us?

**Comment by Ferroin** [comment]
Unless I'm mistaken, it looks like @AudriusButkevicius is correct, provided that you don't want to force usage of TLSv1.3 (and I would suggest not doing so for now, some Linux distros still don't have proper support yet because of all the breaking changes in the version of OpenSSL that supports it).

**Comment by calmh** [comment]
Yeah.

**Comment by AudriusButkevicius** [comment]
So close this in that case I guess?

**Comment by calmh** [comment]
I know we have a differing philosophy on keeping issues around, but I don't mind keeping this open as we currently do not support TLS 1.3 in any official release, and close it when we do - even if due to no action by us other than upgrading Go on the build servers.

**Comment by otbutz** [comment]
Go 1.12 has been released with opt-in support for TLS1.3: https://golang.org/doc/go1.12#tls_1_3
