### ISSUE TITLE
Display historic resource usage in the UI

### ISSUE THREAD

**Issue by EserGozcu** [syncthing/syncthing#5156]
Feature Request: 
Today Syncthing UI provides  data for Download&Upload Rate, RAM&CPU Utilization, however this info is not visualized historically.  My Suggestion is to have a line chart for each item on this menu.   For example: Clicking on Download Rate(drop down menu) can show a line chart showing the rate for the last 10 min.  I am aware that there are many other tools out there for monitoring. Therefore my suggestion is not to create another one but instead showing a real time  line chart only for last X min.  This is to help troubleshooting an ongoing issue. Such as: oh my network connectivity is slow for the last couple of minutes, is it Syncthing consuming too much bandwidth?  

This can be like the Kubernetes Dashboard(that also provides for only the last 15 min)

![opera snapshot_2018-08-31_204117_www google se](https://user-images.githubusercontent.com/9316467/44930338-4b7fd500-ad5e-11e8-8aa9-be98a3ab210f.png)

Thanks,
/Eser

**Comment by calmh** [comment]
Frankly I'm not sure why we bother with CPU and RAM utilization. I suspect from the beginning it's "because we can" and because we developers care. But programs in general do not track this about themselves - like, Word, or Photoshop doesn't have these graphs or indicators...

However, transfer rates are indications of what Syncthing *does* and seem legitimate. We could/should track and visualize that over time.

**Comment by EserGozcu** [comment]
Good point, 

I think it is also for the consistency, if UI shows the CPU usage today, then visualizing the bandwidth but not the CPU might not be very appealing to the eye.

**Comment by AudriusButkevicius** [comment]
Knowing if you are cpu bound for hashing is still useful, so is ram usage when you have all sorts of caching enabled.

**Comment by calmh** [comment]
Yes, but these questions can be as easily and possibly better be answered by the OS activity monitor / task manager / top / whatever. I think it's atypical that a given program shows graphs of its own RAM/CPU usage.

**Comment by AudriusButkevicius** [comment]
Sure, but when someone provides a screenshot is no longer as obvious.

**Comment by calmh** [comment]
Maybe track it and include in #5142

**Comment by uok** [comment]
My vote is against this GUI feature. 

Syncthing runs 99,9% in the background and it is rarely necessary to know traffic some time ago. For example, if I'm on a skype call and connection is bad because something else is using bandwidth I just look what is running *at that moment*, e.g. Syncthing and pause it. A simple pause/resume function in tray icon would make more sense here.

In bigger networks admins simply check which client is causing high traffic with monitoring tools, so again no need for graphs in Syncthing.

**Comment by EserGozcu** [comment]
I understand your point, however I don't agree much. In my humble opinion  We already have download/upload rate available at UI and the momentarily shown data is not very useful for most of the issues.  Being able to correlate the data with an ongoing issue(timestamp wise) is an important feature and historical data will be useful for this. 

"in bigger networks admin simply check which client is causing high traffic with monitoring tools" is unfortunately far from reality.  Maybe network product centric companies or telecom operators do that however most of the companies out there are way more structured, and IT operations does not have the insights of the applications being used at different departments. There might be a case where Syncthing is being used by lets say: R&D XXX team across their servers and it would be a case that they open a ticket to Operations asking for RAM upgrade on Syncthing instances since UI shows that most of the available RAM is being used already.  It is sad but also the fact that initiative generally does not come from Network/System admins but from the application owners. 

I think the question is, where do we want to see the Syncthing at the future? Enterprise grade app that  does what it does normally and provide quick tools for their users for such cases. Or home & small networks;  where user basically do want whatever they want to do and such functionality is not a must.

**Comment by AudriusButkevicius** [comment]
Syncthing is not targetting the enterprise, hence I start to tend to agree that we should probably not do this. You care about monitoring? Set it up externally.

**Comment by uok** [comment]
@EserGozcu Thanks for commenting. I think you don't need to see it in Syncthing. You can use commands like "htop" in Linux or task manager in Windows to compare RAM of Syncthing. Bigger companies have operating processes, admins, etc. that will make sure the software runs fine for all users (e.g. RAM update after requirement listing).

Also you can simply connect your monitoring tools like Nagios (example: https://github.com/vlcty/check_syncthing) or use the excellent REST API for direct access. If you have any use cases or need help, please check the [forum](https://forum.syncthing.net/) which has a great community.

**Comment by bigbear2nd** [comment]
I think it is quite strange there is a super detailed data usage over time available for all devices together, but for my own device the transferred data is reset every restart?

**Comment by AudriusButkevicius** [comment]
Usage reports are usage reports, you can opt out.

**Comment by poloking** [comment]
For transfer rates I think a graph would be extremely useful. An example is where I am testing different rates depending on my situation at the time. Occasionally I am travelling and the rate is so slow. But then I turn on a VPN and it works better. Turned out the transfer rate was fine but just intermittent. A graph would have made this obvious rather than me assuming that the internet was slow.
