### ISSUE TITLE
Disabled Upgrade forces full reload

### ISSUE THREAD

**Issue by milefork** [syncthing/syncthing#5250]
Hi, I'm facing a issue while using the docker version.
In that the upgrade is disabled. (The setting for automatic updates says that) but the Web GUI is trying after a periodic time to get to http://syncthinurl/rest/system/upgrade with responds with 500 Internal Server error and the message "upgrade unsupported".

After that the fully UI gets reloaded/reset with resetting every progress bar and so on.
I don't think it was the intention of that.

For reference my docker images beeing used: 
linuxserver/syncthing
syncthing version: v0.14.51, Linux (64 bit)

Greetings

**Comment by calmh** [comment]
This doesn't happen for me nor, do I suspect, other people with the upgrade disabled. This is not only the Docker image, but all Debian and SNAP packagings for example. If this caused GUI reloads there would be a flood of complaints, but there is not. So I suspect the problem is somewhere else and you need to troubleshoot.
