### ISSUE TITLE
Sync conflicts created for identical files

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5258]
Conflict files should not be created when the contents are the same. Nonetheless, they are.

```
jb@kvin:~/g/s/g/s/s/test $ shasum s2/*
3f5f1edb1297ffac308f3e67fe8ca656a5c9a6d4  s2/syncthing
3f5f1edb1297ffac308f3e67fe8ca656a5c9a6d4  s2/syncthing.sync-conflict-20181011-102906-I6KAH76
jb@kvin:~/g/s/g/s/s/test $
```

To reproduce:

- Two devices, one folder, one file in it, in sync.
- Remove the folder on one device. Add it again. Let it sync.
- Observe conflict file created.

**Comment by calmh** [comment]
OK this is solved by the referencing commit, because identical conflicting files are handled in the shortcutting logic.

**Comment by HITMAnsOFT** [comment]
Hi, I've just set up Syncthing on my Raspberry Pi-based NAS and on my Linux PC to sync my music folders, and I'm getting identical conflict files on Raspberry Pi side.

Both machines are using Syncthing 1.2.1. Previously I was synchronizing these folders with rsync. The folder is set to ignore permissions, because the folder on the Linux PC side is on an NTFS volume and is used by Windows also.

This usually happens with large files (FLACs mostly), 200MiB+. It can be worked around by setting `Max Conflicts` to 0, however the original files will still appear in `Out of Sync` list and will take time to "sync".

Here is one example:
```
ls -l './Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy'*flac
-rw-r--r-- 1 share share 334417554 Jul 28  2014 './Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy.flac'
-rwxrwxrwx 1 share share 334417554 Jul 28  2014 './Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy.sync-conflict-20190811-214311-HZXLKIE.flac'
```
```
sha256sum './Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy'*flac
41be01cdb5372e7881e6fba1deaa6f31af67dfc1d83c76f3f22a802681012cb7  ./Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy.flac
41be01cdb5372e7881e6fba1deaa6f31af67dfc1d83c76f3f22a802681012cb7  ./Classical/Symphonies (various)/Mahler 2 Klemperer Philharmonia Schwartzkopf Majdan 63 EMI great rec/mahler 2 klempy.sync-conflict-20190811-214311-HZXLKIE.flac
```
Shall I open a separate issue?

**Comment by calmh** [comment]
No, open a forum discussion. My guess is you're syncing between devices with differing "large blocks" setting, maybe other side is < 1.2.0.

**Comment by HITMAnsOFT** [comment]
> No, open a forum discussion. My guess is you're syncing between devices with differing "large blocks" setting, maybe other side is < 1.2.0.

Hmm that makes sense, because actually I first set up the folder on the Linux PC on Syncthing 1.0 (ubuntu default version), then upgraded to 1.2.1 from Syncthing apt repo before the full sync was complete. Now that the first sync finished, everything seems to be back to normal. Thanks and sorry for misusing the issue tracker :)
