### ISSUE TITLE
Panic: runtime error: index out of range

### ISSUE THREAD

**Issue by schneeemensch** [syncthing/syncthing#5291]
Hey everyone,

tonight I got a lot of “runtime error: index out of range” panics. They appeared at almost exactly the same time on all receiving devices of one shared folder (not on the sendonly master distributor). The folder on the distributor is constantly changing and can therefore provoke errors, but the panics should still not happen.

I have a sanitized panic log for you. They look similar on the other devices. In total I hav 134 panics across 34 devices which are in differently sized clusters separate for windows and linux.

[syncthing_panic_Index_out_of_range.log](https://github.com/syncthing/syncthing/files/2519163/syncthing_panic_Index_out_of_range.log)

### Version Information

Syncthing Version: v0.14.51
OS Version: Windows / Ubuntu/ RedHat/ CentOs/ SuSe/

**Comment by imsodin** [comment]
Relevant forum threads:
https://forum.syncthing.net/t/panic-runtime-error/12215
https://forum.syncthing.net/t/lots-of-panic-runtime-error-index-out-of-range/12358

In the former thread it was shown with a debug build, that the out of bounds index panic happened due to trying to pull an invalid file, which does not have a block list.
