### ISSUE TITLE
Dangling symlink prevents filesystem watcher on FreeBSD

### ISSUE THREAD

**Issue by gihnius** [syncthing/syncthing#5360]
### Easy to reproduce

$ cd $HOME/Sync/data
$ ln -snf /link-a-non-existing-file  to-here

or from any sub folders inside your sync path

$ cd $HOME/Sync/data/ebooks
$ ln -snf /usr/local/www/non-existing  book.pdf

then you will see the error message from your browser.

```
Filesystem Watcher Errors: error while traversing /path/to/exists/file_or_dir: no such file or directory
```

### Version Information

v0.14.54, FreeBSD (64 bit) 

Syncthing Version: v0.14.54
OS Version: FreeBSD 12.0-RC2
Browser Version: Chrome Version 70.0.3538.67 (Official Build) (64-bit)

**Comment by desbma** [comment]
It is probably specific to FreeBSD, I can not reproduce on Linux.

**Comment by gihnius** [comment]
> It is probably specific to FreeBSD, I can not reproduce on Linux.

Yes, no this problem on both Linux and MacOS.

**Comment by GlenHertz** [comment]
I get this too on FreeBSD 11.2.

**Comment by imsodin** [comment]
This might be kqueue specific, which is used on the BSD variants, and available but unused in favor of fswatcher on macos. We could add a test stage with `-tags kqueue` on macos to test with that backend for notify.

**Comment by liweitianux** [comment]
Hello. I'm having this issue on DragonFly BSD as well.

**Comment by bitclick** [comment]
Hi, I am having the same issue on 

Freebsd 11.3-RELEASE-p5 with 
Syncthing v1.3.0 64bit.

**Fix possible?**
I also think it might be some shortcoming of kqueue. Maybe it has to be called with a special flag, or it depends on some specific kernel-patch? 
This page gives some hints (the test explanations in README):
[https://github.com/libinotify-kqueue/libinotify-kqueue](https://github.com/libinotify-kqueue/libinotify-kqueue)

**maybe-workaround?**
If it depends on the presence of a kernel/library-feature, maybe syncthing could check for that and give a better failure-message?  or it could try to just not watch the offending symlinks (and tell the user), so that theres *some* support for watching.

**do i need watching anyways?**
For the moment i turn off watching completely on this machine. Is there anything to keep in mind about that? It is just a fileserver used as a always-on hub for syncthing. "No" changes on the server are to be expected.

**Comment by f4814** [comment]
Hi. I'm bitten by this as well (FreeBSD 11.3). Is there any chance this will get fixed in the near future?

**Comment by AudriusButkevicius** [comment]
I don't think any of the maintainers runs BSD, so I don't think it's a high priority for us.
We're happy to accept pull requests fixing this.

I suspect a proper fix would needs to happen in the underlying libraries we use.
