### ISSUE TITLE
Build failing on current master?

### ISSUE THREAD

**Issue by fragtion** [syncthing/syncthing#5427]
Hi

Since commit 944ddcf768d14de8e6613fa3758ee56852152119 ("all: Become a Go module"), building with ./build.sh is failing:

> root:/usr/local/src/syncthing-test# ./build.sh
> can't load package: package github.com/syncthing/syncthing/lib/auto: cannot find package "github.com/syncthing/syncthing/lib/auto" in any of:
>         /usr/lib/go-1.10/src/github.com/syncthing/syncthing/lib/auto (from $GOROOT)
>         /root/go/src/github.com/syncthing/syncthing/lib/auto (from $GOPATH)
> can't load package: package github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto: cannot find package "github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto" in any of:
>         /usr/lib/go-1.10/src/github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto (from $GOROOT)
>         /root/go/src/github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto (from $GOPATH)
> exit status 1
> exit status 1
> root:/usr/local/src/syncthing-test#

go version go1.10.4 linux/386

I presume this has something to do with going modular? I'm not sure what that entails, but surely it should not affect normal ./build.sh operation? Pls advise & Tnx in advance :)

**Comment by AudriusButkevicius** [comment]
You need to ./build.sh assets first. Also, you should have asked the questions on the forum.

**Comment by calmh** [comment]
This is a regression though, manually building assets shouldn't be necessary. And isn't, with Go 1.11 in module mode at least.

**Comment by calmh** [comment]
Oh OK, this is an intentional regression. The following works out of the box:

- Building with Go 1.11 outside GOPATH (modules mode)
- Building with any supported Go version inside GOPATH

What does not work is building outside of GOPATH with an old Go version, as removed the special haxery for that. If you do that, you need to jump through the hoop, or use GOPATH as intended in those Go versions.
