### ISSUE TITLE
Filesystem watcher error when watching disk root directory on Windows

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#5578]
External W7 computers as send only, I have a backup server that is receive only. All been fine up until the last update. was on rc2 with no errors

On the remote computers im getting a title of Filesystem Watcher Errors and errors as follows

GetFileInformationByHandle \?\C:: Incorrect function.

on the computers where the software is running and on the network shares…

The network name cannot be found

Although I am able to access the remote folders through explorer. I have also noticed on the sync job rescan section it’s now saying “Failed to setup, retrying”

I have shutdown and restarted Syncthing and get the same issue.

It also seems that the syncs are working so maybe the error is benign / false.

![image](https://user-images.githubusercontent.com/17702842/53869847-efd62300-3ff0-11e9-9083-83a96863ed2d.png)

![image](https://user-images.githubusercontent.com/17702842/53869963-2613a280-3ff1-11e9-9edf-7a8fb8e11226.png)

**Comment by AudriusButkevicius** [comment]
The folder path does not have a trailing slash which seems wrong.

**Comment by tezfair** [comment]
I did, exactly the way you said via config, same result

![image](https://user-images.githubusercontent.com/17702842/53892352-09dd2900-4024-11e9-9fde-b1c7678f0cda.png)

this is another PC as my first posting, but same error

**Comment by imsodin** [comment]
If this will be confirmed to only affect folder roots at drive letter level, this might be related to https://github.com/rjeczalik/notify/issues/148. Even if it's not it's relevant, as it essentially means drive letter watches were ineffective even before this error.

Short term workaround: Disable watching for changes for root level folders.

**Comment by ggppjj** [comment]
I've commented on this issue on the Forum, but to duplicate the comment, I'm seeing the same behavior.

v1.1.0, Windows (64 bit) installed via SyncTrayzor v1.1.22 on Windows 10 Pro Evaluation build 18351.19h1_release.190301-1611.


The share is the root of a non-OS drive, with a few exclusions on the root level and excluding System Volume Information.

**Comment by ewpt3ch** [comment]
> v1.1.0
@st-release st-release released this 8 days ago · 39 commits to master since this release
warning Notice warning
Due to adopting Go 1.12 and API changes there this release does not work on Windows XP / Server 2003 / Home Server. Syncthing 1.0.1 is the latest binary to "support" (it seemed to work, although was still not officially supported) those operating systems.

My reading of this is that from version 1.1 and moving forward syncthing will not be able to work on XP at all, or am I miss reading it and after this bug is fixed it "might" start working again?

**Comment by imsodin** [comment]
This bug has nothing to do with XP, as you can see from reported Windows versions above. In addition this bug does not prevent Syncthing from working as a whole, just the watching for changes component.

**Comment by calmh** [comment]
Reopen due to revert

**Comment by imsodin** [comment]
@calmh What's your opinion: Should I PR the fixed hot-fix (https://github.com/syncthing/syncthing/issues/5696#issuecomment-490609957) again for the next RC or do you want to wait for the more general UNC-stuff (#5696)?

**Comment by calmh** [comment]
A tested hotfix is fine for 1.1.4-rc imo

**Comment by imsodin** [comment]
Turns out I need to change non-test code to make this scenario testable, which in itself already makes it unlikely that the mistake that has lead to the panic happens in the first place (unless there is write access to a drive root on the test system, then the scenario wouldn't have to be faked, but that's hardly possible).

Are you ok with a test of the scenario that has lead to the panic, that can only run after code changes also in this PR?

Unrelated side-note: I think I found a bug in `path/filepath`, in that `filepath.Join("D:", "foo")` returns `D:foo`, while I expected `D:\foo` - I'll bring it up upstream.
