### ISSUE TITLE
BUG: LibreOffice Writer conflicts without cause

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [syncthing/syncthing#5603]
### What happened
When working with a LibreOffice Writer document (.odt) for a longer time, multiple conflicts appear. I am certain there nobody is changing these files on the other machines.

### What I expected
If I edit a file on one machine only, it should not be possible to get a conflict on it, no matter the program.

### How to reproduce
Create a writer document (.odt)
Use it for a time (keeping it open): Edit, write new stuff, delete old stuff etc. Save after every change.

### Notes
I cannot reproduce this behaviour on linux systems.

### Version Information

Syncthing Version: v1.1.0
OS Version: Windows 7

**Comment by calmh** [comment]
Conflicts are not generated locally but by another device. Typically, when it happens automatically like this, it's something on the other side intentionally or unintentionally touching files as soon as they change, perhaps by reading/writing metadata etc. So I'd suggest locating which device is causing the conflicts and looking closer there. If you need help investigating, the support forum is the right place. Once the cause is found we can take another look at whether it's a bug or not.
