### ISSUE TITLE
Move footer links to header

### ISSUE THREAD

**Issue by rEnr3n** [syncthing/syncthing#5607]
I'm requesting to move the footer links somewhere at the top. I believe it's unnecessarily cluttering the page considering that the links are not part of everyday user interaction. Maybe move them (and the Help link) under `About` menu?

**Comment by calmh** [comment]
We can consider a proposal

**Comment by sa3dany** [comment]
# Current Header & Footer
## Header
- Language
- Help **(GUI docs)**
- Actions
  - ...
  - About
  - ...

## Footer
- Home page
- Documentation **(docs home)**
- Support
- Statistics
- Changelog
- Bugs
- Source Code
- Twitter

# Proposed Header
This change requires translations update because of the separation between the GUI docs and the docs homepage.

## Header
- Language
- Help
  - Home page
  - GUI Introduction **(GUI docs)**
  - Documentation **(docs home)**
  - Support
  - Statistics
  - Changelog
  - Bugs
  - Source Code
  - Twitter
  - About
- Actions
  - ...
  - ~About~
  - ...

## Footer
[remove]

**Comment by andrey-ivanov** [comment]
The home page link could be moved to about dialog where it is expected. Or it could be attached to syncthing logo at the header.
