### ISSUE TITLE
Allow users to let other devices see their Ignore Pattern configuration [enhancement]

### ISSUE THREAD

**Issue by senkus** [syncthing/syncthing#5615]
I run a configuration with lots of folders and lots of ignores, e.g. for cached files, device-specific settings, or any other file that might cause cross-device operability problems. Throughout use, it has occurred to me that managing these ignores is the most cumbersome aspect of using Syncthing.
So, to cut down on micromanagement, I propose a scheme whereby users can allow other devices to see their .stignore setup.
For the WebGUI, this could be implemented as a list of devices/rules in the "Ignore Patterns" tab, clicking a plus sign before each rule would add that rule to the device the user is currently configuring.

**Comment by AudriusButkevicius** [comment]
Ignores support includes, so your ignores could just be another synced file. Check the docs.

**Comment by senkus** [comment]
That kinda beats the point of having the "Ignore Patterns" GUI tab in the first place though, and then I also have to fiddle with OS-specific attributes to hide those includes, lest I accidentally delete them. Not a fan of this, honestly.

**Comment by AudriusButkevicius** [comment]
Sure, likewise I am not a fan of a feature that appeals to very little people.

**Comment by calmh** [comment]
I’m thinking out loud here... An advantage of the current workaround is that it works today. A disadvantage of the proposed addition is that it’s more knobs because it has to be optional. That said, two checkboxes on the ignore tab (“announce these patterns to other devices” and “merge patterns from other devices”) would be fairly clear, and I think generally useful.

We’d need a new message type for the update, and an algorithm to do the merge / deduplication. We don’t want to get stuck in an infinite loop of ignore updates. Exclude patterns that are order dependent would need to somehow preserve their ordering while merging with other devices... Ideally the end result between devices with both checkboxes ticked would always be identical ignores. 

There is also the usual chicken and egg problem for people expecting these “auto” ignores to kick in on new devices - we won’t hear about them until we connect to other devices, and we won’t connect to other devices until we’ve done an initial scan of the folder...

**Comment by AudriusButkevicius** [comment]
I think this ticket is about something else, being able to see the ignores.

The sync ignores across device is a separate issue that is not the ambition here.

**Comment by calmh** [comment]
They're not exactly disconnected, imho. The purpose of seeing is to manually sync, and autoamatically syncing isn't a huge step from that point. Probably easier than the proposed plus-per-each-seen-pattern thing.

**Comment by AudriusButkevicius** [comment]
You can already automatically sync via includes, sure editing has to be done outside, but who cares.

I don't think this is about syncing, it's about seeing whats done elsewhere remotely so you could mimic certain parts.
