### ISSUE TITLE
snap: include relay and discovery services

### ISSUE THREAD

**Issue by albertodonato** [syncthing/syncthing#5662]
It would be great to have the relay and discovery services binaries included in the syncthing snap.

**Comment by calmh** [comment]
If so as separate packages I guess. That said, if the stats from Ubuntu are correct the snap packages have approximately zero users and do not justify maintaining the syncthing package at all, much less creating even more niche ones;

<img width="766" alt="Screenshot 2019-04-20 at 16 25 27" src="https://user-images.githubusercontent.com/125426/56458598-14ac0d00-6389-11e9-9ab8-2d407dc6a109.png">

**Comment by albertodonato** [comment]
I agree it'd be better to have a separate snap for other service, but I do think that having snaps is useful.
Snaps work on multiple distributions (and allow using syncthing on devices running ubuntu core as well) and are very cheap to maintain (automatic builds can be set up so that  new packages are built/published at every master commit).

**Comment by AudriusButkevicius** [comment]
very good marketing spiel:

![image](https://user-images.githubusercontent.com/1144861/56459104-fb09c600-6386-11e9-888a-71ed4b9246c7.png)

**Comment by AudriusButkevicius** [comment]
There are many things that are cheap to setup, but if nobody is using them, why waste the effort

**Comment by albertodonato** [comment]
Sure if they don't exist, no one will be using them, though....

**Comment by calmh** [comment]
I've some experience now of building things in many different setups, with everything from Docker Hub via Travis and other CIaaS things and our own build servers. It has not, so far, been less (mental) work for me to integrate with, keep up with, monitor and maintain builds done on other peoples various platforms than doing it myself. The existing snapcraft setup is also annoying, with uploads not seldom failing due to random unavailabiltyness on the server side. 

So far the annoyance is fairly small and most of the work is already done, so the existing Syncthing snap can survive for now.

However I'm not really interested in adding and maintaining more packages, given low uptake and the fact that many or most issues around snaps seem to be filed by Canonical employees.

**Comment by albertodonato** [comment]
@calmh fair enough.

Just FYI the current setup doesn't really take advantage of automated snap builds, which wouldn't require manual uploads to the store.

**Comment by calmh** [comment]
Yes I realize you like your build environment, but as I explained it would just one be *one more* build environment for me to maintain.

**Comment by albertodonato** [comment]
It's not *my* build envirnoment, and I mentioned it as it could actually be easier to maintain than your current setup.

I'm not asking for any action on your side.
