### ISSUE TITLE
feature request: more clear error handling than "out of sync" in case of upper/lowercase collisions

### ISSUE THREAD

**Issue by Px3XjG6P** [syncthing/syncthing#5708]
- what happened, --> Vague error message "out of sync" on one side and "syncing" on the other side
 - what you expected to happen instead, and --> Error message reflecting the upper/lowercase collision, like "already exists: <filename>" or "target system is case insensitive, collision"
 - any steps to reproduce the problem. --> Try syncing subdirectories "blah" and "Blah" from Linux to Android

Also fill out the version information below and add log output or
screenshots as appropriate. --> Version on Linux = v0.14.18-dfsg1, Linux (64 bit) "Dysprosium Dragonfly", version on Android = v1.1.2-dirty + 1.1.2.1

Syncthing Version: Version on Linux = v0.14.18-dfsg1, Linux (64 bit) "Dysprosium Dragonfly", version on Android = v1.1.2-dirty + 1.1.2.1
OS Version: Debian stretch, Android 8.1.0
Browser Version: (if applicable, for GUI issues) Firefox 60.6.1esr (64-bit)

Some comments: It was driving me mad. Tried repeatedly. After syncing about 95% it got stuck with "out of sync". Then I discovered that the source system had subdirectories with same names except casing (blah and Blah). Renaming one of both subdirectories made the problem disappear. It would be nice to have some more clear error message than just "out of sync".

Before I forget: Thanks a lot for Syncthing. I love it. It's an excellent synchronization system.

**Comment by calmh** [comment]
I sympathise, as the current behavior is crap. However I'm not sure how to do this without actually understanding case insensitivity to begin with, which is the problem.

**Comment by marco-m** [comment]
hello @calmh first of all I want to repeat what @Px3XjG6P stated: "Thanks a lot for Syncthing. I love it. It's an excellent synchronization system." ❤️ 

I went through the existing tickets about case insensitiveness (especially #2739) and I understand it is difficult. Now, to this specific feature request, would the following approach work?

Introduce a sort of heuristics. In case of "out of sync", run a series of heuristics to determine what the detailed error might be. For example, if the only changes between the two devices are in the file names, and are a permutation of case, then report to the user that it might be related to case sensitivity.

I am not familiar with the internals of Syncthing, so it might very well be that what I am proposing is garbage :-)

**Comment by AudriusButkevicius** [comment]
The problem is that names in the database are stored with case sensitivity, so when we we try to download the file with new case it does not exist in the database, yet when we check on disk, it does exist (albeit with different casing), and we decide that we need to rescan.

Comfortably when you ask windows if a file exists, it will tell you that it does and it will tell you that it has the exact same casing you gave to the function checking it's existance, not the real case it's stored in the filesystem which is only visible when you do listdir etc.

The only way to do the said heuristic is to either traverse the whole database trying to find an existing file with matching case (as for all that we know the case might have changed at some folder close to the root), or do silly directory listings on every directory up to the file. 

And even if you find the different name, what do you do? Rename some directory that might have changed somewhere along the path? What about all other files there? Now the database and the disk disagrees...

**Comment by marco-m** [comment]
> Comfortably when you ask windows if a file exists, it will tell you that it does and it will tell you that it has the exact same casing you gave to the function checking it's existance, not the real case it's stored in the filesystem

😱 

Thanks for the explanation @AudriusButkevicius, I was too optimistic :-)

**Comment by sisu4syncthing** [comment]
> Both are expensive.

Ok, both ways (which may lead to a possible solution to this case sensitivity thing) are expensive.

And, certainly, we (the users, not the developers) "need" a solution which will eliminate (or clarify at least) the "out of sync" messages, just because a simple rename of a file/folder did happen and Syncthing does not want to do any harm.

I'm not sure, if or what is a good way to go, but which way can we start with to have this (reallly, really inconvenience) behaviour of Syncthing stop and make those "simple" renamings just "simple" renamings (which needs no attention from the user)?

**Comment by lieryan** [comment]
As a user, probably the easiest and best way to fix this, if you're using fairly recent Windows and NTFS, probably would be to change any folders you're using Syncthing to be case sensitive. Note, I don't use Windows myself, so I can't say myself how well this actually works.

If you're using FAT (which is how SD card are usually formatted as, even in Android), well, don't use FAT. Your best bet might be to reformat your SD card to a case sensitive filesystem that's supported by Android like ext3/4, or yaffs2 or jffs if your phone supports them.

**Comment by vacari** [comment]
> Antes que eu esqueça: Muito obrigado pelo Syncthing. Eu amo isso. É um excelente sistema de sincronização.
Same thing here.

**Comment by G2G2G2G** [comment]
To kind of add more "ways to get around the issue" with what @lieryan said:
Right now the best work around I've found at our company is running syncthing on Linux only and having a samba at each location (and VPN access with the same share drive) so people can just use network drives on LAN and vpn + network drives anywhere else. Works great, also saves devices like phones which do not have enough storage to sync our data anyway. 

About 2 years ago we had tons of case sensitive issues because of 50 windows machines and 20 linux machines all clashing constantly. 
From the looks of windows development, it is quickly headed toward a case sensitive file system in the near future. Since they're trying to embrace & extinguish Linux and gobble it into their operating system.

**Comment by daviddelikat** [comment]
2 thoughts...
1. as a user, when I get the conflict, from now on I will rename the local file so that it does not conflict.  this should eliminate the issue locally without creating an issue on remote hosts...  [ I tried renaming the file to match the remote file, but it then causes conflict elsewhere ]
2. from a development side, it seems the only time to check for case issues would be when you try to save a file and it fails.  if a file create fails, then check for a case related issue.  if the problem is with a directory, this may be not help, but if a file exists with a different case combination, then check to see if the files are the same, if they are, then mark the file a success, perhaps indicating the case issue for future reference.
finally, I want to re-iterate the gratitude for the awesome tool that is SyncThing; it has served me well for quite a while now.

**Comment by alyandon** [comment]
I just got bitten by this and was not even aware that this was still a problem.  I have a directory shared one-way between two Windows instances that contains a file that was renamed on the source side to the same name with different casing.  I have no control over the renaming as an application is responsible so what is the procedure to coax the sync to happen?

**Comment by CobraA1** [comment]
Humm, decided to do some research - and case sensitivity with NTFS is quite the rabbit hole.

Here is a good article on the topic I found, maybe it can help.
https://www.tiraniddo.dev/2019/02/ntfs-case-sensitivity-on-windows.html

Also the CreateFileA API documentation, which is a wealth of information it seems.
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

> The problem is that names in the database are stored with case sensitivity, so when we we try to download the file with new case it does not exist in the database, yet when we check on disk, it does exist (albeit with different casing), and we decide that we need to rescan.

Maybe a flag can be put in the database indicating whether a folder is in a location that exhibits this unusual behavior? Would that help inform the code what is happening?

> 
> Comfortably when you ask windows if a file exists, it will tell you that it does and it will tell you that it has the exact same casing you gave to the function checking it's existance, not the real case it's stored in the filesystem which is only visible when you do listdir etc.
> 
> The only way to do the said heuristic is to either traverse the whole database trying to find an existing file with matching case (as for all that we know the case might have changed at some folder close to the root), or do silly directory listings on every directory up to the file.
> 
> Both are expensive.

When the rescan happens, can it resort to an expensive operation? It seems this rescan trigger is rare. What is the rescan doing anyways if it's not picking up the capitalization changes?
