### ISSUE TITLE
Sync Fails When Replacing File with One of Same Name

### ISSUE THREAD

**Issue by markmcb** [syncthing/syncthing#5716]
### what happened

Replacing a file with one of the same name causes sync to fail.

### what you expected to happen instead

New file gets synced.

### any steps to reproduce the problem.

Two systems, A and B. A is send only, B receive only. On A I have file F. I created a new copy of F in a non-synced folder on A. I then moved the new F such that replaced the old F. Still called F, same location as before.

Syncthing says it's out of sync and seems to give up. 

I can resolve the issue if I log into B and manually deleted F, restart syncthing on B, then click "revert local changes"

This happened six times before I noticed it and started deleting the to-be-replaced file first. All files were large (>1 GB).

### Version Information

Syncthing Version: v1.1.3
OS Version: Fedora 30

**Comment by calmh** [comment]
Your use case sounds like the simplest, most guaranteed one of "I changed a file" (atomically), so should of course work, and has since essentially the first version of Syncthing. The only oddity is the send/receive only folders. I tested your reproduction steps now and it works as expected for me.

As such this needs much more narrowing down of the cause, I suggest you turn to the support forum to get help. Once a bug is determined and we know what it is we can reopen.

**Comment by markmcb** [comment]
Ok, maybe I'll raise it over there. The only unique thing I did was use "midnight commander" to move the files, and it was across file systems. Syncthing definitely noticed there was a change, as I could see the temporary hidden file with the to-be copied file name, but it wouldn't continue.
