### ISSUE TITLE
Keep file's modification time (mtime) when archiving (moving the file to .stversions)

### ISSUE THREAD

**Issue by gamato** [syncthing/syncthing#5728]
Please keep modification time (mtime) of a file when moving the file to .stversions folder.

Right now an archived file keeps its creation time (so I guess it is moved to .stversions, not copied) but its mtime is changed to when it was archived. This is unhelpful in case I want to restore the file by moving it back from the archive folder.

**Comment by calmh** [comment]
We intentionally set the modtime to the archive time because this timestamp is used by the various cleanup strategies that determine how many versions to keep per day, or how long to keep versions, etc.

There are valid reasons to do things both ways. We've chosen this one and depend on it, and likely there are also users that depend on it since it's been this way "forever". Hence it would take something much stronger than personal preference to change this.

**Comment by gamato** [comment]
Oh :( ... I needed to restore files from .stversions and I had to fix mtime manually for each of the files. That's a lot of unnecessary work and I'm afraid I'll have to do it again in future occasionally.

The files have not changed so there's no reason from user's point of view why their modtime should change, imho.

Perhaps you could use create (birth) time instead. That is already not kept by Syncthing when synchronising. Or maybe you could store the info in the database, as is done for other things already.

And if you think existing behaviour may be depended on externally, then it should be easy to introduce a switch that controls the behaviour. Thanks.
