### ISSUE TITLE
Hook system for custom versioning (git, etc)

### ISSUE THREAD

**Issue by M0dM** [syncthing/syncthing#573]
Hi,

I thought it could be interesting to use the libgit2 library to provide a complete versionning system.
I want to speak about a local git repository shared between nodes.

Juste create one git repository at each repository creation directly inside the repository main folder.
Each time a modification into the folder is sync -> a commit is created
Like this all revisions are into the .git folder

We also could for example delete automatically the old commits and keep only the last 30 (more or less) commit.

For example :
The user add a file and the sync is launched by the node 
      -> before sync it : create a local commit
      -> if more than 30 commits -> remote the older one
      -> sync all with the new added commit 

the user want to rollback a file or all changes made at last sync : revert to the previous desired commit

We also could think about tag every single commit like this : date-repositoryName-nodeName

I think this could be a good way to give to syncthing an awesome versionning system by simply using an already one -> git

Also this could be totally transparent for the user by just clicking on the web interface on a revert button on the desired file or directory.

Edit : LibGit2 is 100% crossPlatform and a go wrapper already exist
         -> https://github.com/libgit2/git2go

**Comment by alex2108** [comment]
> I'd rather implement this as some sort of hook system, where syncthing can be told to execute commands prior to starting a sync "transaction"

I started implementing the "prior to starting a sync" part as a versioner and I have some questions about implementation details:

1. I think the external script (instead of the syncthing versioner part) should remove the file (it can be moved instead of copied), what should the versioner part of syncthing do what that failed? (file still exists), my suggestion is removing the file to be able to continue normal operation and print a warning to the GUI.
2. Do we need to be able to set the parameter given to the script in the config? My current implementation just passes `folderPath` and `inFolderPath` to the script as first and second argument. Since it most cases the script used will be written for syncthing I think we don't need to make this configurable and if someone needs to pass parameters in another way a simple wrapper scrippt should be fine.

**Comment by calmh** [comment]
@alex2108 For 1, the existing versioner things guarantee (as far as possible) that the file that is going to be archived doesn't exist after the call to `Archive()`. We should preserve that property. For 2, that sounds about reasonable.

One thing your approach doesn't really address is if I for example want to do a git commit after every sync (or after every file, in this case). If so, the hook needs to be called *after* the file has been replaced. But if the script is implementing a versioning scheme where it's supposed to archive the replaced files somewhere else, then it needs to be called *before*...

**Comment by alex2108** [comment]
Yes the "after replace" part is not addressed by this but I could also try to implement this later. At the end of the `performFinish` function in `puller.go` seems to be the place to put this, right?

But before trying this I want to finish the "before replace" part.

**Comment by Zillode** [comment]
Fixed by https://github.com/syncthing/syncthing/commit/d3f1eaf1a3d131aadb1877da0bb3b048cc2053e3
