### ISSUE TITLE
Consider not logging `http: TLS handshake error ... remote error: tls: unknown certificate`

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5738]
We don't particularly care whether the browser likes our certificate or not, and at least with my Chrome, with the certificate properly accepted and the GUI working, it still spams for every poll;

```
2019/05/21 14:07:34 http: TLS handshake error from [::1]:49156: remote error: tls: unknown certificate
2019/05/21 14:07:34 http: TLS handshake error from [::1]:49157: remote error: tls: unknown certificate
2019/05/21 14:07:34 http: TLS handshake error from [::1]:49158: remote error: tls: unknown certificate
2019/05/21 14:07:44 http: TLS handshake error from [::1]:49159: remote error: tls: unknown certificate
2019/05/21 14:07:44 http: TLS handshake error from [::1]:49160: remote error: tls: unknown certificate
2019/05/21 14:07:54 http: TLS handshake error from [::1]:49161: remote error: tls: unknown certificate
2019/05/21 14:07:54 http: TLS handshake error from [::1]:49162: remote error: tls: unknown certificate
2019/05/21 14:07:54 http: TLS handshake error from [::1]:49163: remote error: tls: unknown certificate
2019/05/21 14:08:04 http: TLS handshake error from [::1]:49164: remote error: tls: unknown certificate
2019/05/21 14:08:04 http: TLS handshake error from [::1]:49165: remote error: tls: unknown certificate
2019/05/21 14:08:04 http: TLS handshake error from [::1]:49166: remote error: tls: unknown certificate
2019/05/21 14:08:14 http: TLS handshake error from [::1]:49168: remote error: tls: unknown certificate
2019/05/21 14:08:14 http: TLS handshake error from [::1]:49169: remote error: tls: unknown certificate
2019/05/21 14:08:14 http: TLS handshake error from [::1]:49170: remote error: tls: unknown certificate
2019/05/21 14:08:24 http: TLS handshake error from [::1]:49172: remote error: tls: unknown certificate
2019/05/21 14:08:24 http: TLS handshake error from [::1]:49173: remote error: tls: unknown certificate
2019/05/21 14:08:24 http: TLS handshake error from [::1]:49174: remote error: tls: unknown certificate
and so on and so forth
```

**Comment by charlescurley** [comment]
I see the same thing. Syncthing 0.14.37+ds1-1~bpo9+1 on debian 9 (stretch). E.g:

Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57720: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57724: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57722: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57726: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57730: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57728: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57734: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57732: remote error: tls: unknown certificate
Jul 11 13:13:24 dzur syncthing[541]: 2019/07/11 13:13:24 http: TLS handshake error from 192.168.100.25:57736: remote error: tls: unknown certificate
Jul 11 13:13:26 dzur syncthing[541]: 2019/07/11 13:13:26 http: TLS handshake error from 192.168.100.25:57740: remote error: tls: unknown certificate

**Comment by charlescurley** [comment]
Shutting down the browser (Vivaldi vivaldi-stable  2.6.1566.44-1) on the remote machine ended the problem. The problem is that the browser does not like the syncthing server's cert.

**Comment by charlescurley** [comment]
Here's what vivaldi has to say:

Your connection is not private
Attackers might be trying to steal your information from dzur (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
Subject: dzur

Issuer: dzur

Expires on: Dec 31, 2049

Current date: Jul 11, 2019

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIC3zCCAcegAwIBAgIIXR1QmrEym6QwDQYJKoZIhvcNAQELBQAwDzENMAsGA1UE
AxMEZHp1cjAeFw0xOTA2MDIwMTUxMTBaFw00OTEyMzEyMzU5NTlaMA8xDTALBgNV
BAMTBGR6dXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDcr3l23vdx
SC//t5L6QolgaLm+z0MtKPYMnTt6rQQfuHA6WmrvhPMrn0D2H7hJSN5xaMtDLaVx
h7rEVwc/J61kXVqLDHa+1ExWPAK6KoTs4u42tQzJjlQAXAJXgw4UWQUeEil1MZBy
GHVkfycvPjceOG6YxcbQVWfDZ0qy7nn4R4fQXcXBbgKIfnYlpmW9+Vc1sj/4Iu0Y
hw8vHpp9doEXocLLXbfMuIVHHQbKvgridvNglySmhOJzfyf2iCI+WvbUtpGsZkNU
q6duV5s5sU47tJFitwiRa890wEli30YI+sq+FmZ+SRfyzV7DARIXEdWyOlS941ym
hbs0OTjm/PKFAgMBAAGjPzA9MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOC
AQEAqLsGLSpLr30iBe/HDcvcUX9zhie4GnIARERjmygnd2CeQX9rkWynbetY1tNJ
vJK9UpL3OdLdKcaMj4qD1kkuF1hxKzu43MgqHNBT4km732FKxvvnVzaJ+FOrACPv
P3bkExAoSXvEkGh7KhoNBhwSTQY5SFZLyYhc/91qKvw7xUhaHpa/BZAS3pcmxu0t
tJeTniXbVIUKtSgcx1ZiYT6No8NdpCIC+Bv5poQ4E6hJ7QKrskO+9CKaAiLeen1J
EC5gv5yB4m5UG0S4pAScdJLEBQ/Qa3wKM+QA8wjHNouKdOKNK4AU8xI1tTp+7kwF
W5XUGRIf1tmDz/6VCBg56u+pVA==
-----END CERTIFICATE-----

This server could not prove that it is dzur; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by AudriusButkevicius** [comment]
Syncthings certs are self-signed, so it's expected for them not to be trusted.

**Comment by charlescurley** [comment]
> Syncthings certs are self-signed, so it's expected for them not to be trusted.

Well, then why log them?

**Comment by charlescurley** [comment]
Also, it appears that the server logs when I have two browsers looking at the one machine, but not when I only have one.

**Comment by AudriusButkevicius** [comment]
I am not saying we should log it, I am saying not being trusted is expected. This issue is still open, so we still agree that we should not log it.

I think wether the error comes up or not depends on the browser (the client), and whether it chooses to report an error back to the server or not. I don't think it's related to the count.

**Comment by Ayouberramdan** [comment]
run  apt install libnss3-tools
then run sudo symfony:ca:install
and reload browser
