### ISSUE TITLE
Sync progress can show negative percentages

### ISSUE THREAD

**Issue by skion** [syncthing/syncthing#592]
The files-to-sync can be higher than the files in the global repository:

```
 Globale repository   4922 objecten, ~26.7 GiB
 Lokale repository    0 objecten, ~0 B
 Niet gesynchroniseerd    5027 objecten, ~27.4 GiB
```

When this happens, the sync percentages in the Web UI become negative. Presumably happens when the repo filelist is still being downloaded.

**Comment by sKvps** [comment]
Still seeing this in v0.11.0-beta1, attached below
![ohrgx](https://cloud.githubusercontent.com/assets/562917/6962814/47eb7738-d930-11e4-846e-43ca58461731.png)

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/issues/1567

**Comment by juh2** [comment]
I just saw it on the device side.

![bildschirmfoto vom 2016-08-22 09-00-10](https://cloud.githubusercontent.com/assets/1416069/17846124/f45d64bc-6846-11e6-9e57-cbe4df8c7404.png)

**Comment by Nasnl** [comment]
Yup, I also have it on both sides.

![image](https://cloud.githubusercontent.com/assets/8427570/17864003/6d50ab40-689c-11e6-82c7-76cdb4d0eda1.png)

**Comment by uok** [comment]
@juh2 and @Nasnl can you provide steps to recreate this issue?

**Comment by Nasnl** [comment]
@uok I'll try. I've had it several times, also after de-installing and reinstalling Syncthing.

First time:
- 2 (identical) synology boxes, both with Syncthing 0.14.4
- Both on their own LAN, each LAN connected to the internet
- I used BTSync before to sync 220 GB data (without problems, by the way, but it was no longer supported by DSM 6.0)
- I connected both installations through the UUID
- I created directories on the master (Office) and had them scanning for 5 days
- I shared them to the other box (Home) and accepted them on that side
- They started syncing for about 10 days (both boxes very busy 24hrs/day, but almost no traffic). Then I was at -9%.
- Then I got frustrated and uninstalled everything.

2nd time (I still need a sync anyway and now I left BTSync, so I'll try again):
- same hardware and networks
- Currently, I have just one directory (homes) of 118 GB that I try to sync, now for 4 days
- I shared the directory after I left it scanning on the master until it said Up to date
- then the home installation starting syncing; first growing to 6% and then jumping to -8 or -9%
- there is is now since the last 24 hrs

Ask me anything. I'm happy to contribute, but I'm not a developer, so keep it 'simple'. ;-)
