### ISSUE TITLE
"Local discovery" broadcast breaks mobile/cellular connection

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing#5957]
"Local discovery" broadcast breaks mobile/cellular connection of at least one Cellular operator (Visible @ USA).

It seems the cellular network or provider-specific services in the OS are "allergic" to the broadcast. Changing the port number did not help.

I would suggest limiting local discovery functionality for use on WiFi only.

Maybe the daemon should have a runtime/command-line option to override the feature configured in permanent config so the wrapper/GUI will have the option to detect the condition and pass it to the daemon.

Syncthing Version: v1.2.0
OS Version: Android 9.0
CellOperator: Visible@USA
Browser Version: Android GUI

**Comment by AudriusButkevicius** [comment]
First of all, wrong repo, second of all, you can disable local discovery from the web ui.
Thirdly, your provider should get their shit together.

**Comment by eugenesan** [comment]
First, thank you for such a prompt response.
Second, why is it a wrong repo?
Currently, the daemon supports either enabling the feature or disabling it. On mobile platforms, where type the connection might change on the fly, regardless of the "shittiness" of the ISP, differentiating between types of connections would be a useful addition. Why send local discovery broadcast when not on local network?

P.S. I agree, the provider is at fault for failing with UDP broadcasts.

**Comment by AudriusButkevicius** [comment]
Because syncthing itself has no concept of different types of connections, so if this was due to be fixed, it would have to be fixed in the android wrapper to toggle local discovery based on the connection type.

Yet, this is a network provider issue, and I'd be against adding random workaround into an application to work around some one bad provider.

There is no harm in sending broadcasts all the time, after all, they are broadcasts, looking for things regardless where you are connected to.

Perhaps there is an equally bad provider out there, where people connected to the same tower happen to be in the same LAN with broadcasts enabled 🤷‍♂
