### ISSUE TITLE
Folder "Up To Date" but has pending "Revert Local Changes"

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5968]
I have a Receive-Only folder which has local changes and is displaying the "Revert Local Changes" button. Its status shows as "Up To Date", so without expanding the folder in the GUI there's no apparent need for attention for the folder. I would expect that users need to know if a folder has pending changes to Revert, so perhaps the folder status should show something other than "Up To Date".

**Comment by AudriusButkevicius** [comment]
It's up to date in terms of the files that are advertised in the cluster, all of those files are in sync. 

Sure, perhaps there are some local files, but does that make it out of date with the rest of the cluster? 

It's debatable hence I think this should start on the forum rather than the bug tracker, as it's not obvious what the right behaviour is, and the fact that your view is that it's wrong does immediately turn it into a bug.

**Comment by MasterDimmy** [comment]
Folders are same as i manually copy from master to backup.
But button "revert local changes" never dissapears.

Folders of sync are absolutely identicall, even the date of change and creation of the each file.

I pushed button  "revert local changes" many times, do restarts, do again copies, but all the same.

![222](https://user-images.githubusercontent.com/10881942/63635832-d6dd2f00-c66f-11e9-8b72-784f4aecbfe0.png)

**Comment by imsodin** [comment]
@MasterDimmy  The revert button not working has nothing to do with this issue. Please open a thread on the forum so we can try to figure out what's going on and once we do, open a new ticket regarding that.

**Comment by MasterDimmy** [comment]
> 
> 
> @MasterDimmy The revert button not working has nothing to do with this issue. Please open a thread on the forum so we can try to figure out what's going on and once we do, open a new ticket regarding that.

What is the link to the forum?
Its a really annoying bug

**Comment by imsodin** [comment]
Really? forum.syncthing.net
