### ISSUE TITLE
macOS with APFS filesystem - disk free space issue

### ISSUE THREAD

**Issue by kapitainsky** [syncthing/syncthing#5976]
Recently syncthing I run on my laptop started to stop working (all sync folders show stopped status) randomly with GUI interface reporting errors:

2019-08-24 15:48:49: Error on folder "digitalocean01-home" (#####-#####): insufficient space on disk for database (/Users/admin/Library/Application Support/Syncthing/index-v0.14.0.db): 4.977454 % < 10 %

The situation was puzzling initially as I have plenty of free disk space. E.g. at the moment when above error happened Finder was showing 200 GB free (out of 500GB disk)

Situation would go back to normal after few hours but then would re-appear again. No other program reported low disk memory.

After poking around I identified issue as related to local disk snapshots (used by time machine).  macOS with TM (time machine) enabled takes semi hourly local snapshots of the whole filesystem - it is cheap and fast thanks to COW feature of APFS. Disk space taken by snapshots is not reported by macOS as used but instead Apple calls it purgeable and OS free it if required.

In my case issue is related to heavy use of Virtual Machines recently. BIG files changing frequently - so snapshots very quickly "eat" all available space. Now properly behaving macOS application should read free space available via system call which takes into account purgeable data (as they are freed by OS when space is required).

Not being developer myself I can't easily identify in syncthing source code what method of free space checking is used but my experience shows that it is not the one that should be.

I verified my findings by forcing heavy disk usage and when synching stops with errors I forced snapshots purging (tmutil thinlocalsnapshots / 100000000 1). As expected it makes synching to start again.

### Version Information

Syncthing Version: v1.2.1
OS Version: macOS 10.14.6 (Mojave)
Browser Version: N/A

**Comment by AudriusButkevicius** [comment]
Just set that to zero, sadly this is Go application, not a "proper behaving macOS application", so I suspect there isn't even away to look up these magic numbers you are talking about.

**Comment by calmh** [comment]
This is unfortunately a "functions as designed" sort of situation. We ask the system how much free space there and it tells us. Finder shows something else because it adds purgeable data, but that's a fiction that isn't exposed to the unix side of things.

<img width="560" alt="Screen Shot 2019-08-24 at 16 59 51" src="https://user-images.githubusercontent.com/125426/63639211-f89ade00-c690-11e9-8f4d-6b9106b23159.png">

(There's also 1024-vs-1000 going on in that screenshot but that's a small part of the difference.)

It's not 100% clear to me either what happens when we try to use the supposedly available purgeable space. Does it instantaneously free up the space that wasn't otherwise available? Or is this more of a "it'll clean up periodically once it gets close" sort of situation? From my expectations on time machine I think it's more of the latter, in which case we would run into an out-of-space error anyway if we assumed purgeable space was available and quickly tried to use it.

All in all, we're not going to implement the Finder-like free space accounting, a workaround is to disable the check as Audrius says (or free up more space).

**Comment by kapitainsky** [comment]
Thank you for clarification.

In response to calmh question I did a bit of google and Apple claims that snapshots (and also cloud locally cached data) are cleaned on demand hence Apple does not count it as disk occupied space. Problem is that it is not clearly documented and multiple developers complain about ambiguity of Apple solution here.

I am happy to set free disk space requirement to 0 in the meantime. In my usage risk of getting into trouble is minimal.
