### ISSUE TITLE
Failure to detect renames/moves causes data loss

### ISSUE THREAD

**Issue by madduck** [syncthing/syncthing#5978]
If a file is renamed on one side, the whole file needs to be retransferred, even though all the blocks are already present on the other side. I believe this is tracked in #5660.

It just happened to me though that the remote could not download the new file, reporting "no connected device has the required version of this file". Yet, as next step, it happily removed the old remote file, so it clearly had access to the other device.

I am sorry if this is a bit vague. I am still trying to understand what's going on, and to reproduce the issue. I'll update the issue accordingly.

### Version Information

Syncthing Version: 1.2.1
OS Version: Debian 9.9

**Comment by calmh** [comment]
Blocks are not downloaded if they are already present. However, with 1.2.0 we switched everyone to large blocks, and if you had not done so manually before it's likely that you're seeing the first change to a file after switching to large blocks? They are then all "different" (because different size & hash) and it doesn't see that it can reuse them. Subsequently it will.

The race for detecting renames is a different issue; even when it fails it becomes a copy+delete instead of a rename. It does not become a re-download.

**Comment by AudriusButkevicius** [comment]
Try reproing, if it still happens, shout.

**Comment by madduck** [comment]
> However, with 1.2.0 we switched everyone to large blocks, and if you had not done so manually before it's likely that you're seeing the first change to a file after switching to large blocks?

This was almost certainly the case/problem. Thanks @calmh!
