### ISSUE TITLE
Windows: 1) running Syncthing opens not only a browser tab but also a terminal; 2) 'editing' the sync folder settings produces an uneditable field

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6055]
- I downloaded the Windows version of Syncthing, by using the '64-bit' link on https://syncthing.net/.
- I downloaded and then ran Syncthing. (The download appears to be a portable application. I ran it by running `syncthing.exe`, even though there is another file that appears in Windows Explorer with the same name but, I think, a different extension. All of this is unhelpful.)
- A terminal window appeared as well as browser tab. Clearly enough, that terminal window should not appear, at least not without explanation. If there is some wrapper I should use, then that should be made clear.
- In the browser tab, I tried to edit the default synthing folder - by clicking edit. Adjacent the field containing the path for the folder, one reads about how, if the folder specified does not exist, it will be created. All of this suggests one can edit the path as indeed one should be able to. I tried to edit the path field. It was not editable. I closed the tab and tried again. Same result.

### Version Information

Syncthing Version: v1.3.0
OS Version: Windows 10 1903
Browser Version: Firefox 69.0.1 x64

### Other information

This is the third time I have tried Syncthing. I really want it to work. But the problems that I encounter each time are gross (and this time I have not even tried to get it working on Linux or Android.)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by LinuxOnTheDesktop** [comment]
I am not asking for support. I am reporting a fairly gross problem with your interface.

**Comment by calmh** [comment]
> terminal window should not appear, at least not without explanation. If there is some wrapper I should use, then that should be made clear.

<img width="1579" alt="Screen Shot 2019-10-03 at 19 58 39" src="https://user-images.githubusercontent.com/125426/66151810-591a2500-e618-11e9-999f-f492363abba2.png">

You might be happier with SyncTrayzor. Gross or not, what you're complaining about is by design or largely unavoidable and will not change in the near future.
