### ISSUE TITLE
2Gb index-v0.14.0.db

### ISSUE THREAD

**Issue by 532910** [syncthing/syncthing#6063]
```
% du -sh .config/syncthing/index-v0.14.0.db
2.2G	.config/syncthing/index-v0.14.0.db

% ls -1 .config/syncthing/index-v0.14.0.db | wc -l
938
```

debian sid, 1.1.4~ds1-4

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by 532910** [comment]
`.config` MUST NOT take 2GB!
I don't need support.

**Comment by 532910** [comment]
Moreover, the  `~/.config` is the wrong place for index files.

**Comment by AudriusButkevicius** [comment]
I think it's an ok default as all distributions are different, and I wouldn't be surprised if some lack /var/lib etc.

People can change that on the command line if they wish (or just symlink I guess)

**Comment by 532910** [comment]
I think all distributions respect https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by 532910** [comment]
Also I think that .config must be backupable, and 2Gb of strange files is too much for backup.

**Comment by AudriusButkevicius** [comment]
The index should be backupable too, as you'd end up with conflicts if you restore the config but not the index.

It's size is proportionate to the number of devices and number of files/their size.

**Comment by 532910** [comment]
You a wrong, as after `syncthing -reset-database` index-v0.14.0.db is 32Mb!!!

**Comment by 532910** [comment]
So, reopen this issue please.

**Comment by AudriusButkevicius** [comment]
Something being big does not automatically make it a bug, as it's all down to various circumstances which are not explored here.

As I suggested before, this should be moved to the forum until we can understand the cause of this, and then, if it's deemed to be a bug rather than big for some good reason, we can reopen this.

**Comment by 532910** [comment]
https://forum.syncthing.net/t/2gb-index-v0-14-0-db/13878
