### ISSUE TITLE
Feature request: Ignore depending on file size

### ISSUE THREAD

**Issue by poisonborz** [syncthing/syncthing#6103]
_Disclaimer: I know this was asked and closed 2 times already, but there still was not any discussion on why this would be a bad idea. Also this could be done as part of #2491, but that discussion is a bit fuzzy and this feature is a bit more standout_

Through the ignore files, SyncThing could ignore files if they are under, above, or are equal to a given byte size. Example usage scenarios:
- Mobile device users who want to sync small files but want to avoid large dropped in downloads
- Remote security device with a motion-detecting camera - only large (long, therefore of interest) videos should be synced

In another issue a dev mentioned that this would open the gates of users asking file content analysis but I don't see why - file size is just a standard file property just like the title/path.

**Comment by AudriusButkevicius** [comment]
Nobody does it, and this is so niche that it deserves something custom. 

We don't want syncthing to become "includes a kitchen sink" type of product, where there is so many knobs that users are just baffled how to use it (which is sadly already the case).

Also, we are not going to wedge in features just to fill a feature gap in motion detecting cameras.

You can write a post processing script that copies/moves only large or only small files to syncthing's directory.

**Comment by calmh** [comment]
Apart from the above it *is* also a bad idea on its own.

It means that if we are sharing a file and I edit it so that it moves into some ignored byte threshold you will not get that change, which is surprising as it's not based on any config change. Also, in that situation when the other side edits *their* copy which is *not* in the ignored size range, what happens? Is it ignored or not? If it is, that's odd because it's not in the ignored size range. If it is not, that's odd because my file is in the ignored byte range and was just overwritten.

All in all it would be very confusing.
