### ISSUE TITLE
high RAM usage with high lan network speed

### ISSUE THREAD

**Issue by rezad1393** [syncthing/syncthing#6119]
I have installed latest version on openwrt router (arm based with 500MB ram) and laptop to sync files between them.
when I have near router my wifi speed goes up and so syncthing speed goes up too but that makes it use way more RAM and hangs the router system.
it this preventable with only network speed limit or can ram usage limit be added?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
