### ISSUE TITLE
Consider XXH3 hashing function as experimental feature

### ISSUE THREAD

**Issue by markg85** [syncthing/syncthing#6120]
Hi,

XXH3 seems to be the new kid in town when it comes to blazingly fast hashing functions.
There is a go implementation here: https://github.com/zeebo/xxh3
And the original article introducing the function is here: https://fastcompression.blogspot.com/2019/03/presenting-xxh3.html

I do not know how well it compares to adler32 (which i believe is the current hashing function used in Syncthing). But as xxHash already beats Adler32 hands down and this XXH3 is supposed to be even faster then xxHash was, it's safe to assume this one is just faster :)

As this one is still in development, it might be best to mark it experimental and not default to it. 

Cheers,
Mark

**Comment by AudriusButkevicius** [comment]
Syncthing needs a cryptographically secure hash, which I don't think any of the XX hashes are. We use SHA256 which is implemented in assembly, with some CPUs having native SHA256 instructions which I doubt userland implementations can beat. We do use adler32 as a rolling hash, but that is never the bottleneck. The reason we use adler32 is because it has a rolling property, where you can add a single byte (which drops of last byte of the window) and recompute the hash of the whole window with constant factor regardless of the window size, I don't think XX hashes have this property.

**Comment by markg85** [comment]
Fair enough.
Thank you for the explanation :)
