### ISSUE TITLE
Feature Request: Sharing Features

### ISSUE THREAD

**Issue by trymeouteh** [syncthing/syncthing#6126]
Many cloud storage providers allows you to create a sharing folder which allows you in return to share files with friends and family. I would like to see more features to make Syncthing used as a way to share files between others, here is what I would like to suggest.

Create public Sync ID
Instead of sharing your device ID, to be able to create another Device ID or be able to have a secondary device ID that is meant to be used when sharing files with others and using your main device ID for your own personal devices

Allow/Block Subfolders
An option to not allow subfolders to be synced within the syncthing folder

Data Cap
Set Data Caps to prevent someone from transferring a large file over

Folder Size Cap
Have a cap on how much the folder can contain, this can prevent your folder from ending up to be gigabytes in size.

Approve Transfer
Instead of setting up the device and then the folder connection. You can set a folder to approve the files from another device to be sent over before they are. Maybe even seeing what the files and folders are and how big the files are.

Folder Admin
If you created the folder you can set yourself as the admin, which means only you can share the folder and no one else. So if you created the folder and shared it with Bob, Bob cannot share the folder with others.

**Comment by AudriusButkevicius** [comment]
* Create public Sync ID - device ids do not need to be secret, there is no reason to have secondary device ids
* Allow/Block Subfolders - already supported by ignores
* Data Cap - rate limits is an already existing feature
* Folder Size Cap - use a filesystem that supports quotas
* Approve Transfer - there is already an introducer feature and auto accept folders from trusted devices
* Folder Admin - this is logically impossible to implement, as once Bob has the files, he can do whatever he wants, also, admin is not a sensible concept in a "everyone is equal" peer to peer system.

**Comment by Ferroin** [comment]
> use a filesystem that supports quotas

This is not going to realistically be an option for a large percentage of users. 

* On Android (where it's probably the most useful), it's literally impossible. There is zero end-user accessible quota support on Android, period.
* On Windows, you only have volume-level per-user disk quotas, so no matter how you do things, setup will be complicated beyond the level of the average user (overall limiting would require either a dedicated volume for Syncthing or a running Syncthing under a dedicated user, per-folder limiting would require a volume per folder (at which point quotas are pointless)).
* On Linux, it's only marginally simpler than Windows. You'd need to manage a project quota per folder (which limits your filesystem options, and is, again, complicated), use a dedicated user for Syncthing, use a dedicated volume for each folder, or use BTRFS (because qgroups _could_ do this pretty easily, though that brings it's own set of issues, namely that they're hard for many people to understand and they have a significant negative impact on performance) or ZFS (though that will require a dataset per folder, which is almost as bad as a volume per folder).
* On macOS you have similar limitations to Linux, except that you can't use project quotas (because macOS doesn't support them, only user or group quotas), and BTRFS or ZFS are not an option.
