### ISSUE TITLE
Non-source / read only / untrusted / backup devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#62]
I.e. ones that we never accept updates from, but who can otherwise participate in the exchange as usual. Needs #63 to work securely.

**Comment by dzarda** [comment]
I have found myself in the need of this feature. After reading through this, I got the idea of _setting the scan rate to 0._ This seems to get rid of the Hard-Drive-not-sleeping issue. Syncthing seems to accept this quite well - it disables HDD checking, CPU sits at 0%, so does IO activity.

Note: This is a per-directory approach.

Is this a documented feature? Or did I just create a feature out of thin air? :)

**Comment by Nutomic** [comment]
@dzarda That's definitely working as intended (we use it to disable the scanner on Android where inotify is implemented). I'll update the wiki on this.

But I think it doesn't solve this issue, as it doesn't protect against malicious devices.

**Comment by generalmanager** [comment]
There are many different use cases in which this could be useful. I'll describe a setup which includes the more common ones and their difficulties.
Please skip to the description at the end if you are familiar with the problems of the currently implemented "master" devices.

There are five devices:

1. desktop PC
2. laptop
3. smartphone
4. server
5. a friend's PC

There are four folders:

**1. A global share folder:**

Device | Folder rights
------------ | -------------
PC | RW
laptop | RW
smartphone | RW
server | RO
friend's PC | RW

This is currently not possible, because if all devices exept the server were "master" nodes, they would ignore each others updates. If no device is set to master mode, the RO device would have RW access tough.

**2. A folder containing the pictures from the phone:**

Device | Folder rights
------------ | -------------
PC | RO
laptop | RO
smartphone | RW
server | RO
friend's PC | --

This is possible with the current "master folders", but does not automatically overwrite changes on RO devices, which is very annoying in many cases.

**3. A folder to exchange files between you and a friend:**

Device | Folder rights
------------ | -------------
PC | RW
laptop | RW
smartphone | RW
server | RO
friend's PC | RW

This is not currently possible, same reasons as in **1.**

**4. A backup folder which you entrust your friends with, but you don't want them to make local changes, because it would destroy your backup:**

Device | Folder rights
------------ | -------------
PC | RW
laptop | RW
smartphone | --
server | RO
friend's PC | RO

This is a combination of case **1.** and **2.** While master mode blocks exchanges between the master devices, it doesn't protect one RO device overwriting another RO device. Additionally changes on either RO device are not automatically overwritten, ruling out Syncthing as a backup solution.

**I've got an idea how we can get this to work in a way that is not as horrible UX/UI wise as one would imagine.**

This "this is an RO device" setting should have the the following properties:
1. Be folder specific. As you can see "friend's PC" can RW in case 1 and 3, but RO in case 4. A setting for all folders breaks this common use case where people have friends but no servers.
2. Be secure. As in every device should only be able to change the access rights different devices have in a folder from RO->RW from it's own perspective, but not on other devices.
3. Not be a pain in the ass to setup.

Usually this would mean that we either have to build a decentralized trust or consensus system (like the blockchains of most crypto currencies), which is a huge pain in the ass and doesn't work well when some devices are offline OR put our trust in one device which basically has admin rights to edit the folder rights on all devices. While the first solution sucks because it doesn't work well in popular scenarios (several devices offline), the second one could be part of the solution.

*It would be a pain to have to set the RO status of the devices on all other devices, but if we only set them on the RO devices, we could not trust them to stay that way if they are compromised later on.*

Thus my approach is as follows:
- Every device can tell another device that it's a slave for a specific folder and sign this message with it's private key. The other device then changes it's access rights from RW to RO. But the "slave" device can't take it back. If this should be changed later on, it has to be manually changed on all devices.
- Every device relays the signed "I am a slave for this folder" messages to all devices it shares this folder with. That's basically what introducer nodes do with folders, but because this message is cryptographically signed every node can do it.

This way it's easy to setup complex trust relationships without having to manually configure access rights on every device. It also doesn't introduce new vulnerabilities, because a compromised device can only lower it's own access rights on other devices, but not gain new rights.

**Comment by bencurthoys** [comment]
The BtSync approach of having an RW key and an RO key seems to just short circuit all these problems. So in Syncthing language, when I share a Folder with a device, as well as the visible Folder Id, there's a Read Secret and a Write Secret. You need the Read secret to connect to receive changes. You need the Write Secret to send changes. 

We make sure that the Read secret and Write secret are cryptographically related, so if I've only got the Read secret I can verify that the Device sending me changes has the Write secret, but I don't know what that secret is.

**Comment by AudriusButkevicius** [comment]
This requires a central entity which tracks these secrets.
I think BTSync tracker does that.
In syncthing there is no tracker.

**Comment by bencurthoys** [comment]
Does it? From the point of view of my node, I will only accept changes if it comes with a Write secret that I recognise. I will only send changes if the request comes with a Read secret that I recognise. Why do I need to check those secrets against a central entity? When I create a folder, I create a new pair of secrets to go with it. When I share a folder with someone, I send them one or both secrets. When I receive a shared folder, I get one or both secrets, and hand onto them. 

Now, I might, as an attacker, take a Read Only share from you, and then make up my own secrets, and share that on to others. At which point, your original RW node will certainly not accept changes with my made up RW secret, and won't send changes to nodes using the new made up RO secret, but that doesn't really matter. The effect would basically be the same as making a new folder, it's just that the new folder has a confusingly named visible ID part - and new secrets. 

We don't need a consensus as to which secret is the "right" one. Each node can make up its own mind, and I can't think of a failure mode worse than the one we already have - a cluster with two separate Master nodes fighting with each other, ignoring changes, and breaking consistency =)

**Comment by StrikerTwo** [comment]
The BTSync tracker does not know which secrets are correct. It only maps the secret's hash to a list of IP addresses. Each node decides for itself whether a peer's secret is valid for the share or not.

**Comment by AudriusButkevicius** [comment]
Sot the fact that you have a read only and read write secret implies that you need asymmetric crypto.
I haven't seen asymmetric crypto with 16-32 character keys.

Yes, this is possible, but the read write key would be more like 1700 characters, and the read only key would be like 500 characters

**Comment by generalmanager** [comment]
And all that would have to be done in addition to the current model, otherwise there can be no attribution if the key gets leaked to unauthorized parties. I'm rather certain my proposal involves a lot less friction UX wise.

**Comment by AudriusButkevicius** [comment]
Yes, having read/write permissions per device per folder is the way forward.

**Comment by bencurthoys** [comment]
Ah, I think I see the problem. All changes would need to be signed somehow by the Write key, otherwise RO nodes wouldn't be able to help propagate changes; another RO node wouldn't know that the change the RO node is passing on to it was valid, or had actually been written by the RO node. Sorry!

**Comment by StrikerTwo** [comment]
Well, BTSync does it with 33 characters, so it seems to be a solved problem.

**Comment by AudriusButkevicius** [comment]
I am keen to know how you can fit a sensible size RSA key pair into 33 characters without having a central authority.
Perhaps a device advertises that it has a private part and the public part of the following key, and then devices try to contact that node to get it, by providing the fingerprint? But that doesn't sound reliable, as if you have A who has RW, B who has RO, then A goes down, C comes up with RW key, it wouldn't be able to participate.

**Comment by bencurthoys** [comment]
The problem even more simply: A is RW, B and C are RO. A and B are online, C is offline. A adds a file, B syncs the file. A goes offline. C comes online*.

Can C get A's file from B? If so, how does it know it was added by a valid RW node, and not by an RO node?

I don't think your solution deals with that either, @generalmanager. C knows that B is read only, but it still needs data that B has. 


(*) In real life: A is my desktop. B is my always-on backup server. C is my mobile phone. I write changes on my desktop, switch it off, go out, and then start Syncthing on my phone to get some data. My read-only server *should* be able to give it to me...

**Comment by AudriusButkevicius** [comment]
What I am referring is not the detail of how access works, but brainstorming how BTSync keys work.

**Comment by 12345lamaun** [comment]
If there is a peer on which the folder is created first (so you are not going to sync a already existing folder), that peer could create certificates used to sign changes. these certificates must be propagated to read/write-peers, which then sign the changes - a ReadOnly Peer could then easy check if the changes are valid.

I have read a lot of posts about BTSync in the past, if i remember that right it is a hash-function. if you take the read/write key and hash it, yu geht the read-only key. if you take the ro-Key and hash it, you get the "encrypted key" (so the peer is not able to decrypt the data).
(You were able to generate the ro-Key from the rw-Key simply by knowing the rw-Key. And if you entered the ro-Key as the rw-Key, the then generated key is identical to the encrypted-Key)

**Comment by StrikerTwo** [comment]
Can't we just trust RO nodes not to send stuff they added themselves?

**Comment by StrikerTwo** [comment]
The BTSync encrypted key is double the length of either RW or RO keys, because it contains them both. Or something. I never did get the logic behind it and I was put off by the magic first character that determines if you can generate an encrypted key from a normal key and similar.
See http://forum.bittorrent.com/topic/25823-generate-encrypted-read-only-secret-without-api-key/#entry76262 for more headaches.

**Comment by generalmanager** [comment]
@StrikerTwo No, because the system is supposed to be cryptographically secure against malicious nodes! If you take this away, you break the threat model everything is built upon.

**Comment by StrikerTwo** [comment]
Where does that "malicious nodes" requirement come from? I don't need it. I trust my nodes, otherwise I wouldn't sync my files to them.

**Comment by bencurthoys** [comment]
Having a setting on to say "Never send changes from this device. When you detect a local change, stop syncing that file,and, on demand, revert changes to the file to the latest synced version." has some use cases. I'd use it. (See https://discourse.syncthing.net/t/infrastructure-syncing/1978/7)

But suppose I share my music collection "read only" with you, @StrikerTwo , and you go and untick the Read Only box and replace all the files with Rick Astley. I'd be quite cross =)

**Comment by StrikerTwo** [comment]
Then you'd just stop sharing with me and restore the original versions from the .stversions folder ;)

Having a "voluntary" RO flag would still be better than the current situation, which is a choice of having only one RW (master) node or giving everyone RW access and hoping they won't make changes to the files by accident.

**Comment by AudriusButkevicius** [comment]
Anyways, we can speculate here all we want, but all I am hearing so far it's that 32 or 64 bytes long, or that it's a hash function. Neither of which explains how it actually works. And I cannot comprehend how you fit a key pair into 32 or 64 bytes. Nor I can comprehend how can implement something like this securely with symmetric crypto.

**Comment by generalmanager** [comment]
@StrikerTwo This is common sense. If we have an UI element that makes people believe that someone they only give read access can not change their files, we have to actually enforce those guarantees on a technical basis. Otherwise Syncthing wouldn't be any better than the commercial solutions, which all say "no, we can't read your files" when they mean "no we won't read your files, promise!" 

If whatever we promise is not reflected in the code, there is no reason to try to create something better than the commercial solutions. Just because you happen to own all the nodes and it might not be very important for your specific use case, doesn't mean that the more common use case (people sharing stuff with other people) can be ignored.

And pushing for a solution that doesn't cover most use cases and is technically inferior to slightly more difficult (but cryptographically secure) designs is nothing but a waste of time.

**Comment by StrikerTwo** [comment]
@generalmanager well, that's your opinion.
From my point of view "we" already wasted six months discussing the perfect solution instead of starting with a simple flag that covers at least some use cases, including mine.
Also the original proposal was a "do not send changes" flag that would be set on the originating node, so it would do exactly what it says on the UI element.

**Comment by Finkregh** [comment]
@StrikerTwo i might be a little blunt, but please open a new ticket, as this is about allowing _insecure_ nodes, not some UI quirk that would be easily circumvented.

This is not some trivial problem, so as long as some crypto-uber-got comes around with /the/ solution a longer discussion is totally ok (IMHO)

**Comment by StrikerTwo** [comment]
@Finkregh I might be a little blunt as well: Open a new ticket yourself, I was here first :-P

I still don't see where all this talk about malicious and insecure nodes comes from. That was never the focus until @generalmanager barged in here two days ago. It's still called syncthing, not sharething.

That said, I have nothing against the idea of securing the cluster against non-trusted RO nodes. I just don't see why "your" and "my" proposal have to be mutually exclusive, or why "my" simple solution for trusted nodes can't be implemented while "your" solution for non-trusted nodes is being discussed.

**Comment by calmh** [comment]
Guys, chill.

For this to be implemented it needs to be secure, at least for some value of secure. It's right there in the second sentence of my original ticket description, although it may not be 100% clear -- all devices in a cluster must agree on blocking new data from a device that is not supposed to be able to introduce new data. If it needs to be secured by 10,000 bit asymmetric keys can be discussed, but it should not be circumvented by simply a forgotten checkbox on a single device somewhere.

**Comment by StrikerTwo** [comment]
Fine.

**Comment by Finkregh** [comment]
ooh, i mixed up the discussion from #109 . Sorry. @StrikerTwo 

I think that we indeed might need another ticket for a simple one-way-sync as in #584, as this seems to be another feature heavily tied to #62 


So:
* #109 = encryption, as in "i can sync stuff to my friend who i do not really trust. Or a cloud-provider"
* #584 = create new file on one device (phone, photo), sync to other device (archive), delete on phone & keep on archive - every node is trusted
* #62 (this) = same as #584 , but the archive-node may read my data and it has to be tamper-proof (changes can only be introduced via the not-archive-node (phone?)

i am not sure, but this smells a little like the problem git solved: beeing able to share stuff while knowing when things changed (which i did not want to change)
Could this be solved via building some sort of change-tree (git-ish?) and blessed/(gpg?)signed changes?

**Comment by StrikerTwo** [comment]
Thanks for clearing that up, I was starting to doubt myself ;)
But I'm fine with discussing the full-blown solution here and the simple unsecure solution in #1439.

So, to add to your list:
* #1439 = same as this (#62), but only for trusted nodes

**Comment by mr555ru** [comment]
For many use cases, read-only device is expected to be an "end point" (i.e. you share your files with someone you know over Internet) not meant for retranslating changes. So an easy approach that I see would be to disable read-only node from pushing updates on other nodes. That can be seen as writing changes onto another devices, which exceeds node's read-only scope. The exception would be when the receiving node marks RO-node as "trusted read-only" which would cover use cases such as @bencurthoys's.

The architecture where RO-nodes can retranslate updates would indeed be more convinient, but harder to create with security and decentralization in mind.

**Comment by timhowes** [comment]
The phone photo backup issue is a file versioning issue, not a folder permissions issue. If you want a particular node to have a "no delete" policy, that would best be implemented as a file versioning option, whereby files that are deleted a remote source are kept indefinitely in the local folder.

The idea of having non-source nodes (similar to read-only nodes in BTSync) is a different, more complex issue, which requires a cluster-wide solution, not just a local option.

**Comment by magao** [comment]
I'm coming to this as a newcomer to Syncthing, so I'm only going to describe my proposal at a fairly high level. I've read through the entire thread and I think my proposal addresses most of the concerns raised here.

Just like each device whitelists which devices to use and which shares to use, each device should whitelist which devices to use as a synchronisation **source**. Files on a device that is not a source can still be synced from if the file came from a source accepted by this device (and of course hasn't been changed).

Sources would be specified on a per-share basis (you might want to accept files from a source for one of its shares but not another). Probably want to be able to specify a default for a device (which is used unless a share overrides it), and also probably a delete flag.

Note: I don't think it's worthwhile having a device whitelist (or blacklist) which devices it sends to (destinations). If one of the devices you know about turns out to be malicious, remove the device (there was another issue I read which suggested introducers should also introduce device removal IIRC).

For example, if I want to configure the following 3 devices (using a single share which isn't listed):

Desktop: Will accept files from the laptop, will not accept from the server.
Laptop: Will accept files from the desktop, will not accept from the server.
Server: Will accept files from both the desktop and laptop (backup).

Device | Sources | Receiving from | File modified on | Synced
:--- | :--- | :--- | :--- | :--- | :---
Desktop | Laptop | Laptop | Laptop | Yes
 |  | Server | Laptop | Yes
 |  | | Server | No
Laptop | Desktop | Desktop | Desktop | Yes
 |  | Server | Desktop | Yes
 |  | | Server | No
Server | Desktop, Laptop | Desktop | Desktop | Yes
 | | | Laptop | Yes
 | | Laptop | Laptop | Yes
 | | | Desktop | Yes

So technically how would this be done? My thoughts are that any time a file is synced, part of the metadata is the signature of all sources known to have that exact file. The signature would consist of something like (source device's key + file hash) signed by the source's private key. The receiving device scans the list of signatures and if any match any of its valid sources for that file it accepts, otherwise it rejects.

If a file has been modified on a device, then the only signature for that file will be for that device. However, when it is discovered during a sync that the identical file exists on another device its signature is propagated.

**Potential Issues**

I can see a real scalability issue here - the signature lists for each file would eventually be as large as the total swarm. There are a few ways to minimise the impact. For example, when getting the first piece for a file the receiver sends a list of the device keys it will accept as sources for that file, and the sender chooses one of them for sending with each piece to be verified (minimises the per-piece metadata to a single source signature). Whilst not required, I'd suggest the chosen signature would be for the sending device if it's an accepted source. Once the file has been synced a final transaction occurs where the sources for the file are propagated.

A malicious client could produce massive bogus source signature lists, which would then be propagated through the swarm. A partial mitigation for this would be to also specify devices from which you will accept signature propagation (defaulting to the sources you accept). In the example above, the Desktop would be configured to only have the Laptop as a source, but would accept signature propagation from either the Laptop or the Server. Whilst this wouldn't prevent a bogus list being introduced, it would reduce the total amount of traffic. To prevent bogus source signatures being introduced to the swarm, maybe a device could be configured as a validation device which filters the list to only its own sources e.g. the Server (which is 24/7) is configured this way, and if another device tries to propagate a source signature that isn't in the Server's accepted sources it sends back a "remove signature" message.

**Comment by frank-github** [comment]
today I recognized in advanced panel of web gui

**Comment by frank-github** [comment]
a check box "read only"
is this the solution ? will this node only a "read only node", all local changes will be overwritten?

**Comment by AudriusButkevicius** [comment]
No, it's the same thing as master.

**Comment by favonia** [comment]
I really want this feature, and since the non-source devices are usually under my control in my case, I would like to make the following proposal:

How about allowing the non-source (NS) device to announce its NS status to all peers periodically? Once the NS status is announced successfully to peers, the NS status (at least by default) needs to be manually disabled from the other end. It's like "please ignore me from now on" and others would comply. We only have to check whether a NS device is announcing its NS status properly. It's probably useful to see when the NS status was last announced. Also Introduces should probably propagate the perceived NS status, but I am not entirely sure.

**Comment by sea3pea0** [comment]
I imagine a possible use case of the feature requested as follows:

- You have a server called  "myCloudBox" with a SyncThing master folder named FamilyVideos
- Your have a NAS called "myNAS" with a normal SyncThing folder named FamilyVideos
- Your Mom has NAS called "momNAS" with a normal SyncThing folder named FamilyVideos
- Your Sister has a NAS called "sisNas" with a normal SyncThing folder named Family Videos
- You add videos to the FamilyVideos folder on myCloudBox to share to you and your family's NASs
- Your momNAS adds,deletes files,etc.in FamilyVideos, no changes are passed to myNAS or sisNAS
- Same applies if myNAS or sisNAS make changes, momNAS doesn't receive them
- For unchanged, synced files, bandwidth is still shared between myNAS, sisNAS and momNAS

Anyway I hope I got my mind wrapped around whats being proposed by the feature requested in this thread. This is at least the way I have processed it. Either way it's something I'd really like to see in SyncThing

**Comment by bhelm** [comment]
Having a read-only key that authentificates a client as unauthorized to push updates to the p2p network is an important feature for me, as it allows more secure deployments.

In my specific use case, i would like to have multiple writeable masters and a larger number of read-only slaves. the problem with the current master system is, that you cant have two masters and even of you have only one, if one of the slave changes a file, it gets replicated to all other slaves which is a serious security problem. We are deploying virtual mashines to isolate responsibilities and reduce the impact of hacking attacks, deploying SyncThing would work against this.

another use case is to share files to the public. i had a private lan party where the origanizers had a writeable btsync folder and the visitors only had a read only key. the visitors were doing all strange things, extracting files to that folder, installing applications to it or delete stuff they thought they didnt need to save disk space. worked well with btsync, would have ended in disaster with SyncThing :(

**Comment by arximboldi** [comment]
I'd love if this was a per-folder setting. My idea is for a multi-user setup. For example, I might have a "friends" folder that I share in RO mode with a group of friends. This prevents they removing my files by mistake. If they want to share files with me, they do the same in reverse (share with me some folder of them in RO).

From a UI point of view, it would mean having a new section in the _Edit Folder_ panel called _Share with devices (read-only)_ with checkbox for the different devices.

**Comment by Ferroin** [comment]
@arximboldi I hate to be that guy, but that sounds _exactly_ like the current 'Master' folder configuration item that's already in Syncthing.

**Comment by arximboldi** [comment]
@Ferroin thanks a lot for the tip, I did not know that feature (in my version of Syncthing it's hidden behind a drop-down :S)

That feature seems to be all or nothing though--instead, I would like to share RO with some, but W with others... Still, this Master feature opens interesting use cases for me.

**Comment by timhowes** [comment]
@arximboldi  I have tried adding the same folder to Syncthing twice, giving it two different names like "myfolder" and "myfolder-readonly" (the second one being a master). Then I use the first ID to share between my own devices and the second to give read-only access to friends. This seems to work alright, but it requires that you have one central hub that serves as the intermediary between all the RW nodes and all the RO nodes.

**Comment by ahammond** [comment]
I think that a reasonable solution for this is to replace the "master" toggle button with a 3 way switch:

1. Receive Only (do not send changes to the cluster AKA read-only)
1. Normal (both send and receive changes)
1. Send Only (do not accept changes from the cluster formerly known as Master mode)

I also think that having an "automatically override changes" toggle would make sense. This would allow syncthing in RO mode to automatically replace any local changes with the cluster's official version, or in SO mode to automatically Override Changes. If this sounds like a good idea, it's probably also worth checking for two nodes in SO mode doing auto-override.

**Comment by StrikerTwo** [comment]
+1 for that. I was going to suggest an "auto-override changes" switch as well.

My use case: Fire-and-forget backup solution for Android phones. My users don't even know that Syncthing is running on their phones and they wouldn't find the override button if they needed to.

**Comment by AudriusButkevicius** [comment]
So the idea here is clear, now we just need someone who cares enough about this to implement it.
Locking this, as the discussion is now beginning to repeat itself.

**Comment by AudriusButkevicius** [comment]
Isn't this addressed with receive only folders?

**Comment by calmh** [comment]
Not really. That's voluntary while this is really about mandatory ("untrusted" in the title).

**Comment by imsodin** [comment]
This feature is currently being tested. You can try it out and help ensure it is ready to be used on our precious data. Check this forum thread for infos on how to try it out: https://forum.syncthing.net/t/testing-untrusted-encrypted-devices/16470

**Comment by AudriusButkevicius** [comment]
I think this is now done?

**Comment by calmh** [comment]
Maybe? I think I wasn't envisioning encryption in connection with this specific issue...

**Comment by AudriusButkevicius** [comment]
But this is automatically achieved by the virtue of encryption?

**Comment by calmh** [comment]
Let me think about it for another half decade or so.

**Comment by calmh** [comment]
It's only been a couple of years, but I think my tentative conclusion is "yes, this will suffice".
