### ISSUE TITLE
macOS: Locked files are unchanged and not out of sync but GUI reports Out of Sync errors

### ISSUE THREAD

**Issue by chrisfcarroll** [syncthing/syncthing#6200]
A file is present and correction on the mac filesystem, and has synced to other machines. 
The file has not subsequently changed at all. 
But later, syncthing generates an Out Of Sync error. 
And, the explanation given in the GUI Error List is inscrutable.

## To reproduce on a Mac + 1 other machine
1. Create a synced Folder on a Mac, and include a locked file in it. (In the `Finder` Gui: -> right-click on a file and check it as `Locked`. Or Commandline: `chflags uchg <filename>`)
2. Share and Sync the folder to another machine.
3. Then create changes in both directions, e.g. by adding new files on the other machine.

## Expected:

Status should be 'green' up-to-date.
There should be no error message. 
The file hasn't changed. It can't change; it's locked.
Syncthing should not try to chmod the file.

## Actual:

Syncthing believes that the Locked file is out of sync. 
The GUI reports status 'Out of Sync'. 
The Error List explanation in the GUI is 'operation not permitted' which leaves the user clueless. 
The log file says that `chmod` got the operation not permitted, but the word 'chmod' isn't in the GUI error message:
`Puller (folder "Archive" (Archive), item "...path.../filename.rnc"): chmod /..path/filename.rnc: operation not permitted`

## Sticking plaster in lieu of fix:
- In any case where a file is allegedly not synced because of file permissions, at least suggest in the Error List GUI, “<error message> ... Does this file have unusual permissions or locks?“. That would set some users on the path to a resolution.

### Version Information

Syncthing Version: v1.3.1, macOS (64 bit) "Fermium Flea"
OS Version: macOS Catalina

My “Other Machine” is:  v1.3.1, Windows (64 bit)

**Comment by AudriusButkevicius** [comment]
I think locking a file changes it's permissions, and because syncthing syncs permissions, this is why it happens?

**Comment by calmh** [comment]
I can't reproduce this. Setting the locked attribute isn't visible to Syncthing, doesn't change any attributes we understand, and Syncthing doesn't act on it in any way. However, I'm pretty sure that the 

> 3. Then create changes in both directions, e.g. by adding new files on the other machine

does *something* to this locked file, on the Windows side. Apparently a permissions change, given that Syncthing wants to do a chmod on the Mac side. This fails because the file is locked.

The error as presented in the failed items dialog is indeed a bit terse. The reason is that the *full* error is quite long, and we only show the part after the last colon as this is usually the root cause. The whole thing is in the tooltip. Tooltips aren't super discoverable, but there is a dotted underline to indicate something is available:

<img width="488" alt="Screen Shot 2019-11-29 at 08 47 21" src="https://user-images.githubusercontent.com/125426/69852628-1033c500-1285-11ea-8faa-dade0fb24d80.png">

I don't think there is much we can do better here to be honest.

**Comment by chrisfcarroll** [comment]
Okay thanks for having looked at it. If I can reliably reproduce / show what's actually causing it I'll see if I can raise a better bug and/or a PR. 

It nearly stopped me using syncthing. You may think "You'd know if you locked it" but it's just part of the OS. In my case it was a bunch of downloaded tech specs that I wouldn't have noticed were locked until this happened.
