### ISSUE TITLE
inotify-limits and basically the CPU time is always 50%

### ISSUE THREAD

**Issue by smart-z** [syncthing/syncthing#6228]
Operating version: v1.3.2, Linux (64 bit)
Operating environment: Synology app center installation

Question 1: inotify-limit
Question 2: Basically the CPU time is always 50%
- I have followed the instructions. This is https://docs.syncthing.net/users/faq.html#inotify-limits but I don't know what the reason is, and I will continue to have problem 1 and problem 2 at the same time.

Question 3: Did question 1 cause question 2? How to solve problem 1 completely?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
