### ISSUE TITLE
"Syncing" status should be based on activity, not completion percentage

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#623]
To handle the case where a node ignores a bunch of files, we should not assume a node is "syncing" just because it doesn't have all files we think it should have. It should be based on something else, like whether we've seen a file request from that node in the last x seconds or similar.

**Comment by vext01** [comment]
Just hit the problem where stignore screws up the sync status. It references this bug:
https://github.com/syncthing/syncthing/wiki/Ignoring-Files

Indeed, it would be nice if it were fixed.

**Comment by withinboredom** [comment]
Is this really a bug? If a node ignores 75% of another node's files, it would be correct that it was only 25% synced from one reference while 100% from another.

**Comment by calmh** [comment]
Yeah that's fine. We just shouldn't claim that it's "syncing" when in reality it's just sitting there rolling it's thumbs, happy in it's own little view of the world.

**Comment by calmh** [comment]
Given that we don't keep track of other devices' activity, and can't do so in the general case, would it be a valid bandaid over this to simply rename the state? Instead of "Syncing" (that implies we know something about what the device is doing), call it "Partially in sync" or something equivalent (that only says something that we know)?

**Comment by AudriusButkevicius** [comment]
I wonder if we should add a new message type and publish someof the events to the rest of the peers, just like the events api.

**Comment by dgnuff** [comment]
Forgive me if this cannot be implemented for other reasons, but I believe there is a possible solution to this problem.

Maybe it should be optional because the case that withinboredom points out may be valid some of the time.

In my instance I have three machines, call them Alice, Bob and Charles.  They all share a folder, but Alice ignores some files that Bob and Charles don't.  As reported, this leads to Bob and Charles showing Alice as permanently syncing.

If Bob and Charles knew about Alice's ignore list, then they could figure out the list of files that are actually shared.  They would evaluate a combined ignore list from the union of Alice's ignore list and theirs; from this the shared file list would be the full set of files minus any that are in the combined ignore list.

The problem with this is that right now, a node only has to maintain one ignore list per shared folder.  If this were implemented, it would have to maintain one ignore list for each (shared folder, machine) pair; this could mean a lot more data stored, especially if the number of machines in the cluster is large, and depending on the data requirements of an ignore list.

**Comment by calmh** [comment]
I actually have this implemented in a branch, there was just some tweaking to do with the events generated. I'll push it some time soonish.

**Comment by dgnuff** [comment]
Thank you for your quick response.

Great to hear that you've done this.  I'll be watching for an update.

**Comment by mannp** [comment]
Excellent news, thanks for this :) will it come out in a release candidate first?

**Comment by calmh** [comment]
We didn't merge my stuff as we realized there is a better approach. We'll get there though, in the end, don't worry. :)

**Comment by mannp** [comment]
Thats great news there is a better way, though thanks for your efforts, but is it still on the same release time frame ;-)

**Comment by calmh** [comment]
The better way is not written yet, so it is not planned for any release. Once it is written it'll end up in a release candidate and then a release, yes.

**Comment by mannp** [comment]
Oh thats a shame. Could your way be incorporated as an option and updated later, rather than having the confusing scenario there is now?

Loving the product, but as a noob the x% complete scenario is still confusing :)

**Comment by jsacrist** [comment]
> The better way is not written yet, so it is not planned for any release. 

Is it not written because of lack of developers? I've never contributed to syncthing but I'd happily volunteer for this issue.

**Comment by imsodin** [comment]
I have something in the works, that solves this. It isn't yet a PR, see this discussion: https://forum.syncthing.net/t/device-completion-and-ignores/10765
If you beat me to it, then kudos to you ;)
Also there is plenty of other good stuff yet to be implemented just waiting for you, just ask on the forum if you want pointers.

**Comment by AudriusButkevicius** [comment]
There is a ton of easy tickets under the first issue or something like that label in the tracker if you have the appetite.

**Comment by AudriusButkevicius** [comment]
Is this actually solved? The ticket talks about something else.

**Comment by calmh** [comment]
Yeah I know and I thought the same... And technically it's unrelated, but the only example of the issue that is mentioned in this ticket is that devices with ignores look like they are "99% syncing" forever while they are not syncing... And that is solved by the PR.

**Comment by Xeenych** [comment]
I have a shared folder A with some stuff and subfolder B with hundred thousand of small files (tile cache of web map). Syncthing takes enormous amount of memory and time to scan and rescan A with B. So I add B to ignore and all is ok, because ST does not index ignored files (as opposite to BTSync).

Looks like adding "global ignore list" or sending ignored files to other peers would need ST to scan ignored files and take large amounts of memory and time in my case.
