### ISSUE TITLE
LAN sync, authentication to HTTP proxy and Syncthing updates

### ISSUE THREAD

**Issue by piwi82** [syncthing/syncthing#6246]
(I am just a French frog writing bad English)

Is there a way to get Syncthing update automatically when then only internet access is a HTTP proxy ?

I am planning to use Syncthing to sync ~60.000 static documents (~8GB of datasheets and pictures) across over 60 laptops used by our sales teams.
These devices will sync locally (same subnet) so I disabled global announcing and relaying. Their only access to the internet is available through a HTTP proxy requiring basic authentication (this proxy is not needed by Syncthing to work locally).

The issue : Syncthing doesn't update automatically.
I think I found how to configure Syncthing to use a HTTP proxy (I set the system environment variable `all_proxy` to `http://proxy.domain.local:8080`) but I don't know how to provide credentials required by the HTTP proxy.
Should I use the syntax `http://user:password@host:port` ? (which I don't like much)

Syncthing Version: v1.3.2
OS Version: Windows 10 1903 (10.0.18362.449)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
