### ISSUE TITLE
can not delete a created real repo

### ISSUE THREAD

**Issue by jerome-diver** [syncthing/syncthing#6255]
# There is a "delete" item selection on repo right click menu...

 When user try to delete an existing repo, it should just remove it (without delete the linked directory but maybe ask for recovery storage directories to be deleted with or not). Instead, it doesn't do nothing.
**What is wrong repo and true repo there ? Please be lovely and take time to explain clearly and to be sure about what you write before to close an issue post.**

![try to delete repo](https://user-images.githubusercontent.com/11176132/71805283-298b1680-3066-11ea-9fc4-2fae6f360a52.png "Delete repo or not ?")

Syncthing Version: v1.3.2-1
OS Version: archlinux
Browser Version: gtk or web ui the same

## How to reproduce:

1. create a repo to sync

1. add a remote computer to synch with from this new repo configuration

1. allow new repo to sync from remote computer defined one step before

1. define the directory linked with sync new repo on remote machine

1. let them sync...

1. during process, delete a repo from remote or from master machine doesn't delete repo (and that is to bad).

## How to remove it ?

1. open xml syncthing config file from local home directory .config/syncthing/config.xml

1. remove repos manualy does delete theml also on the gtk and web ui.

**Comment by AudriusButkevicius** [comment]
Sorry but I am going to close this again. 

Your issues convolutes gtk and the web ui which are separate applications. If you have issues with gtk raise it on the gtk repo in github. If you have issues with the web ui, open a thread on the forum, as it's is most likely an issue local to your setup, as otherwise we'd have tons of people talking about this, which we don't.

If you want to make comments, you can make them on a closed issue, no point opening new ones.

Issues are for bug tracking and not support, so opening a second issue with the same content does not suddenly turn it into a bug, or give it a different treatment.

**Comment by jerome-diver** [comment]
yes, understand now. i did post it on the link you sent me just some minutes ago.
I'm going then to delete these issues from there.
thank you
