### ISSUE TITLE
Constant up- and download although nothing is synced

### ISSUE THREAD

**Issue by beatschubser** [syncthing/syncthing#6274]
### Version Information

Syncthing Version: v1.3.3 (all installations)
OS Version: 
- Windows 10 (64 bit)
- Linux (ARM)

Issue: syncthing constantly transfers small amounts of data to remote machines in both directions, although nothing is changing in the synced folders.

It's only a couple of bytes per minute in and out, but it prevents my Synology NAS, where syncthing is running as well, from hibernating the disks. As soon as I shut down the other clients, the NAS goes to hibernate as expected.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by calmh** [comment]
Regardless I think this is expected. There is no constant upload and download, but connections are kept alive by ping messages and there are occasional writes to the database to note when we last saw which devices.
