### ISSUE TITLE
Announce server over HTTP

### ISSUE THREAD

**Issue by stooone** [syncthing/syncthing#628]
It would be great to have the main or a fallback announce server over HTTP, because if you are behind a strict firewall you can sometimes trick it to have your nodes listen at alternate HTTP port, for example 8080, but if they IP address can't detected is worthless.

Regards,

Stone

**Comment by ckoehnen** [comment]
Thank you very much for adding this to the next milestone! I'd really appreciate to have support for a fallback global announcement server to support clients behind strict corporate firewalls by default. 

Please, also configure your global announcement server for this option:

<globalAnnounceServer>http://announce.syncthing.net:80</globalAnnounceServer>

**Comment by calmh** [comment]
To clarify this issue; what use is a discovery server over HTTP if the actual syncthing protocol is not also carried over HTTP?

**Comment by stooone** [comment]
For example if you have a restrictive company firewall what only permits some ports: HTTP, HTTPS and several other for example SSH, then you can setup your other box to listen on one of these ports and that way you are able to sync your boxes if you know the IP address. But if it is dynamic then using the current announce server they can't find each other.

**Comment by ckoehnen** [comment]
I understand, that the current  discovery server communication is maximizing privacy and transmission efficiency. So HTTP communication should be a must-have fallback in case of firewall connectivity problems. 

Currently, the client tries to reach UDP port 22026 on announce.syncthing.net. This is often not reachable, since many corporate networks only allow TCP-Traffic on Port 80 (HTTP) and 443 (HTTPS). 

Port configurations of firewalls are independent for the different protocols UDP and TCP. So, an open port 80 may be available for TCP connections, but is likely not for UDP.

Other corporate networks use HTTP(s) proxy server, which don't allow non-HTTP related payload and the firewalls filter UDP as well. 

If you use a HTTP GET method, you maximize the chance to pass any firewall, proxy or filter. 

Also, if you want to make syncthing a success, similar to other commercial alternatives you must maximize the ease of use, which includes configuration-less global discovery. 

The use of private discovery servers is only relevant for people with technical interests and special privacy concerns, not for the mass you may want to reach.

**Comment by calmh** [comment]
I can see the use case for when there is an actual firewall that only allows TCP connections out on a certain destination port. (That's a completely braindead setup in my opinion, but fair enough.)

If there's a proxy that allows HTTPS (and doesn't attempt to man-in-the-middle the connection) the sync protocol may be able to run over it. If only HTTP and/or MITM:ed HTTPS is allowed, then the sync will not work in any case.

**Comment by timabell** [comment]
This might be a silly question, but assuming the machines can see each other on the corporate LAN (possibly without being able to send broadcast traffic to each other to use local discovery), would the discovery server help them find each-other so they could still sync?

I've seen a few corporate LANs where there is no internet access at all apart from via a web proxy, and still more where traffic is only allowed out for a limited set of destination port numbers. I've heard it justified as making it harder for rogue software to function (e.g. a botnet using an irc for command and control). It's very annoying to work in such an environment, but they exist.

I'm aware that you can work-around the whole thing by not using the discovery server at all and either using local discovery if it works on your LAN (which I do at home), or telling syncthing the other devices' `address:port` explicitly. (I mention this in case anyone else reading didn't know)

**Comment by AudriusButkevicius** [comment]
If multicast/broadcast is disabled on the network, then yes, running a discovery server on the LAN would help, given you are trying to connect a few devices on the local network.

**Comment by timabell** [comment]
Oh sorry, I meant would the global discovery server help? Or does that only deal in public IP addresses?

**Comment by AudriusButkevicius** [comment]
That only deals in public IP addresses, but you can run your own discovery server in the network to make it deal with LAN addresses.

**Comment by timabell** [comment]
Thanks for clearing that up for me.

**Comment by stooone** [comment]
In my case it would help as I wrote in https://github.com/syncthing/syncthing/issues/628#issuecomment-84035910 but if you think it's only me, and nobody would benefit from this then we can close because I can workaround the issue.:)

**Comment by coolDragon66** [comment]
I don't think its just your setup [stoone](https://github.com/stooone) ... fallback for discovery over http would benefit others
