### ISSUE TITLE
Limit concurrent pulls

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6285]
We have a limiter for concurrent scans (#4888, #2760). The issue that this solves also exists on the pulling side: 200 folders pulling data concurrently also cause significant I/O and database load. It would seem like we should also have a pull limiter. In fact, it could be the same limiter if we just called it a folder-I/O-limiter in general...

**Comment by calmh** [comment]
I guess it's a workaround around that issue, yes, which I had forgotten I filed. :)

It's not just copier instances though, there are also things that I'm seeing like a given file being visible in or copied to several folders. Admittedly something of a special case, but still. If all start syncing at the same time there will be no block reuse, as none of them have seen the block in question yet. If there is some sequencing then the later starting folders can take advantage of the data already saved and database:d by the earlier folders.

**Comment by imsodin** [comment]
> [...] a given file being visible in or copied to several folders. [...]

The copier does the block deduplication (the handler before just checks for the existing file), so that would also be covered by a global copier limit I think. However I think in the end it doesn't really matter (at least I can't come up with any reasons right now), so whatever is cleaner/easier or just randomly chosen by the implementer probably works just fine :)

**Comment by calmh** [comment]
Blocks aren't committed to the database for the copier to find though, until a batch is completed.

**Comment by calmh** [comment]
I think this is enough of a duplicate that the original suffices

**Comment by calmh** [comment]
Duplicate of #5914
