### ISSUE TITLE
Stuck at "Syncing 0%" when adding a new folder 

### ISSUE THREAD

**Issue by dbogdanov** [syncthing/syncthing#6327]
I have the problem identical to the one fixed in #2156 on a fresh install of Syncthing v1.3.4 (Linux) sharing my first folder. The problem is resolved by restart on the receiving machine. 

### Version Information
Syncthing Version: v1.3.4
OS Version: GalliumOS 3.1 / Ubuntu

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
