### ISSUE TITLE
Doesn't run monitor process when started with STNORESTART=1

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6440]
In #6278 we intended to always run the monitor process, and this happens with the `--no-restart` flag, but not when the environment variable is set.

**Comment by Catfriend1** [comment]
Hi, I'm currently receiving problem reports from rooted Android users that see a permission denied error issued by libsyncthing.so where the outer monitor process exits with error 2 and the inner (main) syncthing process won't start. Not sure if it might have anything to do with this PR, they are claiming it no longer works since upgrading from v1.4.2.x to 1.5.0.x. It has also been reported to be a problem on fork and official app. Any hints for me?

**Comment by imsodin** [comment]
Before it was the app starting a single process, now it's the app starting a process, which then in turn starts another process. Looks like android doesn't allow the process starting another one -> not a Syncthing bug.
