### ISSUE TITLE
issues when ignoring files with file name containing question mark

### ISSUE THREAD

**Issue by alvinai0** [syncthing/syncthing#6467]
As documented in this [doc](https://docs.syncthing.net/users/ignoring.html), question mark `?` matches a single character. 

However, when I tried to use this pattern `Icon?` to ignore files named `Icon?` (which exist when customizing the folder icon on macOS), it also ignores other files like `Icons` (which I want them to stay synced)

So is it possible to introduce some new syntax like `"Icon?"`  or `Icon\?` to workaround this?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
