### ISSUE TITLE
syncthing causes whole system to be really unresponsive when using "Watch for changes" on FreeBSD (FreeNAS)

### ISSUE THREAD

**Issue by jarmo** [syncthing/syncthing#6531]
### Version Information
Syncthing Version: v1.4.0
OS Version:  FreeBSD 11.3 (FreeNAS-11.3-U2)

When using syncthing on a FreeNAS (basically FreeBSD) jail (have not tried outside of jail since FreeNAS/FreeBSD is not meant to be used like that) then it causes whole system to go really slow/unresponsive. All SMB shares take really long time to respond, SSH is slow, FreeNAS UI is slow etc.

Problem seems to related with "Watch for file changes" functionality and is already present at least from 2018 (https://www.ixsystems.com/community/threads/painfully-slow-performance-in-webgui-ssh-terminal-when-running-syncthing.64044/). I can confirm that this problem still persists - as soon as I turn off "Watch for file changes" and reboot my jail then everything works, but as soon as I turn it on, then after ~10 minutes everything is really unresponsive and I need to turn that functionality off and rely on periodic scanning, which is not ideal.

I'm using "Watch for changes" on all of my other systems (Windows/Linux) and there are no problems whatsoever.

Any ideas what might cause this situation? Can I provide some logs or whatever to help to solve this problem once and for all?

**Comment by calmh** [comment]
Can you try to narrow down what's causing the sluggishness? There are two cases where Syncthing are to blame: unreasonable CPU or RAM usage by Syncthing. This should be obvious from `top` for example. The other alternative is that this is some kernel level limitation that happens when there are too many watches. In that case the problem is conceptual or FreeBSD-side and there's nothing we can do about it.

**Comment by AudriusButkevicius** [comment]
I think this is a support type of issue, not really a bug, so I feel this should be on a forum and not here.

**Comment by jarmo** [comment]
@calm I can try to look, but since everything is that slow it might not be that easy :)

@AudriusButkevicius why would you think so if a lot of people are having the same problem on FreeBSD? I would agree if we're 100% sure that this is not a syncthing problem, but are we already sure about that? I'm not yet.

**Comment by AudriusButkevicius** [comment]
Because it's not clear what the cause is, it's just the consequences that are clear. I think debugging and figuring out the cause of the problem should happen on the forum, and once the steps to fix this are clear, it should be formulated into a workable issue. 

As the issue stands now there is nothing workable here.

**Comment by calmh** [comment]
Potential resource usage issue is fine in the bug tracker.

**Comment by jarmo** [comment]
For me, forum has always been like a place for discussing about configuration/usage and not anything regarding performance/crashes/whatsoever.

Most of the bug reports in the world start out with just stating the problem without any solutions/workable. This is how we try to get there. It's even possible that someone else having this same problem might end up in here and can help to actually get to the solution (if there's any).

As asked from @calmh I will try to look what top shows at the time problem starts to appear.

**Comment by jarmo** [comment]
Can anyone tell me what is used for a file system watcher under FreeBSD?

**Comment by imsodin** [comment]
kqueue (https://github.com/rjeczalik/notify)

> For me, forum has always been like a place for discussing about configuration/usage and not anything regarding performance/crashes/weird behavior.

If you look at the discussions on our forum, you quickly see that's not the case. And regardless, what is handled on here on github on what on the forum is a decision by the Syncthing project, not something up for discussion in the issue tracker (as in if you feel the need to further discuss that policy, head to the forum, not here please).

Please provide the information requested and otherwise keep communication minimal here - reducing noise on the issue tracker is one of the reason for using the forum.

**Comment by jarmo** [comment]
@imsodin Sorry, that was my personal assumption and I didn't mean anything bad with it.

Okay, but I have some investigation results!

I didn't see anything unusual with `top`/`htop` regarding CPU, RAM or IO usage. However, I started to look at the count of open file descriptors and noticed that syncthing opens a lot of file descriptors (and never closes them?). When open file descriptors count exceeded over 100k then system started to become really slow and the speed of opening new file descriptors slowed down too (probably due to performance reasons).

As soon as I disabled "Watch for changes" for all my directories then syncthing had opened roughly ~50 files and that count didn't change even if it was scanning directories.

Having open files at ~50 I did enable "Watch for changes" only for one small shared folder with ~500 files in it and saw a spike of open files immediately to ~550 which implies that Syncthing's file watcher opens a descriptor for all the files in the directory. Situation where I had open 100k+ files happens when I have "Watch for changes" enabled for a directory having 350k files in it.

I'm not sure that these open file descriptors are the actual problem or if it is a symptom, but is it intentional that file system watcher has so many open file descriptors which never get closed? Can it be the source of the problem itself?

This is how I counted open file descriptors:

```
cmdwatch -n2 "lsof -a -p SYNCTHING_PID 2>/dev/null | wc -l"
```

**Comment by imsodin** [comment]
kqueue is a non-recursive system, so every item (whether all file or just dirs I am not sure for kqueue) needs to be watched, not just the toplevel one. I am confused by the performance implications you describe: I'd either expect many more (at least 1k according to data.syncthing.net) people to complain about it or that freebsd/kqueue should just be fine with so many watches active.

**Comment by jarmo** [comment]
@imsodin just to clarify - performance problems happen only when there is over 100k open file descriptors. It's fine when it's ~550 with my smaller directory.

For the directory with over 350k files in it there's 70k directories so I'd expect that its the count of files (and maybe dirs?).

**Comment by imsodin** [comment]
Doesn't really matter though. The question now is: Is this a know limitation of kqueue (which I doubt given no complaints), in which case we should probably disable watching for changes for too large dirs (whatever that means) on freebsd, or is there something special ("wrong") about your system (there's "NAS" in the title, which makes me suspect that's the case, though that's admittedly a prejudice).

Unless other reports about the same problem come in or anyone has authoritative knowledge on kqueue/freebsd in combination with large dirs, I don't think there's anything to do for Syncthing at the moment. And to further debug your system (though wouldn't know what at the moment), I also think the forum is a better place.

**Comment by calmh** [comment]
It's apparently one fd per watched thing (files + directories), so that's a lot of fd's. (Confirmed on my FreeBSD 12.1 box.)

Depending on your sysctl:s I wouldn't be surprised if you're simply hitting the system limits (`kern.maxfiles`) and that this could be affecting other things that need to open file descriptions. I'm not seeing any other adverse effects on my system so I'm feeling that this is a works-as-intended situation at least from our perspective...

**Comment by jarmo** [comment]
Yeah, I also suspected `maxfiles`, but I would have expected to see some errors/warnings in the `/var/log/messages`, but there's nothing and total opened file descriptors are roughly "syncthing opened file descriptors" + 8k.

Default limits for FreeNAS are:

```
kern.maxfiles: 520402
kern.maxfilesperproc: 468360
```

I made a test of doubling these values to:

```
kern.maxfiles: 1040804
kern.maxfilesperproc: 936720
```

It doesn't seem to matter. Everything still becomes unresponsive around 110 - 120k open total file descriptors. This number seems to be close to your limits, but not even close to my initial limits.

So, maybe the problem is still somewhere else, but I will take that to the forum if you find that to be more appropriate place.
