### ISSUE TITLE
Limit number of concurrent writes while syncing

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6541]
Currently we spawn a goroutine to pull a block, and that goroutine does the file write when it's done. The number of goroutines is limited by the `puller max pending kib` setting, but this can still be hundreds of goroutines if the requested blocks are small. This can result in hundreds of concurrent disk writes, in turn spawning hundreds of I/O bound threads.

We should have a couple of goroutines responsible for the writes to handle this separately from the pullers.

(https://forum.syncthing.net/t/insane-load-average/14829)

**Comment by greatroar** [comment]
It's probably simpler to protect the writes with a semaphore.

**Comment by AudriusButkevicius** [comment]
There is also the whole "shuffle order of downloads to have better distribution of data" that causes thrashing on writes which we could address as part of this.

**Comment by calmh** [comment]
Having writer routines behind a channel allows releasing the puller routines while maintaining a small write queue, evening out bursts. It could potentially also be a point where we could do write reorders and merges in the future, if we wanted to do such a thing. 🤷 It's not an enormous amount of code either way.

**Comment by AudriusButkevicius** [comment]
I think the better approach for this would be to split the block list into `remoteDevice.listOfDevicesItSharesTheSameFolderWith` parts where a part if a continous range of blocks, see where our id lands in that list lexically, first fetch our "part", then shuffle the rest of parts and fetch them, but fetch in whole "device" parts in sequence rather than random individual blocks from different parts.

We could also check availability of otehr parts, and work on the least available part.

**Comment by calmh** [comment]
I didn't make any attempt to limit the randomness of writes in my proposed fix, just the simplest possible. Partly it's a separate issue, partly it might be mostly a non-issue with the world moving away from rotating disks plus our writes being generally quite large.
