### ISSUE TITLE
Pull order: oldest first issue

### ISSUE THREAD

**Issue by jimdoc** [syncthing/syncthing#6627]
I sync a partial set of my files (audio and video files) using "Oldest First" pull order.
These files are just transient, so I'm always adding and deleting files as they are consumed.
A complete set of files is on my NAS and I sync them to my laptop.
These files also have widely varying size (400 MB - 10 GB).

Pulling in "Oldest First" order fails when pulling to device with limited space (I set a minimum free disk space value).
If a 10GB file is next oldest to sync, but there is 5GB space available, the 10 GB file may never get synced. Smaller files that are newer than the 10 GB file will get synced first to fill the space available.

Oldest first should honor the "oldest first" policy even if it means newer/smaller files could be synced. Or maybe a "strict" oldest first policy to not change current behavior.

**Comment by AudriusButkevicius** [comment]
Sorry, but I disagree, we should sync as much as possible as fast as possible. 
I fail to see a casual/non-niche use case where you would not want that.

**Comment by calmh** [comment]
Yeah, pull order is the order in which things are processed. Once an item completes (successfully *or fails due to some error*) the next item is processed. This is true regardless of pull order and is how it should be in my opinion. We do not want to fail to sync to all subsequent files due to a permission error, file missing on source error, or even a free space error.
