### ISSUE TITLE
Error: Found something of unexpected type in block list map

### ISSUE THREAD

**Issue by mohe2015** [syncthing/syncthing#6637]
#### Does your log mention database corruption?
Maybe (see log)

#### Info
 - Arch Linux x86_64, Syncthing v1.6.0-rc.1

#### What happened
 - after updating the version of syncthing the following error / warning was shown:
```
May 13 17:06:25 moritz syncthing[530]: [MP6JR] WARNING: Found something of unexpected type in block list map: Symlink{Name:"qq0s0464.default-nightly/lock", Type:SYMLINK, Sequence:2266, Version:{[{MP6JR34 1589311222}]}, Deleted:false, Invalid:false, LocalFlags:0x0, NoPermissions:true, SymlinkTarget:"127.0.0.1:+56071"}
May 13 17:08:06 moritz syncthing[530]: [MP6JR] WARNING: Non-increasing sequence detected: Checking and repairing the db...
May 13 17:08:06 moritz syncthing[530]: [MP6JR] INFO: Repaired 1 sequence entries in database
```

#### Expected
no error / warning

#### How to reproduce

I don't know...

**Comment by calmh** [comment]
Good catch, thanks for reporting.

**Comment by imsodin** [comment]
This is due to a missing symlink check when updating files in the db (and not the transition that I commented on here:https://github.com/syncthing/syncthing/commit/decb967969d164ef788b036791bcf9caa9209217#r39149359), which was there prior to 1.6.0, but only now has consequences...

Is anyone already working on this? @AudriusButkevicius @calmh

**Comment by calmh** [comment]
So we can fix not creating them, and simply ignore them on the read side for now?

**Comment by AudriusButkevicius** [comment]
We can't delete as the handling is in a readonly transaction. Probably a migration to cleanup? Or silence the warning?

**Comment by calmh** [comment]
This is rare enough that I think either just letting it be or silencing the warning. (I didn’t check the code but how come we are even looking at this entry? I would expect to only look at entries matching some block hash?)

**Comment by mohe2015** [comment]
I also don't think it's worth it if that was just an edge case when updating or whatever. It also didn't show up after a restart so the entry probably got deleted by the non increasing sequence entry?

**Comment by mohe2015** [comment]
Btw I'm usually also using git version which is probably a bad idea.

**Comment by AudriusButkevicius** [comment]
This entry does seem to have and match a blockhash... I guess an empty sha256?

**Comment by imsodin** [comment]
exactly, fix incoming

**Comment by mohe2015** [comment]
I don't know if this is the source but I get
```[MP6JR] 2020/05/14 15:12:31.325761 model.go:1957: INFO: Repaired 1 sequence entries in database```
after I reset the whole database and started resyncing with the current master.

**Comment by imsodin** [comment]
Do you mean you still get the warning about the unexpected type too? If not it might still be interesting to know why/under which circumstances it's repairing the sequence, but that would then be better done in the forum (and finally a separate issue, if it turns out to be a bug).

And when talking about master, please specify the commit - it's somewhat of a moving target otherwise ;)

**Comment by mohe2015** [comment]
No, I don't get the warning about the unexpected type. Yeah it's syncing really slow in general because one of the peers is a raspberry pi. I will wait a bit and if it doesn't get better I will create a forum post.
