### ISSUE TITLE
panic: sequence index corruption

### ISSUE THREAD

**Issue by mohe2015** [syncthing/syncthing#6650]
### Does your log mention database corruption?
yes

I don't know but I don't think this has something to do with hardware corruption.

### Include required information

Please be sure to include at least:

 - Arch Linux, Syncthing v1.6.0-rc.2+11-gf05ccd775, f05ccd775abf1a51a39b0363d72fe7942815e01b

Info: I'm also https://forum.syncthing.net/t/up-to-date-but-not-syncing/14998 and I also reported https://github.com/syncthing/syncthing/issues/6637

### what happened
Some time after I checked e-mails with the latest Thunderbird release (I don't know when exactly) syncthing paniced but only at the laptop side not at the raspberry pi 3b. I think it also had the problem outlined in my forum post before but I'm not sure any more.

Logs: https://gist.github.com/mohe2015/126aa0fb81fe4a633fd829e1417ba1bc
More data can be provided on request. I won't reset the database for now (systemctls automatic restarts failed with the same panic) so I could also provide that if that can help.

### what you expected to happen instead
obviously not crashing

### any steps to reproduce the problem.
don't know, it was a fresh database with multiple gigabytes of data on two devices one of which is a laptop with an ssd and the other one is a raspberry pi 3b with a 64gb usb flash drive.

It could be possible that backing up .thunderbird may exhibit the problem.

**Comment by calmh** [comment]
The panic/crash is a debug feature caused by the debug tracing you've enabled. Without that it would try to just heal the inconsistency. That said, there is an inconsistency and there shouldn't be...

**Comment by imsodin** [comment]
Wow. Thank you!

I don't yet have a clue why it's happening, but what is happening is that in a single batch of local file updates, we get the same file twice. We then twice remove the original file from before the update, and add the first and second file.

I do believe it's a bug that we get the same file twice in one batch, but I also think we should handle that case. Because for remote devices I think that can happen legitimately, so we should be able handle it in db.

**Comment by AudriusButkevicius** [comment]
So the same file twice could be done by rename detection, as it makes the file as deleted twice most likely.

**Comment by calmh** [comment]
Sounds plausible, the file is 0 bytes long so likely match for any other created 0 byte long file...

I guess the problem is our non-dirty-read transactions. We create a new item and sequence entry, dropping the old sequence entry. Then we get the next instance, create a new item and sequence entry but can't find the intermediate sequence entry we created.

**Comment by imsodin** [comment]
Ok, then that's the problem. When we insert the same file twice, the first gets sequence A, second sequence B. We delete the old sequence entry, create a new one from A pointing at the file, then create a second one from B to the file and overwrite the file entry with sequence B. Thus the entry for sequence A is still there, pointing at a file with sequence B.

**Comment by calmh** [comment]
Maybe we should skip rename detection for zero byte files, too :)

**Comment by imsodin** [comment]
I'll propose a solution to the general "file present more than once in a to-be-update list", separate from the zero bytes and other rename stuff that can potentially also be improved/fixed.

**Comment by AudriusButkevicius** [comment]
If len(blocks) == 0 goto fail

I guess having a block for an empty file is a very old thing, but I can't think of a good reason why we need it.

**Comment by calmh** [comment]
Yeah I had the same trip down memory lane. To begin with we didn't have a separate size field, I think, and it's still a protocol error for a file not to have blocks.
