### ISSUE TITLE
Preemptively clean database during migrations?

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#6660]
This is an idea related to PR #6659 to avoid panics because of unexpected (seemingly corrupt) database entries.

During my development for #6443 I had deliberately left KeyTypePendingFolder = 14 and KeyTypePendingDevice = 15 entries in the database of a testing instance as data samples.  Recently the same numbers were getting used in master for something else, which is fine.  My PR was updated after merging master, now using the next higher prefix numbers 16 and 17.  However, the old leftover entries now cause panics because of wrong assertions, looking like corrupt database content.

To avoid such issues, I suggest to iterate over entries for all newly introduced key types during a database migration, and delete whatever is in there.  If it wasn't part of the previous database "schema", the entries could be regarded as already invalid and the migration code should make sure that they cannot cause unexpected behavior.

Just a thought, so feel free to close this if you see more problems arising than it would solve.

**Comment by imsodin** [comment]
I don't see problems, but I also don't see how it's practical: If it's not automated, it's essentially useless, because it depends on whoever writes the transition to think of cleaning it out. And I don't see how to automate it expect for writing a linter. So essentially if you have a concrete idea, feel free to propose it, but I don't see the value of a general issue open on this (and frankly, I don't feel like it's much of an issue in the first place).
