### ISSUE TITLE
Consider removing rolling hash support

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6674]
I realize I'm suggesting killing someones baby here. However, weak hashing has some non-zero costs: in calculating when hashing, in checking when syncing, and in code complexity. (Although the latter is not great, as it's proven stable enough to not require a lot of maintenance.)

The utility to compare to the cost is an apparent saving of 1% on data transfer, according to data.s.n:

<img width="966" alt="Screen Shot 2020-05-23 at 10 55 44" src="https://user-images.githubusercontent.com/125426/82726381-021aaa80-9ce4-11ea-8065-1b037a197146.png">

In my mind this effectively rounds to zero, so the question is if it's worth keeping around.

I'm aware that the utility is probably >> 1% to *some* users, possibly to the point of being mission-critical for an extremely small subset of users. The hashing cost is however carried by all.

(There are also many other features with < 1% usage where the same argument could be applied, probably. I'm focusing on this one just because it has a general runtime cost.)

**Comment by AudriusButkevicius** [comment]
Did you evaluate how much of a cost is the non-zero cost? 

If its 1% cost for 1% gain, sounds pretty good to me.
Its also used for the request response validation, which is cheaper than sha256, so there is some utility there.

Also, we could put it back behind a flag, and let people switch it off if you are seeing cases where its detrimental.

**Comment by calmh** [comment]
Good point.

**Comment by greatroar** [comment]
I've been looking at the weakhash finder for some time to see how it could be improved, and I think I found two flaws in it. The algorithm is currently:

1. Finder scans through the file, recording matching offsets for a set of hash values. It always only records the first ten it finds.
2. Client code re-reads the matching blocks and verifies them using SHA-256.

The first flaw is the inefficiency from reading the file multiple times. The second, which I suspect may harm its effectiveness, is that it the finder is biased to the front of the file. If edits occur near the end, then the probability that the first ten matches are all false positives increases with the file size.

I believe both issues can be solved at once by redesigning the finder to be one-pass and stateless aside from the file offset. WDYT?

**Comment by imsodin** [comment]
Single pass would certainly be nice and push the scales even a little more towards a better cost-benefit ratio :)

I don't follow on the false positives: How I understand it, when a "data-interval" with the same weak hash occurs at multiple places in the analyzed files, the first 10 occurrences are recorded. So for any information to get lost, at least one collisions in the weak hash needs to happen (if the same "data-interval" occurs 10 times, it's full without a collision). Even though it's just a "weak" hash that seems negligible when it comes to performance.

**Comment by AudriusButkevicius** [comment]
I don't think it reads the file multiple times? It reads the file once on construction? Why do you think that?

As for false positives, I am not sure if matters which parts it hits. The window is of a fixed size, so the fact something was added to the end has no effect on hashes at the front of the file, as end of file does not fall into the window, so again, I am not sure what the problem here is.

**Comment by AudriusButkevicius** [comment]
I guess the API now reads it twice, once finding the hashes, second time offering the bytes of that block to the consumer who then compares using sha256. In theory it could be given both sha256 and adler32 to find and stop on first match for each block.

**Comment by greatroar** [comment]
Indeed.

The problem with the false positives is that Adler-32 is a very weak hash (according to its designer, [not a hash at all](https://stackoverflow.com/a/13464812)), so it tends to produce many spurious matches for any given hash value. The early stopping is what causes the bias: once ten false positives are recorded, any actual matches are skipped. Passing the SHA-256 to the finder would eliminate the problem.

**Comment by imsodin** [comment]
We are talking 1-2k blocks with a length of 128kB or more that could collide. The question you link is about date strings, i.e. very small input, for which adler is indeed known to be very weak. I doubt there's significant collision potential for our use case. Anyway, if it's preventable with additional benefits without huge additional complexity, this entire discussion is moot anyway. Only if a change were made only to prevent this collision potential, I'd like to see more info on the magnitude of the collision potential before modifying otherwise working code.

**Comment by AudriusButkevicius** [comment]
The api would have to change quite radically to actually only read once, but thats fine

**Comment by greatroar** [comment]
I'm working on some simulations to get realistic figures on collision probabilities.

Regarding API changes, I guess handing the SHA-256 to the Finder is an easy way out of both (potential) problems. To verify the SHA-256, the Finder may still need to read the block again (because chmduquesne/rollinghash doesn't expose its buffers), but that read will almost surely hit the filesystem cache.

**Comment by calmh** [comment]
Closing this as we should not remove rolling hash support (the task of considering that has been completed). If for no other reason, then at least because we're using the hash for other things like quickly validating blocks before sending them.
