### ISSUE TITLE
Curly braces are not recognized by exclude patterns 

### ISSUE THREAD

**Issue by WhiteDiver** [syncthing/syncthing#6711]
Syncthing 1.6.1 for Windows ignores exclude patterns containing curly braces, for example, {}, {Root}, \{Root}, etc. The exclude patterns documentation says nothing about curly braces.

**Comment by calmh** [comment]
Curly braces denote alternatives, though I see this isn't in the documentation.

That is, `{foo,bar}.txt` matches both `foo.txt` and `bar.txt`. `{Root}` thus matches `Root`. To match a literal curly branch you can use a character range: `[{]Root[}]` would match `{Root}`. (On Unixes you can escape them instead as `\{Root\}` but that's not supported on Windows due to backslash being the path separator...)
