### ISSUE TITLE
Disappearing files

### ISSUE THREAD

**Issue by jwr** [syncthing/syncthing#6800]
This happened twice over the course of the last several days, so I thought I'd report it.

I have a git repo that is being synced between several hosts. At the moment, three hosts are active: Linux, and two Mac OS machines (10.14.6 and 10.15.5). All run syncthing 1.6.1.

Git repo became corrupted overnight. Digging into it shows files are missing — for example, the stashes will be gone, or the content of a commit.

The exact startup message on MacOS is:
```
[start] 18:20:25 INFO: syncthing v1.6.1 "Fermium Flea" (go1.14.3 darwin-amd64) brew@Mojave 2020-06-02 09:49:22 UTC
```

On Linux:
```
[start] 08:07:07 INFO: syncthing v1.6.1 "Fermium Flea" (go1.14.4 linux-amd64) deb@build.syncthing.net 2020-06-02 09:49:22 UTC              
```

Linux host shows no significant error messages in the logs. The MacOS hosts, however, show messages like:

```
[GE2OI] 17:54:12 INFO: Puller (folder "xxx" (xxx), item ".git/objects/c7/2c47109a19cb7eb2b833bc8438a4900552809c"): opening temp file: open /Users/xxx/Sync/xxx/.git/objects/c7/.syncthing.2c47109a19cb7eb2b833bc8438a4900552809c.tmp: too many open files
```

I suspect this might have something to do with the problem. Could syncthing delete files in a scenario where the "too many open files" error happens?

My plan is to dig into why homebrew does not increase open file limits for syncthing, but I thought I'd report it, because perhaps this behavior could be improved?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by AudriusButkevicius** [comment]
Also, https://stackoverflow.com/questions/60680946/how-to-clean-damaged-objects-in-git-repository.

Git repos is not something that should be synced, because it's not one file but a collection of files, they are bound to get corrupted.

**Comment by jwr** [comment]
I find this approach very worrying.

First, syncthing deleted files and lost my data. This classifies as a rather serious bug in my book and closing the issue worries me on many levels. It's not the approach I expected from syncthing.

Second, if syncthing is not intended to sync "collections of files", I believe this should be made clear. Specifically, is there a limit on the number of files that *can* be synced?

Third, I've been happily using syncthing for the past several months as a Dropbox replacement and had nothing but praise for it. I was about to start sponsoring it. But if this is the approach taken to data-loss bugs (close the issue immediately), I am having doubts if syncthing can be trusted at all.

**Comment by AudriusButkevicius** [comment]
It is meant to sync collection of files, but a single git branch checkout is also a collection of files. 

There is no atomicity of syncthing at a directory level, It's atomic at a file level, so if you checkout two different git branches, which will be a different collection of git places in it's internal structure for "current branch", and sync them, syncthing will happily merge the two different collection of files representing "current branch", corrupting the repo.

The reason this is closed is because it's not obvious to me what needs fixing.

Yes, something bad happened, and that's not great, but this needs more details and debugging to be able to identify what caused it and what needs fixing, to classify it as a bug, which is what the forum is for.

The issue is local to you, un-reproducible by us, so having "something bad happened, I don't know why, but it's definately a bug" as an issue is not helpful, as there is no clarity how to reproduce it, or what exact part needs fixing.

From the surface, this looks like something that happened because of the context you were using syncthing in, as in, syncing individual files (which is what syncthing does), when you really need directory level atomicity (which is what git requires, and syncthing does not provide).

**Comment by jwr** [comment]
I think there might be a misunderstanding here:

> There is no atomicity of syncthing at a directory level, It's atomic at a file level, so if you checkout two different git branches, which will be a different collection of files git places in it's internal structure for "current branch", and sync them, syncthing will happily merge the two different collection of files representing "current branch", corrupting the repo.

My problem was not that the current working directory had missing files. The problem was that the objects in `.git/objects` were missing. This has nothing to do with branches (which in git are only pointers anyway), or atomicity. Note that git does not modify its `objects` when you switch branches, and I'm talking about missing files in `objects`. Lost data.

I would humbly suggest that it is worth investigating what happens when the "too many files" error is encountered. What I wrote seems to at least point in that direction — my first guess would be that the Mac client is unable to open a file because of the limit, and hence considers the file deleted and reports it as such to other peers, but that's just a wild guess.

I would also humbly suggest that not all bugs are reproducible and that sometimes (in my case, very often) thinking about a problem leads directly to a solution, even without a reproducible test case. Closing bugs does not make them go away. It can make *me* go away, but the bug is there and will resurface sooner or later, causing data loss somewhere.

**Comment by AudriusButkevicius** [comment]
I've checked the code path, and it would just terminate the download and print an error message as it did.
It would not record anything in the database and would stay "needing" that file.

People hit "too many open files" issue all the time on RPi's and I don't think we've ever had reports of data loss from them.

We did have quite a number of people reporting git repo corruption (effectively data loss in .git/objects), so I am fairly certain that
git and syncthing doesn't play well, oppose to a generic "syncthing loses data" bug as you claim.

`.git/objects/<2 first chars of hash>/<rest of hash>` holds unpacked objects for use.

`git gc` for example (which happens periodically even if you don't want to) takes unused objects, compresses them and puts them in `.git/objects/pack` hence why files in `.git/objects` can and do disappeared, so switching a branch on can cause files to disappear.

Now if the other machine doesn't think these objects should have been packed (I have no idea what criteria it uses for that), it will start complaining the files are now missing. 

I am not going to go read gits source code to get to the bottom of this, but I am fairly certain that syncthing did not lose those files, and that external processes made them disappear, and that syncing that dis-appearance has upset the git instance on the other side.

Very unlikely, but perhaps git itself failed to do it's packing, and lost those files, if you hit the user fd limit, rather than process fd limit.

**Comment by AudriusButkevicius** [comment]
You could also have a race, where one instance of git (a) decides to pack the file, the other instance (b) decides to create a new head referring to that now packed/pruned file, hence removing it from the candidates to be packed.

Now let's say the devices were offline, they now connect, creation of the new head gets synced to from b to a, and removal and packing of that object gets syned from a to b, now both instances have a head that refers to something that doesn't exist anymore. 

This is the atomicity at the directory level that is required, because we've merged two disparse directory trees without understanding what's in them.

**Comment by jwr** [comment]
Thank you for taking the time to consider this problem and think about possible causes.

I disagree with your conclusions, however. In my case, I am certain that git was *not* used simultaneously (for any definition of "simultaneously") on multiple machines. What you described above are conflicts resulting from *running* git on multiple machines, before data was fully synced. While not impossible, this is very, very unlikely to have happened here.

There is nothing special about git data. It's just files. Either syncthing is capable of making sure that files are synchronized between multiple machines, or it isn't. This really seems to be a bug and sweeping it under the rug is one of possible solutions, but it will come back in a different setting one day.

**Comment by AudriusButkevicius** [comment]
Yes, git is composed of files, which syncthing is able to sync, but state of a git repo is not just a file, it's a collection of files which all need to be there.

It doesn't need to happen simultaneously, it's enough for use to use git on two machines while they are disconnected for this to happen. 

I've already explained how this can happen, but you seem to ignore it and keep dismissing it as a bug.

**Comment by jwr** [comment]
I understand your explanation of how this can happen. I think the only disagreement is that I am saying that I did not use git on two machines while they were disconnected, therefore this is unlikely to be the cause.

And having used syncthing since Aug 2019 (and Dropbox for many years before that), I have reasons to believe I know how to avoid the scenario you described.

I also do not think I am "dismissing" anything, quite the contrary. I think this is very serious.

Anyway, I do not want to waste any more of your time. I will look at workarounds like switching back to Dropbox, I guess, or making automated hourly snapshots in case of data loss.
