### ISSUE TITLE
no AAAA dns entry for relays.syncthing.net 

### ISSUE THREAD

**Issue by berkas1** [syncthing/syncthing#6810]
### Does your log mention database corruption?

not applicable

### Include required information

When trying to set up a new relay server on server with IPv6-only connection, it could not join the relays pool server. It seems that the **relays.syncthing.net address has no AAAA record in DNS.** Could this record be put in the DNS? Thank you

**Comment by calmh** [comment]
The relays are intended as a workaround for ipv4 nat breakage, and as far as I know there are no actual ipv6 relays so unfortunately adding an aaaa record would not be useful. 

If you have working v6 it seems like a better option to allow direct connections. You could probably also set up a dual stack relay and manually point to it from either device, to bridge between v6 and v4.

**Comment by phloggu** [comment]
There is at least one IPv6 relay: mine...:-) Every relay with IPv6 connectivity will by default also listen on its IPv6 address. So I guess there are up to 100 IPv6 relays out there (according to [Google](https://www.google.com/intl/en/ipv6/statistics.html) IPv6 is used by 35% of their visitors and there are about 300 relays in the default pool).

Even with IPv6 relays remain important: Network administrators do not just open their nets all of a sudden and for a lot of users maintaining their own infrastructure opening a port is challenging. So there is still a need for relays also with IPv6.

It seems to be the only problem that the pool server is not IPv6 friendly. Apart from the pool server has to be reachable over IPv6 it should also serve corresponding addresses. It looks like there are only IPv4 addresses registered in the pool today. I don't know where the problem is and how hard it is to solve it, but I believe in the long run the default pool should get IPv6 ready.

If the pool server code can handle IPv6 addresses it would be enough to run another instance of the default pool server on IPv6 using the same DNS name as the IPv4 instance and make sure the capable relays register their addresses on both instances. However, I don't know where the problems really are, but it would be nice the pool server handling IPv6 just fine at some point in the future.
