### ISSUE TITLE
Global state incorrect when ignoring local change

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#6850]
Steps to repro:

1. Create receive-only folder
2. Add some file, which is then displayed as a local change.
3. Add an ignore pattern matching the added file.

Result: Local state zero, global state still 1.

Expected: Both 0.

**Comment by imsodin** [comment]
I just realized the same problem exists in `removeFromGlobal`. However thinking a bit more about it, why do we include receive-only changed items in the global count in the first place? That seems completely wrong to me: The global state is what everyone agrees upon. Receive-only changed items are the complete antithesis to that. If we didn't add it to the global state, receive-only items would lead to a higher local than global state, which seems right. It also removes the need for the workaround added in #6852. Thus I propose to not add invalid items to the global state. Am I missing some catch with that?

**Comment by calmh** [comment]
Sounds reasonable to me. Generally we should never add invalid stuff to the global state, and those are invalid-ish?

**Comment by tomasz1986** [comment]
I hope it is OK to write here instead of the forum, as this has just come to my mind while reading the @imsodin's message. I had a problem when my Receive Only folder was in a "Revert Local Changes" state, i.e. after deleting some files locally. Without pressing the red button, I changed the folder from type "Receive Only" to "Send & Receive". However, Syncthing would still not push the local deletions to the other device, and the folder itself was marked "Up to Date", even though some of the files were missing from it.

Is this somewhat related, or a completely different issue?

**Comment by imsodin** [comment]
That's most likely unrelated, as it concerns actual syncing while this issues is entirely about metadata (local/global states). I might have an idea what you are experiencing, but lets take that to the forum please.
