### ISSUE TITLE
No update since 1.7.1 release

### ISSUE THREAD

**Issue by bobaxxx** [syncthing/syncthing#6854]
Hi,

On my client (linux mint 20), Syncthing 1.7.1 package is not available through update manager since the release, i am with the 1.6.1 version

Though, my server still got the last update 1.7.1 yesterday (raspbian buster)

The result is that i cant connect to the server since yesterday because of usual version conflict

 - Client Syncthing version installed : 1.6.1
- Server syncthing version installed : 1.7.1
- OS : Linux mint 20 ulyana.

apt-get update & apt upgrade doesnt show any new version of syncthing

**Comment by AudriusButkevicius** [comment]
You need to talk to your distribution maintainer. We don't manage releases of various distros.

**Comment by calmh** [comment]
Also there is no "usual version conflict", 1.6.x will sync just fine with 1.7.x

**Comment by bobaxxx** [comment]
Nope, i noticed everytime the server and the client doesnt have the same version, there is no more sync between my server under raspbian and my client under linux mint, this is a fact

anyway, this was just the repository that was automatically removed after ulyana update

btw, no need to comment me on if you dont help a bit

thx for all

**Comment by calmh** [comment]
Any 1.x version will sync with another 1.x version. Lots of people run with significant version mismatches for whatever reason. We can't help you with Mint not updating their package because we are not Mint. We can suggest using our packages from https://apt.syncthing.net/ and we can suggest reaching out for help on https://forum.syncthing.net/ if you can't get your things to connect. As noted super clearly in the issue templates this is not a general support forum -- the forum is.
