### ISSUE TITLE
Ignored files kept in global state when present only in a RO folder

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6988]
Please forgive me if this is the intended behaviour, but this how to reproduce:

1. A pair of SO and RO folders is in sync with one another.

![image](https://user-images.githubusercontent.com/5626656/93190351-3aa42f80-f77e-11ea-8f4e-6f1efdfdb3aa.png)
![image](https://user-images.githubusercontent.com/5626656/93190354-3c6df300-f77e-11ea-99b3-f8d280d8802f.png)

2. Ignore everything in the SO folder. The local state reflects the change, but the global state remains unchanged, and the ignored files are kept in the RO folder.

![image](https://user-images.githubusercontent.com/5626656/93190370-3ed04d00-f77e-11ea-8068-b0d8533f7e11.png)
![image](https://user-images.githubusercontent.com/5626656/93190377-4132a700-f77e-11ea-8af0-e021aa493069.png)

3. Ignore everything in the RO folder. Now the local and global states in both folders match.

![image](https://user-images.githubusercontent.com/5626656/93190854-d03fbf00-f77e-11ea-9278-d3749f5fa4dc.png)
![image](https://user-images.githubusercontent.com/5626656/93190860-d2a21900-f77e-11ea-8bdc-d1ff620d8830.png)

4. Unignore everything in the RO folder. Now the RO folder is marked as "Local Additions". Pressing the "Revert Local Changes" button deletes the files.

![image](https://user-images.githubusercontent.com/5626656/93191244-42180880-f77f-11ea-8029-7e1d948e0df1.png)
![image](https://user-images.githubusercontent.com/5626656/93191252-447a6280-f77f-11ea-8e61-611b959a0f56.png)

My first question is, should the files present only in the RO folder and ignored elsewhere be included in the global state? I personally expected them to be removed from the RO folder (or marked as "Local Additions"), but please correct me if I am wrong. However, if this is the intended behaviour, then why would ignoring and unignoring the files on the RO side mark them as "Local Additions" afterwards?

Tested with self-compiled `main` (`v1.9.1-dev.31.gecc24428, Windows (32 bit)`).

**Comment by imsodin** [comment]
> My first question is, should the files present only in the RO folder and ignored elsewhere be included in the global state? I personally expected them to be removed from the RO folder (or marked as "Local Additions"), but please correct me if I am wrong.

That's expected behaviour: The file on the RO device is a valid global file. The other device did not remove that file, it just doesn't care about it anymore. I get why you'd expect a file that now only exists on receive-only folders to be marked as a local addition, but we can't detect that: Imagine a second receive-only folder. The file from the other receive-only device will look perfectly valid to a receive-only folder, so it can't detect that only receive-only folders have the file. Even if there was a way to circumvent that problem, unless this causes any real-world problems I personally think this does not need fixing/improving.

> However, if this is the intended behaviour, then why would ignoring and unignoring the files on the RO side mark them as "Local Additions" afterwards?

That part is correct regardless of the above: Ignoring a file means you stop being in sync with others. Once you un-ignore, you don't just go back to the state before ignoring, you start from scratch locally. I.e. it's treated like a new file, thus it's a "Local Addition".

**Comment by tomasz1986** [comment]
> I get why you'd expect a file that now only exists on receive-only folders to be marked as a local addition, but we can't detect that: Imagine a second receive-only folder. The file from the other receive-only device will look perfectly valid to a receive-only folder, so it can't detect that only receive-only folders have the file.

Yeah, I think the reason why I find it difficult to accept is the fact that there are only two folders in question here - the initial SO folder, and the RO folder. If more folders are included in the equation, then the situation becomes much easier to understand.
