### ISSUE TITLE
"watch for changes" doesn't work on Pixel 5 with google camera and fotos

### ISSUE THREAD

**Issue by bahrthaare** [syncthing/syncthing#7062]
Hello, I’m using syncthing v1.11.0-rc3 on Android in the Pixel 5 with Android 11. It themes to me that the ‘watch for changes’ function does not work If the google camera app or the google fotos app do changes, with other apps like google files the changes will recognized imminently. The changes from the camera or fotos app will only recognized if a manual scan is performed.

Don’t know if someone else has this problem.

**Comment by calmh** [comment]
Hi! This is unfortunately the wrong repository / issue tracker for your issue. Please file it in http://github.com/syncthing/syncthing-android/issues to get the correct attention. That said, I suspect the issue here is that the app in question don't change the size or timestamp of the file, so there's nothing to indicate to Syncthing that a full rehash is reauired.
