### ISSUE TITLE
Setting modTimeWindowS does not clear "Local Additions" in Receive Only folder

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7067]
How to reproduce:

1. Share a folder with 1 file between Device A and B.
2. Let the two folders sync.
3. Set the folder on Device B as Receive Only.
4. Modify the mtime of the file on Device B by a few seconds.
5. The folder on Device B is now marked as "Local Additions".
6. Set `modTimeWindowS` in the RO folder on Device B to `60`.
7. The folder on Device B is still marked as "Local Additions".

However, if `modTimeWindowS` is already set to `60` when modifying the mtime, then the folder is correctly marked as "Up to Date".

Tested with `main` (`v1.11.0-rc.3.dev.7.gdeafe4ca`).

**Comment by imsodin** [comment]
This is expected: The modification time is compared at scan time. If it differs, the file is considered different and stored thus. Changing `modTimeWindowS` only affects changes after that. We could check the entire db when `modTimeWindowS` is  changed to find files within the window that are otherwise identical. However that's way too much effort for a tiny benefit: For non-receive-only folders there's no benefit and for receive-only folders it safes a click on revert changes.

**Comment by tomasz1986** [comment]
> However that's way too much effort for a tiny benefit: For non-receive-only folders there's no benefit and for receive-only folders it safes a click on revert changes.

I am not sure if I understand this. The revert changes button does not work in this case. It only marks the folder "Up to Date" until the next scan. As soon as the folder is rescanned, the "Local Additions" come back.

**Comment by tomasz1986** [comment]
This should be in not docs though. Right now, the behaviour is confusing. It makes an impression that `modTimeWindowS` is just not working at all. The Docs also state that `Used in Android only` is "Used in Android only", which is not the case.

I will update the Docs to add this information.
