### ISSUE TITLE
option to not perform UTF8 localization and keep filenames as they are

### ISSUE THREAD

**Issue by mikelpr** [syncthing/syncthing#7101]
### Include required information

 - which version of Syncthing and what operating system you are using
1.11.1, Gentoo

 - what happened,
item has UTF8 encoding conflict with another item

 - what you expected to happen instead
no problems syncing

 - any steps to reproduce the problem.
download torrents that use odd characters

I don't understand why syncthing even performs the normalization. I just want to sync my files back and forth as they were exactly. Normalization breaks restarting torrents when syncing the data back as it changes the filenames' characters

**Comment by calmh** [comment]
I'm skeptical as unicode normalization of synced files is essential for any kind of cross platform operation, and I think it would be a huge footgun with even more mysterious effects if we disabled it. That said, you can disable that fix that Syncthing applies locally, in order to avoid the issue with your torrents: set the advanced folder config `autoNormalize` to false. The files will still not sync as long as they are not well formed utf8, but Syncthing will leave it alone on disk.

**Comment by mikelpr** [comment]
I don't know, having both machines being linuxes I wouldn't be affected and it'd just sync the files with their names as is even if they're bad UTF chars.

maybe make it a three option: no autoNormalize and no sync, no autoNormalize but sync, and autoNormalize + sync

**Comment by mikelpr** [comment]
I want to insist that normalizing or complaining about it not being normalized is an issue. Right now I can't sync with syncthing some music made by friends that had é in them because on their macOS computers it uses e and a ´ so they're not in the correct normalization, but I know for a fact my linux machine can deal with e ´ separated

**Comment by calmh** [comment]
Yes, I realize that Linux can deal with filenames that are not correctly normalized UTF-8. You can even run your entire system in ISO-8859-1 or Big 5, and it'll work fine, but Syncthing insists on UTF-8 or filenames. This is a limitation but not one we are likely to alter.
