### ISSUE TITLE
Archival policies as an option per folder to support archiving away of large folders

### ISSUE THREAD

**Issue by anilgulecha** [syncthing/syncthing#7171]
Syncthing does one job, and does it well. Syncing of a folder across devices. Knowing this, I'd carefully like to propose a small feature addition that will take on a big problem.

One of the most common target device is a phone, and syncthing defaults to adding in the camera (DCIM) folder. A common problem is that pictures/videos eat up device storage space quickly, and some kind of archival of these is needed. Untold amounts of happy memories are lost, because people do not have the energy or technical capability of setting this up. I think syncthing can solve for this usecase

User Persona: Syncthing admin/user, who sets up devices for their family members, and friends.

Requirement:
 - Allow automated syncing to nodes with larger storage space.
 - Allow smaller clients to not run out of space.

User flow: Under advanced settings: Under advanced settings of a folder, a new checkbox option: **Archived ?**. When selected, a size in GB is needed which indicates what's the archived mode **Max size** (default 5gb).

With this option turned on, If the contents of the folder are upto max_size, they will be fully synced. Should the size be > max_size, then the max_size GB of the most recent files are the ones that are synced.

This will achieve the desired result:
 - Larger clients (rPI with a HDD attached), will never turn on this option, and have all files available there.
 - smaller clients (phones, etc) will only have the most recent max_size of contents, and also the peace of mind that the older data is archived away on larger clients.
 - The user's requirement is fulfilled: they can one-time onboard the camera, and other folders for family and friends, whose devices will continuously backup content into the larger clients, while the local client will not run out of space, and also have access to the most recent files (which is the primary usecase for camera photos).

While the above is a general implementation idea, I've not investigated if the syncthing replication protocol will allow for above exact solution. If someone more knowledgeable here can point out a more elegant solution for the usecase, I would appreciate it.

Workarounds: I currently manually copy over my friends and family's photos into my disk. I don't believe a solution for the above currently exists

**Comment by calmh** [comment]
Given that the phone camera folder is where new data is produced, is the intention that Syncthing would delete older data from that folder when it sees newer data being produced?

**Comment by imsodin** [comment]
> Syncthing does one job, and does it well.

Use that: Sync all these camera folders to your beefy node. There have a program/script/whatever that archives those, i.e. immediately backs them up/copies them to a different directory and delete the oldest files above the chosen threshold storage. That way syncing is done by Syncthing, which it is great at, and archival/backup is done by whatever tool you choose, which is great at archival/backup (you anyway really need proper backups of your photos).

In my opinion something like this is out of scopy for Syncthing (if even sanely implementable).

**Comment by anilgulecha** [comment]
> Given that the phone camera folder is where new data is produced, is the intention that Syncthing would delete older data from that folder when it sees newer data being produced?

You've captured the intention correctly. This should be purely opt-in - per folder, per device.

**Comment by anilgulecha** [comment]
> Use that: Sync all these camera folders to your beefy node. There have a program/script/whatever that archives those, i.e. immediately backs them up/copies them to a different directory and delete the oldest files above the chosen threshold storage. That way syncing is done by Syncthing, which it is great at, and archival/backup is done by whatever tool you choose, which is great at archival/backup (you anyway really need proper backups of your photos).

Indeed, that may very well be the right way of scoping the boundary of syncthing's functionality - the core team and community is best placed to decide.

My rationale for bringing up this feature request was to outline a rather large real-world usecase, which could potentially be within syncthing's scope. The utilitarian advantage would be opening up syncthing to this large problem.

Philosophical advantage: the world would be a happier place if the amount of media and memories lost inadvertently is reduced :)

**Comment by AudriusButkevicius** [comment]
I feel this is out of scope for syncthing. Syncthings purpose is to sync files from A to B and back. 

Archival deletion of files and what not was never a goal for it.

On my pixel phone google photos already do that (once the photis are uploaded), so I think you should find a different application that would do that for you.

**Comment by ProactiveServices** [comment]
I have to say this sets off my "sanity alarm" but I guess some real-world questions and examples are helpful:

When the global status is >max_len, what would the smaller device show as its sync status? What whould a remote device show as its sync status to such a device? It may never be up-to-date. How big are directories? How are we rounding file sizes? How do we manage disparities between the smaller and larger device for these? What happens when say, all of the time stamps are set to $now on either device,? What happens when a user decides to remove the geotag from all of their >max_size media?

A few problematic cases off the top of my head:

- Large Node has 10GB data, Small Node has 5GB data, max_size is 5GB.
- Large Node updates a 1GB file.
- Small Node must delete 1GB of files to obey the limit.
- Small Node syncs updated file.
- User realises they didn't want the 1GB of older files deleted.

How does the user get those 1GB of files back on Small Node? Forcing changes to ctime is one way, but non-technical users would struggle to do this, and forcing metadata changes is data loss, IMO.

- User zips a copy of 5GB of the files on Large Node and copy them to a USB stick.
- 4GB of data is added to Large Node.
- Small Node erases 4GB of old files.
- User moves 4GB zip file from Large Node to USB stick.
- Small Node now has to resync 4GB of the most recent files, chewing battery and WiFi.

User complains of the forum that Syncthing is using up all their battery and WiFi bandwidth.

**Comment by imsodin** [comment]
If anyone was here with a PR to do this, there would be some merit in discussing it. Right now this is not relevant for development, but more of a generic use-case presentation/explanation - lets move that to the forum.

**Comment by anilgulecha** [comment]
Thank you all for engaging. Should someone come across this problem in the future, and has a solution that they've figured out - can you please share there.

**Comment by mmonaco** [comment]
Interesting that this is only a recent FR, has it been discussed before? I've hoped for a similar feature for years for safely managing photos/videos from phone. I think it would be **very useful** to be able to have Syncthing remove (or treat as a ring buffer similar to OP's description) files when they've been synced to something like *n devices* or *x,y,z device*. This would be on top of the oneway+ignoredelete configuration.

This is desirable in Syncthing because a) it already knows the global state of each file, and more generally b) it doesn't feel like a big stretch from the current feature set. I wouldn't be excited about running two services to do this, especially on a mobile phone.
