### ISSUE TITLE
Spurious unexpected directory in untrusted folder

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7184]
After rescanning an untrusted folder a bunch of "unexpected items" appear, each representing a directory. These appear to be for cases where we've split a long directory name by adding slashes to avoid max filename length issues.

That is, a short directory on disk might be represented as `0.syncthing-enc/AB/CDEFGH` and that's handled. A longer one might be `0.syncthing-enc/AB/CDEFGH...XYZ/ASDFG` and in this case the intermediate directory is considered unexpected.

A practical problem here is that we can't actually look at any given directory in isolation and draw any conclusions about whether it's unexpected or not, because it might be just part of a longer file or directory name. Perhaps we should let any and all directories slide, as long as they are under a `?.syncthing-enc` top level directory, and just react to files that can't be properly mapped.

(Or maybe just let any unexpected things be there and be ignored... Keeping in mind that just opening an encrypted dir in a file browser is likely to litter it with .DS_Store and other crap on mac, possible similar stuff on other platforms...)

(`v1.12.1-dev.41.gc1b452df`)

**Comment by imsodin** [comment]
We can detect if something could be expected. It's still possible that a user was crafty or unlucky to create a dir that has the right length, but I don't think that's anything we need to be concerned about (that dir will just be ignored or deleted if empty). Fixed in #7184 

As to whether it would be good enough (because easier) or even better to just ignore everything that's in a toplevel `.synthing-enc` type directory:  
I think it's not better. Sure all those auto-generated files are just an annoyance. However those are an annoyance in both receive-encrypted and "normal" folders. So an actual solution should take care of them in general - something like adding common (effecting all folders locally) and/or default ignore patterns.  
Assuming the above judgement holds, that leaves us with the evaluation of "good enough" (ignore everything) vs "complexity" (best effort filtering of extraneous items). This bug is evidence that it can go wrong, thus I clearly can't claim it's super simple, then again I am somewhat hopeful with the pending fix we are clear now. And I haven't come up with any scenario where a mess happens, such that it's hard for the user to make a distinction between Syncthing's items and extraneous files. So we might as well not care about the distinction and call it good enough.  
I am sort of undecided, with a tendency to keep filtering potentially extraneous files, but my gut says that I just want to keep it because it's already implemented and it would be better to remove it :D
