### ISSUE TITLE
Build script -no-upgrade handling is unintuitive

### ISSUE THREAD

**Issue by philpennock** [syncthing/syncthing#7199]
Having discovered that my self-built binary had been auto-upgraded, I went looking to disable that feature.  I found the `build.go` option `-no-upgrade` and it almost works.

```console
$ git describe
v1.12.1-rc.1-12-g466e8a5c
```

The problem is that the `stupgrades` command, understandably, doesn't compile under the `noupgrade` build tag.

I fixed it for myself the fast and crude way, but I'm not familiar enough with the code base to know what the best structure is, so rather than fork/dance/PR, here's a fast fix which WorksForMe™; a better fix might be to move a bunch of logic out of `init()` time so that flags are available at the time the data structure is first built.

```patch
diff --git a/build.go b/build.go
index cc23c92d..9c13590f 100644
--- a/build.go
+++ b/build.go
@@ -256,6 +256,18 @@ func main() {
 		}()
 	}
 
+	if noupgrade {
+		all := targets["all"]
+		t := make([]string, 0, len(all.buildPkgs))
+		for _, s := range all.buildPkgs {
+			if s != "github.com/syncthing/syncthing/cmd/stupgrades" {
+				t = append(t, s)
+			}
+		}
+		all.buildPkgs = t
+		targets["all"] = all
+	}
+
 	// Invoking build.go with no parameters at all builds everything (incrementally),
 	// which is what you want for maximum error checking during development.
 	if flag.NArg() == 0 {
```

**Comment by calmh** [comment]
Yeah, that option is for building Syncthing packages specifically, as it doesn't make sense for the other various things.

It's [mostly documented](https://docs.syncthing.net/dev/building.html#subcommands-and-options):

> The options `-no-upgrade`, `-goos` and `-goarch` can be given to influence `build`, `tar` and `zip`. Examples:
>
> `go run build.go -goos linux -goarch 386 tar`
>    Builds a tar.gz distribution of Syncthing for linux-386.
>
> `go run build.go -goos windows -no-upgrade zip`
>    Builds a zip distribution of Syncthing for Windows (current architecture) with upgrading disabled.

If anything I guess the build script could be made to reject the option except for those subcommands. Or the command line parsing changed so that the option only exists for those subcommands. Seems potentially over engineered though. 🤷
