### ISSUE TITLE
Impossible to ignore files/folders with leading spaces

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7228]
There are two issues here.

First, the GUI strips leading spaces from ignore patterns.

1. Add " test" to Ignore Patterns using the Web GUI.
2. Save the changes and then check the patterns again.
3. " test" has automatically been changed to "test".

Now, the actual issue.

1. Create a new file called " test" (yes, with 1 leading space).
2. Add " test" to `.stignore` manually (not with the GUI).
3. The file remains not ignored.

Tested with v1.12.0.

**Comment by calmh** [comment]
I think white space trimming is sensible, as your use case should be exceedingly rare. You should be able to apply same the workarounds needs for files starting with `#` or `(?i)` etc: lead with a slash and/or `**/`. 

This could be a documentation improvement somewhere.

**Comment by tomasz1986** [comment]
There is no real use case, I am just fooling around :flushed:.

Note that it strips not only normal spaces, but also all other type of space-like Unicode characters (non-breaking space, narrow space, etc.).

"**/ " works nicely though. I will try to update the docs if no-one else does it.

**Comment by calmh** [comment]
Yes, and this is intentional. Many editing environments (like my phone with autocorrect) will add trailing spaces and both those and leading spaces are essentially invisible to the user, so removing them is the right thing. Having them being taken literally would almost never be the right thing. So functions as designed.
