### ISSUE TITLE
panic: deadlock detected at fmut

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7231]
Possibly related to https://github.com/syncthing/syncthing/issues/7230, but not sure. It happened 15 minutes before the other panics. The cause is unknown, but I was maybe trying to pause and resume a folder at that time.

```
[D4DZU] 18:55:26 INFO: Failed to exchange Hello messages with CWXZ7CV-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at [::]:22000-178.42.98.249:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: Application error 0x0: closing
Panic at 2020-12-24T19:08:28+09:00
panic: deadlock detected at fmut

goroutine 58 [running]:
github.com/syncthing/syncthing/lib/model.(*deadlockDetector).Watch.func1(0x12c60ff0, 0x32f86fd8, 0x12baa720, 0xd961dc, 0x4)
	github.com/syncthing/syncthing/lib/model/util.go:61 +0x2b4
created by github.com/syncthing/syncthing/lib/model.(*deadlockDetector).Watch
	github.com/syncthing/syncthing/lib/model/util.go:37 +0x93

goroutine 1 [chan receive, 55 minutes]:
github.com/syncthing/syncthing/lib/syncthing.(*App).Wait(...)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:370
main.syncthingMain(0x12a58700, 0x1f, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:719 +0x59f
main.main()
	github.com/syncthing/syncthing/cmd/syncthing/main.go:438 +0x33b
```

[panic-20201224-190828.log](https://github.com/syncthing/syncthing/files/5739282/panic-20201224-190828.log)

Syncthing v1.12.0.

**Edit**: Just for the record, I have found the older issue (https://github.com/syncthing/syncthing/issues/6076), but this here is not a slow device.

**Comment by imsodin** [comment]
The trace doesn't match the v1.12.0 source code, deadlock-watchers are only enabled on RCs/dev builds and the first line containing the version is missing in the panic log - could you recheck the Syncthing version please.

**Comment by tomasz1986** [comment]
Yeah, this is a dev build with 5 custom commits on top of v1.12.0. I am sorry for not mentioning this above. With the exception of the CPU/RAM measurement revert, the commits are very minor though. I should have still have been specific about it regardless.

These are the changes: https://github.com/tomasz1986/syncthing/commits/tomasz86-release.

Anyhow, I cannot reproduce the issue, so this one-time panic log is all I have right now.

**Comment by AudriusButkevicius** [comment]
This looks suspicious:
```
1: select [23 minutes] [Created by config.(*wrapper).notifyListeners @ wrapper.go:210]
    model           indexsender.go:115        (*indexSender).pause(#703)
    model           indexsender.go:395        (*indexSenderRegistry).pause(#459, #1162, 0xb)
    model           model.go:496              (*model).restartFolder(#190, #290, 0xb, #291, 0x6, 0, #292, 0x6, 0, #642, ...)
    model           model.go:2479             (*model).CommitConfiguration(#190, 0x20, #654, 0x20, 0x20, #624, 0x9, 0x9, 0x1, #339, ...)
    config          wrapper.go:220            (*wrapper).notifyListener(#76, #21, #190, 0x20, #654, 0x20, 0x20, #624, 0x9, 0x9, ...)
    config          wrapper.go:211            (*wrapper).notifyListeners.func1(#76, #1018, #433, #26, #1164, #21, #190)
```

Config wrapper is hanging on pausing the index sender, yet it seems there is no reference to the index sender anymore? 
0x13b4a5a0 is the address of the sender, but it only appears in the panic once.

It seems because of that, the rest call seems to be hanging.

Wonder if we could change the lock acquisition to be a 
```
WithFmut(() => {
})
WithPmut(() => {
})
```
so that it would be easier to see in the call stacks who's holding what.

**Comment by AudriusButkevicius** [comment]
Actually no, this **is** the deadlock, restartFolder holds both pmut and fmut while pausing the sender.

**Comment by imsodin** [comment]
For the blocking index-sender `(*indexSender).pause(#703)` there is no `Serve` routine running, but the connection isn't closed either. When a sender is regularly stopped, it is also removed from the index sender map under lock, i.e. the `pause` call shouldn't happen in the first place. The only way I can see this happening is on a db error, in which case the index-sender stops without dropping the connection, and no-one knows about that.

I added a generic mechanism that unblocks methods of `indexSender` regardless of why `Serve` terminated (instead of unblocking on closed connection only): https://github.com/syncthing/syncthing/pull/7232
