### ISSUE TITLE
infinite filesystem recursion due to missing file id

### ISSUE THREAD

**Issue by GitHobi** [syncthing/syncthing#7385]
I'm trying to use syncthing with a folder exposed by cryptomator. 

The problem is that I'm getting for all folders / files "infinite filesystem recursion" as the virtual filesystem of cryptomator seems to not generate a unique file id for each file.

As example:
X:>fsutil file queryfileid keyfiles
File ID is 0x00000000000000000000000000000000

X:>fsutil file queryfileid pictures
File ID is 0x00000000000000000000000000000000

As far as I have seen syncthing relies on the unique file id for internal purposes. So far so good. However, I've created an issue on the cryptomator side (see https://github.com/cryptomator/cryptomator/issues/1540), but as I understood having a unique file id (provided by the file systems) is nothing you can rely on, according to the cryptomator developers. 

I'm not sure if this is true or not, but it seems to be true, as e.g. almost all tools can work with a cryptomator drive without issues - but syncthing. 

As syncthing is a greate / cool tool, I'd like to bring this to your attention.

Syncthing in use: V1.13.1, Windows 10 20H2.

**Comment by tomasz1986** [comment]
Please check https://forum.syncthing.net/t/the-system-cannot-find-the-file-specified-cryptomator/16228.

**Comment by GitHobi** [comment]
Thanks for the hint. I did not see that post.
I can confirm this seems to work. Is this a reliable workaround?

**Comment by tomasz1986** [comment]
Not really, if you read the last forum posts. I may give it another try later today. Also, the thread on the forum is still open, so I would suggest to continue this discussion there.

**Comment by imsodin** [comment]
Maybe it would make sense for `os.SameFile` to return false if the id is 0, similar as when an error occurs getting the id: https://golang.org/src/os/types_windows.go#l216. You could ask about it on some Go forum: https://golang.org/help/

**Comment by AudriusButkevicius** [comment]
To be honest, the simplest option is to avoid checking infinite recursion unless junctionsAsDirs is enabled.

**Comment by tomasz1986** [comment]
I have given it another shot, and it seems that:

1. The problem is limited to subfolders only, as files located in the main path do not trigger the error.
2. Even without this issue, there seem to be problems detecting changes on the Cryptomator volume. It seems to work fine in the beginning, but if you try to add/modify/delete files, then you will see that Syncthing will eventually fail to detect those changes simply by rescanning the folder. They only seem to get detected after pausing and resuming the folder, but even that does not appear to work all the time.

I am not going to do any more testing, as I am not a Cryptomator user anyway. In this state though, I would say that the combination of Cryptomator and Syncthing is not usable.
