### ISSUE TITLE
Settings is blank

### ISSUE THREAD

**Issue by dannytech** [syncthing/syncthing#7397]
I'm having the same issue as #4467. Most of the settings (except the device name and listen address) are blank. There aren't any errors in the browser (network and console) or server logs besides what is expected (a 500 error on the upgrade endpoint). The one difference is that I'm only encountering the issue on Chromium Edge 88.0.705.74, both Chrome 88.0.4324.182 and Firefox 84.0.2 work just fine. I've tried everything mentioned in the linked issue, deleting cache and even cookies, with no luck. I've confirmed that all the settings are in `config.xml`, they're just not displaying.

System information: Syncthing 1.9.0 running in a TrueNAS 12.2 jail. All browsers running on Windows 10.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request, especially since it seems to be localized to a single browser? Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
