### ISSUE TITLE
Prevent constant sync of the file user continuously works with.

### ISSUE THREAD

**Issue by phonexicum** [syncthing/syncthing#7590]
**Situation example**: User works with the big file all day through application/IDE with autosave feature. To make things worse let the file format be zip-compressed, therefore the user's changes will change the file significantly.

**Problem**: syncthing will constantly copy the file to other devices. It will have 2 negative consequences:
* the network resource will be consumed for nothing;
* the SSD or flash drive of other devices will experience a lot of **useless** write operations exhausting their lifecycles;

**Proposal**: introduce the "file sync delay" option (e.g. X seconds), which will prevent syncthing to sync the file, which has been changed less than X seconds before (e.g. 300, 600, 900, ... seconds).

**Comment by imsodin** [comment]
That option is there already `fsWatcherDelayS`: https://docs.syncthing.net/users/config.html

**Comment by phonexicum** [comment]
If I understand the description of `fsWatcherDelayS` correctly: it will delay all files synchronization for X seconds.  
There is 2 consequences:
* In the situation described previously syncthing will perform useless synchronizations from time to time;
* There is no need to defer sync process for all files, only for the file which is currently modified by user;

That is why I propose additional option, which will force syncthing to check if the file hasn't been modified for some time.

**Comment by AudriusButkevicius** [comment]
I understand what you are proposing, but I don't think we want that, as things like log files would never get synced, as they are constantly written to.

**Comment by phonexicum** [comment]
I didn't mean the log files.  
Examples can be taken from ordinary user's files: Outlook's `*.pst`, big PowerPoint/Word presentations, ...  
I also assume there is a lot of other applications (in different industries: video, ...), whereas applications regularly update the file containing data, while user edit it.  
Or maybe a developer, who all day work under the project and builds it. There is a lot of artifacts, which will change every time, but there is no need to synchronize every version of them.

There is also another consequence in addition to the previous 2 I proposed:
* If the application creates temporary files near the user's target file and updates the file, there is no need to synchronize such temporary files at all.

**Comment by AudriusButkevicius** [comment]
We don't want to get into a territory of classifying files by type and then doing certain things based on type.

In the general case syncthing should do what it's made for, and that is sync files as fast as it can, under any circumstances.

If your use case suffers from this behaviour, then you can manage this by pausing the folder while you don't want it to do things, or perhaps it's the wrong software for you to start with.

The temporary file case can be solved by ignore patterns.

We are not going to add "don't sync files because they changed recently" as I feel thats the wrong thing to do in the general case (logs etc). And we are not going to add "don't sync file because it's a word document" because that's a rabbit hole.
