### ISSUE TITLE
Incorrect local state when using negated patterns inside ignored parent folder on both sides

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7740]
I have finally managed to reproduce https://forum.syncthing.net/t/folder-stuck-in-sync-and-non-matching-local-and-global-states/16431.

1. On Device 1, create a folder called `test1`.
2. In the folder, create a folder `test`, and then inside it another folder `test`.
3. The folder structure now looks like `test1\test\test`.
4. Add the `test1` folder to Syncthing with the following ignore patterns.
   ```
   !/*/
   *
   ```
   As expected, both the subfolder and its parent folder have been indexed.
   
   ![image](https://user-images.githubusercontent.com/5626656/120593696-d4317f80-c47a-11eb-844b-e22c93bd0a7d.png)

5. Share the folder with Device 2, and accept it there with the same ignore patterns as above.
6. The folder state on Device 2 is correct, but the local state on Device 1 has changed. The parent folder has been ignored, despite its child being unignored.

   ![image](https://user-images.githubusercontent.com/5626656/120593803-f62b0200-c47a-11eb-8f24-3503984eca31.png)
   ![image](https://user-images.githubusercontent.com/5626656/120593806-f7f4c580-c47a-11eb-9700-df1fe3213c7d.png)

Logs with `model` and `db`:

[syncthing1.log](https://github.com/syncthing/syncthing/files/6589230/syncthing1.log)
[syncthing2.log](https://github.com/syncthing/syncthing/files/6589231/syncthing2.log)

One thing to note is that the folder states are correct when not using the same ignore patterns on the other side. It seems that it is only when the same negate/ignore patterns are applied to both sides that the issue occurs.

**Comment by imsodin** [comment]
Ah wow, this is a weird problem, coming down to one difference between scanning and syncing: Scanning traverses the entire filetree, while syncing deals with individual items.  
Here we have a parent dir which is ignored according to patterns, but not ignored because there's an included child. Scanning does see the child and thus does not ignore the parent. Syncing just sees individual files and marks the parent as ignored when syncing it. Thus we enter an infinite loop which is visible in the logs you provided (thanks):

1. Device 1 adds parent and child from scanning, i.e. not ignored with versions {1: 1}
2. Device 2 syncs parent as ignored, child as not ignored.
3. Device 2 scans, sees that parent is ignored but shouldn't be. Thus un-ignores the file which ends up with version {2: 1} which is in conflict with device 1.
4. Pulling resolves the conflict, ignoring the parent. Go back to 3.

I see one hopefully rather small and unobtrusive change that would fix this and also benefit other scenarios: When unignoring something during scanning, get the current global file. If the files are equivalent, use the global version. Currently we drop the version to intentionally create a conflict (as an ignored file might have changed compared to the global while ignored). Thus there's no need to go through a puller iteration to resolve the "conflict" when items are actually identical with the global file. I'll look into doing that.
