### ISSUE TITLE
Change how we acquire locks

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#7765]
So this is a long shot, but I think we should change how we acquire locks to make it easier to debug deadlocks.

Namely, we could have something like

```go
var var1, var2
m.withFmut(func() {
   ...
   var1 = x
   var2 = y
})
```
or
```go 
m.withLock(m.fmut, func() {})
```

Or given we own the locks package, we could add utilities functions to the locks themselves.

```go
m.fmut.WithRlock(func() {
})
```

This obviously makes it sad and painful to get variables out of the lock block, but atleast the fact that a routine holds a lock would be clearly visible in the stacktraces.

What do people think? If people agree, then I'm happy to do the work.

**Comment by calmh** [comment]
I've used this in the past and I dislike how it makes returning a value from inside the closure annoying (more than just regular variables declared above the closure) because you can't just return for a for loop or whatever. This is mostly a thing in the model though and we could use it judiciously there. With either of the patterns suggested or manually with foo() being a thing wrapper around fooLocked() type things.

**Comment by imsodin** [comment]
I can't remember deadlocks to have been an issue in quite a long while. All the fmut/pmut reports I looked at were false positives (I am considering doing something unrelated about those) or nonsensical (e.g. blocking on cancelling a context that exists nowhere else). Thus I am unsure the effort required for and drawbacks of the change proposed here are worth it. Obviously not having noticed any deadlocks isn't the same as there really not being any. If you believe it would help, I am not opposed :)

**Comment by AudriusButkevicius** [comment]
I think this is now much easier given generics?
