### ISSUE TITLE
#7598 broke compatibility 

### ISSUE THREAD

**Issue by r13l** [syncthing/syncthing#7767]
Android: v1.17.0
Desktop: v1.0.0
What I expected to happen: connections and syncing
What actually happened: `server selected unsupported protocol version 303` errors on the Android phone, nothing on the desktop side

The two devices cannot sync because v1.17.0 includes #7598, which broke compatibility with v1.0.0 (and perhaps other versions), despite the guidance in the [Version & Releases](https://docs.syncthing.net/users/releases.html) documentation.

**Comment by AudriusButkevicius** [comment]
That ship has sailed. I don't think we are going to do anything about this.

There is zero reason to be on 1.0.0

**Comment by AudriusButkevicius** [comment]
The docs talk about protocol compatability. They are still technically protocol compatible, they are not transport compatible, so if I was a lawyer I could say we are still true to our words.

**Comment by r13l** [comment]
> There is zero reason to be on 1.0.0

Running Debian stable is a reason to be on 1.0.0. The alternative of adding a project-specific APT repo is IMHO a non-starter for any administrator who seeks stability and the assurances that come with installing _only_ packages from his preferred distribution.

I think there are two issues here: one, breaking compatibility; two, not labelling it. With respect to the first, it might indeed be time to not just deprecate but disable TLS 1.2, but I think that should not happen until all major downstream distributions (and Debian is certainly a major distro) have had sufficient time to upgrade to a compatible version. With respect to the second, I think that labelling the incompatibility might have led to giving more consideration and thought to those downstream effects.

Syncthing has been an _awesome_, reliable project. I have used it for years and years, and recommended it to others. Thanks very much for all the hard, excellent work y’all have done. I love and share your concern for security. I think that in this particular case the project moved too quickly and broke things. Granted, a sync system which does not work _is_ secure, but … it’s also not a sync system.

**Comment by acolomb** [comment]
I kind of agree that knowingly breaking compatibility was not a really nice move.  Part of the justification comes down to: "If people insist on staying with old versions, they will not have this problem anyway.  They will just use whatever old version everywhere."  But with a distributed network like Syncthing, you don't always have control over all participants.

It's kind of comparable to the Internet / browser situation:  Servers update all the time, basically dictating what technologies a client must support.  You cannot actively use Firefox 1.5 nowadays (although it was a great release!) because it lacks many protocol requirements of modern web servers.  What Debian & Co. does is they pull in recent versions of such software regularly, even for rather old, but still active LTS releases.

So the Right Thing to do would be an SRU (stable release update) for the Debian (Ubuntu, etc.) package, citing this TLS 1.3 change as a reason.  As it's a change in the name of network security, and the browsers are treated similarly, I think that might have a good chance of getting accepted.  Somebody just needs to open a bug report and convince the downstream maintainers.  Then all Debian admins will become happy v1.18.0 users :-)

**Comment by AudriusButkevicius** [comment]
We did the breakage consciously, and it was the first line in the release notes for 1.17.0.

We don't control Debian release cycles.
We don't want to control Debian release cycles.
I don't think there is anyone in Debian looking after syncthing releases, so I think it's likely to be stuck for 1.0.0 potentially forever.

We have our own distribution channels, and those are the only channels we are responsible for and make sure they align.

If you are suggesting for us not to move forward with improvements to software because syncthing is abandoned on Debian, then I can tell you, this is not going to happen.
I don't think we should be held hostage by any distribution that decides to package syncthing and then doesn't move it's versions forward. Regardless if it's a one man band distributions or large distributions like Debian.
We don't want to have to tie our release timelines/dependencies with them.

If you feel a strong need to use Debian packages, then I suggest you find something similarly abandoned for Android and avoid our releases.

If that's not an option, I suggest you go through each release notes with a toothpick and make your own call if you want to upgrade other things that do use our release channels.

I don't really see anything actionable on this issue, namely there is nothing being asked other than a complaint that things stopped working, which is "working as intended" as far as I am concerned, and I don't think we'll revert anything, hence I am closing this.

**Comment by imsodin** [comment]
How is nobody mentioning `insecureAllowOldTLSVersions`?  
You shouldn't use it, you should upgrade. However we consciously added that to keep backwards compatibility. Copy of the release notes:

> This release deprecates TLS 1.2 for sync connections; other side should
be Syncthing 1.3.0 or newer, or see
[insecureAllowOldTLSVersions](https://docs.syncthing.net/advanced/option-insecure-allow-old-tls-versions.html).

Someone mentioned documentation: It's in the release notes *and* calmh even wrote documentation detailing an option we don't want you to use, but still offer.

>  I don't think there is anyone in Debian looking after syncthing releases, so I think it's likely to be stuck for 1.0.0 potentially forever.
>
> [...]
>
>  If you are suggesting for us not to move forward with improvements to software because syncthing is abandoned on Debian, then I can tell you, this is not going to happen.

Just to clarify: It isn't abandoned in debian. As a matter of fact I backported a few fixes I considered highly important for the upcoming debian release, which will be on v1.12.1 (which reminds me that I need to check if they were actually integrated). It's just the way debian works: You get whatever was packaged when it is released plus security updates. If you want up-to-date-ish debian releases, you need to use debian testing. If you want really up-to-date releases, use apt.syncthing.net.

**Comment by aviau** [comment]
I can confirm that Syncthing isn't abandonned in Debian. I put in many hours of work to get 1.12 in. Per Debian stardards, 1.12 isn't old. We would never release if we only settled for 2-months-old software.

**Comment by AudriusButkevicius** [comment]
To clarify my position, I have not heard from @aviau in a while, and having seen the latest version is still at 1.0.0, I assumed nobody was working on it, which is incorrect from my side.

Never the less, getting 27 month old release of software, that used to be released weekly, still feels a bit abandoned, and telling users to upgrade their operating system/switch to testing repos is generally not a great experience.

I understand the ambition for sysadmins to have a stable distribution/operating system, but it's strange that the same rules apply to auxiliary software that has nothing todo with the operating system itself.

The release cadence mismatch will always be there, and I don't think there is a good way around this, other than suggesting that people should prefer our channels, or if they choose the distribution channels, it becomes their responsibility to do the homework to figure out if things will not break, and we do our best by adding flags as usual, and hoping that we didn't screw up.

We even accidentally break things between minor releases, and the fact that we can kick out a new version quickly is usually the thing that saves the bacon, so from my personal perspective, committing to not breaking anything for 2 years is a big ask.

**Comment by r13l** [comment]
> How is nobody mentioning `insecureAllowOldTLSVersions`?

Thanks for mentioning this! I had looked for it last week, but your mention inspired me to go digging again, and I found it this time. For the next fellow who needs to figure this out, here is how to enable backwards compatibility:

1. Open the web UI.
2. Gear menu
3. Advanced
4. Options
5. Set Insecure Allow Old TLS Versions

**Comment by NeonHorizon** [comment]
Unfortunately it also broke sync with Ubuntu clients and servers using LTS versions. I think since its reasonably likely Ubuntu is the largest Linux distribution in use today and Canonical have stated LTS versions are by far the most popular, its almost certain this has detrimentally affected a large number of people.

However in Syncthings defence I am also well aware of the frustration developers face with the speed distributions update their packages and the version lock in issues, so both sides have my sympathies.

For me personally I can solve the issue with Syncthings recommended repo's but not everyone can afford this luxury, especially in strictly controlled environments.
https://apt.syncthing.net/

I do agree with others that have said a breaking change like this should really have been postponed to a major version release or remained backwards compatible by default. However these things happen and like others have said this is an exceptionally good project overall and I am for one grateful for the devs that keep it running.

Thanks!

**Comment by netlore** [comment]
@NeonHorizon 

It seems from the above that this is due to older, insecure versions of TLS being disabled by default as they have been in browsers and other software for some time, and there appears to be an option to "Allow Old TLS Versions" if you don't care about security, it seems that Syncthing did the right thing.... you wouldn't say that Google did a bad thing when they disabled older insecure TLS versions by default, even tho everyone who was running old software had to update their web servers....  This seems similar to me.

A security fix is not optional, and so it had to be done...  and either individual people will have to upgrade via the repo, or if there is enough demand, then Debian will do an SRU...

**Comment by r13l** [comment]
@netlore 

This disabled support for TLS _1.2_ by default; as of today and per [Wikepedia](https://en.wikipedia.org/wiki/Transport_Layer_Security#Web_browsers) it appears that no major versions have disabled support for TLS 1.2. In this case Syncthing is more forward-leaning than any browser or other software of which I am aware.

Sometimes a security fix is mandatory (e.g. one which patches a vulnerability); sometimes it is optional (e.g. one which marginally improves security). Disabling SSL 1.0 would be a mandatory security fix; I think disabling TLS 1.2 in 2021 should be optional.

**Comment by NeonHorizon** [comment]
@netlore If this is indeed a "mandatory security fix", then that implies the Ubuntu default repositories contain an insecure version of Syncthing. Thats a pretty serious problem since a person may only ever run the versions from the main repo, everything would work and they would have no idea they were insecure?

Surely it should be either removed from the repositories or updated?

**Comment by netlore** [comment]
@r13l "I think disabling TLS 1.2 in 2021 should be optional", If I am reading the above correctly... it is optional, we are just debating what the default should be for /new/ installations.  I do have some questions that seem pertinent.

1) Does updating an existing installation on Debian, perhaps from 1.0.0 to 1.12.1 also change the default, or does it continue to allow TLS 1.2 after an upgrade.  I think @NeonHorizon 's concern is largely alleviated if this is just relevant to new installations.

2) What is the minimum version that must be in place to be compatible, clearly 1.0.0 is not compatible with the change in 1.17.0, but what about the 1.12.1 which @aviau mentioned is the current version in Debian (and Ubuntu).

**Comment by NeonHorizon** [comment]
1. It (pretty much silently) broke existing working installations in production. Essentially causing out of sync files which result in a lot of work to correct.

2. The current version in Ubuntu is not 1.12.1 unless you run non LTS releases (which as previously stated is a monitory of Ubuntu users).

**Comment by netlore** [comment]
I think my suggestion would have be for those people had working installations who just upgraded,  perhaps leave the setting ticked to enable TLS1.2 (perhaps warn during the upgrade), and only set it to disabled if it was a fresh install.... at least for a while... and @NeonHorizon does make a good point (out of band), that part of the reason this caused him such a big issue, is that most clients simply stopped syncing, but did not warn the user that they were not syncing.

**Comment by imsodin** [comment]
I am locking this issue - quoting myself from a few comments above:

> If you feel the need to discuss further (I don't), there's already a topic open about the topic on the forum: https://forum.syncthing.net/t/server-selected-unsupported-protocol-version-303/16902
