### ISSUE TITLE
Watching for changes using too many system resources on BSDs (kqueue)

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7855]
Kqueue is a very heavyweight mechanism to watch for changes. Issues about systems being brought to their knees by Syncthing's watching for changes with large folders come in every now and then, see e.g. https://forum.syncthing.net/t/truenas-freenas-folder-watcher-unusably-slow-crashes-host/17161

We should somehow prevent this. Either disabling kqueue alltogether or adding a limit for items in a folder (disable kqueue once reached). The latter will be somewhat annoying, as I guess users will want to adjust/override that, and we'd need to enable watching only after the initial scan (so we know how many items there are). However just disabling it will probably make a lot of people mad.

**Comment by alexmarkley** [comment]
Thanks for adding this issue @imsodin. As you noted via the above forum post link, this issue bit me hard this week, so I would have benefited from some kind of mitigation.

Changing the defaults when the host is BSD would have been helpful, but honestly would not have helped me **that** much, because I probably would have simply turned it on when I set everything up.

Honestly, as a sysadmin, I would cast my vote for a UI warning along with some clear documentation around the risks and tradeoffs of enabling the feature. I think that would have saved me a couple days of hair-pulling.

Thanks again for working on Syncthing. It's pretty incredible!

**Comment by koskee** [comment]
I agree, it took me several weeks of screwing around to finally figure out why anytime Syncthing was enabled my system would CRAWL and be literally unusable (which was tough to troubleshoot because the shell and webgui would actually time out before getting a response.) I was trying to install custom Syncthing jails with resource limits and all kinds of circular goose chasing, only to find out it was just an otherwise innocent looking setting...

**Comment by calmh** [comment]
So perhaps a one time notification similar to the "you should set up authentication" one, like "my dude, you're on a system with kqueue, use filesystem notifications with care and be aware that enabling it for large folders will use lots of system resources", perhaps with a link to some suitable doc article / faq...

**Comment by koskee** [comment]
Exactly. Just something to make the average user aware of the performance impact. For me, the filesystem watcher works flawlessly on my Windows and my prior Linux setup, but the FreeBSD version (that i only started using/learning a month ago) basically left me completely unaware.

Otherwise, its a pretty nice bit of code you've got here.

**Comment by AudriusButkevicius** [comment]
"Average user" and "BSD" in the same sentence, wat?

**Comment by koskee** [comment]
Right. That is a fair point you have there.. Perhaps rookie, inexperienced or just plain dumbass (me) users might have been more precise - hard to say. Bahaha

**Comment by bitclick** [comment]
i think, regardless of the user-model, (this) software should give relevant information to the user in order to not waste their time. So a notification should be fine. This would be in the bsd-spirit  :smile:

**Comment by pushytoxin** [comment]
Is this a scalability issue? Could I fix the hang by adding another 128GB RAM to the box running Syncthing?

**Comment by AudriusButkevicius** [comment]
Its probably cheaper to move to linux, if you can.

**Comment by pushytoxin** [comment]
I already tried and it didn't help

**Comment by AudriusButkevicius** [comment]
Tried what and what didn't help?

**Comment by pushytoxin** [comment]
256GB RAM in the box, the issue described above still happens (~11M files)

**Comment by AudriusButkevicius** [comment]
Yes, on BSD watching large folders does not work, this is what issue talks about.

**Comment by DJstone** [comment]
I can not confirm this general statement.
I have one TrueNAS server which totally works fine detecting changes on a summarized size of ~ 33TB (774 k files).
The other TrueNAS server I have is struggling as soon as I switch the on the watcher. So there must be something that allows it or cripples it.

Both systems are Supermicro ones.
The first system is my beafy main one (16 Cores, 2 Sockets, 128 GB RAM).
The second system is my backup system (4 Cores, 1 Socket propagated, 32 GB RAM).
Both have a X9 board and are using LSI/Broadcom JBOD controllers.

**Comment by calmh** [comment]
You have relatively few files, and by default the system limit on fd:s is relative to the amount of RAM.

**Comment by DJstone** [comment]
So it isn't FreeBSD in general then, it is the amount of RAM - you say.
But what about 

> 256GB RAM in the box, the issue described above still happens (~11M files)

**Comment by calmh** [comment]
What about it?

**Comment by pushytoxin** [comment]
> Yes, on BSD watching large folders does not work, this is what issue talks about.

To which the question arose, what is the limiting factor. Not memory, apparently.

**Comment by AudriusButkevicius** [comment]
Seems like this question should be asked on the BSD forums?
I don't think any of the syncthing maintainers can answer questions about BSD scalability concerns.

**Comment by calmh** [comment]
Yeah. The limit is max possible fd:s. This apparently scales with ram somehow, in at least some configurations. But really, the details are up to you as system administrator of your system to figure out. I don't think questioning us why 775k files hit the limit on 32 gigs when it doesn't on 128 gigs and how that rhymes with 11m files on 256 gigs is the thing. These are freebsd limits so apply freebsd knowledge.

**Comment by lapo-luchini** [comment]
The issue to follow seems to be [FreeBSD PR 258010](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258010).

**Comment by InQuize** [comment]
Just got this warning for a bunch of Syncthing folders that had 0 files since update and restart (used for auto cloning between systems with manual deletion after move to final destination).

Seeing that `kqueueItemCountThreshold = 10000` and the condition for warning is
`summary.Data.(map[string]interface{})["localTotalItems"].(int) > kqueueItemCountThreshold`

I am now confused as to what `localTotalItems` is and where exactly I should avoid enabling FS watching.

Is it `Local State (Total)` number of files in this instance of Syncthing, 100k in my case, and it is a bad idea to enable FS watching an any of the folders not considering the actual amount of files in them?

**Comment by imsodin** [comment]
I am a bit confused as you are saying first 0 files then 100k? Anyway I can't tell you if it's a problem, but I assume if you don't observe anyproblems with your current set up, semms like it's fine. Generally lets please take further discussion on your specific use-case to https://forum.syncthing.net, we handle support-like discussions there.

Maybe emitting a warning for this is too much and "INFO" would have been the sweet spot. The reason I used a warning is that hardly anyone notices an info level line in the logs. However that might just be a good thing: Dosn't spook anyone, but if issues arise there's a hint in the logs if anyone starts digging.

**Comment by ajshea** [comment]
Something broke with this revision. 

I have two FreeBSD systems syncing the same sets of files. I had to increase kern.maxfiles sysctl when first setting them up, but they have worked well up until this revision. Global state is  90,262 files, 8,127 directories, ~343 GiB. 

1. I get the warning even for sets with only 10 files in one directory. 
2. Disabling file system watching does not reduce the system load. Even scanning a set with 10 files bumps CPU to 95% for 15-20 seconds. Previously syncthing CPU usage was less than a few percent almost all the time. 
3. One system has UFS, the other has ZFS. UFS has become almost unusable unless I pause all but the smallest sets. ZFS CPU usage has jumped to between 40-50% during rescans, but otherwise the system is still usable. 

Reverting to v1.19.2 on the UFS system seems to return the CPU usage to a sane level -- peaks to 95% for a few seconds when unpausing large sets, but dropping below 60-70% for 15-20 seconds while scanning all sets, then dropping to less than 1% overall. 

I will leave upgrades disabled and watch this version to confirm, but so far it seems to undo the CPU usage problem.

**Comment by imsodin** [comment]
1. That's indeed a bug: The limit also considers deleted items. Fix: https://github.com/syncthing/syncthing/pull/8365

The cpu usage problem is definitely not related, all the change did is print a warning - no behaviour change otherwise. Please post on the forum to get help with diagnosing your problem: https://forum.syncthing.net

**Comment by ajshea** [comment]
Thanks for the clarification. 

Something in 1.20 and following definitely changed the CPU usage. I'll post on the forum to see if we can narrow down what changed.

**Comment by InQuize** [comment]
> I am a bit confused as you are saying first 0 files then 100k?

Sorry, for late reply, missed notification. 100k is the total number of files in all of Syncthing's (TrueNAS jail) folders, which includes ZFS mounts from 5 different pools.

Not that I was seeking support, but rather was trying to clarify how `kqueue` works in order to understand this limitation, particularly what is the context for this 10k threshold. Is it single Syncthing folder that is being watched, or an underlying filesystem of that mount, or even the filesystem of the whole jail including all mounts.

For the sake of curious minds that would come across this thread as it is the only thing coming up during research of the warning. Anyway, hope we are talking about the same issue and last commit fixes things.

**Comment by InQuize** [comment]
It still warns about folders with 0 files after a restart on v1.20.2

![zero](https://user-images.githubusercontent.com/12504278/173222654-89c79408-a681-4ca5-9ebf-663fabb5c41c.jpg)
![kqueue](https://user-images.githubusercontent.com/12504278/173222655-2f402758-2ea3-44fb-a0db-47f7507ba9c0.jpg)

**Comment by imsodin** [comment]
That's weird, now I can't come up with an explanation anymore. Can you run Syncthing with `-verbose` or enable `events` debug logging and look for `FolderSummaries` and post a few of those here please (those are used to trigger this warning).

**Comment by InQuize** [comment]
> look for `FolderSummaries` and post a few of those here please (those are used to trigger this warning).

Here you go:
<details>
  <summary>Folder "p2p-plex-node1-SYNC"</summary>
  
  ```
 2022-06-20 23:11:45 Summary for folder "p2p-plex-node1-SYNC" is &{Errors:0 PullErrors:0 Invalid: GlobalFiles:0 GlobalDirectories:0 GlobalSymlinks:0 GlobalDeleted:5010 GlobalBytes:0 GlobalTotalItems:5010 LocalFiles:0 LocalDirectories:0 LocalSymlinks:0 LocalDeleted:8275 LocalBytes:0 LocalTotalItems:8275 NeedFiles:0 NeedDirectories:0 NeedSymlinks:0 NeedDeletes:0 NeedBytes:0 NeedTotalItems:0 ReceiveOnlyChangedFiles:0 ReceiveOnlyChangedDirectories:0 ReceiveOnlyChangedSymlinks:0 ReceiveOnlyChangedDeletes:0 ReceiveOnlyChangedBytes:0 ReceiveOnlyTotalItems:0 InSyncFiles:0 InSyncBytes:0 State:idle 23:11:39 +0300 MSK Error: Version:17901 Sequence:17901 WatchError:}
2022-06-20 23:11:45 Completion for folder "p2p-plex-node1-SYNC" on device ZRHYUWI- is 100% (state: valid)
  ```
</details>

<details>
  <summary>Folder "p2p-plex-node4-CLONE"</summary>
  
  ```
2022-06-20 23:11:45 Summary for folder "p2p-plex-node4-CLONE" is &{Errors:0 PullErrors:0 Invalid: GlobalFiles:0 GlobalDirectories:0 GlobalSymlinks:0 GlobalDeleted:98 GlobalBytes:0 GlobalTotalItems:98 LocalFiles:0 LocalDirectories:0 LocalSymlinks:0 LocalDeleted:97 LocalBytes:0 LocalTotalItems:97 NeedFiles:0 NeedDirectories:0 NeedSymlinks:0 NeedDeletes:0 NeedBytes:0 NeedTotalItems:0 ReceiveOnlyChangedFiles:0 ReceiveOnlyChangedDirectories:0 ReceiveOnlyChangedSymlinks:0 ReceiveOnlyChangedDeletes:0 ReceiveOnlyChangedBytes:0 ReceiveOnlyTotalItems:0 InSyncFiles:0 InSyncBytes:0 State:idle 23:11:39 +0300 MSK Error: Version:210 Sequence:210 WatchError:}
2022-06-20 23:11:45 Completion for folder "p2p-plex-node4-CLONE" on device ZRHYUWI- is 100% (state: valid)
  ```
</details>

**Comment by imsodin** [comment]
The condition is:

```
const kqueueItemCountThreshold = 10000
[...]
			} else if data.Summary.LocalTotalItems-data.Summary.LocalDeleted > kqueueItemCountThreshold {
```

So clearly not fulfilled for the summaries you showed above.

You did also get a new warning in the logs? Not just that you didn't press ok in the web UI (grasping at straws here).

**Comment by InQuize** [comment]
> You did also get a new warning in the logs? Not just that you didn't press ok in the web UI (grasping at straws here).

Yeah, I though that warning could be carried from previous version in case I did not press "OK", but I rechecked that multiple times since then, hit "OK", had restarts, but it persistently pops up again on every restart.
