### ISSUE TITLE
Adding Ignore Patterns to a new folder will pause the folder and ignore its Ignore Patterns

### ISSUE THREAD

**Issue by Stolka** [syncthing/syncthing#7858]
Adding a local folder or accepting a folder request with Ignore Patterns will add the folder but it will be paused and the ignore patterns didn't get saved, so I would need to Resume the folder manually and add the ignore patterns. I believe it wasn't like this and this behavior is not normal.

I've attached a video to reproduce.

https://user-images.githubusercontent.com/44819843/127618492-2ec5df40-d347-4e63-8f29-b7232625c340.mp4

**Comment by tomasz1986** [comment]
I can confirm the bug, and I would say that this is quite annoying :pensive:. For instance, I have just shared a folder with a new device, but I wanted to ignore everything with `*` first, and then sync only some exclusions. 

However, right now such a folder gets added in the following state:

![image](https://user-images.githubusercontent.com/5626656/129452243-2a4fa456-28ba-4118-af59-e66442c377aa.png)

and you cannot edit the ignore patterns at all:

![image](https://user-images.githubusercontent.com/5626656/129452282-979b29fc-9317-4529-aca5-82486cce662f.png)

The reason for all this seems to be that the folder has actually not been created on the disk at all! No surprise that Syncthing cannot read the ignore patterns, because there is no folder, and thus no `.stignore` file too. It is only after unpausing the folder that it is physically created on the disk, but with no ignore patterns, so the user has to add them one more time.

I will try to investigate which exact commit is the culprit (probably tomorrow).

**Comment by tomasz1986** [comment]
I cannot reproduce the problem in my test environment 😕. I will try to do it again on the real device later, but it may take some time, as I need to finish syncing other stuff first.

@Stolka 

If you always experience the problem as demonstrated in the video, would you mind enabling `db` and `model` debug logging and then uploading the logs here?

**Comment by Stolka** [comment]
@tomasz1986
I tried to reproduce it on a few cloud providers and found something interesting, I can't reproduce this issue on Digital Ocean and Vultr, but I could reproduce it on Scaleway and Hetzner, all of them were running latest version (1.18.1) and fresh OS install (Ubuntu 20.04).
So the issue may be specific to hardware configuration or virtualization?

I also enabled the db and model debug logging, but I get only `Paused folder "test" (q34qj-egeiw)`.
I attached the log with all loggings enabled.
[log.txt](https://github.com/syncthing/syncthing/files/6987776/log.txt)

I hope this helps.

**Comment by Stolka** [comment]
@tomasz1986
I just noticed all the servers I had issue with used NVMe drive(s).

**Comment by tomasz1986** [comment]
> So the issue may be specific to hardware/system configuration or virtualization?

I personally doubt hardware plays a role here, although I don't remember where exactly I experienced the problem myself. I'd guess there must be a specific chain of events or particular configuration options enabled to cause this effect.

> I just noticed all the servers I had issue with used NVMe drive(s).

No NVMes on my side, only standard SATA SSDs and HDDs.

**Comment by tomasz1986** [comment]
I have managed to reproduce. **The problem happens if the default folder path is either invalid or inaccessible**.

1. Set the default folder path to `/`.

   ![image](https://user-images.githubusercontent.com/5626656/136670870-52aa7063-1231-4043-84ad-c07ca26d2bcd.png)

2. Add a new folder with ignore patterns.
3. The folder is added paused, and the ignore patterns are lost.

**Comment by tomasz1986** [comment]
This issue has been fixed as a byproduct of https://github.com/syncthing/syncthing/commit/21d04b895a7b3ee0803e36e4f0b3f5e8e6cf1379. Ignore patterns are now added only after folder creation, so it doesn't matter whether the default folder path is invalid or not.
