### ISSUE TITLE
Unexpected cleanup behavior for Simple File Versioning

### ISSUE THREAD

**Issue by Mr-Eager** [syncthing/syncthing#7988]
### Issue
"Clean out after" setting removes files based on their last modified time (mtime)
### Expected Result
Files are removed based on when they were deleted (~datestamp tag value)

## Overview:

I had been following #6527 and #6884 and finally got around to trying it out in my deployment. Based on the cleanup documentation (https://docs.syncthing.net/users/versioning.html) I expected the behavior to follow "_If this is set to a positive number of days, files will be removed when they have been in the trash can that long_," however, on first run, clean up removed considerably more files than I expected (obviously, these files were already in the .stversions directory, so non-critical in this case). Based on quick look through the code, cleanByDay func called by both the Trash Can and Simple Versioning methods directly reference the file's ModTime (https://github.com/syncthing/syncthing/blob/main/lib/versioner/util.go#L318) and ignore the datestamp applied when the file was archived by the simple versioning process.

### Example/reproduce

- Clean out after is set to 30 days, runs once a day
- File (say, a picture) is modified on 2021-04-29
- File is deleted on 2021-10-02, and moved to .stversions
- File's mtime is unchanged (no content change)
- Clean runs later in the day, and immediately deletes the file because mtime is > 30 days in the past, even though the datestamp is less than 24 hours in the past

This could lead to a user deleting a file that was last modified greater than the "Clean out after" setting, and be unable to recover as the clean task removed it immediately on next run. Additionally, collecting logs for this behavior is difficult as the clean functions do not appear to have any debug logging - I can easily trace where a file is archived, but only see when the clean job is run, not specific files cleaned.

**Comment by tomasz1986** [comment]
You're 100% right. I've just tested this.

1. Trash Can changes the file's mtime and performs cleanup based on that.
2. Staggered adds date to the filename and uses that for cleanup.
3. Simple should be same as Staggered, but it's actually same as Trash Can right now.

In my testing, I set the cleanup interval to `10` with maximum age set to `30`. Next, I deleted a 6-month-old file, which was then send to `.stversions` on the other device. The file was wiped out from there almost immediately.

**Comment by fbayerx** [comment]
> This could lead to a user deleting a file that was last modified greater than the "Clean out after" setting, and be unable to recover as the clean task removed it immediately on next run.

That is exactly what happend to me... Fortunately I was able to recover the files from an external source.
I think this is a serious issue, because it is hard to detect while testing the versioning (it works with newer files) and could lead to preventable data loss.

Is there a recommended workaround until the problem is fixed?

**Comment by tomasz1986** [comment]
> Is there a recommended workaround until the problem is fixed?

There is no workaround unless you re-implement the same logic using a custom script with external versioning. Otherwise, I'd suggest to switch to staggered for now (yes, it's not the same and can potentially use much more disk space, but it's definitely better than the unexpected early deletions).

**Comment by tomasz1986** [comment]
Just for the record, the cleanup functionality hadn't originally been present in the Simple File Versioning at all. It was only added in https://github.com/syncthing/syncthing/pull/6884. However, it seems that the PR simply took out the Trashcan cleanup function, moved it to `lib/versioner/util.go`, and then re-used it as it was for Simple Versioning. This couldn't really work in practice, as the Trashcan cleanup is based on the fact that files have their mtime changed upon being moved to `.stversions`, and then they're cleaned up based on that changed mtime. In the case of Simple Versioning, there's no mtime change, so the Trashcan cleanup code is simply not suitable for it.

I assume that one way to fix the issue could be to move the Trashcan cleanup function from `lib/versioner/util.go` back to `lib/versioner/trashcan.go`, and then move the Staggered cleanup function from `lib/versioner/staggered.go` to `lib/versioner/util.go` instead, so that it could be reused for both Staggered and Simple Versioning. I think this should work fine, as both Simple and Staggered Versioning seem to use the same versioning filename scheme.
