### ISSUE TITLE
Symlink support on Windows

### ISSUE THREAD

**Issue by dancojocaru2000** [syncthing/syncthing#8002]
Now that newer versions of Windows 10 allow symlink creation without admin permissions if developer mode is turned on, could symlink support for Windows be added?

This is perhaps best done via an advanced setting, since turning developer mode on is a prerequisite, and without that Windows still asks for admin permissions to create a symlink.

Another alternative could possibly be attempting to create a symlink in a temporary folder, and if that works (no permission errors) then symlink support can be enabled automatically.

**Comment by AudriusButkevicius** [comment]
I don't think we want to open that can of worms again, there is simply too many "ifs" here.

In practice I suspect none of our users run with developer mode enabled, and to be honest, nobody on windows generally cares/uses symlinks.

It's also not as trivial as just commenting out `if os == windows: skip` branch in the existing symlink code

Windows symlinks are special, as they have a type, unlike other operating systems, which makes the whole thing super complicated, because a dangling symlink created on linux, needs to be created with some type on windows, which adds a ton of complexity if the symlink becomes non-dangling, because we might need to start changing symlink types on windows.

Effectively, a ton of edge cases with potential security implications, for some 3 users.

**Comment by dancojocaru2000** [comment]
From what I can see, symlinks on Windows just store if they're directories or files. Is this that much complexity and that huge of a can of worms?

Since dangling symlinks seem to be the only problem (can't guess what it's pointing to if it's pointing to nothing), just don't create those. Create only symlinks that point to a file / directory that already exists.

**Comment by AudriusButkevicius** [comment]
It's not just dangling symlinks.

I know it might seem like a simple problem on the surface, but its not. 

We had symlink support in windows, but we've removed it because of how many edge cases there was.

Its perfectly valid for the target of the symlink to change on linux, yet it has no effect on the symlink itself, so we have no way to detect that the target changed, which is not propagated to windows, which ends up pointing to things with the wrong type of symlink.

**Comment by dancojocaru2000** [comment]
I played a bit with the `CreateSymbolicLinkW` function last night and Windows doesn't go crashing down if the types mismatch. The symlink doesn't work (can't open a "file" if the link points to a directory), but it's not like a bluescreen happens.

Given that, I'd personally be quite fine with just having the links there, because then I can cobble together a Python script that traverses all files and recreates all symlinks with the proper type. At least then I'd have something usable, unlike now where I need to SSH into my server whenever I want to do something related to symlinks, and where I can't use Windows at all for working on synced stuff that needs the symlinks.

Since absolute symlinks or symlinks that point to stuff outside the synced folder would almost certainly be invalid when synced to another computer (no matter the OS) anyway, one could exercise proper symlink hygiene in this case and not do  
```
rm file
mkdir file
```

I would be more than pleased if this would be something hidden inside the advanced options and turned off by default. But something would be better than nothing.

**Comment by AudriusButkevicius** [comment]
I understand that something is better than nothing. 

Yet I am still not convinced we want to go back to the 100s lines of code handling this, for very few users.

**Comment by gohma231** [comment]
Here's a semi-related questions: Would symlinks work out of the box if you installed syncthing on the WSL or WSL2? Sure, you might have reduced sync performance, but I'm wondering what other limitations may exist, if any.

**Comment by ssgromov** [comment]
> Here's a semi-related questions: Would symlinks work out of the box if you installed syncthing on the WSL or WSL2? Sure, you might have reduced sync performance, but I'm wondering what other limitations may exist, if any.

Yes, however only properly working from within WSL as well (tested about a year ago). 

These symlinks are seen on Windows as symlinks, however with screwed/not accessible pointers IF destination file/dir did not exist during the symlink creation. That means that dead symlinks can't be used, "live" symlinks should be OK.  

I guess some hope can be cherished using a scheme with only valid directory/file symbolic junctions used on the Windows side...
