### ISSUE TITLE
panic: too many open files (REST API?)

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#805]
1) I'm unsure but I think my external tool (https://github.com/Zillode/syncthing-inotify/) caused this by not properly performing the HTTP requests. I think I fixed it via (https://github.com/Zillode/syncthing-inotify/commit/9dd2a2fd4ba1a9e9b7551ef3ea253885903bba1f and my -incoming- pull request) but it isn't running long enough to retrigger the bug.

2) If this is not due to the REST API, it might be related to https://github.com/syncthing/syncthing/issues/587

The log is big so I've put it online at http://wilma.vub.ac.be/~lhoste/private/panic-20141008-121902.log (will be deleted when issue is closed)

```
[45W46] 12:04:17 WARNING: multicast interfaces: netlink rib: too many open files
[45W46] 12:04:17 WARNING: Broadcast: interface addresses: netlink rib: too many open files
[45W46] 12:18:49 WARNING: Broadcast: interface addresses: netlink rib: too many open files
panic: open /home/____/.config/syncthing/index/030242.log: too many open files
...

goroutine 2592 [IO wait, 57 minutes]:
net.runtime_pollWait(0x7f3e31f8dd20, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20b06fb80, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20b06fb80, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20b06fb20, 0xc209cf4000, 0x1000, 0x1000, 0x0, 0x7f3e4e3233c8, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc2090834a0, 0xc209cf4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/net.go:122 +0xe7
bufio.(*Reader).Read(0xc20afedaa0, 0xc209cf4000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /usr/local/go/src/pkg/bufio/bufio.go:165 +0x13b
main.(*WrappedConnection).Read(0xc2084053e0, 0xc209cf4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /data/Sync-Projects/golang-workspace/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:146 +0x77
net/http.(*liveSwitchReader).Read(0xc209858f28, 0xc209cf4000, 0x1000, 0x1000, 0xf4a, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:206 +0xaf
io.(*LimitedReader).Read(0xc208405400, 0xc209cf4000, 0x1000, 0x1000, 0x1d, 0x0, 0x0)
    /usr/local/go/src/pkg/io/io.go:399 +0xd0
bufio.(*Reader).fill(0xc20afedb00)
    /usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc20afedb00, 0x44650a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/bufio/bufio.go:298 +0x22c
bufio.(*Reader).ReadLine(0xc20afedb00, 0x0, 0x0, 0x0, 0x445100, 0x0, 0x0)
    /usr/local/go/src/pkg/bufio/bufio.go:326 +0x69
net/textproto.(*Reader).readLineSlice(0xc208992990, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/textproto/reader.go:55 +0x9d
net/textproto.(*Reader).ReadLine(0xc208992990, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/textproto/reader.go:36 +0x4e
net/http.ReadRequest(0xc20afedb00, 0xc20950eea0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/request.go:556 +0xc7
net/http.(*conn).readRequest(0xc209858f00, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:577 +0x276
net/http.(*conn).serve(0xc209858f00)
    /usr/local/go/src/pkg/net/http/server.go:1132 +0x61e
created by net/http.(*Server).Serve
    /usr/local/go/src/pkg/net/http/server.go:1721 +0x313
...
```

**Comment by ozra** [comment]
I got this error just esterday after having installed 11.1 on both my machines. I was syncing upp my photo directory. I copied it with rsync -a to both nodes, in order to avoid syncing all via syncthing. Anyways, this error popped up all the time, restart, po up again, restart.. ad infinitum. After closing inotify (0.6.1) (only on node B) it finally progressed. When things had settled down, I restarted inotify and all worked as usual.
It's hard for me to tell which repo to report this issue on. Tell me if I should report it in syncthing-inotify instead.
I will run them in separate terminals from now so I see which app spits out which message...

**Comment by calmh** [comment]
@ozra logs?

**Comment by ozra** [comment]
Sorry, ditched them because I had several processes running in the same terminal.
I'm running syncthing, inotify and others in their own now. I'll try to reproduce the problem.

**Comment by TraceyC77** [comment]
I'm seeing this error repeatedly in logs. 
Syncthing on the server is v 11.11 but this has been happening for a few versions
This is the command I use to run syncthing:
screen -dmS sync sh -c ' /home/syncthing/syncthing/syncthing 2> ./logs/sync-stderr.log 1> ./logs/sync-stdout.log'

It's also interesting that errors are being written as "info" to stdout rather than stderr.

Typical error output:
[YENHX] 13:34:18 INFO: Puller: final: open /backup/syncthing/win_games/SteamLibrary/SteamApps/common/Borderlands 2/WillowGame/Localization/ESN/.syncthing.GD_Population_Loader.ESN.tmp: too many open files

Some relevant log output is here. It only took a few minutes for this log to reach 8M.
http://pastebin.com/dupBZazu
