### ISSUE TITLE
Switch Folder Type / Sync direction by glob or at least subfolder

### ISSUE THREAD

**Issue by adnoh** [syncthing/syncthing#8061]
Given the following daily situation I'm confronted with and example folder structure:
```
/
   Art
   Content/
                 Foo
                 Baz
   Source
   Plugins/
                 Bar
```

I have several people - lets call them designers and developers - working on that project on the same time. The folder structure is more or less dictated by the software they're using.
It would help me to have a possibility to define for the subfolders which Folder Type they are.
For example make the Root per default `Receive Only`, and for an artist Subfolder Art `Send & Receive`, and for an developer Source and Content/Foo `Send & Receive`

Possible implementation could be a file like the ignorefile but for specifying this modes with the same globs you're already using extended by the mode and NodeID. This FR is not about security - only about preventing human misstakes.

```
// GLOB          MODE NODEIDSGLOB
/Art      Send AAAAA-AAAA-AAAAA-AAAAA
/Content/Foo      Send YYYY-YYYY-YYYY-YYYY
/Content/Baz      Sync    *
Source      Send YYYY-YYYY-YYYY-YYYY
*.c*      Send {YYYY-YYYY-YYYY, XXXXX-XXXX-XXXX-XXXX}
**      Receive *
```

Given AA is an "Artist" Node, and the others are developer machines. Could also be very useful to group them in the file like
```@art AAAAA-AAAA-AAAAA-AAAAA
@devs YYYY-YYYY-YYYY-YYYY, XXXXX-XXXX-XXXX-XXXX
*.c* Send @devs
```

I thought about creating several shared folders and include them as subfolders to create some ignorelist to make this work but this doesn't look like the right way to do it for me.
More or less - even if not the same - I need something like `git submodule` where I can control or prevent accidental changes from the wrong persons in specific folders where they are not the authority for.

Thankful for any discussion or ideas for workarounds.

**Comment by AudriusButkevicius** [comment]
So by definition, this cannot be about security, as folder type has only meaning locally. It's not a cluster level thing.

The fact that the folder is set to send only on your device doesn't mean that other devices that are connected directly will not exchange data, its just that your device will refuse to download it, but designers will still be able to change .c files and the changes will be replicated to developers if they are connected directly and if local designer folder type is not receive only.

In general, what you are asking for, is generally unfeasible in syncthing, because the folder type affects many different things, the code for each type is separate, database logic is separate, hence this could not be done by folder/path etc. 

You could work around this by having multiple folders all with different types etc (but as I suggested, the types are only meaningful locally), or using filesystem permissions.

To be honest, the use case you are trying to use syncthing for doesn't seem like the one it was made for. It seems to make that you would be better off with a simple network storage (NFS etc) server with good old filesystem permissions to restrict access.

Sorry, but I don't see this happening in syncthing.
If you want to have a further discussion, I suggest you start a topic on the forums.

**Comment by adnoh** [comment]
Thank you @AudriusButkevicius for your feedback. That sounds fine for me. In my usecase I don't have a NAS or VPN most of the team is super "agile" and changes in its conditions and all with different Operating Systems. So I can't use NFS or NAS or s.th. else easily also the projects (mostly 3D and games) get quite huge in filesizes so a decentralized solution is ideal for us without the need of a central server to rent. Also GIT etc is not a solution because of a lot of the information is binary so you get nothing out of SCM. I'll try to live with it as it is or look for a different solution.
But it's a neat idea to run the software with a different user and "protect" my local folders by filesystem acls.
Thanks for your time and keep up the good work.
