### ISSUE TITLE
Allow specifying ports in --generate

### ISSUE THREAD

**Issue by Bill-Stewart** [syncthing/syncthing#8090]
On Windows, I am updating my installer to generate the `config.xml` at first installation so I can set the config options appropriate before the user starts Syncthing for the first time.

When I run `syncthing generate`, the Windows firewall prompts me to create a firewall rule. Is this because `syncthing.exe` opens a network connection?

Does `syncthing generate` need to access the network, and if so, can we change this behavior so that `syncthing generate` doesn't perform any network access?

**Comment by calmh** [comment]
What's the suggested rule? As far as I know there should be no network activity required or intended for `-generate`.

**Comment by Bill-Stewart** [comment]
I believe what happens is that when you run `syncthing.exe`, it listens on one or more TCP ports. Windows detects that `syncthing.exe` is listening and prompts the user if they want to create firewall rules for it. If I remove all firewall rules that refer to `syncthing.exe` and run `syncthing generate`, Windows prompts me to create the firewall rules.

So what this seems to mean is that when we run `syncthing generate` on Windows, `syncthing.exe` listens on one or more TCP ports (if even for a short time), because the OS asks to create the rules. (Normally this behavior is helpful, but not when you are trying to automate an installation and configuration process that shouldn't block for various reasons.)

**Comment by AudriusButkevicius** [comment]
I don't think we can avoid that. We need to pick a free port.

**Comment by Bill-Stewart** [comment]
Even when just generating a config and then exiting?

**Comment by calmh** [comment]
Ah, right, yes. Because on first start / when generating the config we pick a GUI port - 8384 if it's free, but otherwise some other one, in case there are multiple instances of Syncthing or something else in the way.

**Comment by Bill-Stewart** [comment]
Ah. In that case, nothing to fix here. My workaround to avoid this is to check for a firewall rule first.

**Comment by Bill-Stewart** [comment]
What happens, then, in the following scenario?

1. User A logs on and starts Syncthing, TCP 8384 is available, so Syncthing uses it.
2. User B logs on and starts Syncthing. Nobody is using TCP 8384, so user B's Syncthing also uses that port.
3. User A logs back on while user B is still logged on.

What happens then?

**Comment by rasa** [comment]
Can the GUI port be bound to 127.0.0.1? That would not cause a firewall prompt, yes?

**Comment by AudriusButkevicius** [comment]
I think it does that by default? So I don't think so?

Regardless, agreed the generate logic is not bullet proof if you run multiple instances, but I don't think we are going to fix anything here.

**Comment by Bill-Stewart** [comment]
Understood. I guess I was trying to make the point that the `generate` implementation doesn't _have to_ make a TCP binding and in fact there are cases where this won't work anyway, so maybe there's an improved approach that could be considered.

**Comment by AudriusButkevicius** [comment]
And what's the improved approach?

**Comment by Bill-Stewart** [comment]
One alternative would be to allow the user to specify the desired port(s) with the `generate` command. If user specifies port(s), then there's no need to perform a binding. (This approach would be more convenient from an automation perspective, where configs could be generated by script for multiple user scenarios.)

**Comment by AudriusButkevicius** [comment]
Sure, I guess we allow specifying the username/password, so I don't see why we wouldn't allow port.

**Comment by acolomb** [comment]
I started looking into this and think it needs some more clarification.  In principle, what you want to achieve can be done with just a snippet `config.xml` file that you pre-populate only with those options that your installer wants to set.  The purpose for the `--gui-user` and `--gui-password` options is mainly to avoid the need to hash the password externally.  Giving either of those results in a fully normalized `config.xml` being generated, possibly based on any pre-existing file.

Right now, when a `config.xml` file already exists during `syncthing generate`, we just leave it alone as long as none of the above options were supplied.  That could be changed to always read, normalize and write the config file, which would otherwise happen anyway during the first run of `syncthing serve`.  That avoids the need for additional CLI options to set any possible config element.  And your installer can make sure the config snippet is valid before actually running `syncthing serve`.

What may help with the original issue here would be a new `--skip-port-probing` option, which applies for both `generate` and `serve` subcommands.  Note that the probing is done for the GUI and the listen address, but only when no `config.xml` file previously exists.

**Comment by Bill-Stewart** [comment]
> What may help with the original issue here would be a new `--skip-port-probing` option, which applies for both `generate` and `serve` (first run) subcommands. Note that the probing is done for the GUI and the listen address, but only when no `config.xml` file previously exists.

Yes, I believe this would work perfectly for this use case. Thanks!

**Comment by acolomb** [comment]
Any opinions on whether `syncthing generate` should not touch a pre-existing `config.xml` in any case?  IMHO it would be fine to make it always result in a fully normalized config file.

**Comment by Bill-Stewart** [comment]
It seems to me that a case could be made either way. If `generate` always writes out a fully normalized `config.xml` file, it would be good to preserve existing settings (when possible).

**Comment by acolomb** [comment]
Of course, that's the idea. Parse anything that's already there and fill in the rest from the hard coded defaults.

**Comment by calmh** [comment]
This seems fine to me.

**Comment by acolomb** [comment]
I wouldn't jump to the whole complexity of migrations.  Only try to parse the config as is, then serialize and write it back to XML.  Just as the generate subcommand does now.

**Comment by calmh** [comment]
The config loader does some migrations when it loads a config of an old format. Probably nothing destructive, though.

**Comment by acolomb** [comment]
Sorry you're right.  I thought that was happening in `syncthing/utils.go` but it's actually called when creating the config Wrapper.

**Comment by acolomb** [comment]
I separated the two proposed changes into #8098 and #8099, which I think should be merged separately in order.  Docs at https://github.com/syncthing/docs/pull/706.

**Comment by Bill-Stewart** [comment]
Thanks for adding `--skip-port-probing` option!

**Comment by bugith** [comment]
Windows firewall, when prompting user to create a new rule, doesn't care about ports, only profiles (Private, Public, Domain), and only for the executable file path : if you move the file and run the program again you'll be promped again and the Windows firewall will create a new rule... and keep the previous one as is. ST should (?) be allowed to run from any of these 3 profiles as long as traffic is cyphered. In some countries, using ST in Public profile (if not any) maybe be harmful to the user because of government censorship, so the last word on the decision to allow or not a profile should remain in user decision.

**Comment by acolomb** [comment]
The point of this change was to make the check appear when first running the application to actually sync, opposed to during setup. It's now possible to pre-configure fixed ports and generate the keys without even touching the network at that time.
