### ISSUE TITLE
"too many paths watched"

### ISSUE THREAD

**Issue by IRigoutsos** [syncthing/syncthing#8100]
Greetings.  I posted this on the mobiussync forum and cross-posting here because this maybe related to the underlying syncthing (and not Mobiussync-specific).

I have just installed syncthing on my MAC and Mobiussync on my ipad. I have 14 entry points (top directories) that I sync independently between the two devices. The directories have different fan-outs and depths. In all, the setup is meant to sync about 150 Gbytes of data spread over 45,000 folders and 300,000 files. Even when no files change, and depending on the time of the day, I get a list of error messages (the same error message) for multiple entry points. The error messages are all of this type:

top_entry_point_being synced -> error while traversing /private/var/mobile/Containers/rest_of_path_to_some_deeper_folder: too many paths watched fed=4001

Occasionally, instead of 4001, I see 4002, 4003, or 4004 but I have not noticed a pattern.

Note: at times, I get the above message even for a top_entry_point that is only one level deep and has only two dozen files in it.

Thank you and Happy New Year!

**Comment by imsodin** [comment]
Please don't post MobiusSync issues here, unless their support clearly determined it is a Syncthing issue. This is a community project while Mobius is a commercial venue, so they should take their own support burden.  
And if it turns out this is a Syncthing issue, please post on https://forum.syncthing.net, as this looks more like a support request than an actionable bug report.

Thanks!
