### ISSUE TITLE
Further adaption to XDG Base Dir Spec

### ISSUE THREAD

**Issue by DC7IA** [syncthing/syncthing#8102]
### Does your log mention database corruption?

n/a

### Include required information

Please be sure to include at least:

 - 1.18.5, Debian, Syncthing Repo
 - browser and version, if applicable

The Syncthing config dir contains a log file which is definitely not config. The standard document ( https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ) makes it quite clear that `$XDG_STATE_HOME` has to be used for log files.

>The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable >enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
> -  actions history (logs, history, recently used files, …)
>
> -  current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

The config directory also contains certificate files that have to be placed somewhere else since they are not config:

> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is > either not set or empty, a default equal to $HOME/.local/share should be used. 

The config should be non-specific to the host (like not contain keys) so that it can be synced using Syncthing.

Everything that is not config is not in the correct location if placed in `$XDG_CONFIG_DIR`.

**Comment by imsodin** [comment]
Syncthing doesn't claim to be XDG compliant. Since https://github.com/syncthing/syncthing/issues/4924 it can (and does by default on new installs with `XDG_DATA_HOME` env var set) store the db and logs separate from the config. The config itself will always be specific to a host (remotes, name of local device, ...), so I don't see any point in separating cert files from config. The state vs data difference could probably be implemented sensibly (keep current defaults unless explicitly changed). As in I don't personally care for it, but I wouldn't mind a quality PR. Other maintainers may disagree though, I can see arguments against the complexity of splitting up our state even more.

**Comment by calmh** [comment]
> The Syncthing config dir contains a log file which is definitely not config.

I don't think so?

> The config directory also contains certificate files that have to be placed somewhere else since they are not config:

I think they're fine where they are.

> The config should be non-specific to the host 

That's, like, your opinion, man. ;)

So, no, unless there are specific reasons to change things that I don't see.

**Comment by acolomb** [comment]
I think the culprit here is that Syncthing's config is definitely machine-specific, while the XDG spec considers everything under `.config/` sharable between machines.  So effectively, *none* of the files currently managed by Syncthing in its "configuration" directory really belong under `.config/` according to XDG, but rather `.local/` (or `%LOCALAPPDATA%` on Windows, which is used correctly).

Arguably the DB and CSRF tokens could be considered for `$XDG_STATE_HOME`, while certs and config belong in `$XDG_DATA_HOME`.  But the spec is rather unclear on the distinction between state and other data, so I'd err to consider everything as data.

I don't see a pressing need to change anything though.  But would be open to discussion if a PR was to emerge.

**Comment by DC7IA** [comment]
> > The config directory also contains certificate files that have to be placed somewhere else since they are not config:
> 
> I think they're fine where they are.

Certificate files are not config.

> That's, like, your opinion, man. ;)
> 
> So, no, unless there are specific reasons to change things that I don't see.

The possibility to sync `$XDG_CONFIG_DIR` across hosts, which currently Syncthing blocks.

> I think the culprit here is that Syncthing's config is definitely machine-specific, while the XDG spec considers everything under `.config/` sharable between machines. So effectively, _none_ of the files currently managed by Syncthing in its "configuration" directory really belong under `.config/` according to XDG, but rather `.local/` (or `%LOCALAPPDATA%` on Windows, which is used correctly).

Exactly. It'd be great if we could use Syncthing to sync the config of our desktops. For now I'm working around that by symlinking the config directory of every program to a Syncthing folder, if Syncthing had none of these files in there, I could just sync the whole folder, like it was intended.

In my opinion even just a `~/.syncthing` folder would be better since it still allows to use `XDG_CONFIG_DIR` the way it was intended. But I'd prefer to follow the standard and use the folders the way @acolomb said.

> Arguably the DB and CSRF tokens could be considered for `$XDG_STATE_HOME`, while certs and config belong in `$XDG_DATA_HOME`. But the spec is rather unclear on the distinction between state and other data, so I'd err to consider everything as data.

Yup, host-specific config is definitely not state information, but it is definitely data.

> I don't see a pressing need to change anything though. But would be open to discussion if a PR was to emerge.

Too bad I don't know anything about go, otherwise I'd do it. :/

Not a pressing need, but it'd allow us to finally sync the config the way it was intended. It's so great having all programmes behave exactly the same on every machine!

(And I, for example, use two laptops, so it'd be annoying to set every single setting on every machine... I could use Ansible, but it's much nicer to have settings synced. :D)

**Comment by acolomb** [comment]
For your use case: We've determined that nothing inside `.config/syncthing/` is actually host-independent.  So just exclude that directory from a sync by using ignore patterns.

**Comment by imsodin** [comment]
Syncthing as it is currently can fulfill all the use-cases brought up so far - this is a support request at this point. Please move any further discussions to https://forum.syncthing.net
