### ISSUE TITLE
"Out of disk space" error with plenty of free disk space

### ISSUE THREAD

**Issue by martinlindhe** [syncthing/syncthing#8186]
### Include required information

Syncthing v1.19.0, Windows (64-bit Intel/AMD)

I put my sync folders on D: but now my C: drive is now low on disk space.

I get these errors and Syncthing refuses to sync. My D: drive has over 90 gb free space.

```
 2022-02-16 03:15:16: Error on folder "Sync" (default): insufficient space on disk for database (C:\Users\martin\AppData\Local\Syncthing\index-v0.14.0.db): 0.9 % < 1 % 
```

**Comment by tomasz1986** [comment]
> You can change the location of the DB if you'd rather want it on D:

Just to be clear, because this process isn't described in the docs, using the `--config` flag will not move the existing DB. If you want to keep using it rather than having Syncthing create a new one (and potentially lead to conflicts, etc.), you need to shut Syncthing down first, then move the whole `C:\Users\martin\AppData\Local\Syncthing\index-v0.14.0.db` folder to a new location on `D:`, and only then start Syncthing again pointing at the new location.

Also, on a side note, Windows is bound to have serious problems or even crash completely if your disk space on the system drive is so low, so I'd suggest to worry about that first.

If you've got more questions or need more help, please create a new topic on the https://forum.syncthing.net instead.

**Comment by martinlindhe** [comment]
@bt90 @tomasz1986 
Thanks both for your help!
