### ISSUE TITLE
Does not work with other drives (i.e. Drive D:) other then drive C:

### ISSUE THREAD

**Issue by Cryptogram-zz** [syncthing/syncthing#8225]
On Windows acting as a server, with different partition then drive C: (i.e. Drive D:), it does not work even if the windows account has access and is administrator, any drive other then C: is erroring out. Maybe syncthing needs to run under the network account or system account?

error:
[VUVGO] 01:13:56 INFO: Puller (folder "Repository_Backup" (6zcuq-mvuqx), item "inst - Copy.txt"): syncing: opening temp file: open \\?\D:\Repository_Backup\~syncthing~inst - Copy.txt.tmp: The system cannot find the file specified.

this is running with administrator on Windows Server 2022 . the folder has the right permissions.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by Cryptogram-zz** [comment]
This is not a feature I.e. it's the same as if Linux I would use
/mnt/location1 vs /mnt/location2

Same for windows if I want the sync folder in c:\location1
Or
D:\location2

It's a bug, I researched it already.


Gali

**Comment by tomasz1986** [comment]
Syncthing does normally work with different partitions in Windows. If it doesn't for you, then it's likely something related to the specific configuration on your system. That's why you've been redirected to the forums where we can try to investigate further to find the culprit.

If you don't believe it, please try to reproduce the error on a clean system (e.g. a fresh Windows installation on a virtual machine) and then come back with clear steps that anyone can follow to reproduce it.

**Comment by Cryptogram-zz** [comment]
Sound good will do.

Gali
