### ISSUE TITLE
Show connection type in Remote Devices

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#8244]
### Problem

I've noticed that more often than I'd expect, I have devices connected over a (slow) relay when they can have a (fast) local connection. It's easy to miss, but when big syncs take a long time, you'll start looking. I've seen this multiple times, for a variety of reasons. One time I entered the wrong tcp://ip-address so dynamic was used. Another time I used a laptop at the office first and the 24/7 online home server never used the local ip when I was on the home wifi, until I restarted syncthing on the home server. And just now I noticed that a remote connection with a very fast optical fiber was using a slow relay for the past year.

### Feature

It would help to see a label, icon or indicator of sorts to show if a relay was used, or a direct remote connection, or a LAN connection, and some polite way of indicating that a direct connection is better than a relay.  This way you'd immediately see if it is what you expected or not. This illustrates what I mean:

> ### Remote Devices
>
> [[device1]       [LAN 🤩] [Up to Date]]
> [[device2]       [LAN 🤩] [Up to Date]]
> [[device3]       [direct 😄] [Up to Date]]
> [[device4]       [relay 🙂] [Up to Date]]

Encouraging users to check their connections this way also alleviates relays that provide an invaluable service from peers that unknowingly unnecessarily burden those relays when all they need to do is a restart, config change or port forward. This way they get a faster sync, and the relays are free to service users that really need it.

**Comment by AudriusButkevicius** [comment]
You can already see the address it used to infer the type of connection, so its already done as far as I am concerned. You also don't need to restart things if better connections are available, syncthing will switch itself.

I don't think we want to be a kindergarten to start using crayons and emojis to expose this information that is already exposed.

**Comment by tomasz1986** [comment]
The emojis are probably a no-go, but I'd personally very much like to have a clear and visible indicator about what kind of connection is being currently used. Just the address isn't really enough, as non-technical users have absolutely no idea whether addresses like `192.168.x.x` or `10.0.0.x` are local or remote. At the moment, there is a pop-up shown on hover which does contain information like `tcp-server`, `relay-server`, etc. but these are still way too technical for "average" users to understand.

**Comment by bt90** [comment]
Wholeheartedly agree with @tomasz1986 

A clear indicator for non-technical users would be very appreciated.

**Comment by imsodin** [comment]
I think understanding URLs is enough steps above kindergarden that it warrants a ui enhancement requst for a small, non-emoji status indication about what kind of connection is active besides the URL (which as explained does indicate that information already, so it's just a user aid).

**Comment by AudriusButkevicius** [comment]
I don't think non technical users will understand the difference between whatever indication we put, as they don't understand how the internet works.

**Comment by bt90** [comment]
Even more technically inclined users might not understand the implications of e.g QUIC vs TCP or direct vs relay

A simple good/better/best indicator would be enough IMHO.

Most people have no idea about NAT but most games will give you a NAT rating and people know if things are good or if they need reach out for help if not.

**Comment by tomasz1986** [comment]
> Lan/wan or the benefits of one or the other has no meaning to them.

Yeah, but from my experience, even non-technical are aware of the implications when they are told that the current connection is a "direct connection through the local network, i.e. potentially the fastest possible" and an "indirect connection through a remote relay server, i.e. potentially slow", etc. Basically, as long as overly technical language is avoided and no fancy abbreviations are used, people do understand 🙂.

**Comment by calmh** [comment]
We could use something commonly understood like a signal strength indicator. One bar is a relay connection, two bars is a quic connection, three bars a tcp connection to a random address, four bars a tcp connection to a LAN-like address, five bars a tcp connection to a directly connected network, or something like that.

**Comment by bt90** [comment]
https://icons.getbootstrap.com/icons/reception-1/  up to https://icons.getbootstrap.com/icons/reception-4/ maybe?

**Comment by Redsandro** [comment]
I didn't mean to suggest literally adding emoji's, it was just the quickest way of illustrating what I meant with a _"polite way of indicating"._ :sweat_smile: 

What I'm looking for is an indicator directly in the overview, _preferably without having to drill down_ (i.e. click things) and analyse/compare an address to calculate if it's yours or not. So that in a single glance, you can see all your devices and judge if they are the type of connection you'd expect. Every suggestion here sounds like an improvement to me. I prefer something that indicates the distinction between relay, WAN and LAN.

You can do bars, stars or bootstrap reception icons mentioned above:
![image](https://user-images.githubusercontent.com/1702193/161102273-41a30950-2590-4336-a29c-32ac9bc6a236.png)

Or labels using the keywords mentioned by some of you above, e.g.:
![image](https://user-images.githubusercontent.com/1702193/161099907-217957df-b788-47c8-ac74-e6c680cf34b4.png)

Or show nothing on LAN connection, but a NAT success (direct) or fail (relay) label upon WAN connection:
![image](https://user-images.githubusercontent.com/1702193/161100599-5c5b0bfa-6903-40da-a771-fdc8c68e3ea8.png)

Or a mix:
![image](https://user-images.githubusercontent.com/1702193/161105132-3c59c13d-8c53-4c6d-9ca8-a1f80296a1a1.png)


Just visualizing some of the ideas for brainstorm purposes.

**Comment by bt90** [comment]
IMHO reception bars paired with color coding (orange to green) would take the least space while offering a quick overview.

**Comment by tomasz1986** [comment]
> IMHO reception bars paired with color coding (orange to green) would take the least space while offering a quick overview.

I'd also vote for the bars, perhaps with a tooltip on hover with a detailed explanation. The keyword labels like LAN, WAN, etc. are still alien to non-tech people. Is colouring necessary though? Most systems (e.g. Windows, Android, etc.) seem to just stay with the monochrome regarding reception bars.

**Comment by Redsandro** [comment]
Bars without colors sounds good too. So for people who don't care, it's easy on the eyes. For people who do care, they can look up what the bars mean. Perhaps the alien words like LAN, WAN and relay can be used in the tooltip.

The icon set referenced by @bt90 has 5 variants.

![image](https://user-images.githubusercontent.com/1702193/161159036-f2f39183-a1ae-4ecd-a985-e5995bd84ee5.png)

**Comment by bt90** [comment]
I left out the first variant on purpose as this indicates "no connection" and we already have a concept to display that.

**Comment by kuzmandi** [comment]
I think the display of the connection type is good but would like to suggest a different way of display. The bars instinctively indicate a connection quality of the same type of connection, but this is not the case. It is now as if 4 bars on the smartphone stand for WLAN and 1 bar for GSM. In addition, in my opinion, a connection should not look inadequate just because it is not possible directly.

**Comment by tomasz1986** [comment]
> Regression: 0 bars look like 'Disconnected...', indicating that Syncthing is actively trying to connect or in progress of establishing a connection.

This should look a little better in future versions, as the icon alignment and size has been tweaked in the meantime. Especially concerning the dots, they will be bigger, so hopefully they won't be confused for an ellipsis.

**Comment by Redsandro** [comment]
Not my first choice, but I am very happy with this. :+1:

**Comment by kuzmandi** [comment]
For me, it does not fit into the picture at all that one thing is displayed as text (Up to date, Disconnected) and one as a symbol (connection quality as a bar).

Honestly, I'm skeptical. This type of display is strange. But I like to be positively surprised in the future...

**Comment by CaptainFlint** [comment]
A bit of friendly criticism from a user perspective, if I may.

Today I noticed these new icons, and was completely flabbergasted as to what they meant. Connectivity issues? Latency? Connection speed? Network stability? Percentage of uptime? I opened the device info, and could not find anything related (now I know where to look, but I didn't then). I went to documentation, no mention there either (since the docs are still 1.22.0). From the changelog I found this discussion, and I can definitely say that using a "better-worse" connectivity kind of bar is not the best idea. I think, different kinds of connections should simply have different kinds of icons. For example (from the top of my head), a network icon 🖧 for LAN (maybe of different colours for TCP and QUIC), a world icon 🌐 for WAN (also same colour-coding for the protocol types), a link icon 🔗 for relay… A "prohibited" icon 🚫 for disconnected… And tooltips explaining what these icons mean.

Of course, tooltips would also help with the current design, but the current concept seems a bit inappropriate to me. We are too used to low bars meaning a bad signal. So 1 bar for relay makes me think that the device is on the brink of disappearing — but it's a perfectly working and stable configuration. Also, it's not clear for me why TCP WAN is "better" than QUIC WAN.

**Comment by Redsandro** [comment]
In response to the dissatisfaction with the icon type, I see that Bootstrap also has numbered labels in their icon set.

E.g.:
![image](https://user-images.githubusercontent.com/1702193/202033354-f3abea76-fc81-4446-9c3f-120b2c6bf015.png)

Perhaps that is a better indicator, as long as there is a tooltip explaining the number?

![image](https://user-images.githubusercontent.com/1702193/202033544-f4dd5b41-fa36-4504-b8fd-ed05975b278b.png)
![image](https://user-images.githubusercontent.com/1702193/202033244-b9eae97b-b578-42cb-8e1c-440d460586ef.png)

You could also use **0 1 2 3** for **disconnected relay wan lan**, and use the inverse fill icon for QUIC.

I'm satisfied with the icons, just hoping to address the dissatisfaction and find something that everyone can live with.

> Also, it's not clear for me why TCP WAN is "better" than QUIC WAN.

Ah, so the new indicator made you curious to learn something that you didn't know before. That's always a good result, no?  :smile:

So unless things have changed, TCP was benchmarked to be considerably faster than QUIC. QUIC implementation is experimental and its intended usecase is UDP holepunching where one can establish a connection even when both sides are firewalled without port forwarding. So if the superior TCP does not work and downgrades your connection to a Relay, QUIC just might work to set up a direct connection, which is faster.

**Comment by CaptainFlint** [comment]
@Redsandro 
Thank you for the details; that's indeed new for me; I always thought that QUIC would be a better protocol, being a more recent invention, designed specifically to be fast and overcome the restrictions of TCP...

> The new indicator made you curious about something. That's always a good result, no?

I've just realized that I may have sounded like I didn't like the idea in general. That's definitley not the case, sorry for not saying it out loud. I do like the idea of having the status icons, and I'm all for it! It's a nice little touch.

I just don't feel so enthusiastic about this particular design, that's all. Neither do I think that 0-5 would be clear enough. I still am of the opinion that relay=1 being so close to disconnected=0 (whether it's it in the form of a "connectivity bar", or a number), is not the kind of impression that users need to receive. Neither can you say, for instance, that TCP WAN connection is 4 times "better" than relay connection. That's why I suggested some different form which would not imply direct numerical comparisons of different connection types. In reality, these numbers don't represent the actual measurable "amount of quality" — but they look like they do, and this may confuse users. Real connection quality and speed depend on many more factors than just the connection type. In reality, LAN connection could be even worse than a relay connection (if you, for example, happen to have another device attached to a Wi-Fi behind two solid walls, in a very noisy radio environment, making is unrelyable and slow; while a relayed device can be connected via stable and fast cabled Internet routes). Maybe it's not the most frequent situation, I admit, but not totally unthought of.

If you still think that "directly comparable" connection types are more preferrable, we need to at least have a signficant gap between the disconnected state and the relay state, so that relayed device did not look to the users like it is about to drop dead. Maybe instead of numbers it could be a simple figure (like a circle) with a colour, defining the connection type. For example: red=bad=disconnected, blue=normal=relay, teal=a bit better=QUIC, cyan=better=WAN, green=best=LAN. This way you still have the quality range and direct comparison between them, and at the same time the relay connection type does not look like it's almost the same as "disconnected".

**Comment by acolomb** [comment]
One more thing to consider, being on a LAN cannot be detected really reliably. I usually see all my devices classified with three bars and as TCP WAN, while they are actually connected to the same gigabit switch on my desk. But they get globally valid IPv4 addresses from DHCP server, not from the unroutable private address range. I'm not even sure how the distinction could be made for IPv6, since globally routable addresses are much more common because of e.g. router prefix delegation. AFAIK we don't prefer link-local addresses specifically, so getting a TCP LAN classification on IPv6 is rather unlikely.

**Comment by bt90** [comment]
Well you *could* factor in the source and target addresses. At least for IPv6 the same subnet equates to LAN.

**Comment by acolomb** [comment]
True, but how do we know the subnet prefix length? Maybe this discussion should move on to the forum, as no longer strictly related to the issue.

**Comment by bt90** [comment]
Feel free to discuss: https://forum.syncthing.net/t/towards-better-connection-type-icons/19333

**Comment by igpit** [comment]
Try to pass along the relevant information to the user:
- connection type (e.g. relay / QUIC / TCP)
- available end-to-end bandwidth (how fast will larger amounts of data get transferred)
- end-to-end latency (how fast will lots of small changes/checks/... go )
- end-to-end connection stability (aka packet drop percentage, how good is your connection) 

All those things are very different. There is no way to merge all that into a single icon.

**Comment by Redsandro** [comment]
> There is no way to merge all that into a single icon.

That's okay, no one is asking for that. The last 3 points are unrelated to this issue. We just want to communicate the connection type at a glance so you can confirm quickly that your devices are connected as intended, and not downgraded due to reasons.

**Comment by imsodin** [comment]
The conversation has already continued in the forum topic linked above, please contribute there: https://forum.syncthing.net/t/towards-better-connection-type-icons/19333

This issue was actioned - any further improvement/changes are currently discussed in the forum and if a consensus to change something arises, we'll open a new ticket (referencing this one).
