### ISSUE TITLE
Autostart - console is displayed although -no-console 

### ISSUE THREAD

**Issue by 2GUN99** [syncthing/syncthing#8248]
After boot Syncthing.exe run while displaying console. This happens since 2 weeks or so. 

Shortcut to Syncthing is place in:

C:\Users\USER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

target is:
"C:\Program Files\Syncthing\syncthing.exe" -no-console -no-browser

 - Windows 11
 - Chrome

Not sure if actual bug or user error

**Comment by tomasz1986** [comment]
Just a guess, but I think this may be caused by using the "new" Windows Terminal instead of the classic CMD. There was an issue in the past related specifically to this. In short, if you want to have the console window hidden, you need to set the console to run in "legacy" mode instead of utilising Windows Terminal.

Otherwise, you can also use the Task Scheduler method from [https://docs.syncthing.net/users/autostart.html](https://docs.syncthing.net/users/autostart.html), which with the "Run whether user is logged on or not" checkbox enabled runs completely hidden in background.

**Comment by 2GUN99** [comment]
fixed, seems to be a user error. 

I recently set Windows Terminal as standard shell. Changing this option in the actual Windows Terminal app within the settings fixed the issue.

**Comment by 2GUN99** [comment]
@tomasz1986 thank u very much! 
just figured it out at the same time . I will probably switch to task scheduler in the long run :D

**Comment by bt90** [comment]
Couldn't we built the syncthing binary with `-H windowsgui` to suppress the console by default and rather explicitly spawn one if `--no-console` isn't present?

**Comment by calmh** [comment]
We can, but then it's impossible to get any console output ever, even when run with like --help from cmd.

**Comment by Unc3nZureD** [comment]
@calmh That's not entirely true. Check the following code:

`cpp
#include <Windows.h>
#include <stdio.h>

int APIENTRY wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
{
	// If console is needed
	{
		// Try to attach to an already existing first:
		BOOL success = AttachConsole(ATTACH_PARENT_PROCESS);

		// If previous doesn't exist, let's create one
		if (!success)	
		{
			success = AllocConsole();
		}

		if (success)
		{
			// Open the channels, so that later prints can work
			FILE* dummy = nullptr;
			freopen_s(&dummy, "CONOUT$", "w", stdout);
			freopen_s(&dummy, "CONOUT$", "w", stderr);
		}
		else
		{
			// Fatal error
			return 0;
		}

	}

	printf("printf\n");
	fprintf(stdout, "fprintf: stdout\n");
	fprintf(stderr, "fprintf: stderr\n");

	return 0;
}
`

**Comment by balazs-ita-epam** [comment]
Would be nice to hande this issue in Windows 11.

**Comment by Grimeton** [comment]
To fix this on all Windows versions, the image's (syncthing.exe) PE header IMAGE_SUBSYSTEM type needs to be changed from IMAGE_SUBSYSTEM_WINDOWS_CUI (0x3) to IMAGE_SUBSYSTEM_WINDOWS_CUI (0x2).

[Go's linker](https://pkg.go.dev/cmd/link) has an option for this:

> -H type
> 	Set executable format type.
> 	The default format is inferred from GOOS and GOARCH.
> 	On Windows, -H windowsgui writes a "GUI binary" instead of a "console binary."

Windows automatically opens a console window when the PE header value is IMAGE_SUBSYSTEM_WINDOWS_CUI. That's standard behavior since Windows NT was created. What happens behind the scenes on the OS side has changed over the decades, especially with Windows' refactoring efforts over the last decade.  

So all you need to do is add some linker flags to go's build command

> go build -ldflags "-H windowsgui" ...

And you should be fine. 

Here a screenshot of depends.exe showing the current subsystem type of syncthing.exe as "console":
![Screenshot 2023-01-09 225227](https://user-images.githubusercontent.com/2773919/211415812-8dd40e44-f5b7-4bbc-9035-09e5218b29ff.png)

KR,

G.

**Comment by acolomb** [comment]
Well that is not a solution though. As the issue title says, we have a `--no-console` option. If that is not given, the terminal output is really the desired outcome. Linking as a GUI executable takes away that possibility completely.

**Comment by Martchus** [comment]
Yes, using a GUI executable will have its disadvantages. You can still have a console in this case but unless I'm missing something there are caveats as mentioned in the [forum](https://forum.syncthing.net/t/windows-console-window/19635/6).

**Comment by Bill-Stewart** [comment]
The `--no-console` parameter seems to have an unintended side-effect...

To reproduce:

1. Open a Windows console window (e.g., PowerShell)
2. Run `syncthing --no-console`
3. The Windows console gets hidden and is now inaccessible (have to kill the hidden process to close it)

**Comment by Martchus** [comment]
I can't reproduce it with the current Syncthing release ([v1.23.0](https://github.com/syncthing/syncthing/releases/tag/v1.23.0)). Maybe it depends on the Windows version and how one launches PowerShell. However, this is definitely a problem of Syncthing itself anyways.

Note that the Syncthing Tray launcher starts Syncthing in a way that hides the console regardless of Syncthing's `--no-console` option. So you can simply ditch the option. (You should likely be aware of this as you have also took part in the recent [forum discussion](https://forum.syncthing.net/t/windows-console-window) on that topic.)

I suppose I should remove remove the `--no-console` flag from the defaults, tough.

**Comment by Martchus** [comment]
Oh, somehow I was convinced that this was an issue comment in the Syncthing Tray repository. Apparently I'm subscribed to this topic due to my comment from 2 weeks ago. Well, at least I could come up with a slight improvement for Syncthing Tray again.

**Comment by Bill-Stewart** [comment]
Right, I'm not talking about "syncthing tray" but rather just running `syncthing.exe` with the `--no-console` option.

From the observed behavior, it seems that `--no-console` hides the console window it's executed from. Just tested that again and it does seem this is what's happening.

In my opinion, this approach is not correct because if I am running from a command window and specify `--no-console` I now have an "orphaned" console window session. At the very least this is an unexpected (and rather unpleasant) side effect that should at least be documented.

If it were me, I would drop the `--no-console` option and instead provide a separate GUI application that spawns `syncthing.exe` in a hidden window (as suggested in the forum topic).

**Comment by calmh** [comment]
There's a draft PR in progress to do just that.
