### ISSUE TITLE
Outdated thrift dependency through quic-go

### ISSUE THREAD

**Issue by dmanlfc** [syncthing/syncthing#8256]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 v1.19.1 or v1.19.2 build, using buildroot for Batocera Linux,.

 - browser and version, if applicable
 N/A
 - what happened,

Syncthing 1.19.1 or .2 cannot be built from sources.
The depency thrift source website is out of date. See error...

	git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /x86_64/host/usr/share/go-path/pkg/mod/cache/vcs/f6f367fb9d5656665ab3c2c1c3b2a44c2ffc79f6b70612f5864d7ceedcc7b9ea: exit status 128:
	**fatal: repository 'https://git.apache.org/thrift.git/' not found**

 - what you expected to happen instead, and
 - any steps to reproduce the problem.

Try to build from sources.

**Comment by tomasz1986** [comment]
It appears the particular URL has not been working since at least 2019 (see https://github.com/googleapis/google-api-go-client/issues/347).

I've got no idea for what this particular tool is used, but Syncthing still appears to build fine when following the instructions from https://docs.syncthing.net/dev/building.html.

**Comment by dmanlfc** [comment]
we've been using the build instructions for automated builds for months, about 48hrs ago it started failing... we haven't changed anything apart from upgrading to the latest release.

**Comment by imsodin** [comment]
Looks like that's quic-go using an abandoned project with said dependency: https://github.com/francoispqt/gojay/issues/128  
Filed an issue asking to move away from it there: https://github.com/lucas-clemente/quic-go/issues/3373

Maybe building works due to some proxy/cache still having the code for the given module. As a short term remedy a replacement directive (or replacing) that location with github.com/apache/thrift should work.

It is unlikely to have anything to do with the latest release, as nothing changed with regards to those dependencies in Syncthing.

**Comment by dmanlfc** [comment]
this will need to be resolved at source.
we can't patch this like normal methods as buildroot using 'go' will try to download the dependencies before getting to the patching phase (hence the issue report).

**Comment by imsodin** [comment]
Sure, however a heads-up regarding expectations: If building works in the go toolchain (looks like it does) and you use some custom tools instead, that likely won't get the urgency of "does not build", but just "the library used since a long time is unmaintained - that's not ideal".

**Comment by dmanlfc** [comment]
thanks @imsodin 

I don't think we're doing anything out of the ordinary - effectively a `go run build.go -goos linux -goarch <arch> build`
Unless you see something obvious in here...
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/utils/syncthing/syncthing.mk

if you can't simply modify go.sum then I guess we'll have to disable syncthing in batocera until resolved.

**Comment by imsodin** [comment]
I removed all my mod and build caches, and it does build, but it also doesn't download the "thrift" dep at all. Turns out we don't actually depend on it, as in no package we use depends on it (but modules do, that's why it figures in go.sum). Do you run an old go version - maybe it doesn't have that optimisation yet?

Modifying go.sum doesn't work. What would likely work is a replace directive for thrift, but adding that for something that isn't even used seems wrong.

**Comment by dmanlfc** [comment]
Current buildroot version is v1.17.7

**Comment by imsodin** [comment]
Then I have no clue what's causing the problems for you. As nothing changed with the Syncthing release, I'd check any other reent changes to either your build instructions or infrastructure to see what changed/broke it.

In any case I don't see anything actionable for us about this, thus I'll close the issue. I am happy to help with any further questions (don't really have an ideas/suggestions at this point). Please open a topic on https://forum.syncthing.net for that - thanks!
