### ISSUE TITLE
Option to not sync mtime

### ISSUE THREAD

**Issue by rando79** [syncthing/syncthing#831]
Trying to sync my android device and my NAS(armv5) both using syncthing v0.10.0:

On the ntfs mount of the NAS the file **/my/directory/.syncthing.example.test** is created then I get:

**puller: final: chtimes /my/directory/.syncthing.example.test: invalid argument**

File **/my/directory/example.test** is not created. Syncthing continues with the next file but the same error happens for all the files in the directory.

**Comment by rdiaz02** [comment]
Sorry if I this is obvious, but I am not sure what the current status is
(i.e., if it is a known fact that syncing two Androids does not work
well).


My scenario is very much like the one described by @SenK9, where I have
two Android devices and a Linux computer and the Androids are unable to
just finishing syncing successfully. 


When both Android devices (and the computer) directly share the directory
I get the "Folder blablba isn't making any progress. Pauring puller for 1
mm0s" message in the web GUI of at least one of the Android devices.


If the directory in question is not shared directly between the two
Android devices (as @NickPyz suggested above, 20-Oct) but only shared
through a Linux computer I keep seeing in the logs the "shortcut:
chtimes /blabla: operation not permitted". 

Manually starting and stopping as @jthornhill, 24-Oct, mentions, is
something I'd rather avoid and, moreover, I am afraid that were I to not
stop once when I should, I'd be deep in the mess again.


Is the only reliable workaround for now to run the CLI syncthing as root
(as @jthornhill mentions above; see also
https://discourse.syncthing.net/t/android-frozen-syncs/741/34)?


Even if the answer is "only two rooted Androids will do for now", I am
still intrigued, because I see the above problems in a directory of ~ 7.4
GB, 10000 files and 3000 directories, but not on small test directories
(or, if they happen, they seem not to prevent syncing from completing
successfully).

**Comment by sciurius** [comment]
Can anyone run btsync with strace to find out how *they* manage to get correct mtimes?

**Comment by madalu** [comment]
Perhaps I am missing something here. On my android devices (both
running CM11) the mtime is changed on the filesystem when syncthing
updates a file. 

Let's say that I create a file on my computer in the Sync repository:

touch new.txt

I monitor my android device for changes:

````
root@ovation:/sdcard/Sync/test # ls -al
-rw-rw-r-- root     sdcard_rw        0 2015-03-12 15:40 new.txt
````

Then I run on my computer 'echo "A new line" >> new.txt':

I wait for the changes to be propagated across the network.

Then on the device:

````
root@ovation:/sdcard/Sync/test # cat new.txt                                                                                                                  
Add a line
root@ovation:/sdcard/Sync/test # ls -al                                                                                                                       
-rw-rw-r-- root     sdcard_rw       11 2015-03-12 15:45 new.txt
root@ovation:/sdcard/Sync/test # stat new.txt                                    
File: 'new.txt'                                                              
  Size: 11              Blocks: 8          IO Block: 4096   regular file
Device: 13h/19d Inode: 1097771608  Links: 1    
Access: (0664/-rw-rw-r--)  Uid: (    0/    root)   Gid: ( 1015/sdcard_rw)
Access: 2015-03-12 15:45:53.000000000
Modify: 2015-03-12 15:45:53.000000000
Change: 2015-03-12 15:45:53.000000000
````

And yet, as several have noted, my two android devices never get in sync; they keep bouncing file metadata around my mesh, which means more bandwidth, CPU, etc.

**Comment by AudriusButkevicius** [comment]
This bug in android only applies to external sd cards.

**Comment by madalu** [comment]
Thanks! So I suppose my problem has to do with the enforced lenient mtimes in the Android app? As @calmh says above: "With the above commit in place, you can add a <lenientMtimes>true</lenientMtimes> to the folder configuration to restore the old v0.9 behaviour. Note that two Android devices running with that setting will never get in sync though." 

However, it seems to me to be impossible with the Android syncthing (mines current from F-Droid) to turn that setting off. Even if I modify it in the config file via vim, I find that it changes back to the default after launching the Android GUI. So I'll submit a bug report over in the Android app's issue page.

**Comment by rdiaz02** [comment]
I am not sure what @AudriusButkevicius means by "This bug in android only applies to external sd cards". As @madalu says, two Android devices will never get in sync, and this happens also if one does not use an external SD card.

**Comment by Nutomic** [comment]
@madalu Yeah I programmed it so that `lenientMtimes` is automatically set to true on start.

But as I understand it, there's no way it works on Android without the setting, so why would you want to turn it off?

**Comment by AudriusButkevicius** [comment]
It works fine on my nexus, since it has no sd card slot.

**Comment by madalu** [comment]
@AudriusButkevicius - Does it work with two android devices in your mesh? Syncthing works fine when I use only one Android device, regardless of where I store the files (but my external_sd is also formatted as ext4).

@Nutomic - My main reason is simply to test different scenarios/setups for syncthing for android. I noticed that the mtimes are indeed being modified on the sdcard. So out of curiosity, I'd like to see what happens when I turn off lenientMtimes and run syncthing as a non-root user. I can change lenientMtimes and run from the command line via adb:

````
cd /data/data/com.nutomic.syncthing/
./lib/libsyncthing.so -home="./files"
````

But I don't know how to test the same thing as a non-root user.

More generally, I'm confused as to why syncthing when started from the Android app cannot read the modification times that are in fact being written to the sdcard. So (forgive my ignorance about Android internals): I assume the binary is sandboxed in such a way as to prevent reading mtime data?

**Comment by madalu** [comment]
O.K. After looking at the syncthing code, I finally understand. The problem does not have to do with files whose content changes. It is that os.Chtimes (invoked in internal/model/puller.go) returns an error when trying to bring just the change time into sync with other nodes. So @Nutomic, you are right: setting lenientMtimes to false would do nothing. Sorry for the noise.

**Comment by Nutomic** [comment]
@AudriusButkevicius I think the problem still occurs in internal storage, because Android treats it like an sd card. It only works in the app's data folder. But I could be wrong.

@madalu If you still want to play around, you can recompile syncthing-android with the relevant code in ConfigXml commented out.

**Comment by rdiaz02** [comment]
@AudriusButkevicius  and @Nutomic: Yes, I confirm the problem does occur in internal storage, at least in my two tablets (one a Nexus 7 with stock 4.4.4 and the other a TF 201 with stock 4.1.1, none of which have external SD ---the Nexus because it can't, the TF because I just don't have an external SD inserted).

As @madalu says, this issue shows up when syncing **two** or more Android devices (and yes, even using just internal storage). With a single android device you might never notice the problem.

The problem can be circumvented by running the android apk as root or by running a linux (arm) version of ST under linux for android.

**Comment by AudriusButkevicius** [comment]
Given you have root access, you can use a custom kernel which has this issue fixed.

**Comment by rdiaz02** [comment]
So there is a third workaround, that involves using a custom kernel in the Android? However, for the average user, isn't installing a custom ROM a little bit more problematic than just running the app as root or running linux from the Android devices ? (I think installing a custom ROM increase my chances of doing something silly and bricking the device).

**Comment by AudriusButkevicius** [comment]
Actually, I take my words back. It breaks always when running as non-root, no matter if it's external sd card or internal storage. I just have a single android device, hence never noticed it.

**Comment by rdiaz02** [comment]
Thanks for the confirmation. I will stick to the root or linux under android for now then (which works great, by the way).

**Comment by madalu** [comment]
@Nutomic: I can confirm that everything works properly if the synced directory is in the app's data folder: /storage/emulated/0/data/com.nutomic.syncthingandroid. Ownership of files in this directory is given to the app's uid. 

So for user's who don't want to run as root or install a linux chroot, the simplest solution is to use sync files in the app data directory. Perhaps the Android app could make that the default home for new directories (and provide a warning about the limitations of other locations when more than one Android device is being synced)?

**Comment by rdiaz02** [comment]
@madalu: can you access (read and write) those data from other apps?

**Comment by madalu** [comment]
@rdiaz02: Yes, any app that has permissions to write to external storage (WRITE_EXTERNAL_STORAGE - listed as "modify or delete the contents of your SD card" in app info) can read or write those files. I created a shortcut on my home screen to the directories and then open files in other apps (e.g., text editor) from there.

The syncthing app also has permissions to read and write to the SD card. However, it seems that it can only change the mtime on files within its own data directory.

**Comment by sciurius** [comment]
I still wonder how btsync can do it.....

**Comment by fmarani** [comment]
I am running v 0.10.26 on both my laptop (amd64) and my Synology NAS (arm) and I am getting these errors on the NAS

the NAS filesystem is:  /dev/vg1/lv on /volume1 type ext4 (usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,synoacl)

this is the error
Puller (folder "photos-lenovo", file "2011/03/27/_MG_3774.JPG"): shortcut: chtimes /volume1/photos/photos-lenovo/2011/03/27/_MG_3774.JPG: operation not permitted

is it the same error? (No Android here...)

**Comment by AudriusButkevicius** [comment]
try changing the time yourself with `touch -m -t` and see if that works.
Perhaps the user doesn't have right permissions or something?

**Comment by fmarani** [comment]
I am running the shell and syncthing with the same user. `touch -m -t` is not supported by the busybox binary, but I can use `touch` without options and it seems to change the modification time correctly.

**Comment by AudriusButkevicius** [comment]
It does support -m I believe, check the help.

touch without a specific date just does an open and close with 'w' flag, which then forces the kernel to bump the mtime.

**Comment by fmarani** [comment]
this is the help:

```
BusyBox v1.16.1 (2015-01-07 14:59:24 CST) multi-call binary.

Usage: touch [-c] [-d DATE] FILE [FILE]...

Update the last-modified date on the given FILE[s]

Options:
	-c	Don't create files
	-d DT	Date/time to use
```

but it turns -d is broken :( http://forum.synology.com/enu/viewtopic.php?f=19&t=83345

so I used this perl snippet:
```
use Time::Local;
$when = timelocal(00,11,11,11,11,2011);
utime $when, $when, "ubuntu-13.10-desktop-amd64.iso";
```
and seems to work
```
DiskStation> ls -let ubuntu-13.10-desktop-amd64.iso 
-rw-rw-rw-    1 admin    users    925892608 Sun Dec 11 11:11:00 2011 ubuntu-13.10-desktop-amd64.iso
```

**Comment by AudriusButkevicius** [comment]
I guess the next step is to get a tiny go binary compiled to do the same (or just a script if you have the go runtime installed) and compare the strace output to see how it's different.

**Comment by wweich** [comment]
btsync does not set the mtime on Android.
I copied a file from 2010 to one of my btsync folders and it has `2015-03-20 21:19 GMT+1` as mtime.
When I sync the same file with btsync to a windows client, the mtime is set.
So btsync cannot set the mtime on Android either, and uses other information to see if the file is in sync.

*btsync version: 2.0.80 on Android, 2.0.93 on linux*

**Comment by sciurius** [comment]
It has been mentioned several times that this affects synching with two androids. 
I have a folder that a Linux box (folder master) shares with a single android client, and I still get the "Override changes" button on the master.

**Comment by wweich** [comment]
Thats because your android wants to sync back the mtimes of every file.

I am currently syncing files without problems with two Android devices by placing the synced files inside a subfolder in `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid/`.
It is not as *pretty* as directly in `/storage/emulated/0/` and now the files are counted for apps (Syncthing) instead of Picture, Videos or Audio, but thats OK for me (Uninstalling the app will probably also delete all the synced files).

Google Play Music won't find the music files anymore, but alternative music apps probably will (I am using Tomahawk)

I never liked the fact, that files transfered with btsync would have wrong mtimes (especially documents and the like, not so much with multimedia files), so placing the files in the data folder belonging to the syncthing app is the best compromise for me.

For DCIM and Downloads I will probably have a folder for each Android device on my server, where the files are then consolidated to *global* Pictures and Downloads folders which is then synced between all devices.

The folder picker in the syncthing app UI suggests putting the files inside `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid/files`, but then DicePlayer doesn't find most of my videos, as the folder hierarchy is probably to deep, so I placed my folders directly in com.nutomic.syncthingandroid.

**Comment by rdiaz02** [comment]
@madalu: I was trying to use your suggestion but do you get the /storage/emulated/0/Android/data/com.nutomic.syncthingandroid directory automatically? That is what I think should happen, but I do not have that directory in two different androids running stock roms (4.4.4 and 4.1.1). I do have /data/data/com.nutomic.syncthingandroid, but that is only accessible to root.

I could create the directory, but I think that is not the point. Could this have something to do with your running CM11?

**Comment by wweich** [comment]
The folder picker inside the app has the directory `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid/files`listed as one of the default "entry points".
When you select that directory and create a new folder, the app will create the main folder, if it doesn't exist yet..
The directory didn't exist on my devices as well, so I created it manually.

**Comment by rdiaz02** [comment]
Thanks. That worked in one device (nexus, android v. 4.4.4.) but on the other the directory  /storage/emulated/0/Android/data/com.nutomic.syncthingandroid/files was not offered as the default (only /sdcard/storage0 and /sdcard/storage1) so I created it by hand, and things are working fine.

**Comment by Nutomic** [comment]
@rdiaz02 That's because this API was only added in Kitkat.

**Comment by rdiaz02** [comment]
Aha, I didn't know that. Anyway, I do not have any sd card in any device, and things do seem to be working OK (i.e., the androids are no longer playing catch with each other, forever out-of-sync). That this seems to solve the issue is the same that @madalu and @wweich reported. 

(Actually, things are OK except for when one of the devices decides that "/storage/emulated/0" just does not exist. But I think this is just an android issue, totatlly unrelated to ST.)

**Comment by wweich** [comment]
Isn't `/stroage/emulated/0/`or `/storage/sdcard0`in almost all cases (on modern devices) the internal memory, whereas `/storage/emulated/1/` or `/storage/sdcard1/`would be the *real* sd card?
But even on the sd card, setting the mtime should be no problem as even FAT32 has mtimes.
I just checked my HTC Desire HD to be sure (took a while, this thing is sooo slow). Files are synced and mtime is set correctly.
Although I have CM 12 / Android 5.0.2 installed. Maybe old Android versions can't do that.

**Comment by v6ak** [comment]
@wweich As far as I understand it, the problem is not in file not having a mtime, but in a file where Syncthing is not allowed to set an arbitrary mtime. (See the “operation not permitted” error messages.)

Android has (since 4.4?) an emulation layer over the FAT32 sdcard that handles some permissions based on file location. This seems to be the reason why moving the directory inside /storage/emulated/0/Android/data/com.nutomic.syncthingandroid works around the issue.

**Comment by wweich** [comment]
@v6ak So only users with version 4.4 or higher will have an advantage by using `storage/emulated/0/Android/data/com.nutomic.syncthingandroid`.
For older versions it doesn't matter, as either way, the mtimes cannot be set?

**Comment by Nutomic** [comment]
I think the mtime thing has been in Android far longer than 4.4, what's new in 4.4 is the fact that apps can't easily access sd card any more.

And like I said, I don't think it's different for `Android/data/com.nutomic.syncthingandroid` because that makes no sense (tapparently he point is to prevent sd card wear). Though I haven't tested this.

**Comment by v6ak** [comment]
Well, with 4.4, it is more complicated.

There is a strange term “external storage”, which defined as a storage of certain capabilities and features, like case insensitivity. It does not have to be actually external, any internal storage with these features is considered as “external”.

Applications with a proper permisson can access the *primary* “external” storage, which is usualy the internal storage. In some cases (rather older phones that rely only on sdcard with external storage), the primary external storage is the SD card. Lenovo seems to offer selecting the primary storage, but that's a rare case and it is not intuitive for end users.

In the secondary external storage, no app can write outside the `Android/data/<app pkg id>` directory.

In the primary external storage, apps can write outside the `Android/data/<app pkg id>` directory, but they can’t set mtime there. Moving the data to `Android/data/<app pkg id>` seems to allow setting mtime.

Android 5 introduces some new API to handle KitKat’s issues with writing to external storage. I haven’t explored it, but it might be worth exploring the API for Syncthing. As far as I know, it also provides apps like DropBox, GDrive and Syncthing a way to expose their folders to other apps.

**Comment by Nutomic** [comment]
That way is probably he [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html). They extended it a little for Lollipop, but it's also in 4.4. I want to implement that for syncthing-android, but just don't have the time for it.

**Comment by dcarosone** [comment]
FWIW, this is not just about Android (or at least not just useful there).

I just used lenient mtime to solve a different problem. I understand clearly why it solved the problem, but not so much why the problem happened in the first place (there may be another issue lurking here?).

One of my st folders comes from a shared server where several colleagues change files (using other mechanisms).  We've arranged umasks so we can r/w the file contents by group, but the file owner remains as the person who created the file, by design and intent.  I can't chmod or chtimes files I don't own, and neither can my syncthing process.

Syncthing got upset, initially at a few files where it had decided permissions or times had changed. Logs were complaining about fastpath and chmod permission denied.  I don't know why it had decided there was a change; by visual inspection (and rsync -cai) they were identical on both nodes, other than ownership (I owned them at my end, someone else on the server).  

After trying a number of things to resolve it, I eventually dumped the database and rescanned on the server node. Big mistake - now it was complaining about every file I don't own on the server.

I took a look at the code, and saw the "ignore permissions" path.  I thought maybe st was seeing the ownership as a metadata difference, and failing at the chmod step, so I set that option on the server.  All that achieved was to instead fail in the chtimes step, so I also set lenient mtimes.  That let it proceed and worked around the problem, by setting all the mtimes on my end to match the server. 

Which they did already. The folder was originally pulled down from the server via Syncthing and was fully in sync.  None of the files in question changed in the meantime (the timestamps are still in Feb). What I still don't understand was why differences were detected at all.  

So in part this is an issue of failing to change modes or times unnecessarily (to their current value) which could be optimised away, and in part a question of why there was a difference detected at all.

What debug settings would be best to try and track down specifically why syncthing thought something had changed?

**Comment by calmh** [comment]
> So in part this is an issue of failing to change modes or times unnecessarily (to their current value) which could be optimised away, and in part a question of why there was a difference detected at all.

This is due to how the file versioning works. When a file is independently detected and scanned on two devices (say they have the same file already at initial setup, or if you reset the database) they have different version information. Basically one side has information that says "found on device A, not present anywhere else" and the other one says "found on device B, not present anywhere else". This is "out of sync" as far as syncthing is concerned, and it will want to sync this file. When doing the sync it will notice that the content hashes are exactly the same and hence transfer no data and just update the metadata - this is the "fast path". It doesn't check if the mtime and permissions are already the same as what it wants to set, it just sets it once and for all instead. Of course, if this fails there is unhappiness...

**Comment by dcarosone** [comment]
Thanks, that explains it.

Is it worth implementing either:
- detection that the files from both nodes are identical, both hash and
metadata, and reducing to a nop, or
- detection that chmod/chtimes is unnecessary since the filesystem already
matches (perhaps in the error path, to save io but resolve a relatively
common case) and allow progress?

**Comment by cdhowie** [comment]
This issue impacts me severely; I may take a stab at implementing this "virtual mtime" proposal.  I see it working like this:

When a file is created or updated, if the operation to change the mtime of the file fails with "operation not permitted" then we read the current mtime of the file and write three things into a database: the file path, the file's mtime on disk ("disk-mtime"), and the mtime we *tried* to set it to ("actual-mtime").

When a file's metadata is being read, we will look in the database for the file.  If we find it *and* if the file's mtime on disk matches the "disk-mtime" column in the database, we *instead* pretend the file has the mtime of the "actual-mtime" column.  Otherwise, we use the mtime on disk.

This should neatly satisfy the case where the file is modified locally and so has a newer mtime, but also allow the mtime for files that didn't change to be preserved in some way on systems that don't support it.

Without pulling in a new dependency, do we have access to some kind of database facility right now?

**Comment by calmh** [comment]
@cdhowie Yeah that sounds like the way to go about it. You have the leveldb key value store to save things in. It's not super cleanly separated from everything else, but look for "blockmap" in internal/db for a file that uses it in quite a standalone matter.

**Comment by cdhowie** [comment]
Alright, sounds good.  I will need to learn Go but that shouldn't be terribly difficult, and it would be a good one to have in my toolkit.  Unfortunately I don't have the time and desire to set up an Android environment, but to test virtual mtimes I'll just hack locally to simulate failures from chtimes and verify that everything is happy with my changes.

**Comment by AudriusButkevicius** [comment]
I think there is a mount option which kills mtimes

**Comment by cdhowie** [comment]
Is `osutil.Rename()` going to alter the mtime on Android?

https://github.com/syncthing/syncthing/blob/master/internal/model/rwfolder.go#L1120

Obviously not on other systems or calling `os.Chtimes()` first would be an error everywhere, but since we cannot even set the mtime on Android I am reluctant to rely on this being the same.

**Comment by calmh** [comment]
Renaming does not alter mtime.

**Comment by cdhowie** [comment]
Just to clarify, I do know this about most systems.  But with Android all bets are off, so I wanted to confirm. :)

**Comment by calmh** [comment]
Well, that would be even more astonishly broken than it is now, and in a new direction, so if that's really the case I'll probably just give up and ignore the platform even exist any more.

**Comment by abondis** [comment]
I think I'm actually having this issue too. I keep some files opened on my desktop during the day, but it seems my files on the android devices always win.

**Comment by wweich** [comment]
Renaming and moving files does not change mtime on Android. Would really be messy if it would.
Tested with Total Commander on Nexus 5 (stock, not rooted) with a file directly in `/storage/emulated/0/`.

**Comment by cdhowie** [comment]
Thanks for confirming that, @wweich.

I hope to have a pull request ready sometime this weekend.  I am very new to Go so I may submit some "pre-pull requests" to get input on the direction I'm going.  If I'm going down the wrong path I would like to find out sooner rather than later.

@calmh One aspect of the code I'm working on creates a leveldb inside of each rwFolder, named `.stmtimes.db`.  I've added this name to the magic "ignore our own files" code.  Does this seem like a reasonable place to store this data, or should I store it in the database on the Model type?  I suspect that would be the wrong place for it, hence my decision to go with a per-folder DB.

**Comment by AudriusButkevicius** [comment]
I think you should store it in the general database. There is a thing called namespacedKV for creating your own space within the general db, so I think each folder should have one of these.

**Comment by cdhowie** [comment]
Alright, well that will simplify my code quite a bit.

**Comment by cdhowie** [comment]
Please comment on PR #1802 if you are interested.

**Comment by stooone** [comment]
@cdhowie Don't forget to grab the bounty for this at https://www.bountysource.com/issues/5226549-option-to-not-sync-mtime :)

**Comment by cdhowie** [comment]
@stooone Thanks for the pointer, done. :)

**Comment by stooone** [comment]
@cdhowie thanks for closing itt.
