### ISSUE TITLE
Export and Import config

### ISSUE THREAD

**Issue by guglovich** [syncthing/syncthing#8389]
Please make the Export and Import settings in the web interface in the settings. If there is a definition of a first run, make a dialogue offering the import. 

- This solves the problem of transferring the configuration to a new other installed system
- it is a good UX experience. the app should be simple for all categories of users
- copied the configuration from the old system, it didn't work. or I didn't do it right. so all the more reason to ask

**Comment by AudriusButkevicius** [comment]
What would that do? Produce a file with the config?

Why not just copy the existing config file that is already there?

**Comment by calmh** [comment]
Maybe a zip file with the keys + config

**Comment by AudriusButkevicius** [comment]
Would we remove the foldera? How would we know where they are on the new system? Or worse, accidentally merge two d:\ drives or something.

**Comment by guglovich** [comment]
> Would we remove the foldera? How would we know where they are on the new system? Or worse, accidentally merge two d:\ drives or something.

It is possible to make an export without specifying location options, just folders to accept, their settings, and an ignore list. But without paths to synchronise here, you'll have to give the application a bit of a hand.

**Comment by imsodin** [comment]
It's definitely not as simple as just a one shot import/export button or something. Having something like a first start/setup wizard to get users started (e.g. replacing the default folder, instead walking them through setting a folder up) could be integrated with such a functionality - where it's possible to take information from an existing/exported config to re-create that locally (either as a replacement for said config, i.e. same ID, or as a new device that has same/similar options/folders/devices). This is a huge undertaking though. I haven't found any existing github issue for it, but I might just have failed searching. Otherwise having a single "user onboarding wizard with config setup/import" would be a valuable feature request to have open (likely in perpetuity, but still :) ).

**Comment by guglovich** [comment]
Backing up settings may not be a quick task, but in this case how could another task not have been simplified. After installation, it is possible to take a minute, select the device, select the main folder that was for synchronisation and enable Auto Acceptance. But for some reason they couldn't simplify the task here either. Syncthing just makes new folders with new crooked names, instead of trivial folder availability check and sync.
