### ISSUE TITLE
Indicate/Guarantee date of last full chain sync

### ISSUE THREAD

**Issue by jtagcat** [syncthing/syncthing#8511]
I want to monitor from a single device, that the folder I have (receive-only) is up to date at least after a given timestamp. Via metrics / API I can then notify if something is not right.

1. Device A scan at '2022-08-20'
2. Connection with device B at 2022-08-21
3. Sync finished on 2022-08-22

Last seen: 2022-08-22
Finished full sync minimum: 2022-08-20

The devices can be last seen, but not actually do a full sync of metadata, or do a sync of metadata and changes on remote might not have seen by remote.

The resulting timestamp on the folder should be the minimum (guaranteed) version.
 - per folder: all devices syncing this folder have scanned and sync at least timestamp
 - per device-folder: guarantee for sync between remote and local instance of folder state at timestamp
 - per device?

**Comment by AudriusButkevicius** [comment]
The idea sounds interesting, 

I think most of what you want you can already be composed from the existing API so there is nothing new that is required in theory.

I don't however think this should be part of syncthing, as it will not make sense most of the time for some set of users and just cause confusion, because people have some old no longer used device still in the list, or have a folder paused, etc.

This is where "but if X then I think you should do Y" user suggestions will start to come in, where there will be no consensus as to what the "right way" is, as there is none, as it's all subjective to what the user wants, hence should be implemented by the user. Some might want overall timestamp, some might want only one that includes their main offsite instance, etc, etc.

On that basis, I'm closing this, and suggest that any further discussion should be continued on the forum, which has more people that might have an opinion.
