### ISSUE TITLE
Legacy ARM support on releases 1.20+

### ISSUE THREAD

**Issue by ai91** [syncthing/syncthing#8534]
Starting from v1.20 the Syncthing has been updated to go 1.18, what leads to cut off support of legacy devices which stuck on older linux/kernel versions. Some cheap ARM-based NAS devices (out of support by vendors) get no updates anymore.
Unfortunately, after last Syncthing release, Syncthing is also not supported anymore, due to lack of `accept4()` support.

### Practical use case:
Zyxel NSA 325 v2, 
```
# uname -a
Linux ### 2.6.31.8 #2 Fri Jun 23 11:03:47 CST 2017 armv5tel GNU/Linux
```

Syncthing log:
```
[start] INFO: syncthing v1.21.0 "Fermium Flea" (go1.19 linux-arm) teamcity@build.syncthing.net 2022-08-16 08:01:49 UTC
...
[57PPE] WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
....
[57PPE] WARNING: GUI/API: accept tcp [::]:8888: accept: function not implemented (restarting)
```

### TODO
I don't see valid solution for the problem, though could be some workarounds:
- escalate a new request to Golang maintainers to introduce a fallback for `accept4` on unsupported configurations
- add to Syncthing release assests one more asset which built with older Go-version
- introduce in Syncthing code some fallback implementation when lack of accept4 detected
- ??? discuss other possible solutions (more details could be found on this topic https://forum.syncthing.net/t/web-gui-suddenly-stopped-working-on-arm-v1-21-0/18969 )

**Comment by calmh** [comment]
Unfortunately, I don't think any of the proposed solutions are going to fly, nor can I think of any better ones myself. We release binaries with the latest Go compiler and runtime, because that's the best and most secure one. Our source code is compatible with the previous Go release, but that moves forward once every six months so using an older compiler is not a long term solution.

Unfortunately, this boils down to the same thing as support for other old operating systems (Windows XP, etc). If you need to use an old OS, you also need to stick with an older Syncthing.
