### ISSUE TITLE
Increased file size when sharing between encrypted devices

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#8556]
v1.21.0, Linux (64-bit Intel/AMD)

Host1 normal: 2 bytes
Host1 normal -> host2 encrypted: 1435 byte
Host2 encrypted -> host3 encrypted: 1806 byte
Host3 encrypted -> host4 encrypted: 2177 byte

Seems just add 371 bytes of zero data

Data can be decrypted, but have some problems:
1. Data not interchangeable between different encrypted hosts (seems file size stored in database)
2. Data comparison problematic for check same state

All files for investigation: [data.zip](https://github.com/syncthing/syncthing/files/9649668/data.zip)

**Comment by AudriusButkevicius** [comment]
Data is not supposed to be interchangeable nor comparable, and this is done on purpose, as it's encryption after all.
Otherwise you potentially open up oracles and known cipher text attacks. 

i.e, if I know that I have an encrypted file that is top secret government document, and encryption was interchangeable and comparable, I could just find all other people that have the same encrypted file, and expose them.

If you wish to discuss this further, please take this to the forum.

**Comment by Ratio2** [comment]
Discussion on forum problem for me, just some notes:
1. Encrypted data same, only zeroes added on another encrypted device (see screenshot)
2. We can add padding on data transmission, no reason to keep zeroes on disk (we can trim zeroes and get same data)

![Screenshot from 2022-09-27 01-24-10](https://user-images.githubusercontent.com/2958497/192391274-42bf7bf9-5185-4043-9817-5b7327387d99.png)

**Comment by imsodin** [comment]
I don't think the OP was a complaint about added data/bytes when encrypting, but about unexpected behaviour of size when sharing with multiple encrypted devices. And the zeros look weird, data should be all random for encrypted files. Anyway it's not clear how the sharing exactly works. @Ratio2 Could you please explain with steps what you did to arrive to those file sizes, as suggest in a topic on https://forum.syncthing.net/ please.

**Comment by Ratio2** [comment]
https://forum.syncthing.net/t/adding-unnecessary-zeros-when-sync-between-encrypted-folders/19028

**Comment by imsodin** [comment]
With the additional information from the thread above, it's clear there is a bug:  
The problem lies in the trailer added on receive-encrypted folders containing the encrypted file-info (for offline decryption): On device 2, the size on the global file is 1064 as expected (minPaddedSize + blockOverhead). The local file is 1435 bytes, as the trailer size is added to the fileinfo. dev3 has those 1435 bytes as global, and adds its own trailer -> 1812 bytes.
