### ISSUE TITLE
upload rate not work

### ISSUE THREAD

**Issue by anythink-wx** [syncthing/syncthing#8562]
I set the global Outgoing speed limit to 10Mbps, but it doesn't work, please see the screenshot.

v1.21.0, Windows (64-bit Intel/AMD)

![image](https://user-images.githubusercontent.com/3948755/192997486-7726fa04-955f-45dd-9cc4-bc31d2ccd14b.png)

**Comment by imsodin** [comment]
You are likely connected to a device on LAN, where the speed limit doesn't apply by default. If this information doesn't help you figure out what you see, please use the forum - https://forum.syncthing.net/ - for support. The forum has a lot more eyes and friendly people on it than the issue tracker. If it turns out to be a bug, we can re-open the ticket.

Thanks!

**Comment by anythink-wx** [comment]
Thanks for the reply, it is a device in the LAN, so what is the way to limit the intranet transfer rate

**Comment by AudriusButkevicius** [comment]
Check the forum. People already answered your question there.
