### ISSUE TITLE
Very poor performance with lots of small files

### ISSUE THREAD

**Issue by peterhoeg** [syncthing/syncthing#8602]
I'm trying to sync 654,364 files in 16 folders with a total size of ~69.3 GiB.

And it is *slow*. Like 2 hours for 10% slow. I basically killed it and `rsync`ed it over instead which was much faster.

### Does your log mention database corruption?

No

### Include required information

Please be sure to include at least:

 - Syncthing 1.22 on x86_64, NixOS unstable (on both sides)
 - 32GB (receiver) and 16GB (sender) RAM
 - SSD on both sides
 - Scanning was very quick (appx 10 minutes)
 - Wired 1gbps LAN between the 2 machines
 - btrfs on both sides with zstd:2 compression, no inline de-dupe
 
 References:
 - https://github.com/syncthing/syncthing/issues/6806

**Comment by bt90** [comment]
See @calmh explanation: https://forum.syncthing.net/t/scan-not-finishing-after-10-days/19059/17

**Comment by tomasz1986** [comment]
Not that nothing could be improved, but 10 hours to transfer this many files is probably normal. Syncthing does a lot of processing for each file, encrypts the data before transfer, decrypts it afterwards, etc. You can't really compare this to a one-way copy that rsync (or other similar tool) does.

**Comment by peterhoeg** [comment]
rsync over SSH does compression and encryption as well. I understand it’s not directly comparable but 1MB/s seems *very* low. Or maybe there just is a lot of overhead for small files?

**Comment by calmh** [comment]
Syncthing has significant per-file overhead that raunchy doesn't, yes.

**Comment by peterhoeg** [comment]
Even with fsync disabled, a regular SATA SSD should be able to sustain more than 1MB/s. Worth looking into?

**Comment by calmh** [comment]
Not really, we know why it's slow -- we do a lot of things per file in addition to the transfer: a database read, several stats and one or more listdirs, an fsync of the file and directory, and a database write. All of this is done because if there's an interruption in the process we need to have a known state or we risk data loss (sync in the wrong direction or similar) when things come back up again. We could skip all of that and significantly improve performance, but if you have a power failure on the receiving side we have no idea what the state is when it comes back up again: a bunch of files will differ from what is recorded in the database, but is that because they were synced but not recorded in the database, or changed by the user, or are in some intermediate state? rsync does none of this because it doesn't need to: it's uni directional, has no database, and if it fails you can just run it again for the same results.

**Comment by peterhoeg** [comment]
Fair enough, thanks for the explanation (and for syncthing!)
