### ISSUE TITLE
Enable setting 'Enable Relaying' on a per-folder basis

### ISSUE THREAD

**Issue by befocken** [syncthing/syncthing#8612]
Currently, there is a global setting for `syncthing` to enable or disable relaying (as discussed in #2433). However, I thought about having some folders that are only synced in the local network, e.g. for especially sensitive and private data, and some that are ok to be synced via the internet.

The only other workaround to currently achieve that (and that I thought of) is to have multiple instances of `syncthing` running, one for such local syncing only, and another for syncing via the internet. I'm not sure if/how that works with mobile clients, however, as you cannot install or run multiple instances of an app as far as I know.

Therefore, I think it would be awesome to have a setting on each folder to enable or disable relaying (in addition to the global switch). If the global switch is set to `disabled`, all folders cannot use relaying, if it is `enabled`, one can disable some folders to not use relaying.
This gives the ultimate customisability in my opinion.

I am aware that all transmitted data should be transmitted securely and private anyway, as it's being encrypted.
However, I think this could give some people (such as myself) more peace of mind, as there's not even a chance that the sensitive data is being disclosed if it never gets transmitted via the internet anyway (in case of a bug or something).

**Comment by acolomb** [comment]
Security wise, I think having a connection open from Syncthing to the Internet is enough to consider it a potential threat to your data confidentiality. It's more likely to exploit a bug in Syncthing than to decrypt intercepted traffic IMHO. Not that I see much probability for either of those.

As for the feature, you should understand that relaying is a thing related to devices, not folders. You have usually not more than one connection to a device, either via relay or something else, but that applies to all folders shared with it. So adding a switch *per device* to disallow relay connections for it would make more sense.

However I do see some value in your proposal, not related to security but rather network load. If you have a folder with 5 TB of relatively unimportant data, you might want to avoid burdening the relay server network with such load and only sync that when connected directly. This is harder to implement, because right now we can pause a folder or a device, but not a folder only for one specific remote device, while still syncing it with others. That would require deeper internal changes.

**Comment by bt90** [comment]
"Peace of mind" shouldn't be a reason to add more complexity.

**Comment by calmh** [comment]
In any case, I think relaying is the wrong security boundary. If the desire is that the data never pass over the public Internet then I think the allowed networks option is the right solution. That's also per device of course so doesn't help here, but it seems the request should be "allowed networks, per folder" instead perhaps.

**Comment by acolomb** [comment]
> but it seems the request should be "allowed networks, per folder" instead perhaps.

Or possibly "pause folder, per device", then one can add any kind of automation for conditions to trigger it using the API.
