### ISSUE TITLE
Unable to connect neither to relays nor directly to computers under Russia's IP

### ISSUE THREAD

**Issue by azatsh** [syncthing/syncthing#8625]
- which version of Syncthing and what operating system you are using
 v1.22.0 Windows 10 Pro
 
 - browser and version, if applicable
 Chrome 106.0.5249.119
 
 - what happened
Syncthing can't connect to relay servers and to other computers directly when I'm in Russia. The htpps connection seems gets timeout. The same connection works fine when I use VPN and IP gets in USA. I wonder if you maybe block Russia intentionally. 
I also tried extracting certificates and importing them into Windows cert storage, but that didn't help.

See the error message:
[EMEDQ] 2022/10/26 15:24:15 INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": dial tcp 143.244.196.6:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by calmh** [comment]
This is a Russia problem, not a Syncthing problem.

**Comment by azatsh** [comment]
@calmh 
Can you elaborate that answer please? Even I'm in Russia I still can use many different services like youtube, whatsapp, etc. 
What is exceptional with syncthing ?
Can I disable ssl/tls or do some workaround ?

**Comment by nekr0z** [comment]
> Can you elaborate that answer please? Even I'm in Russia I still can use many different services like youtube, whatsapp, etc. What is exceptional with syncthing ? Can I disable ssl/tls or do some workaround ?

Russian communication watchdog Roskomnadzor blocks various IP addresses and web services as it sees fit. Many services are unavailable to users in Russia or require jumping through various hoops (VPNs, Tor, etc.) Many other services (including Syncthing relays) are blocked and unblocked at random.

Syncthing does nothing to block or otherwise hinder experience for users in Russia; the issues users in Russia have with Syncthing are because of Russia's actions. Syncthing is not in a place to influence Roskomnadzor; arguably, it's Russian users' job.

Some internet services have made a point to help users in Russia circumvent the government blocks (one notable example was Telegram). Syncthing does not have resources to do that, and besides, fighting for the right of users in Russia (or any other country) to use Syncthing (or any other software or service) is not, and has never been, one of the goals of the Syncthing project and the Syncthing Foundation.

Please use the forum for further discussion if you think further discussion is required.

**Comment by azatsh** [comment]
@nekr0z 
Thanks for explanation !

**Comment by tomasz1986** [comment]
This was discussed on the forum in May (see https://forum.syncthing.net/t/internet-provider-yota-blocks-the-name-https-relays-syncthing-net-endpoint/18501). In short, the only solution other than using VPN/proxy would be to run your own relay server. If you decide to do that and need help, please open a new topic on the forum about it.
