### ISSUE TITLE
Conflicts created on Android on files modified by other devices

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#8654]
As reported in a ot of places:

https://github.com/syncthing/syncthing/issues/8604#issuecomment-1306112744

https://forum.syncthing.net/t/keep-getting-conflicts-generated-on-android-device-for-files-modified-only-on-a-desktop-pc/19060/24

https://forum.syncthing.net/t/file-conflict-for-every-modification-on-android/19272

**Comment by tomasz1986** [comment]
How about changing the title to something more alike "Conflicts created on Android on files modified by other devices"? I think that's what the problem is really about. I'd also add that it's not exactly "on every modification", but I couldn't figure out why sometimes conflicts were created and other times weren't 🤔.

**Comment by jeron1** [comment]
Just donated 20 Euros, as I greatly appreciate this maintenance and the continued smooth syncing between my Android and Linux PCs. 
![st donate](https://user-images.githubusercontent.com/73413568/208987353-884a2d7f-0df7-4c9c-a8c5-ddb101ab3e73.png)
