### ISSUE TITLE
"Sync Conflict" when file is open

### ISSUE THREAD

**Issue by marsch1975** [syncthing/syncthing#8666]
Hello,

when I'm working on an OpenOffice or Excel file on my Windows 10 pc Syncthing produces files like in the screenshots...

This confuses a lot because:
1. question is, is all "up to date" data in the "normale named" file and
3. what do i do with all these "wrong files", do I delete them straight away or should I check before and so on...

Is there a way to avoid those "wrong files"?

Syncthing Version 1.21.1

Thanks
Markus
![Synthing Conflicts](https://user-images.githubusercontent.com/116442584/201175884-27d06524-59c6-4b8a-8b2a-220509eebbb4.jpg)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

There were a lot of a conflict-related issues recently, especially if Android was involved. These should be resolved in the latest hotfix for Android and the 1.22.2-rc.

Thanks!

**Comment by marsch1975** [comment]
When it is no bug why is there a hotfix?

I have this since 1.22.1 came out a few days ago... With 1.22.0 it was fine...

I find it bad to be always send from forum to GitHub and back, it should be under one roof...

I will wait for 1.22.2

**Comment by Glutamat42** [comment]
I recently observe a similar issue with an excel file i have nearly permanently open on a windows host (and almost never on another host). Since 7.11. i have 10 conflict files. Before 7.11 there were maybe one every few months. I couldn't narrow it down further until know, but at least since that date all my clients are on 1.22.1.

There's also an android client (syncthing fork) involved, which was also the last client i updated, so it's absolutely possible this client is causing problems. But the only thing changed is the update and the affect file is never touched on android. Will try if this still happens if i remove the android client.

**Comment by imsodin** [comment]
As you can see if you search for conflict on either github or the forum (https://github.com/syncthing/syncthing/issues?q=is%3Aissue+conflict), there were bad issues around conflicts. They are solved in syncthing-android 1.21.1.1 and syncthing 1.21.2-rc.2. So please update to that and if you still have questions use https://forum.syncthing.net.

Locking this issue.
