### ISSUE TITLE
Unknown Device after suspend

### ISSUE THREAD

**Issue by hykilpikonna** [syncthing/syncthing#8738]
After waking up my laptop from suspension, the web UI will fail to identify this device (XPS) and show it as "unknown device," but also show the correct information of this device in the Remote Devices tab. There are no errors in the JS console.

![image](https://user-images.githubusercontent.com/22280294/210283585-f9d77b7e-08c7-408d-8aad-a9e476d2fc7d.png)

This issue can always be fixed using a `systemctl restart syncthing@username` reboot, but always show up after waking from suspension.

![image](https://user-images.githubusercontent.com/22280294/210283733-6a26a865-0583-46fe-aa06-bd4f2a0bc5a4.png)

### Include required information

Please be sure to include at least:

Syncthing Version: `syncthing v1.22.1 "Fermium Flea" (go1.19.3 linux-amd64) syncthing@archlinux 2022-11-03 07:35:59 UTC [noupgrade]`
Browser Version: `Google Chrome 108.0.5359.124`
OS: 
![image](https://user-images.githubusercontent.com/22280294/210283799-9916a809-eb20-4db9-9390-10656d951e06.png)

**Comment by tomasz1986** [comment]
> but also show the correct information of this device in the Remote Devices tab.

This one isn't actually helpful here as the name on remote devices doesn't change even if you edit it locally (unless you tweak the default settings). You could, however, for testing purposes simply delete the label on the remote device completely, and then try to pause and unpause the device to trigger a reconnection. This way you will be able to verify whether the issue is just a glitch in the GUI or whether the device name is really reported to other devices as "unknown".

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by calmh** [comment]
Strike that, I misunderstood. This seems to be some sort of issue, though I'm not sure what it could be.

**Comment by hykilpikonna** [comment]
I have no clue on the issue either, but it was fixed after I tried `syncthing --reset-database`
