### ISSUE TITLE
Option to disable encryption

### ISSUE THREAD

**Issue by D4rk4** [syncthing/syncthing#8770]
I guess it's will be a good idea to have the ability to disable encryption per device basis.
It's will be useful in WAN nets, already connected to each other via VPN with encryption.
So in this case we just save computer power and make the world green.
In other cases (it's my case), we got many sites connected to each other via VPN and using WAN optimization hardware (it's just QoS + traffic deduplication).
In this case, if encryption is turned off, we can save extra traffic because WAN optimization devices can dedup Syncthing traffic (with encryption it's not possible).

**Comment by bt90** [comment]
Plain and simple: no

* encryption on any processor manufactured in the last decade has next to zero overhead. It's done in hardware.
* it's a massive footgun. Your VPN isn't running and your leaking data.
* their is nothing you could deduplicate or compress which isn't already covered by Syncthing. Worse, compression might actually inflate the amount of transfered data
* TLS is also used by peers to identify each other

**Comment by acolomb** [comment]
If you really do need this (which I doubt), you could probably build your own custom version of Syncthing from source, changing the preferences for the stream ciphers used in the connection. I don't know if there even is a "no encryption" option in TLS. But in fact, we do need the TLS connection because it also serves the purpose of device authentication among each other.
