### ISSUE TITLE
Don't reconnect if connected one way when device wakeup

### ISSUE THREAD

**Issue by BirdInFire** [syncthing/syncthing#8830]
### Does your log mention database corruption?

No database corruption.

### Include required information

Please be sure to include at least:

 - Syncthing 1.23.1 Fedora Last stable version (37 as i write this issue)
 - N/A
 - Some device in the network who go outside must have a full closed port, so the connection only happen when initiated by the device, when this device (the one who initiate), go to sleep and later is waken up, syncthing actually never reconnected from this sleep, and since the server cannot reach them (due to the firewall settings mandatory on these device), the sync never restart (until the device (who initiate) itself or syncthing is rebooted).
 - When the device woke up after some time (5 to 15 minutes) syncthing re-initiate the connection to the server by itself.

#Additional information : 

- I do think it's only happening on these device because other have the server who check them up, and so the connection restart (due to the server who will initiate the connection instead of the device) when in this kind of configuration (with all incoming port closed) without any external connection to wake him up it rest disconnected.

- Also the device/server have ip and port hardcoded into the settings so no autodiscovery etc is never involved in this senario.

**Comment by bt90** [comment]
What kind of connection is established between the two nodes? It sounds like the QUIC protocol is used, because your description would fit a connection setup via holepunching. If that is the case, a slower (re)connection establishment is more likely.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

This needs logs of the non reconnecting side to see what’s going on. 

Thanks!

**Comment by acolomb** [comment]
Please @BirdInFire, don't misunderstand our attitude. There might be a real bug in the behavior you describe, but we have too little information to locate it or rule it out yet. The only thing @calmh asked was to move that information collection process to a forum thread, because that's not how we want to use the GitHub issue tracker. It's really just a tracker for things a contributor might start working on when they feel like it, and hence needs to be concise and complete enough to actually facilitate picking up the issue. Discussing your setup and collecting information distracts from that and you are very kindly requested to adhere to this usage pattern. Since it's all volunteers putting in their free time as maintainers, please accept that we make our rules for organizing our work.

I'm sure you'll get better help if you do open a forum thread. Of course, you're also free to (not) use any software as you see fit.
