### ISSUE TITLE
Local state is incorrect

### ISSUE THREAD

**Issue by DeinAlptraum** [syncthing/syncthing#8844]
### Does your log mention database corruption?
No

### Include required information
Setup: Sharing one folder between my PC and laptop. There's no ignore patterns involved.

Versions:
Syncthing & OS on both devices: syncthing v1.23.2 "Fermium Flea" (go1.20.1 linux-amd64) syncthing@archlinux 2023-03-07 18:47:24 UTC [noupgrade]
Browser on both devices: Mozilla Firefox 111.0.1

What happened: The shared folder shows as "Up to Date" on both devices, and supposedly contains 616 files.
This is not the case however: on the laptop, the folder contains 617 files and the .stfolder, on the PC it's 629 files and the .stfolder.
Both devices had at least one file that couldn't be found on the other device.
When I deleted one of those files from the laptop, then the local state on *both* devices updated, down from 617 to 616. The number of files in the shared folder on my PC has not changed though.

Things I've tried:
1. restarting syncting 
1. removing the folder from the laptop, and then re-sharing it from the PC
2. --reset-database on both devices

Steps to reproduce: no idea

**Comment by ThiloteE** [comment]
you could use [meld](https://meldmerge.org/) to find differences in between the folders.

**Comment by calmh** [comment]
I'm closing this because there's not enough information to do anything useful with it. Obviously we should have asked for that information earlier, sorry about that. If it happens again, we need:

- which file is missing from the database?
- what does that file look like on disk, exactly?
- what do the logs say?
- if nothing interesting, what do the logs say when running with `STTRACE=scanner`?
