### ISSUE TITLE
Inotify support

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#9]
To notice changes more quickly.

**Comment by jkaberg** [comment]
@calmh @AudriusButkevicius @Zillode Have you guys ruled out ionotify or is it something that might be implemented "later down the road"? If the later, would you humor me with an rough ETA guess? 2015, 2016, 2017+?

I've already seen the various implementations using the API endpoints, and I'm sure they work but IMO Syncthing is worth something better :smiley:

**Comment by AudriusButkevicius** [comment]
The original problem discussed in this ticket still exists.

OS X is bad at performing file watches, and requires tweaking kernel settings to be usable, which is not an option for average joe, hence I guess why it's still not part of syncthing.

**Comment by rkfg** [comment]
How do they work around it in Dropbox? It's available for OS X.

**Comment by calmh** [comment]
Probably mainly by giving most users a small enough quota that it doesn't happen, and then switching to scanning if it does... But, the plan has always been to integrate syncthing-inotify when it works well enough in most case. I think it may be getting there.

**Comment by rkfg** [comment]
They have a 100 Gb paid plan and scanning this much data, if it consists of many small files, may be pretty expensive. It could be interesting to investigate their methods further as Dropbox is de-facto the leading (or at least the most popular) product in its field. Maybe [this](http://www.quora.com/Why-does-Dropbox-slow-down-my-Mac) points out that the file watches are used all the time?

**Comment by calmh** [comment]
Actually, on Mac at least, the native fseventsd API can be used without any restriction on number of watched files (as far as I can tell). Windows and Linux probably have similar API:s.

**Comment by AudriusButkevicius** [comment]
Yeah but fsevents requires linking against CoreServices, hence requiring a special build environment.

**Comment by jkaberg** [comment]
Glad to hear it @calmh , looking forward to that day :-)

**Comment by lucb1e** [comment]
Was looking forward to moving away from the proprietary btsync, but this is a deal breaker for me as well. Nice that there is a workaround, but it should totally have been done in the main application.

I'm having a hard enough time moving people at school away from Dropbox, let alone also going "oh and if you don't want a performance hog and battery drain every single minute, you have to install and configure this external thing as well [which every other file sync tool on the planet has built-in]". Not being able to turn others over means I can't use this either.

The issue I read in the thread is that there is no good cross-platform thing that scales, but it's not that hard to write it for one platform (so that the code structure is there) and then let pull requests add and maintain other platforms. A few people in this thread offered to write code and I see various implementations to use the API. The desire and support is there. As long as automatic fallback to rescanning works well, there is no regression.

**Comment by drgowen** [comment]
Just an informational comment to @lucb1e :  I tried syncthing again wondering if the scanning was actually an issue or not.  It turns out there's another deal breaker, it cant punch through firewalls that effectively ruling it out completely at my workplace (some ports blocked but not all and btsync works fine).

**Comment by Schroedingers-Cat** [comment]
@lucb1e Why not use https://github.com/canton7/SyncTrayzor or https://github.com/syncthing/syncthing-gtk - both have inotify support and are easier to set up as they have an installer/repo.

**Comment by calmh** [comment]
To be clear, a working solution will always be welcomed and merged. Syncthing-inotify is the closest I know of. Any effort towards putting in whatever finishing touches are necessary and getting it merged is welcome. Cross platform doesn't need to mean "works perfectly everywhere" - supporting Windows and Linux would cover almost 90% of the current user base and is a good start.
