### ISSUE TITLE
Favicon is stuck in notify state

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#9149]
As discussed in the forum: https://forum.syncthing.net/t/favicon-notification-breakdown-sticky-black-exclamation-mark-across-browsers/20882/7

https://github.com/syncthing/syncthing/pull/8918 removed the connection entry for the device itself:

https://github.com/syncthing/syncthing/blob/4f6b86a1c09b99aeb239d49c92ea7036f7a24e9e/lib/model/model.go#L745-L747

But this entry is required for the UI to properly determine the status of the device itself:

https://github.com/syncthing/syncthing/blob/4f6b86a1c09b99aeb239d49c92ea7036f7a24e9e/gui/default/syncthing/core/syncthingController.js#L1076-L1078

**Comment by calmh** [comment]
The place calling `$scope.deviceStatus` should skip the local device.

**Comment by LinuxOnTheDesktop** [comment]
This problem long irked me, so I'm glad of progress. However, and on Syncthing 1.26.0: on Firefox on Windows, the problem is solved; but, on Firefox ESR, also on Windows, I get, not an icon with an exclamation mark, but a generic grey icon - thus (see top right):

![image](https://github.com/syncthing/syncthing/assets/47056543/bc78bf54-d7b7-4d13-8f54-eb167218a8a7)

**Comment by bt90** [comment]
Any warnings or errors in the browser console?

**Comment by LinuxOnTheDesktop** [comment]
@bt90 

Nothing relevant, I think. ([Output](url).) But my own screenshot should have made me wonder why I seem to have several bookmarks that show only a generic (symbolic) icon . .
