### ISSUE TITLE
"Override changes" should honor `ignoreDelete`, or perhaps new `ignoreOverride` setting

### ISSUE THREAD

**Issue by khimaros** [syncthing/syncthing#9228]
N.B. i, and a close friend of mine, have lost data due to this innocuous little button. i live in constant fear that i will accidentally press this button again and annihilate my precious data.

at a minimum, i believe the documentation for `ignoreDelete` should make it very clear that deletes are **not ignored** if any send-client uses the "Override changes" button. this was very non-obvious to me.

an even better solution would be to prevent this from happening programmatically. i think it is more intuitive to prevent all deletes (even via override) when that setting is enabled. however, for backward compatibility, i can see that it may be better to have a new (eg. `ignoreOverride`) folder setting.

i understand from various [developer](https://github.com/syncthing/syncthing/issues/6521#issuecomment-612246889) [responses](https://github.com/syncthing/syncthing/issues/6185#issuecomment-612865623) that send-then-delete is not an intended use case for syncthing. however, because despite this intention, syncthing still appears to be the best/only tool for this job on Android, this seems to be a [common](https://github.com/syncthing/syncthing/issues/6185#issuecomment-612864151) [enough](https://github.com/syncthing/syncthing/issues/6185#issuecomment-640349736) [use case](https://github.com/syncthing/syncthing/issues/6521) for people backing up photos/videos.

i believe that it is worth attempting to protect users at bit more from this particular foot gun.

thank you for all of the amazing effort and work that has gone into syncthing. i am passionately filing this issue because it is one of the very few problems i've encountered with syncthing as an otherwise extremely satisfied user. syncthing rests at the very core of my Android backup methodology.

**Comment by calmh** [comment]
I don't think I understand the problem or scenario you're describing. Can you describe the setup, what you did, what you expected to happen, and what happened instead?

**Comment by khimaros** [comment]
@calmh sure, i'd be happy to.

i have SERVER and PHONE clients configured. the PHONE has one of its directories (DCIM) setup as a send-only share to the SERVER (which is configured as receive-only with `ignoreDelete`).

at some point, after replication had been running cleanly for some months, i deleted some of the older files (photos/videos) on the PHONE to free up space.

as a result, that folder shows up as "Out of Sync" on the PHONE because the SERVER has not replicated the deletes (all of this is WAI according to the [syncthing docs](https://docs.syncthing.net/advanced/folder-ignoredelete.html)). this is all fine.

the problem arises as a result of the "Override changes" button, which becomes available on the PHONE for that folder. when pressed, syncthing forcefully deletes all of the files on the SERVER which were previously removed from the PHONE.

does that help clear things up?

**Comment by calmh** [comment]
Yes/no... What you describe isn't what should happen, and isn't what happens when I try it now. I'm with up to this part

> as a result, that folder shows up as "Out of Sync" on the PHONE because the SERVER has not replicated the deletes (all of this is WAI according to the [syncthing docs](https://docs.syncthing.net/advanced/folder-ignoredelete.html)). this is all fine.

Yep, that happens. However,

> the problem arises as a result of the "Override changes" button, which becomes available on the PHONE for that folder. when pressed, syncthing forcefully deletes all of the files on the SERVER which were previously removed from the PHONE.

This doesn't happen, at least not as a result of *just* the described situation. The sending side doesn't see any changes to override, because the other side hasn't sent any.

Sending (phone) side with one file deleted:

<img width="1582" alt="Screenshot 2023-11-16 at 23 45 50" src="https://github.com/syncthing/syncthing/assets/125426/0ad56ec5-d87f-418b-8ad1-33a2e1f0bfe2">

Receiving side (server):

<img width="1582" alt="Screenshot 2023-11-16 at 23 45 54" src="https://github.com/syncthing/syncthing/assets/125426/27e2bca3-58d9-4134-9129-e204f674e1f8">

"Override changes" implies something has changed locally - some file added, modified, deleted -- that wasn't sent from the phone.

**Comment by khimaros** [comment]
perhaps this has been fixed (or partially fixed) in newer releases (or in latest git)? my SERVER at least was quite out of date, it seems:

PHONE: v1.26.0 from F-Droid (com.nutomic.syncthingandroid), Android 14
SERVER: v1.12.1-ds1, Linux (64 bit), Debian Bullseye

after updating the SERVER to v1.19.2-ds1 (Debian Bookworm), my SERVER side looks more like yours with the "Altered by ignoring deletes" message.

however, my PHONE still shows the "Override changes" button in the Android wrapper as well as on the Web GUI. PHONE also shows different file counts for Local State vs. Global State on that folder, where yours shows no difference.

oddly, the Global State on the PHONE also doesn't match Global State on the SERVER. the SERVER matches the output of `find -type f | wc -l` and the phone shows about 35 files fewer. maybe *that* is what's leading to the button appearing?

**Comment by calmh** [comment]
Possibly. That (1.19.2) is still an old Debianised version, I suggest our builds from https://apt.syncthing.net/. Anyway, this seems not clear cut, I think it's a support case at this point so the forum (https://forum.syncthing.net/) is the better place to sort out what's going on.

In any case, `ignoreDelete` applies equally to all remote-deleted files, regardless of sendonly/receiveonly etc so I think the issue here is not what it might have looked like initially.
