### ISSUE TITLE
Deprecate 32bit Windows build

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#9289]
With Windows 7 and Windows Server 2008 support not being a thing anymore, the case for 32 bit Windows binaries is pretty weak.

**Comment by tomasz1986** [comment]
Why do you think so? Windows 10 still supports x86-32 and the last Enterprise LTS(C) release with this support is supported by Microsoft until year 2031.

I personally use 32-bit releases on Intel Atom devices which have 32-bit UEFI and because of that cannot run Windows x64. I have also stumbled upon quite a few installations of 32-bit Windows on computers with 2GB RAM or less, e.g. in educational institutions.

**Comment by tomasz1986** [comment]
> I was under the wrong impression that 32bit isn't really a thing anymore on Win10+.

It has been dying out, but schools/universities tend to use their computers till the very end, and it makes more sense to install Windows x86 on devices with 1-2 GB of RAM, so they often do it (even though the hardware itself is 64-bit capable).

On the other hand, the Atom devices with 32-bit UEFI are probably the last that don't support Windows x64. They were produced between 2012-2015 (i.e. in the Windows 8 era), so they aren't that old yet.
