### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [syncthing/syncthing#9318]
### Include required information

It would be nice if the app's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by calmh** [comment]
My vote is no.

**Comment by er-pa** [comment]
>and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.
How so? Microsoft has been quite active (contributions as well as support) in the Open Source community for over a decade now. Why would Github being owned by MS be a danger?

**Comment by bt90** [comment]
> How so? Microsoft has been quite active (contributions as well as support) in the Open Source community for over a decade now. Why would Github being owned by MS be a danger?

Most points are covered by the SFC: https://sfconservancy.org/GiveUpGitHub/

While I agree with the motivation, there would be a lot of work involved in moving the project. The code is one thing, but we would also have to migrate all of our Github actions. Losing potential contributors due to account creation fatigue is also a valid concern.

As a result my view is a bit more pragmatic. I don't mind if we move the project as long as someone is willing to foot the bill.

**Comment by tomasz1986** [comment]
> Losing potential contributors due to account creation fatigue is also a valid concern.

I would add also fewer non-technical people coming to report potential issues. GitHub's interface is already a bit intimidating for them, but GitLab with its information overload and more technical wording is something they are never going to overcome. Someone using GitLab on a daily basis will probably disagree, but for me it seems obvious that the platform has been designed by programmers and for programmers only.

Codeberg, on the other hand, does look much more user-friendly in terms of the UI (i.e. it's very similar to GitHub). It's obviously a much smaller and less well known platform than the other two though.

**Comment by er-pa** [comment]
> Most points are covered by the SFC: https://sfconservancy.org/GiveUpGitHub/

While those are solid points, they barely scratch the surface of why it is "more of a danger". It's more of a summary of ideological stances and complaints rather than explanations of why it is actually considered problematic to keep using Github. Of course, ideology can be enough to warrant a migration, but it doesn't really support the 'fear' that's being included in the reasoning here.

But by the looks of it, the alternatives are either self-hosting or use a much lesser known solution. Not sure if either is really preferred, regardless of whether someone puts in the effort to pull the horse across the stream.

**Comment by imsodin** [comment]
Ah yeah no. Sure I love to hate on Microsoft as much as anyone (even more so since forced onto Teams in my day-to-day 🤮 ), but github still works perfectly fine and moving would be a big burden. If anyone feels like deliberating this any further, please take it to https://forum.syncthing.net/
