### ISSUE TITLE
Not all files or folders have been sent to the receiving device

### ISSUE THREAD

**Issue by Preagles** [syncthing/syncthing#9431]
Snycthing Version 1.27.3. Sharing from a windows 11 laptop to android fold 3 UI 6.0 12GBRAM 512GB storage space. Laptop is a Dell inspiron, 32GB RAM and 1.5TB SSD. Space on both should be more than enough. 

When backing up my files some files and folders are just not backed up. The omissions appear to be random, sometimes files within the same folder (same type of file) will have some copied and some omitted. In the app the shared folder shared shows 42.7Gb, 9918 files, 1965 folder. However, in windows it shows this folder contains 45.7GB, 11997 files and 1987 folders. 
Sometimes entire folders are missing. Sometimes just some files within a folder (one particular folder for example only 3 of 6 files were copied. All files were of the same type and of similar size.).
I have tried a second backup of the main folder and it showed the exact same size, folder and file numbers as the previous one. 
I'm not sure what to do to fix this. Any ideas are welcome.

**Comment by tomasz1986** [comment]
The issue is unclear, so if you don't mind, please open a new topic at https://forum.syncthing.net for further investigation first. You can copy and paste the same text there. Please make sure that you're running the newest version of Syncthing on both sides, and also please include screenshots of the Syncthing Web GUI from both sides. On Android, the Web GUI can be accessed from the left slide-out menu.
