### ISSUE TITLE
Allow partial downloads to be available for pulling

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#950]
As per subject.
Would be interesting to discuss the implementation details.
I guess it needs some sort of 'announcements' for partial downloads, or scanning of tmp files marking them as tmp so that others wouldn't try and pull them?

**Comment by afeblot** [comment]
This is indeed the missing feature that pushes us back to BT sync, which allows faster sharing of large files among a group.

**Comment by kluppy** [comment]
I found mention of this in the forum.
How is it going? Are you still looking at this or has it stalled?
The feature isn't a big deal for me but I think a lot of people would assume it is how synching already operates and could make a big difference to small clusters.
I ask because @calmh removed it from v1.0-maybe

**Comment by AudriusButkevicius** [comment]
It's superceeded by https://github.com/syncthing/syncthing/pull/2252
