### ISSUE TITLE
get pending status for 10s files, 60s deletion on api.

### ISSUE THREAD

**Issue by DEvmIb** [syncthing/syncthing#9508]
### Feature description

file watcher does not report "hey, there was a change on file, i have to wait $fsWatcherDelayS" in any debug logs. the first entry appears after the 10s for files or 60s for deletion. so /rest/db/status?folder= could have "PendingFiles" and/or "PendingDeletions" and "state" not idle?

### Problem or use case

the problem is, how to known "can i shutdown the machine or is syncthing waiting to check files", after moving files to sync folder or or or.

### Alternatives or workarounds

-

**Comment by calmh** [comment]
If you did a manual change and want to be super duper sure, just trigger a manual rescan and wait for it to show up to date. If you're wondering about changes that might happen in the background, this wouldn't help because a change might happen the millisecond after you check and consider it done.

I don't think there's anything we could/should do here, exposing changes that are pending deep in some third party package is too niche for a general API feature...
