### ISSUE TITLE
add exit on sync or execute on sync

### ISSUE THREAD

**Issue by muzzol** [syncthing/syncthing#9526]
### Feature description

Exit the program or execute script when all folders or specific one is fully synced.

My proposal is to add a global flag like **--exit-on-sync**
If no folder id is specified, all folders should be on Up to Date state to trigger the parameter.

With this parameter a simple script like this should work:

```
#!/bin/bash
syncthing --no-browser --exit-on-sync --folder-id=abcde-12345
poweroff
```

Alternatively a similar effect could be achieved with **--execute-on-sync=my-script.sh**

In any case, the goal is to have a very simple way to know when a folder is synced and give control back to the console and don't wait indefinitely.

### Problem or use case

Users with different computers (home, studio, work) with a single folder but huge size, so that have to wait for hours or leave the computer on if they don't have physical access to it.

### Alternatives or workarounds

There's a lot of different aproaches on the forums and issues but none is reliable because they use parsing files or programs.

**Comment by imsodin** [comment]
> There's a lot of different aproaches on the forums and issues but none is reliable because they use parsing files or programs.

The problem is the unreliability wont change by pushing this into syncthing. All the information that Syncthing would use to determine if it's in sync is available in the API. As such I think it should be left to the user to define what they consider being in sync using the info available in the API, and then do whatever (here stop syncthing and shutdown).
