### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by steom** [syncthing/syncthing#9587]
### Feature description

When a node,  remote devices, goes offline, or stay offline for a predefined time, other system send out email notifications.

### Problem or use case

Useful to recovery a remote device connectivity 

### Alternatives or workarounds

Execute external command

**Comment by calmh** [comment]
Yep, doing this externally in something that talks to the API is the correct solution.

**Comment by acolomb** [comment]
I don't know of any such effort that has been published.  For an end-user without scripting skills it is currently not easily doable.  You'll need to find someone who can code it for your needs.  However, in Syncthing itself an implementation is highly unlikely, as there is a vast diversity of requirements and we cannot support every feature in the core itself, making it unmaintainable.  That's why there is a generic API that can be used for all kinds of purposes like the one you describe.
