### ISSUE TITLE
Device names aren't updating on remote peers

### ISSUE THREAD

**Issue by lesha-co** [syncthing/syncthing#9592]
### What happened?

- have two devices syncing several folders
- neither of the devices has a "custom" name for each other
- on device A web ui go to `Settings —> General -> Device name` and change it.
- Device B does not update it, not immediately, not even several minutes later

I know that I can change device names myself, it's just weird that they don't do it on their own 

in the logs below you see that remote device announces its name (different from the UI) but UI has old name

----
speculation on what's happening: Syncthing remembers what the name ("old_name") was when devices were introduced to each other, but is not updating the name because it thinks that 
"old_name" is a custom name that you can assign through the UI. I can "fix" problem by going to remote device's "settings -> general -> device name" and emptying it then restarting syncthing. It will wait for announce and then save "new_name" 

### Syncthing version

1.27.8

### Platform & operating system

Linux (64-bit Intel/AMD), macOS (64-bit Intel/AMD)

### Browser version

N/A

### Relevant log output

```shell
2024-06-24 11:01:53 Established secure connection to KXW7NTK at xxx.xxx.xxx.xxx:22000-xxx.xxx.xxx.xxx:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256/...
2024-06-24 11:01:53 Device KXW7NTK client is "syncthing v1.27.8" named "server gosha" at 192.168.0.5:22000-95.84.184.181:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256/...
```

**Comment by calmh** [comment]
Names of peers are by default controlled locally (you can call your peers what you want without them overriding it). There is a setting for allowing override though, possibly under "advanced". Not at a Syncthing computer at the moment.

**Comment by lesha-co** [comment]
Oh, I see, `overwriteRemoteDeviceNamesOnConnect`. Sorry for not looking hard enough haha

Is there a reason why this setting is global and not device-specific?

**Comment by acolomb** [comment]
Less code, less complexity. Usually you don't change device names that often, so it's really a niche case. Deciding for each device individually whether you want the overriding is just as difficult as simply changing the device name individually.

Note that the default of not using the changed remote name is kind of a security feature, as it would make it easier to trick someone into sharing a folder with the wrong device. That's why the names are considered local knowledge only meaningful for the user who sets them.
