### ISSUE TITLE
Folder label instead of unique folder ID

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#966]
Current situation when adding a new folder
+) think of unique name that's short and unique but also descriptive (max. 64 chars)
+) hope that other devices does not have the same name

Idea
+) user can enter a (non unique) label according to own ideas (not char limit)
+) Syncthing creates a random unique folder ID 
(similar to device ID, but shorter, maybe a hash derived from user input)

example (same ID but different labels)
* user in USA "Munich-Paris"
* user in Germany "Datentausch München-Paris"
* user in China "数据交换 慕尼黑-巴黎"
* lazy user "MP" :-)

As a user shares a folder with another device, the recieving user could be informed about the label as an example (but can change it). If this feature is implemented existing folder IDs could be used as labels

**Comment by jkaberg** [comment]
Might I suggest perhaps adding in a "descriptive comment" aswell? 

So for example;
Label (or name?): School project X
Comment: This contains stuff for my thesis
Unique ID: 3568989dg89d989398359

**Comment by shish** [comment]
Linking with the discussion thread - https://forum.syncthing.net/t/friendly-names-for-shared-folders/2477/17

An extra use case from there: Programatically add new shares without user interaction, since the user can change all the user-facing details later; in particular, this allows "right click folder -> add to syncthing" to Just Work(tm), no need to prompt the user to come up with a unique share name, since the share ID will be unique and the share name can just be the name of the folder (and changed later)

Discussion of right click -> share in windows: https://github.com/canton7/SyncTrayzor/issues/77

**Comment by jerryjacobs** [comment]
The folder label is a very nice addition, @calmh very nice to add this to v0.12 or v1.0-maybe milestone.

**Comment by lovetox** [comment]
if this comes and works, it will be a huge step for syncthings UX :)

**Comment by giosh94mhz** [comment]
:+1: for this!

**Comment by lkwg82** [comment]
+1
