### ISSUE TITLE
Inconsistent instances even though each one claims it is complete

### ISSUE THREAD

**Issue by sagamusix** [syncthing/syncthing#9794]
### What happened?

I have one source (send-only) Syncthing instance (v1.28.0, Windows) and two receive-only Syncthing instances (v1.19.2-ds1 from Debian). Today noticed that a folder I created yesterday is missing updates on the two latter instances. All three instances agree about the amount of files they know about (global and local state number matches on all three instances). However, even after forcing refresh on all three machines, the latter two miss several files that have been updated on the origin. Some files are present but in an outdated version. Manually updating one of those files on the origin also doesn't update the file on the other two machines. If I rename one of those outdated files on the origin (e.g. x.txt -> !x.txt), the outdated files disappear, but the new file doesn't show up (i.e. now there's neither x.txt nor !x.txt).

Needless to say, those files are not part of any ignore patterns, and identically-named files in neighbouring folders are not affected. It's just this one folder. Now I understand this is an extremely vague description, so I'll be happy to provide any logs or test any further hypetheses you want me to test.

### Syncthing version

v1.28.0 + v1.19.2-ds1

### Platform & operating system

Windows x86-64 + Debian (ARM)

**Comment by imsodin** [comment]
Generally please update the outdated debian versions - we don't have the capacity to debug old versions. You can use our apt repo for that - instructions also to be found here: https://apt.syncthing.net/

And then as you already noted yourself, the report in the current state isn't actionable. As there's no indication of what is going wrong. For cases like this we first support and debug them on the forum - https://forum.syncthing.net/). The forum has a lot more eyes and friendly people on it than the issue tracker. When tangible information is collected there and it still looks like a bug, an issue can be created that then already includes the relevant information to make it actionable. In this case I'd start by upgrading. And then create a topic on the forum with screenshots and plain logs as they are now - even if there's nothing there that reveals the issue, it can help with more targeted requests for information. Thanks!

**Comment by timabell** [comment]
Thank you for the pointer to the apt feed, I had the same problem with missing files and hadn't realised how out of date the default apt feed was.

Updating the machine that had all the files by installing the newer syncthing daemon from the apt feed was all it took for it to notice and get on with syncing the missing items. 🙌 🙏 

version that wasn't sending the missing files:
```
╰─$ /home/tim/.local/bin/syncthing --version                                                                                                                                                  
syncthing v1.18.2 "Fermium Flea" (go1.17 linux-amd64) teamcity@build.syncthing.net 2021-08-22 18:04:47 UTC 
```

updated version that did send the files:
```
╰─$ /usr/bin/syncthing --version
syncthing v1.29.7 "Gold Grasshopper" (go1.24.3 linux-amd64) debian@github.syncthing.net 2025-05-29 08:04:08 UTC [noupgrade]
```

My install script based on the apt link above - 
https://github.com/timabell/dotmatrix/blob/59fe425bc53a478776000ce175f8ae6e274773fd/software/syncthing.sh

The receiving machine that had never received half the files it should have was stuck at this version even though syncthing-gtk should have updated it, it's receiving all the missing files now even though I haven't yet updated it, but of course I'll update that too now I know:
```
╰─$ /usr/bin/syncthing --version
syncthing v1.18.0-ds1 "Fermium Flea" (go1.18.1 linux-amd64) debian@debian 2024-11-15 23:18:02 UTC
```

Issues and responses like this are so helpful, they save so much time because a quick search of the internet for the stuck-sync found this and saved me a lot of head-scratching.
