### ISSUE TITLE
Clarify log message for ignored folders

### ISSUE THREAD

**Issue by rmmonster** [syncthing/syncthing#9875]
### What happened?

`[XXXXX] 2024/12/17 23:52:30 INFO: Ignoring folder "some folder name" (some-folder-id) from device SOME-VERY-LONG-DEVICE-ID since we are configured to`

I try to figure out why a folder does not show on my desktop when offering a folder from my mobile and the log message just cuts out when it gets to the interesting part.

### Syncthing version

v1.28.1

### Platform & operating system

Windows 11 (64-bit Intel/AMD)

### Browser version

Firefox 133.0.3

### Relevant log output

```shell
[XXXXX] 2024/12/17 23:52:30 INFO: Ignoring folder "some folder name" (some-folder-id) from device SOME-VERY-LONG-DEVICE-ID since we are configured to
```

**Comment by rmmonster** [comment]
[Quick code search links it to](https://github.com/search?q=repo%3Asyncthing%2Fsyncthing%20%22since%20we%20are%20configured%20to%22&type=code)

**Comment by acolomb** [comment]
I suppose this is just a question of writing style / grammatics.  It's meant to say:

`[XXXXX] 2024/12/17 23:52:30 INFO: Ignoring folder "some folder name" (some-folder-id) from device SOME-VERY-LONG-DEVICE-ID since we are configured to` [...ignore it]

Certainly the software speaking of itself in plural form is not the best idea, but the sentence makes sense and is not cut off.  Your proposal is fine, except I'd like to keep the word "configured" or "configuration" in there somehow.  Can't think of a better alternative though.
